Repository halo-dev/halo, pull requests merged in 2020-03, with the labels that each got.

#609 Fix attachment upload to sm.ms failed.
  src/main/java/run/halo/app/handler/file/SmmsFileHandler.java
Labels: bug

#610 Support set archives page size.
  src/main/java/run/halo/app/controller/content/model/CategoryModel.java
  src/main/java/run/halo/app/controller/content/model/PostModel.java
  src/main/java/run/halo/app/controller/content/model/TagModel.java
  src/main/java/run/halo/app/model/properties/PostProperties.java
  src/main/java/run/halo/app/service/OptionService.java
  src/main/java/run/halo/app/service/impl/OptionServiceImpl.java
Labels: enhancement

#619 Fix failure of suffixes in posts.
  src/main/java/run/halo/app/controller/admin/api/AttachmentController.java
  src/main/java/run/halo/app/controller/admin/api/CategoryController.java
  src/main/java/run/halo/app/controller/admin/api/JournalCommentController.java
  src/main/java/run/halo/app/controller/admin/api/LogController.java
  src/main/java/run/halo/app/controller/admin/api/PhotoController.java
  src/main/java/run/halo/app/controller/admin/api/PostCommentController.java
  src/main/java/run/halo/app/controller/admin/api/SheetCommentController.java
  src/main/java/run/halo/app/controller/admin/api/TagController.java
  src/main/java/run/halo/app/controller/content/ContentContentController.java
  src/main/java/run/halo/app/controller/content/model/CategoryModel.java
  src/main/java/run/halo/app/controller/content/model/JournalModel.java
  src/main/java/run/halo/app/controller/content/model/PhotoModel.java
  src/main/java/run/halo/app/controller/content/model/PostModel.java
  src/main/java/run/halo/app/controller/content/model/TagModel.java
  src/main/java/run/halo/app/controller/core/CommonController.java
Labels: enhancement

#620 Modify the address of the default comment plugin.
  src/main/java/run/halo/app/model/properties/CommentProperties.java
Labels: enhancement

#626 Fix a fatal filter bug
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/java/run/halo/app/filter/CorsFilter.java
  src/main/java/run/halo/app/filter/LogFilter.java
  src/main/java/run/halo/app/security/filter/AbstractAuthenticationFilter.java
  src/main/java/run/halo/app/security/filter/AdminAuthenticationFilter.java
  src/main/java/run/halo/app/security/filter/ApiAuthenticationFilter.java
  src/main/java/run/halo/app/security/filter/ContentFilter.java
Labels: bug, vulnerability

#632 Refactor/meta
  src/main/java/run/halo/app/controller/content/model/PostModel.java
  src/main/java/run/halo/app/controller/content/model/SheetModel.java
  src/main/java/run/halo/app/core/freemarker/tag/PostTagDirective.java
  src/main/java/run/halo/app/model/params/PostParam.java
  src/main/java/run/halo/app/model/params/SheetParam.java
  src/main/java/run/halo/app/model/vo/PostDetailVO.java
  src/main/java/run/halo/app/model/vo/PostListVO.java
  src/main/java/run/halo/app/model/vo/SheetDetailVO.java
  src/main/java/run/halo/app/security/filter/AbstractAuthenticationFilter.java
  src/main/java/run/halo/app/service/PostService.java
  src/main/java/run/halo/app/service/SheetService.java
  src/main/java/run/halo/app/service/base/BaseMetaService.java
  src/main/java/run/halo/app/service/impl/BaseMetaServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/main/java/run/halo/app/service/impl/SheetServiceImpl.java
Labels: enhancement

#633 Remove/recovery api
  src/main/java/run/halo/app/controller/admin/api/RecoveryController.java
  src/main/java/run/halo/app/security/filter/AdminAuthenticationFilter.java
  src/main/java/run/halo/app/service/RecoveryService.java
  src/main/java/run/halo/app/service/impl/RecoveryServiceImpl.java
Labels: enhancement

#635 Refactor post month path type.
  src/main/java/run/halo/app/service/impl/PostCommentServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
Labels: enhancement

#636 Refactor attachment month path.
  src/main/java/run/halo/app/handler/file/LocalFileHandler.java
Labels: enhancement

#639 optimize FileHandler's logic
  src/main/java/run/halo/app/exception/RepeatTypeException.java
  src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
  src/main/java/run/halo/app/handler/file/BaiduBosFileHandler.java
  src/main/java/run/halo/app/handler/file/FileHandler.java
  src/main/java/run/halo/app/handler/file/FileHandlers.java
  src/main/java/run/halo/app/handler/file/LocalFileHandler.java
  src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
  src/main/java/run/halo/app/handler/file/SmmsFileHandler.java
  src/main/java/run/halo/app/handler/file/TencentCosFileHandler.java
  src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
  src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
Labels: enhancement

#641 Fix rss invaid char error.
  src/main/java/run/halo/app/controller/content/ContentFeedController.java
  src/main/resources/application-dev.yaml
  src/main/resources/templates/common/web/atom.ftl
  src/main/resources/templates/common/web/rss.ftl
Labels: bug

#638 Refactor hibernate column build.
  src/main/java/run/halo/app/handler/file/LocalFileHandler.java
  src/main/java/run/halo/app/listener/StartedListener.java
  src/main/java/run/halo/app/model/dto/StatisticWithUserDTO.java
  src/main/java/run/halo/app/model/entity/Attachment.java
  src/main/java/run/halo/app/model/entity/BaseComment.java
  src/main/java/run/halo/app/model/entity/BaseEntity.java
  src/main/java/run/halo/app/model/entity/BaseMeta.java
  src/main/java/run/halo/app/model/entity/BasePost.java
  src/main/java/run/halo/app/model/entity/Category.java
  src/main/java/run/halo/app/model/entity/CommentBlackList.java
  src/main/java/run/halo/app/model/entity/Journal.java
  src/main/java/run/halo/app/model/entity/Link.java
  src/main/java/run/halo/app/model/entity/Log.java
  src/main/java/run/halo/app/model/entity/Menu.java
  src/main/java/run/halo/app/model/entity/Option.java
  src/main/java/run/halo/app/model/entity/Photo.java
  src/main/java/run/halo/app/model/entity/PostCategory.java
  src/main/java/run/halo/app/model/entity/PostTag.java
  src/main/java/run/halo/app/model/entity/Tag.java
  src/main/java/run/halo/app/model/entity/ThemeSetting.java
  src/main/java/run/halo/app/model/entity/User.java
  src/main/java/run/halo/app/model/params/BaseMetaParam.java
  src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
  src/main/resources/migration/V3__migrate_1.3.0-beta.1_to_1.3.0-beta.2.sql
Labels: enhancement

#657 Add Index on photos.team
  src/main/java/run/halo/app/model/entity/Photo.java
Labels: enhancement

#655 Add Index on menus.parent_id
  src/main/java/run/halo/app/model/entity/Menu.java
Labels: enhancement

#651 Add Index on links.name
  src/main/java/run/halo/app/model/entity/Link.java
Labels: enhancement

#664 Update readme.
  README.md
Labels: enhancement

#668 Add Index on logs.create_time
  src/main/java/run/halo/app/model/entity/Log.java
Labels: enhancement

#671 Add Index on post_categories.post_id and post_categories.category_id
  src/main/java/run/halo/app/model/entity/PostCategory.java
Labels: enhancement

#675 Add Index on post_tags.post_id and post_tags.tag.id
  src/main/java/run/halo/app/model/entity/PostTag.java
Labels: enhancement

#681 Add Index on theme_settings.setting_key and theme_settings.theme_id
  src/main/java/run/halo/app/model/entity/ThemeSetting.java
Labels: enhancement

#676 Fix post query sql.
  src/main/java/run/halo/app/repository/PostRepository.java
Labels: bug

#677 Fix #547
  src/main/java/run/halo/app/controller/content/api/JournalController.java
  src/main/java/run/halo/app/controller/content/api/PostController.java
  src/main/java/run/halo/app/controller/content/api/SheetController.java
Labels: bug

#672 Add data export and import api.
  src/main/java/run/halo/app/controller/admin/api/AdminController.java
  src/main/java/run/halo/app/controller/admin/api/BackupController.java
  src/main/java/run/halo/app/controller/admin/api/DataProcessController.java
  src/main/java/run/halo/app/controller/admin/api/InstallController.java
  src/main/java/run/halo/app/controller/admin/api/MailController.java
  src/main/java/run/halo/app/controller/admin/api/MigrateController.java
  src/main/java/run/halo/app/controller/admin/api/OptionController.java
  src/main/java/run/halo/app/controller/admin/api/ThemeController.java
  src/main/java/run/halo/app/controller/admin/api/UserController.java
  src/main/java/run/halo/app/exception/RepeatTypeException.java
  src/main/java/run/halo/app/handler/file/FileHandler.java
  src/main/java/run/halo/app/handler/file/FileHandlers.java
  src/main/java/run/halo/app/handler/migrate/HaloMigrateHandler.java
  src/main/java/run/halo/app/handler/migrate/OldVersionMigrateHandler.java
  src/main/java/run/halo/app/mail/AbstractMailService.java
  src/main/java/run/halo/app/model/entity/Attachment.java
  src/main/java/run/halo/app/model/entity/BaseComment.java
  src/main/java/run/halo/app/model/entity/BaseMeta.java
  src/main/java/run/halo/app/model/entity/BasePost.java
  src/main/java/run/halo/app/model/entity/Category.java
  src/main/java/run/halo/app/model/entity/CommentBlackList.java
  src/main/java/run/halo/app/model/entity/Journal.java
  src/main/java/run/halo/app/model/entity/Link.java
  src/main/java/run/halo/app/model/entity/Log.java
  src/main/java/run/halo/app/model/entity/Menu.java
  src/main/java/run/halo/app/model/entity/Option.java
  src/main/java/run/halo/app/model/entity/Photo.java
  src/main/java/run/halo/app/model/entity/PostCategory.java
  src/main/java/run/halo/app/model/entity/PostTag.java
  src/main/java/run/halo/app/model/entity/Tag.java
  src/main/java/run/halo/app/model/entity/ThemeSetting.java
  src/main/java/run/halo/app/model/entity/support/CustomIdGenerator.java
  src/main/java/run/halo/app/model/enums/MigrateType.java
  src/main/java/run/halo/app/security/filter/AdminAuthenticationFilter.java
  src/main/java/run/halo/app/service/BackupService.java
  src/main/java/run/halo/app/service/CommentBlackListService.java
  src/main/java/run/halo/app/service/ThemeSettingService.java
  src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
  src/main/java/run/halo/app/utils/ImageUtils.java
  src/main/java/run/halo/app/utils/ReflectionUtils.java
  src/main/resources/migration/V4__migrate_1.3.0-beta.2_to_1.3.0-beta.3.sql
Labels: enhancement

#684 Add Index on posts.(type,status) and posts.create_time
  src/main/java/run/halo/app/model/entity/BasePost.java
Labels: enhancement

#687 Refactor backup service.
  src/main/java/run/halo/app/config/properties/HaloProperties.java
  src/main/java/run/halo/app/controller/admin/api/BackupController.java
  src/main/java/run/halo/app/controller/admin/api/DataProcessController.java
  src/main/java/run/halo/app/listener/StartedListener.java
  src/main/java/run/halo/app/model/dto/BackupDTO.java
  src/main/java/run/halo/app/model/entity/PostCategory.java
  src/main/java/run/halo/app/model/support/HaloConst.java
  src/main/java/run/halo/app/service/BackupService.java
  src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
Labels: enhancement

#689 feat: #598
  src/main/java/run/halo/app/core/freemarker/tag/CategoryTagDirective.java
  src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
Labels: enhancement

#691 Support custom email templates.
  src/main/java/run/halo/app/listener/comment/CommentEventListener.java
  src/main/resources/templates/common/mail_template/mail_notice.ftl
  src/main/resources/templates/common/mail_template/mail_reply.ftl
Labels: enhancement

#694 Update readme.
  README.md
Labels: enhancement

#696 Update readme.
  README.md
Labels: enhancement

#697 Refactor independent sheet.
  src/main/java/run/halo/app/controller/admin/api/SheetController.java
  src/main/java/run/halo/app/model/dto/IndependentSheetDTO.java
  src/main/java/run/halo/app/service/SheetService.java
  src/main/java/run/halo/app/service/impl/SheetServiceImpl.java
Labels: enhancement

#698 Refactor get database version.
  src/main/java/run/halo/app/listener/StartedListener.java
  src/main/java/run/halo/app/model/support/HaloConst.java
  src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
Labels: enhancement

#705 Fix #703
  src/main/java/run/halo/app/service/impl/StatisticServiceImpl.java
Labels: bug

#708 Fix installation bug
  src/main/java/run/halo/app/security/filter/ContentFilter.java
Labels: bug

#710 WIP: Provide static mapping feature
  src/main/java/run/halo/app/cache/InMemoryCacheStore.java
  src/main/java/run/halo/app/config/HaloRequestMappingHandlerMapping.java
  src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
  src/main/java/run/halo/app/controller/admin/api/StaticStorageController.java
  src/main/java/run/halo/app/event/StaticStorageChangedEvent.java
  src/main/java/run/halo/app/factory/StringToEnumConverterFactory.java
  src/main/java/run/halo/app/handler/file/SmmsFileHandler.java
  src/main/java/run/halo/app/model/enums/AttachmentType.java
  src/main/java/run/halo/app/model/enums/BanStatusEnum.java
  src/main/java/run/halo/app/model/enums/CommentViolationTypeEnum.java
  src/main/java/run/halo/app/model/enums/DataType.java
  src/main/java/run/halo/app/model/enums/GlobalPathType.java
  src/main/java/run/halo/app/model/enums/MigrateType.java
  src/main/java/run/halo/app/model/enums/OptionType.java
  src/main/java/run/halo/app/model/enums/PostEditorType.java
  src/main/java/run/halo/app/model/enums/PostPermalinkType.java
  src/main/java/run/halo/app/model/enums/StaticDeployType.java
  src/main/java/run/halo/app/model/properties/UpOssProperties.java
  src/main/java/run/halo/app/security/filter/AbstractAuthenticationFilter.java
  src/main/java/run/halo/app/service/StaticStorageService.java
  src/main/java/run/halo/app/service/impl/OptionServiceImpl.java
  src/main/java/run/halo/app/service/impl/StaticStorageServiceImpl.java
Labels: enhancement

#711 update some chinese descriptions
  src/test/java/run/halo/app/controller/DisableOnConditionController.java
Labels: bug

#718 添加attachments.media_type索引加快相关查询速度
  src/main/java/run/halo/app/model/entity/Attachment.java
Labels: enhancement

#719 Refactor extra properties in build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#727 添加photos.create_time索引加快相关查询速度
  src/main/java/run/halo/app/model/entity/Photo.java
Labels: enhancement

#731 新增DateTimeUtils
  src/main/java/run/halo/app/service/impl/CommentBlackListServiceImpl.java
  src/main/java/run/halo/app/utils/DateTimeUtils.java
  src/test/java/run/halo/app/utils/DateTimeUtilsTest.java
Labels: enhancement

#732 Upgrade fastjson dependency.
  build.gradle
Labels: enhancement

#735 Add switch type for theme settings.
  src/main/java/run/halo/app/handler/theme/config/impl/YamlThemeConfigResolverImpl.java
  src/main/java/run/halo/app/model/enums/InputType.java
Labels: enhancement
