Repository halo-dev/halo, pull requests merged in 2020-12, with the labels that each got.

#1173 feat: #1103
  src/main/java/run/halo/app/controller/content/ContentContentController.java
  src/main/java/run/halo/app/model/enums/PostPermalinkType.java
  src/main/java/run/halo/app/service/impl/PostCommentServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
Labels: enhancement

#1177 feat: #1174
  src/main/java/run/halo/app/controller/content/ContentContentController.java
  src/main/java/run/halo/app/model/enums/SheetPermalinkType.java
  src/main/java/run/halo/app/model/properties/PermalinkProperties.java
  src/main/java/run/halo/app/service/OptionService.java
  src/main/java/run/halo/app/service/impl/OptionServiceImpl.java
  src/main/java/run/halo/app/service/impl/SheetCommentServiceImpl.java
  src/main/java/run/halo/app/service/impl/SheetServiceImpl.java
Labels: enhancement

#1184 Upgrade dependencies
  .github/workflows/gradle.yml
  .travis.yml
  Dockerfile
  build.gradle
  src/main/java/run/halo/app/Application.java
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/java/run/halo/app/config/HaloMvcConfiguration.java
  src/main/java/run/halo/app/config/HaloRequestMappingHandlerMapping.java
  src/main/java/run/halo/app/config/SwaggerConfiguration.java
  src/main/resources/application-demo.yaml
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: dependencies

#1190 Chore/remove redis cache store
  build.gradle
  src/main/java/run/halo/app/cache/RedisCacheStore.java
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/resources/application-user.yaml
Labels: dependencies

#1191 Make more friendly error track
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/run/halo/app/controller/core/CommonController.java
  src/main/java/run/halo/app/core/ControllerExceptionHandler.java
  src/main/java/run/halo/app/core/ControllerLogAop.java
  src/main/java/run/halo/app/filter/LogFilter.java
  src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
  src/main/java/run/halo/app/handler/file/BaiduBosFileHandler.java
  src/main/java/run/halo/app/handler/file/FileHandler.java
  src/main/java/run/halo/app/handler/file/FileHandlers.java
  src/main/java/run/halo/app/handler/file/HuaweiObsFileHandler.java
  src/main/java/run/halo/app/handler/file/LocalFileHandler.java
  src/main/java/run/halo/app/handler/file/MinioFileHandler.java
  src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
  src/main/java/run/halo/app/handler/file/SmmsFileHandler.java
  src/main/java/run/halo/app/handler/file/TencentCosFileHandler.java
  src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
  src/main/java/run/halo/app/utils/ImageUtils.java
  src/main/resources/application.yaml
Labels: bug

#1207 fix bug for issue#1200
  src/main/java/run/halo/app/task/RecycledPostCleaningTask.java
Labels: bug

#1203 feat: #1160.
  src/main/java/run/halo/app/model/params/JournalParam.java
Labels: enhancement

#1209 fix: #1180
  src/main/java/run/halo/app/controller/admin/api/ThemeController.java
Labels: bug

#1210 feat: #766
  src/main/java/run/halo/app/controller/content/api/CategoryController.java
  src/main/java/run/halo/app/controller/content/api/TagController.java
Labels: enhancement
