Repository halo-dev/halo, pull requests merged in 2020-01, with the labels that each got.

#494 feat: add leveldb cache store impl
  build.gradle
  src/main/java/run/halo/app/cache/LevelCacheStore.java
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/java/run/halo/app/config/properties/HaloProperties.java
  src/main/resources/application-dev.yaml
  src/test/java/run/halo/app/cache/CacheStoreTest.java
Labels: enhancement

#465 feat:(add comment blacklist)
  src/main/java/run/halo/app/controller/content/api/PostController.java
  src/main/java/run/halo/app/model/entity/CommentBlackList.java
  src/main/java/run/halo/app/model/enums/BanStatusEnum.java
  src/main/java/run/halo/app/model/enums/CommentViolationTypeEnum.java
  src/main/java/run/halo/app/model/properties/CommentProperties.java
  src/main/java/run/halo/app/repository/CommentBlackListRepository.java
  src/main/java/run/halo/app/repository/PostCommentRepository.java
  src/main/java/run/halo/app/service/CommentBlackListService.java
  src/main/java/run/halo/app/service/PostCommentService.java
  src/main/java/run/halo/app/service/impl/CommentBlackListServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostCommentServiceImpl.java
Labels: enhancement

#499 Fix vulnerability due to uncheck theme id
  src/main/java/run/halo/app/utils/FileUtils.java
Labels: vulnerability

#489 fix: #489
  .github/FUNDING.yml
  src/main/java/run/halo/app/controller/content/ContentArchiveController.java
  src/main/java/run/halo/app/controller/content/ContentIndexController.java
  src/main/java/run/halo/app/controller/content/model/PostModel.java
  src/main/java/run/halo/app/model/vo/AdjacentPostVO.java
  src/main/java/run/halo/app/repository/base/BasePostRepository.java
  src/main/java/run/halo/app/service/PostService.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/main/java/run/halo/app/service/impl/StaticPageServiceImpl.java
Labels: enhancement

#503 feat: create theme content api.
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/java/run/halo/app/controller/content/ContentArchiveController.java
  src/main/java/run/halo/app/controller/content/ContentContentController.java
  src/main/java/run/halo/app/controller/content/ContentIndexController.java
  src/main/java/run/halo/app/controller/content/api/ArchiveController.java
  src/main/java/run/halo/app/controller/content/api/CategoryController.java
  src/main/java/run/halo/app/controller/content/api/JournalController.java
  src/main/java/run/halo/app/controller/content/api/LinkController.java
  src/main/java/run/halo/app/controller/content/api/MenuController.java
  src/main/java/run/halo/app/controller/content/api/OptionController.java
  src/main/java/run/halo/app/controller/content/api/PostController.java
  src/main/java/run/halo/app/controller/content/api/SheetController.java
  src/main/java/run/halo/app/controller/content/api/StatisticController.java
  src/main/java/run/halo/app/controller/content/api/TagController.java
  src/main/java/run/halo/app/controller/content/api/ThemeController.java
  src/main/java/run/halo/app/controller/content/api/UserController.java
  src/main/java/run/halo/app/controller/content/model/PostModel.java
  src/main/java/run/halo/app/model/enums/BanStatusEnum.java
  src/main/java/run/halo/app/model/enums/CommentViolationTypeEnum.java
  src/main/java/run/halo/app/model/properties/CommentProperties.java
  src/main/java/run/halo/app/model/vo/AdjacentPostVO.java
  src/main/java/run/halo/app/repository/PostCommentRepository.java
  src/main/java/run/halo/app/repository/base/BasePostRepository.java
  src/main/java/run/halo/app/service/CommentBlackListService.java
  src/main/java/run/halo/app/service/PostService.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/main/java/run/halo/app/service/impl/StaticPageServiceImpl.java
Labels: enhancement

#506 refactor: WordPress data import
  build.gradle
  src/main/java/run/halo/app/handler/migrate/WordPressMigrateHandler.java
  src/main/java/run/halo/app/handler/migrate/converter/Converter.java
  src/main/java/run/halo/app/handler/migrate/converter/WordPressConverter.java
  src/main/java/run/halo/app/handler/migrate/support/vo/PostVO.java
  src/main/java/run/halo/app/handler/migrate/support/wordpress/Channel.java
  src/main/java/run/halo/app/handler/migrate/support/wordpress/Comment.java
  src/main/java/run/halo/app/handler/migrate/support/wordpress/Item.java
  src/main/java/run/halo/app/handler/migrate/support/wordpress/Rss.java
  src/main/java/run/halo/app/handler/migrate/support/wordpress/WpCategory.java
  src/main/java/run/halo/app/handler/migrate/utils/PropertyMappingTo.java
  src/main/java/run/halo/app/handler/migrate/utils/RelationMapperUtils.java
  src/main/java/run/halo/app/utils/WordPressMigrateUtils.java
  src/main/java/run/halo/app/utils/XmlMigrateUtils.java
  src/test/java/run/halo/app/utils/XmlMigrateUtilsTest.java
  src/test/resources/wordpressdemo.xml
Labels: enhancement

#525 Enable github ci on pull request
  .github/workflows/gradle.yml
Labels: enhancement

#523 Uncomment content url mappings
  src/main/java/run/halo/app/controller/content/ContentContentController.java
Labels: bug

#527 Close file input stream after reading image file
  src/main/java/run/halo/app/handler/file/LocalFileHandler.java
Labels: bug

#528 Fix test error
  src/main/resources/application-test.yaml
  src/test/java/run/halo/app/cache/CacheStoreTest.java
Labels: bug
