Repository halo-dev/halo, pull requests merged in 2020-02, with the labels that each got.

#535 feat: support set theme static source path type.
  src/main/java/run/halo/app/listener/freemarker/FreemarkerConfigAwareListener.java
  src/main/java/run/halo/app/model/enums/GlobalPathType.java
  src/main/java/run/halo/app/model/properties/OtherProperties.java
Labels: enhancement

#536 Fix wordpress importor.
  src/main/java/run/halo/app/handler/migrate/WordPressMigrateHandler.java
  src/main/java/run/halo/app/handler/migrate/converter/WordPressConverter.java
  src/main/java/run/halo/app/handler/migrate/support/wordpress/Comment.java
  src/main/java/run/halo/app/handler/migrate/support/wordpress/Item.java
  src/main/java/run/halo/app/handler/migrate/utils/PropertyMappingTo.java
  src/main/java/run/halo/app/utils/XmlMigrateUtils.java
Labels: bug

#537 feat: support freemarker template Inheritance #534
  build.gradle
  src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
Labels: enhancement

#538 feat: change themes assets base path
  src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
  src/main/java/run/halo/app/listener/freemarker/FreemarkerConfigAwareListener.java
Labels: enhancement

#540 style: collate configuration files.
  src/main/resources/application-dev.yaml
  src/main/resources/application-user.yaml
  src/main/resources/application.yaml
Labels: enhancement

#539 feat: support set attachment path type.
  src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
Labels: enhancement

#550 Configure halo.workDir into application-test.yaml
  src/main/resources/application-test.yaml
Labels: bug

#554 Fix #553
  src/main/java/run/halo/app/listener/freemarker/FreemarkerConfigAwareListener.java
  src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
Labels: bug

#556 Fix #517
  src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
Labels: bug

#558 Add custom RequestMappingHandlerMapping for enable static resources access
  src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
  src/main/java/run/halo/app/controller/content/ContentArchiveController.java
  src/main/java/run/halo/app/controller/content/ContentContentController.java
Labels: duplicate, enhancement

#566 Fix admin index page redirect
  src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
  src/main/java/run/halo/app/controller/content/MainController.java
  src/test/java/run/halo/app/conf/AntPathMatcherTest.java
Labels: bug

#565 Fix backup function
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/java/run/halo/app/config/properties/HaloProperties.java
  src/main/java/run/halo/app/controller/admin/api/BackupController.java
  src/main/java/run/halo/app/filter/CorsFilter.java
  src/main/java/run/halo/app/listener/StartedListener.java
  src/main/java/run/halo/app/model/enums/Mode.java
  src/main/java/run/halo/app/model/support/HaloConst.java
  src/main/java/run/halo/app/security/filter/AbstractAuthenticationFilter.java
  src/main/java/run/halo/app/security/filter/AdminAuthenticationFilter.java
  src/main/java/run/halo/app/security/filter/ApiAuthenticationFilter.java
  src/main/java/run/halo/app/security/filter/ContentFilter.java
  src/main/java/run/halo/app/security/service/OneTimeTokenService.java
  src/main/java/run/halo/app/security/service/impl/OneTimeTokenServiceImpl.java
  src/main/java/run/halo/app/security/util/SecurityUtils.java
  src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
  src/main/resources/application-test.yaml
  src/test/java/run/halo/app/security/OneTimeTokenTest.java
Labels: bug, enhancement

#571 Refactor halo mode
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/java/run/halo/app/config/properties/HaloProperties.java
  src/main/java/run/halo/app/model/enums/Mode.java
  src/main/java/run/halo/app/security/filter/AbstractAuthenticationFilter.java
  src/main/java/run/halo/app/security/filter/AdminAuthenticationFilter.java
  src/main/java/run/halo/app/security/filter/ApiAuthenticationFilter.java
  src/main/java/run/halo/app/security/filter/ContentFilter.java
  src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-test.yaml
Labels: enhancement

#569 feat: add basic functions of demo mode
  src/main/java/run/halo/app/controller/admin/api/AdminController.java
  src/main/java/run/halo/app/controller/admin/api/OptionController.java
  src/main/java/run/halo/app/controller/admin/api/UserController.java
  src/main/java/run/halo/app/handler/aspect/DisableOnConditionAspect.java
  src/main/java/run/halo/app/model/annotation/DisableOnCondition.java
  src/main/java/run/halo/app/model/enums/Mode.java
  src/main/resources/application-demo.yaml
  src/test/java/run/halo/app/controller/DisableOnConditionController.java
  src/test/java/run/halo/app/handler/aspect/DisableOnConditionAspectTest.java
Labels: enhancement

#574 Support set thumbnail to category and tag.
  src/main/java/run/halo/app/model/annotation/DisableOnCondition.java
  src/main/java/run/halo/app/model/dto/CategoryDTO.java
  src/main/java/run/halo/app/model/dto/TagDTO.java
  src/main/java/run/halo/app/model/entity/Category.java
  src/main/java/run/halo/app/model/entity/Tag.java
  src/main/java/run/halo/app/model/params/CategoryParam.java
  src/main/java/run/halo/app/model/params/PostParam.java
  src/main/java/run/halo/app/model/params/SheetParam.java
  src/main/java/run/halo/app/model/params/TagParam.java
  src/main/java/run/halo/app/model/support/HaloConst.java
Labels: enhancement

#575 Organize configuration files.
  src/main/resources/application-demo.yaml
Labels: bug

#578 Fix installation on the first startup
  src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
  src/main/java/run/halo/app/security/filter/AbstractAuthenticationFilter.java
Labels: bug

#581 Fix file upload exception
  src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
  src/main/java/run/halo/app/handler/file/BaiduBosFileHandler.java
  src/main/java/run/halo/app/handler/file/FileHandler.java
  src/main/java/run/halo/app/handler/file/FileHandlers.java
  src/main/java/run/halo/app/handler/file/LocalFileHandler.java
  src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
  src/main/java/run/halo/app/handler/file/SmmsFileHandler.java
  src/main/java/run/halo/app/handler/file/TencentCosFileHandler.java
  src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
  src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
  src/main/resources/application.yaml
Labels: bug

#583 Fix typo about login translate
  CHANGELOG.md
  src/main/java/run/halo/app/model/params/LoginParam.java
  src/main/java/run/halo/app/security/filter/AdminAuthenticationFilter.java
  src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
Labels: bug

#584 Refactor email service and remove oh-my-email dependency
  build.gradle
  src/main/java/run/halo/app/controller/admin/api/MailController.java
  src/main/java/run/halo/app/listener/comment/CommentEventListener.java
  src/main/java/run/halo/app/mail/AbstractMailService.java
  src/main/java/run/halo/app/mail/MailProperties.java
  src/main/java/run/halo/app/mail/MailSenderFactory.java
  src/main/java/run/halo/app/mail/MailService.java
  src/main/java/run/halo/app/mail/MailServiceImpl.java
  src/main/java/run/halo/app/model/properties/PropertyEnum.java
  src/main/java/run/halo/app/service/OptionService.java
  src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
  src/main/java/run/halo/app/service/impl/MailServiceImpl.java
  src/main/java/run/halo/app/service/impl/OptionServiceImpl.java
Labels: bug, enhancement

#587 Fix #549
  src/main/java/run/halo/app/controller/content/MainController.java
  src/main/java/run/halo/app/utils/HaloUtils.java
  src/test/java/run/halo/app/utils/HaloUtilsTest.java
Labels: bug

#563 [WIP] Feature/custom url
  src/main/java/run/halo/app/controller/admin/api/PostController.java
  src/main/java/run/halo/app/controller/admin/api/SheetController.java
  src/main/java/run/halo/app/controller/content/ContentArchiveController.java
  src/main/java/run/halo/app/controller/content/ContentContentController.java
  src/main/java/run/halo/app/controller/content/ContentJournalController.java
  src/main/java/run/halo/app/controller/content/ContentSearchController.java
  src/main/java/run/halo/app/controller/content/ContentSheetController.java
  src/main/java/run/halo/app/controller/content/model/CategoryModel.java
  src/main/java/run/halo/app/controller/content/model/JournalModel.java
  src/main/java/run/halo/app/controller/content/model/PhotoModel.java
  src/main/java/run/halo/app/controller/content/model/PostModel.java
  src/main/java/run/halo/app/controller/content/model/SheetModel.java
  src/main/java/run/halo/app/controller/content/model/TagModel.java
  src/main/java/run/halo/app/core/freemarker/tag/CategoryTagDirective.java
  src/main/java/run/halo/app/core/freemarker/tag/PostTagDirective.java
  src/main/java/run/halo/app/core/freemarker/tag/TagTagDirective.java
  src/main/java/run/halo/app/listener/comment/CommentEventListener.java
  src/main/java/run/halo/app/listener/freemarker/FreemarkerConfigAwareListener.java
  src/main/java/run/halo/app/model/properties/PermalinkProperties.java
  src/main/java/run/halo/app/model/properties/PropertyEnum.java
  src/main/java/run/halo/app/model/properties/SheetProperties.java
  src/main/java/run/halo/app/service/OptionService.java
  src/main/java/run/halo/app/service/PostCommentService.java
  src/main/java/run/halo/app/service/PostService.java
  src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
  src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
  src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
  src/main/java/run/halo/app/service/impl/OptionServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostCategoryServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostCommentServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostTagServiceImpl.java
  src/main/java/run/halo/app/service/impl/SheetCommentServiceImpl.java
  src/main/java/run/halo/app/service/impl/SheetServiceImpl.java
  src/main/java/run/halo/app/service/impl/TagServiceImpl.java
  src/main/resources/templates/common/error/error.ftl
  src/main/resources/templates/common/mail_template/mail_reply.ftl
  src/main/resources/templates/common/template/post_password.ftl
  src/main/resources/templates/common/web/atom.ftl
  src/main/resources/templates/common/web/readme.ftl
  src/main/resources/templates/common/web/robots.ftl
  src/main/resources/templates/common/web/rss.ftl
  src/main/resources/templates/common/web/sitemap_html.ftl
  src/main/resources/templates/common/web/sitemap_xml.ftl
Labels: enhancement

#593 Stop supporting admin folder mapping in workspace.
  src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
Labels: enhancement

#595 Support category feed.
  src/main/java/run/halo/app/controller/content/ContentFeedController.java
  src/main/resources/templates/common/web/atom.ftl
  src/main/resources/templates/common/web/rss.ftl
Labels: enhancement

#600 Refactor installation data.
  src/main/java/run/halo/app/controller/admin/api/InstallController.java
Labels: enhancement

#605 Add editorType for post.
  src/main/java/run/halo/app/controller/admin/api/SheetController.java
  src/main/java/run/halo/app/controller/content/model/PostModel.java
  src/main/java/run/halo/app/controller/content/model/SheetModel.java
  src/main/java/run/halo/app/model/dto/post/BasePostMinimalDTO.java
  src/main/java/run/halo/app/model/entity/BasePost.java
  src/main/java/run/halo/app/model/enums/PostEditorType.java
  src/main/java/run/halo/app/model/params/PostParam.java
  src/main/java/run/halo/app/model/params/SheetParam.java
  src/main/java/run/halo/app/model/properties/OtherProperties.java
  src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
Labels: enhancement
