Repository halo-dev/halo, pull requests merged in 2020-07, with the labels that each got.

#942 chore(deps): change undertow to jetty.
  build.gradle
Labels: dependencies

#835 fix issue 515&592
  build.gradle
  src/main/java/run/halo/app/controller/admin/api/ThemeController.java
  src/main/java/run/halo/app/service/ThemeService.java
  src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
  src/main/java/run/halo/app/utils/FileUtils.java
  src/main/java/run/halo/app/utils/GitUtils.java
  src/main/java/run/halo/app/utils/GithubUtils.java
  src/test/java/run/halo/app/service/impl/OptionServiceImplTest.java
  src/test/java/run/halo/app/service/impl/ThemeServiceImplTest.java
  src/test/java/run/halo/app/utils/GitTest.java
  src/test/java/run/halo/app/utils/GithubUtilsTest.java
Labels: enhancement

#943 Upgrade spring boot dependency and change some mockito tests
  build.gradle
  src/test/java/run/halo/app/aspect/DisableOnConditionAspectTest.java
  src/test/java/run/halo/app/aspect/SensitiveConcealAspectTest.java
  src/test/java/run/halo/app/cache/CacheStoreTest.java
  src/test/java/run/halo/app/cache/InMemoryCacheStoreTest.java
  src/test/java/run/halo/app/conf/AntPathMatcherTest.java
  src/test/java/run/halo/app/handler/theme/YamlThemePropertyResolverTest.java
  src/test/java/run/halo/app/model/MediaTypeTest.java
  src/test/java/run/halo/app/model/dto/base/InputConverterTest.java
  src/test/java/run/halo/app/model/dto/base/OutputConverterTest.java
  src/test/java/run/halo/app/model/enums/AttachmentTypeTest.java
  src/test/java/run/halo/app/model/enums/DataTypeTest.java
  src/test/java/run/halo/app/model/params/InstallParamTest.java
  src/test/java/run/halo/app/model/properties/PropertyEnumTest.java
  src/test/java/run/halo/app/repository/SheetRepositoryTest.java
  src/test/java/run/halo/app/security/OneTimeTokenTest.java
  src/test/java/run/halo/app/service/RecoveryServiceTest.java
  src/test/java/run/halo/app/service/impl/OptionServiceImplTest.java
  src/test/java/run/halo/app/service/impl/PostServiceImplTest.java
  src/test/java/run/halo/app/service/impl/ThemeServiceImplTest.java
  src/test/java/run/halo/app/service/support/HaloMediaTypeTest.java
  src/test/java/run/halo/app/utils/BcryptTest.java
  src/test/java/run/halo/app/utils/BeanUtilsTest.java
  src/test/java/run/halo/app/utils/DateTimeUtilsTest.java
  src/test/java/run/halo/app/utils/DirectoryAttackTest.java
  src/test/java/run/halo/app/utils/FileUtilsTest.java
  src/test/java/run/halo/app/utils/FilenameUtilsTest.java
  src/test/java/run/halo/app/utils/GitTest.java
  src/test/java/run/halo/app/utils/GithubTest.java
  src/test/java/run/halo/app/utils/GithubUtilsTest.java
  src/test/java/run/halo/app/utils/HaloUtilsTest.java
  src/test/java/run/halo/app/utils/InetAddressTest.java
  src/test/java/run/halo/app/utils/JsonUtilsTest.java
  src/test/java/run/halo/app/utils/LocalDateTimeTest.java
  src/test/java/run/halo/app/utils/PathTest.java
  src/test/java/run/halo/app/utils/PathsTest.java
  src/test/java/run/halo/app/utils/ReflectionUtilsTest.java
  src/test/java/run/halo/app/utils/SlugUtilsTest.java
  src/test/java/run/halo/app/utils/TimeUnitTest.java
  src/test/java/run/halo/app/utils/TwoFactorAuthUtilsTest.java
  src/test/java/run/halo/app/utils/URITest.java
  src/test/java/run/halo/app/utils/YamlTest.java
Labels: dependencies

#952 perfect: Link random order display,listByRandom and listTeamsByRandom.
  src/main/java/run/halo/app/core/freemarker/tag/LinkTagDirective.java
  src/main/java/run/halo/app/service/LinkService.java
  src/main/java/run/halo/app/service/impl/LinkServiceImpl.java
Labels: enhancement

#954 修改缓存时长
  src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
Labels: enhancement

#956 如果系统设置了http代理则创建httpClient时设置代理
  build.gradle
  src/main/java/run/halo/app/utils/HttpClientUtils.java
  src/test/java/run/halo/app/utils/HttpClientUtilsTest.java
Labels: enhancement

#960 chore: add zxing dependency.
  build.gradle
Labels: bug

#970 Add iterable objects validation
  src/main/java/run/halo/app/utils/ValidationUtils.java
  src/test/java/run/halo/app/utils/ValidationUtilsTest.java
Labels: enhancement

#962 Make some unnecessary error detail hide
  src/main/java/run/halo/app/controller/content/ContentFeedController.java
  src/main/java/run/halo/app/core/ControllerExceptionHandler.java
  src/main/java/run/halo/app/security/handler/DefaultAuthenticationFailureHandler.java
  src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
  src/main/java/run/halo/app/utils/GitUtils.java
Labels: enhancement

#981 fix: #822
  src/main/java/run/halo/app/controller/content/api/PostController.java
  src/main/java/run/halo/app/controller/content/api/SheetController.java
Labels: bug

#979 fix: #853
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
  src/main/java/run/halo/app/model/support/HaloConst.java
  src/main/resources/application.yaml
Labels: bug

#983 fix error description
  src/main/java/run/halo/app/service/impl/StaticPageServiceImpl.java
Labels: bug
