Repository halo-dev/halo, pull requests merged in 2021-01, with the labels that each got.

#1212 Replace travis ci with github action
  .github/workflows/gradle.yml
  .github/workflows/halo.yml
  .travis.yml
  Dockerfile
  build.gradle
Labels: enhancement

#1236 feat: support custom post password template.
  src/main/java/run/halo/app/controller/content/model/PostModel.java
  src/main/java/run/halo/app/model/support/HaloConst.java
  src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
  src/main/resources/templates/common/web/readme.ftl
Labels: enhancement

#1237 pref: clean unnecessary code.
  src/main/java/run/halo/app/cache/AbstractCacheStore.java
  src/main/java/run/halo/app/cache/InMemoryCacheStore.java
  src/main/java/run/halo/app/cache/LevelCacheStore.java
  src/main/java/run/halo/app/config/properties/HaloProperties.java
  src/main/java/run/halo/app/controller/admin/api/AdminController.java
  src/main/java/run/halo/app/core/CommonResultControllerAdvice.java
  src/main/java/run/halo/app/factory/StringToEnumConverterFactory.java
  src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
  src/main/java/run/halo/app/handler/file/HuaweiObsFileHandler.java
  src/main/java/run/halo/app/handler/file/MinioFileHandler.java
  src/main/java/run/halo/app/model/support/HaloConst.java
  src/main/java/run/halo/app/service/AdminService.java
  src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
  src/main/java/run/halo/app/service/impl/BaseMetaServiceImpl.java
  src/main/java/run/halo/app/service/impl/LinkServiceImpl.java
  src/main/java/run/halo/app/service/impl/MenuServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostMetaServiceImpl.java
  src/main/java/run/halo/app/service/impl/SheetMetaServiceImpl.java
  src/main/java/run/halo/app/utils/Version.java
  src/test/java/run/halo/app/utils/GithubTest.java
Labels: enhancement

#1242 fix: #1214.
  build.gradle
  src/main/resources/application.yaml
Labels: bug

#1217 Fix theme updation error
  build.gradle
  src/main/java/run/halo/app/config/HaloMvcConfiguration.java
  src/main/java/run/halo/app/controller/admin/api/ThemeController.java
  src/main/java/run/halo/app/core/ControllerLogAop.java
  src/main/java/run/halo/app/exception/ThemeUpToDateException.java
  src/main/java/run/halo/app/handler/file/LocalFileHandler.java
  src/main/java/run/halo/app/handler/theme/config/support/ThemeProperty.java
  src/main/java/run/halo/app/listener/StartedListener.java
  src/main/java/run/halo/app/mail/AbstractMailService.java
  src/main/java/run/halo/app/mail/MailServiceImpl.java
  src/main/java/run/halo/app/repository/ThemeRepository.java
  src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java
  src/main/java/run/halo/app/service/ThemeService.java
  src/main/java/run/halo/app/service/TraceService.java
  src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
  src/main/java/run/halo/app/theme/GitThemeFetcher.java
  src/main/java/run/halo/app/theme/GitThemeUpdater.java
  src/main/java/run/halo/app/theme/MultipartFileThemeUpdater.java
  src/main/java/run/halo/app/theme/MultipartZipFileThemeFetcher.java
  src/main/java/run/halo/app/theme/ThemeFetcher.java
  src/main/java/run/halo/app/theme/ThemeFetcherComposite.java
  src/main/java/run/halo/app/theme/ThemeMetaLocator.java
  src/main/java/run/halo/app/theme/ThemePropertyScanner.java
  src/main/java/run/halo/app/theme/ThemeUpdater.java
  src/main/java/run/halo/app/theme/ZipThemeFetcher.java
  src/main/java/run/halo/app/utils/FileUtils.java
  src/main/java/run/halo/app/utils/GitUtils.java
  src/main/java/run/halo/app/utils/RemoteGitHelper.java
  src/test/java/run/halo/app/theme/GitThemeFetcherTest.java
  src/test/java/run/halo/app/theme/ZipThemeFetcherTest.java
  src/test/java/run/halo/app/utils/FileUtilsTest.java
  src/test/java/run/halo/app/utils/GitTest.java
Labels: bug, enhancement

#1248 Refactor Dockerfile with layered jar
  .github/workflows/halo.yml
  Dockerfile
  build.gradle
Labels: enhancement

#1249 Fix folder copy error: ProviderMismatchException
  src/main/java/run/halo/app/utils/FileUtils.java
Labels: bug

#1246 fix: unable to access custom sheet.
  src/main/java/run/halo/app/controller/content/ContentContentController.java
Labels: bug

#1215 doc: add document website.
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  src/main/java/run/halo/app/controller/admin/api/InstallController.java
Labels: enhancement

#1235 feat:#1225
  src/main/java/run/halo/app/controller/admin/api/AdminController.java
  src/main/java/run/halo/app/controller/admin/api/CategoryController.java
  src/main/java/run/halo/app/controller/admin/api/MigrateController.java
  src/main/java/run/halo/app/controller/admin/api/PostController.java
  src/main/java/run/halo/app/controller/content/ContentContentController.java
  src/main/java/run/halo/app/controller/content/api/CategoryController.java
  src/main/java/run/halo/app/controller/content/model/CategoryModel.java
  src/main/java/run/halo/app/controller/content/model/PostModel.java
  src/main/java/run/halo/app/core/freemarker/tag/CategoryTagDirective.java
  src/main/java/run/halo/app/core/freemarker/tag/PostTagDirective.java
  src/main/java/run/halo/app/exception/UnsupportedException.java
  src/main/java/run/halo/app/model/dto/CategoryDTO.java
  src/main/java/run/halo/app/model/entity/Category.java
  src/main/java/run/halo/app/model/enums/EncryptTypeEnum.java
  src/main/java/run/halo/app/model/params/CategoryParam.java
  src/main/java/run/halo/app/repository/PostCategoryRepository.java
  src/main/java/run/halo/app/service/AuthenticationService.java
  src/main/java/run/halo/app/service/AuthorizationService.java
  src/main/java/run/halo/app/service/CategoryService.java
  src/main/java/run/halo/app/service/PostCategoryService.java
  src/main/java/run/halo/app/service/PostService.java
  src/main/java/run/halo/app/service/impl/AuthenticationServiceImpl.java
  src/main/java/run/halo/app/service/impl/AuthorizationServiceImpl.java
  src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
  src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostCategoryServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/main/resources/templates/common/template/post_password.ftl
Labels: enhancement
