Repository halo-dev/halo, pull requests merged in 2021-07, with the labels that each got.

#1415 fix: api parameter names in the post list content api.
  src/main/java/run/halo/app/controller/content/api/PostController.java
Labels: bug

#1426 fix: incorrect comment count statistics. #1411
  src/main/java/run/halo/app/repository/JournalCommentRepository.java
  src/main/java/run/halo/app/repository/PostCommentRepository.java
  src/main/java/run/halo/app/repository/SheetCommentRepository.java
  src/main/java/run/halo/app/repository/base/BaseCommentRepository.java
Labels: bug

#1427 fix: #1417
  src/main/java/run/halo/app/config/HaloMvcConfiguration.java
  src/main/resources/application.yaml
Labels: vulnerability

#1430 文件删除失败无响应的问题修复
  src/main/java/run/halo/app/handler/file/LocalFileHandler.java
  src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
  src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
Labels: lgtm

#1436 fix: the keyword and categoryId parameters of the post list api are required #1432
  CHANGELOG.md
  src/main/java/run/halo/app/controller/content/api/PostController.java
Labels: lgtm

#1438 fix: deleting a non-picture file throws an exception.
  CHANGELOG.md
  src/main/java/run/halo/app/handler/file/LocalFileHandler.java
Labels: bug

#1440 fix: add region for operate minio attachment
  src/main/java/run/halo/app/handler/file/MinioFileHandler.java
  src/main/java/run/halo/app/model/properties/MinioProperties.java
Labels: enhancement, lgtm
