Repository halo-dev/halo, pull requests merged in 2021-11, with the labels that each got.

#1510 Refactor docker release in GitHub workflow
  .github/workflows/halo.yml
Labels: enhancement

#1511 Set the final version with tag name when releasing
  .github/workflows/halo.yml
  build.gradle
  gradle.properties
Labels: enhancement

#1515 feat: add photo teams api in content api
  src/main/java/run/halo/app/controller/content/api/PhotoController.java
Labels: enhancement

#1526 Fix the problem of updating categories and menus in batch
  src/main/java/run/halo/app/controller/admin/api/MenuController.java
  src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
  src/main/java/run/halo/app/service/impl/MenuServiceImpl.java
Labels: bug, confirmation-pending

#1527 Support querying multi post statuses
  src/main/java/run/halo/app/controller/content/api/PostController.java
  src/main/java/run/halo/app/model/params/PostQuery.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
Labels: enhancement, lgtm

#1537 Support photo likes
  src/main/java/run/halo/app/controller/admin/api/PhotoController.java
  src/main/java/run/halo/app/model/dto/PhotoDTO.java
  src/main/java/run/halo/app/model/entity/Photo.java
  src/main/java/run/halo/app/repository/PhotoRepository.java
  src/main/java/run/halo/app/service/PhotoService.java
  src/main/java/run/halo/app/service/impl/PhotoServiceImpl.java
Labels: enhancement

#1536 Add api for modifying journal comment content
  src/main/java/run/halo/app/controller/admin/api/JournalCommentController.java
Labels: enhancement

#1540 Fixed a bug that did not clear access rights when the password of private posts or categories was changed
  src/main/java/run/halo/app/cache/CacheStore.java
  src/main/java/run/halo/app/cache/InMemoryCacheStore.java
  src/main/java/run/halo/app/cache/LevelCacheStore.java
  src/main/java/run/halo/app/service/impl/AuthorizationServiceImpl.java
  src/test/java/run/halo/app/cache/InMemoryCacheStoreTest.java
  src/test/java/run/halo/app/service/impl/AuthorizationServiceImplTest.java
Labels: bug

#1535 Mark email as not required parameter in BaseComment
  src/main/java/run/halo/app/model/entity/BaseComment.java
  src/main/java/run/halo/app/model/params/BaseCommentParam.java
  src/main/java/run/halo/app/service/impl/BaseCommentServiceImpl.java
  src/main/resources/migration/V5__migrate_remove_notnull_for_email_in_comments_table.sql
  src/test/java/run/halo/app/it/BaseApiTest.java
  src/test/java/run/halo/app/it/PostCommentApiTest.java
  src/test/java/run/halo/app/model/params/validation/PostCommentParamValidationTest.java
  src/test/java/run/halo/app/service/impl/PostCommentServiceImplTest.java
Labels: enhancement, lgtm
