Repository halo-dev/halo, pull requests merged in 2021-06, with the labels that each got.

#1390 fix: #1386
  src/main/java/run/halo/app/service/CategoryService.java
  src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
  src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
Labels: bug

#1396 fix: #1394
  src/main/java/run/halo/app/controller/admin/api/InstallController.java
  src/test/java/run/halo/app/it/IndexPageRequestTest.java
Labels: bug

#1402 fix(security): freemarker SSTI vulnerability.
  src/main/java/run/halo/app/listener/freemarker/FreemarkerConfigAwareListener.java
Labels: vulnerability

#1401 chore(deps): upgrade spring-boot to 2.5.1
  build.gradle
Labels: dependencies

#1406 feat: MarkDown supports footnote rendering
  build.gradle
  src/main/java/run/halo/app/utils/FootnoteNodeRendererInterceptor.java
  src/main/java/run/halo/app/utils/MarkdownUtils.java
  src/test/java/run/halo/app/utils/FootnoteNodeRendererInterceptorTest.java
  src/test/java/run/halo/app/utils/MarkdownUtilsTest.java
Labels: enhancement
