Repository halo-dev/halo, pull requests merged in 2021-03, with the labels that each got.

#1289 Upgrade spring boot version
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
  src/main/java/run/halo/app/config/HaloMvcConfiguration.java
  src/main/java/run/halo/app/config/properties/HaloProperties.java
  src/main/java/run/halo/app/controller/content/ContentContentController.java
  src/main/java/run/halo/app/controller/core/CommonController.java
  src/main/java/run/halo/app/controller/error/DefaultErrorController.java
  src/main/java/run/halo/app/controller/error/DefaultErrorViewResolver.java
  src/main/java/run/halo/app/core/CommonResultControllerAdvice.java
  src/main/java/run/halo/app/exception/ThemeNotFoundException.java
  src/main/java/run/halo/app/listener/StartedListener.java
  src/main/java/run/halo/app/listener/freemarker/FreemarkerConfigAwareListener.java
  src/main/java/run/halo/app/model/support/HaloConst.java
  src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java
  src/main/java/run/halo/app/service/impl/OptionServiceImpl.java
  src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
  src/main/resources/application.yaml
  src/main/resources/templates/common/error/404.ftl
  src/main/resources/templates/common/error/500.ftl
  src/main/resources/templates/common/error/error.ftl
  src/test/java/run/halo/app/repository/ThemeRepositoryImplTest.java
  src/test/java/run/halo/app/utils/GitTest.java
Labels: dependencies

#1298 Make more tolerant of reading image
  src/main/java/run/halo/app/handler/file/LocalFileHandler.java
Labels: bug

#1300 Fix error for updating activated theme
  src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java
Labels: bug

#1301 Fix error about response committed
  build.gradle
  src/main/java/run/halo/app/security/filter/ContentFilter.java
  src/main/java/run/halo/app/service/impl/AuthorizationServiceImpl.java
  src/test/java/run/halo/app/it/BaseApiTest.java
  src/test/java/run/halo/app/it/IndexPageRequestTest.java
  src/test/resources/application-test.yaml
Labels: bug

#1303 Refactor system configuration
  src/main/java/run/halo/app/aspect/DisableOnConditionAspect.java
  src/main/java/run/halo/app/aspect/SensitiveConcealAspect.java
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/java/run/halo/app/config/properties/HaloProperties.java
  src/main/java/run/halo/app/listener/StartedListener.java
  src/main/java/run/halo/app/model/enums/Mode.java
  src/main/java/run/halo/app/security/filter/AbstractAuthenticationFilter.java
  src/main/java/run/halo/app/security/filter/AdminAuthenticationFilter.java
  src/main/java/run/halo/app/security/filter/ApiAuthenticationFilter.java
  src/main/resources/application-demo.yaml
  src/main/resources/application-dev.yaml
  src/main/resources/application-user.yaml
  src/main/resources/application.yaml
Labels: enhancement

#1315 feat: #1313
  src/main/resources/templates/common/web/rss.ftl
Labels: enhancement

#1324 Upgrade to Spring Boot 2.5.0-M3
  build.gradle
Labels: dependencies

#1328 feat: enable swagger configuration in development.
  src/main/java/run/halo/app/config/SwaggerConfiguration.java
  src/main/java/run/halo/app/config/properties/HaloProperties.java
  src/main/java/run/halo/app/listener/StartedListener.java
  src/main/resources/application-dev.yaml
Labels: enhancement

#1325 Automate attribute converter
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/java/run/halo/app/config/attributeconverter/AttributeConverterAutoGenerateConfiguration.java
  src/main/java/run/halo/app/config/attributeconverter/AttributeConverterAutoGenerator.java
  src/main/java/run/halo/app/config/attributeconverter/AttributeConverterInterceptor.java
  src/main/java/run/halo/app/config/attributeconverter/AutoGenerateConverterPersistenceUnitPostProcessor.java
  src/main/java/run/halo/app/model/entity/Journal.java
  src/main/java/run/halo/app/model/enums/JournalType.java
  src/main/java/run/halo/app/model/enums/PostType.java
  src/main/java/run/halo/app/model/enums/ValueEnum.java
  src/main/java/run/halo/app/model/enums/converter/AbstractConverter.java
  src/main/java/run/halo/app/model/enums/converter/AttachmentTypeConverter.java
  src/main/java/run/halo/app/model/enums/converter/CommentStatusConverter.java
  src/main/java/run/halo/app/model/enums/converter/DataTypeConverter.java
  src/main/java/run/halo/app/model/enums/converter/LogTypeConverter.java
  src/main/java/run/halo/app/model/enums/converter/PostStatusConverter.java
  src/main/java/run/halo/app/model/enums/converter/PostTypeConverter.java
  src/main/java/run/halo/app/service/OptionService.java
  src/main/java/run/halo/app/service/impl/OptionServiceImpl.java
  src/test/java/run/halo/app/attributeconverter/AttributeConverterApplyTest.java
  src/test/java/run/halo/app/attributeconverter/City.java
  src/test/java/run/halo/app/attributeconverter/CityLevel.java
  src/test/java/run/halo/app/attributeconverter/CityRepository.java
Labels: enhancement

#1327 fix: #1311
  src/main/java/run/halo/app/repository/base/BaseCommentRepository.java
  src/main/java/run/halo/app/service/base/BaseCommentService.java
  src/main/java/run/halo/app/service/impl/BaseCommentServiceImpl.java
  src/main/java/run/halo/app/service/impl/JournalServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/main/java/run/halo/app/service/impl/SheetServiceImpl.java
Labels: bug

#1331 feat: #1036
  src/main/java/run/halo/app/controller/admin/api/DataProcessController.java
  src/main/java/run/halo/app/model/dto/BaseCommentDTO.java
  src/main/java/run/halo/app/model/properties/CommentProperties.java
  src/main/java/run/halo/app/service/AttachmentService.java
  src/main/java/run/halo/app/service/DataProcessService.java
  src/main/java/run/halo/app/service/OptionService.java
  src/main/java/run/halo/app/service/PhotoService.java
  src/main/java/run/halo/app/service/ThemeSettingService.java
  src/main/java/run/halo/app/service/base/BaseCommentService.java
  src/main/java/run/halo/app/service/base/BasePostService.java
  src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
  src/main/java/run/halo/app/service/impl/BaseCommentServiceImpl.java
  src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
  src/main/java/run/halo/app/service/impl/DataProcessServiceImpl.java
  src/main/java/run/halo/app/service/impl/JournalCommentServiceImpl.java
  src/main/java/run/halo/app/service/impl/OptionServiceImpl.java
  src/main/java/run/halo/app/service/impl/PhotoServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostCommentServiceImpl.java
  src/main/java/run/halo/app/service/impl/SheetCommentServiceImpl.java
  src/main/java/run/halo/app/service/impl/ThemeSettingServiceImpl.java
Labels: enhancement

#1332 fix: incorrect number of children comment.
  src/main/java/run/halo/app/repository/base/BaseCommentRepository.java
  src/main/java/run/halo/app/service/impl/BaseCommentServiceImpl.java
Labels: bug

#1333 feat: add gravatar source field for comment options api.
  src/main/java/run/halo/app/controller/content/api/OptionController.java
Labels: enhancement

#1334 chore: remove deprecated code.
  build.gradle
  src/main/java/run/halo/app/controller/admin/api/AdminController.java
  src/main/java/run/halo/app/controller/admin/api/ThemeController.java
  src/main/java/run/halo/app/model/dto/StatisticDTO.java
  src/main/java/run/halo/app/service/AdminService.java
  src/main/java/run/halo/app/service/ThemeService.java
  src/main/java/run/halo/app/service/ThemeSettingService.java
  src/main/java/run/halo/app/service/base/BaseCommentService.java
  src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
  src/main/java/run/halo/app/service/impl/MenuServiceImpl.java
  src/main/java/run/halo/app/service/impl/OptionServiceImpl.java
  src/main/java/run/halo/app/service/impl/StatisticServiceImpl.java
  src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
  src/main/java/run/halo/app/service/impl/TraceServiceImpl.java
  src/main/java/run/halo/app/service/impl/UserServiceImpl.java
  src/main/java/run/halo/app/utils/GitUtils.java
  src/main/java/run/halo/app/utils/GithubUtils.java
  src/test/java/run/halo/app/security/OneTimeTokenTest.java
  src/test/java/run/halo/app/utils/GithubUtilsTest.java
Labels: enhancement

#1335 chore(deps): upgrade ali oss sdk dependency.
  build.gradle
Labels: dependencies
