Repository halo-dev/halo, pull requests merged in 2021-12, with the labels that each got.

#1554 Add cherry_pick_pull.sh for cherry-picking pull request
  CONTRIBUTING.md
  hack/cherry_pick_pull.sh
Labels: enhancement

#1564 Add a batch creation api for photos
  src/main/java/run/halo/app/controller/admin/api/PhotoController.java
Labels: enhancement

#1566 Tag support color options
  src/main/java/run/halo/app/model/dto/TagDTO.java
  src/main/java/run/halo/app/model/entity/Tag.java
  src/main/java/run/halo/app/model/params/TagParam.java
  src/main/java/run/halo/app/model/support/HaloConst.java
Labels: enhancement

#1571 Remove prefix v of tag name when releasing a new version
  .github/workflows/halo.yml
Labels: bug

#1582 Add some apis for group obtain theme configurations and setting items
  src/main/java/run/halo/app/controller/admin/api/ThemeController.java
  src/main/java/run/halo/app/service/ThemeService.java
  src/main/java/run/halo/app/service/ThemeSettingService.java
  src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
  src/main/java/run/halo/app/service/impl/ThemeSettingServiceImpl.java
Labels: enhancement

#1589 fix: huawei obs upload file address is incorrect
  src/main/java/run/halo/app/handler/file/HuaweiObsFileHandler.java
Labels: bug

#1567 Include posts that under the subcategories when getting posts b…
  src/main/java/run/halo/app/model/projection/CategoryPostCountProjection.java
  src/main/java/run/halo/app/model/vo/CategoryVO.java
  src/main/java/run/halo/app/repository/PostCategoryRepository.java
  src/main/java/run/halo/app/service/CategoryService.java
  src/main/java/run/halo/app/service/PostCategoryService.java
  src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostCategoryServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/test/java/run/halo/app/service/impl/CategoryServiceTest.java
Labels: enhancement

#1604 fix: Log4j Security Vulnerabilities
  build.gradle
Labels: dependencies

#1602 Bump version of dependencies
  build.gradle
  settings.gradle
Labels: dependencies
