Repository halo-dev/halo, pull requests merged in 2022-07, with the labels that each got.

#2204 Implement Extension reconciliation mechanism
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/core/extension/reconciler/UserReconciler.java
  src/main/java/run/halo/app/extension/DefaultExtensionClient.java
  src/main/java/run/halo/app/extension/ExtensionClient.java
  src/main/java/run/halo/app/extension/Watcher.java
  src/main/java/run/halo/app/extension/WatcherPredicates.java
  src/main/java/run/halo/app/extension/controller/Controller.java
  src/main/java/run/halo/app/extension/controller/ControllerBuilder.java
  src/main/java/run/halo/app/extension/controller/ControllerManager.java
  src/main/java/run/halo/app/extension/controller/DefaultController.java
  src/main/java/run/halo/app/extension/controller/DefaultDelayQueue.java
  src/main/java/run/halo/app/extension/controller/ExtensionWatcher.java
  src/main/java/run/halo/app/extension/controller/Reconciler.java
  src/main/java/run/halo/app/extension/controller/RequestQueue.java
  src/main/java/run/halo/app/extension/controller/RequestSynchronizer.java
  src/main/java/run/halo/app/extension/store/ExtensionStoreClientJPAImpl.java
  src/main/java/run/halo/app/security/SuperAdminInitializer.java
  src/main/resources/application-dev.yaml
  src/test/java/run/halo/app/PathPrefixPredicateTest.java
  src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
  src/test/java/run/halo/app/extension/FakeExtension.java
  src/test/java/run/halo/app/extension/controller/ControllerBuilderTest.java
  src/test/java/run/halo/app/extension/controller/DefaultControllerTest.java
  src/test/java/run/halo/app/extension/controller/DefaultDelayQueueTest.java
  src/test/java/run/halo/app/extension/controller/DelayedEntryTest.java
  src/test/java/run/halo/app/extension/controller/ExtensionWatcherTest.java
  src/test/java/run/halo/app/extension/controller/RequestSynchronizerTest.java
  src/test/java/run/halo/app/security/SuperAdminInitializerTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2195 perf: optimize the update logic of post editTime field
  src/main/java/run/halo/app/controller/admin/api/PostController.java
  src/main/java/run/halo/app/model/params/BasePostParam.java
  src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
Labels: lgtm, release-note-none, approved, kind/improvement

#2207 Fix directory traversal issue while renaming static file
  src/main/java/run/halo/app/utils/FileUtils.java
  src/test/java/run/halo/app/utils/FileUtilsTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#2211 refactor: plugin custom api generate rules
  src/main/java/run/halo/app/core/extension/Role.java
  src/main/java/run/halo/app/plugin/PluginRequestMappingHandlerMapping.java
  src/main/java/run/halo/app/security/authorization/Attributes.java
  src/main/java/run/halo/app/security/authorization/AttributesRecord.java
  src/main/java/run/halo/app/security/authorization/RbacRequestEvaluation.java
  src/main/java/run/halo/app/security/authorization/RequestInfo.java
  src/main/java/run/halo/app/security/authorization/RequestInfoFactory.java
  src/test/java/run/halo/app/plugin/PluginRequestMappingHandlerMappingTest.java
  src/test/java/run/halo/app/security/authorization/PolicyRuleTest.java
  src/test/java/run/halo/app/security/authorization/RequestInfoResolverTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2209 Revert huaweicloud-sdk-java-obs from 3.21.8.1 to 3.21.4
  build.gradle
  src/test/java/run/halo/app/handler/file/HuaweiObsSdkTest.java
Labels: kind/bug, lgtm, kind/regression, area/core, approved, release-note

#2217 Add rolebinding reconciler to reset role names of users
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/core/extension/reconciler/RoleBindingReconciler.java
  src/test/java/run/halo/app/core/extension/reconciler/RoleBindingReconcilerTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2222 refactor: JSON serialize exception
  src/main/java/run/halo/app/infra/utils/JsonParseException.java
  src/main/java/run/halo/app/infra/utils/JsonUtils.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2223 Add support for custom endpoints
  docs/developer-guide/custom-endpoint.md
  src/main/java/run/halo/app/config/WebFluxConfig.java
  src/main/java/run/halo/app/core/extension/endpoint/CustomEndpoint.java
  src/main/java/run/halo/app/core/extension/endpoint/CustomEndpointsBuilder.java
  src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, kind/api-change, approved

#2221 feat: add plugin reconciler
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/plugin/PluginInitializationLoadOnApplicationReady.java
  src/main/java/run/halo/app/plugin/PluginLifeCycleManagerController.java
  src/main/java/run/halo/app/plugin/PluginService.java
  src/main/java/run/halo/app/plugin/PluginServiceImpl.java
  src/main/java/run/halo/app/security/authorization/DefaultRuleResolver.java
  src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
  src/test/java/run/halo/app/plugin/PluginLifeCycleManagerControllerTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2227 refactor: allow additional headers for session CORS login
  src/main/java/run/halo/app/config/WebServerSecurityConfig.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2235 Change optimization into improvement in PR template
  .github/pull_request_template.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2236 Refactor CICD for Halo next
  .github/workflows/halo.yaml
  .github/workflows/halo.yml
  .github/workflows/needs-more-info-closer.yml
  .github/workflows/on-comment.yml
  .github/workflows/on-label.yml
  Dockerfile
  build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2232 feat: add configmap extension
  src/main/java/run/halo/app/extension/ConfigMap.java
  src/test/java/run/halo/app/extension/ConfigMapTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2238 feat: add plugin setting support
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/core/extension/Setting.java
  src/main/java/run/halo/app/infra/SchemeInitializer.java
  src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
  src/main/java/run/halo/app/plugin/SettingFetcher.java
  src/test/java/run/halo/app/core/extension/SettingTest.java
  src/test/java/run/halo/app/plugin/SettingFetcherTest.java
  src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2239 Add an endpoint to grant permissions to user
  src/main/java/run/halo/app/core/extension/Role.java
  src/main/java/run/halo/app/core/extension/RoleBinding.java
  src/main/java/run/halo/app/core/extension/User.java
  src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  src/main/java/run/halo/app/core/extension/reconciler/RoleBindingReconciler.java
  src/main/java/run/halo/app/extension/ExtensionOperator.java
  src/test/java/run/halo/app/core/extension/RoleBindingTest.java
  src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
  src/test/java/run/halo/app/core/extension/reconciler/RoleBindingReconcilerTest.java
  src/test/java/run/halo/app/extension/ExtensionOperatorTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, kind/api-change, approved

#2241 Add checkout-from parameter for composite action
  .github/workflows/halo.yaml
Labels: kind/bug, lgtm, release-note-none, approved

#2240 feat: add an API to fetch user permissions
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/core/extension/Role.java
  src/main/java/run/halo/app/core/extension/User.java
  src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  src/main/java/run/halo/app/core/extension/reconciler/RoleBindingReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/RoleReconciler.java
  src/main/java/run/halo/app/core/extension/service/DefaultRoleService.java
  src/main/java/run/halo/app/core/extension/service/RoleService.java
  src/main/java/run/halo/app/core/extension/service/UserService.java
  src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
  src/main/java/run/halo/app/infra/utils/JsonUtils.java
  src/main/java/run/halo/app/security/authorization/DefaultRuleResolver.java
  src/test/java/run/halo/app/core/extension/TestRole.java
  src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
  src/test/java/run/halo/app/core/extension/reconciler/RoleBindingReconcilerTest.java
  src/test/java/run/halo/app/core/extension/reconciler/RoleReconcilerTest.java
  src/test/java/run/halo/app/core/extension/service/DefaultRoleServiceTest.java
  src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2243 refactor: the value structure of ConfigMap for Setting custom extension
  src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  src/main/java/run/halo/app/plugin/SettingFetcher.java
  src/test/java/run/halo/app/plugin/SettingFetcherTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2244 Refactor the response structure of Extension list API
  src/main/java/run/halo/app/extension/DefaultExtensionClient.java
  src/main/java/run/halo/app/extension/ExtensionClient.java
  src/main/java/run/halo/app/extension/ExtensionRouterFunctionFactory.java
  src/main/java/run/halo/app/extension/ListResult.java
  src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
  src/test/java/run/halo/app/extension/ExtensionListHandlerTest.java
Labels: lgtm, release-note-none, area/core, kind/api-change, approved, kind/improvement

#2242 refactor: the way of plugin initialize load
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/infra/ExtensionResourceInitializer.java
  src/main/java/run/halo/app/infra/properties/HaloProperties.java
  src/main/java/run/halo/app/plugin/PluginLoadedListener.java
  src/main/java/run/halo/app/plugin/PluginStartedListener.java
  src/main/java/run/halo/app/plugin/YamlPluginFinder.java
  src/test/java/run/halo/app/infra/ExtensionResourceInitializerTest.java
  src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
  src/test/resources/plugin/plugin.yaml
  src/test/resources/plugin/test-unstructured-resource-loader.jar
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2247 refactor: super administrator role has all UI permissions
  src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  src/main/java/run/halo/app/security/SuperAdminInitializer.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2248 Create super admin initializer and run extension controllers conditionally
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  src/main/java/run/halo/app/extension/controller/ControllerManager.java
  src/main/java/run/halo/app/infra/properties/ExtensionProperties.java
  src/main/java/run/halo/app/infra/properties/HaloProperties.java
  src/main/java/run/halo/app/infra/properties/SecurityProperties.java
  src/main/java/run/halo/app/security/SuperAdminInitializer.java
  src/test/java/run/halo/app/security/SuperAdminInitializerTest.java
  src/test/resources/application.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/failing-test, kind/improvement

#2255 feat: plugin class is registered as a bean at startup
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/plugin/BasePlugin.java
  src/main/java/run/halo/app/plugin/BasePluginFactory.java
  src/main/java/run/halo/app/plugin/HaloPluginManager.java
  src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
  src/main/java/run/halo/app/plugin/YamlPluginDescriptorFinder.java
  src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
  src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2250 Add an API to change password of user
  src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  src/main/java/run/halo/app/core/extension/service/UserService.java
  src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
  src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
  src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2249 refactor: scanning of the jsBundleRule for plugins
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/plugin/resources/JsBundleRuleProvider.java
  src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
  src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
  src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactoryTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2259 perf: access to admin page changed to template rendering
  src/main/java/run/halo/app/controller/content/MainController.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2264 Change image name to halo-dev
  .github/workflows/halo.yaml
Labels: lgtm, kind/flake, release-note-none, approved

#2262 feat: add plugin initial resource cleanup when plugin stop
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/plugin/HaloPluginManager.java
  src/main/java/run/halo/app/plugin/PluginApplicationContext.java
  src/main/java/run/halo/app/plugin/PluginBeforeStopSyncListener.java
  src/main/java/run/halo/app/plugin/PluginStartedListener.java
  src/main/java/run/halo/app/plugin/YamlPluginFinder.java
  src/main/java/run/halo/app/plugin/event/HaloPluginBeforeStopEvent.java
  src/test/java/run/halo/app/core/extension/reconciler/RoleReconcilerTest.java
  src/test/java/run/halo/app/plugin/PluginStartedListenerTest.java
  src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2267 Refactor deletion of Extension in Extension client
  src/main/java/run/halo/app/extension/DefaultExtensionClient.java
  src/main/java/run/halo/app/extension/ExtensionRouterFunctionFactory.java
  src/test/java/run/halo/app/config/ExtensionConfigurationTest.java
  src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
  src/test/java/run/halo/app/extension/ExtensionDeleteHandlerTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2269 Upgrade Spring Boot to 3.0.0-M4
  build.gradle
Labels: lgtm, kind/flake, release-note-none, area/core, approved

#2271 Provide an endpoint to install plugin using Jar file
  src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  src/main/java/run/halo/app/infra/properties/HaloProperties.java
  src/main/java/run/halo/app/plugin/PluginProperties.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2272 refactor: plugin components finder to avoid cannot be started after installing the plugin
  src/main/java/run/halo/app/plugin/HaloPluginManager.java
  src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
  src/main/java/run/halo/app/plugin/SpringComponentsFinder.java
  src/test/java/run/halo/app/plugin/SpringComponentsFinderTest.java
  src/test/resources/plugin/test-plugin-components.idx
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2273 Refine Swagger API with group
  src/main/java/run/halo/app/config/SwaggerConfig.java
  src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  src/main/resources/application-dev.yaml
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2274 Initialize required extensions when system starts up
  src/main/java/run/halo/app/infra/ExtensionResourceInitializer.java
  src/main/java/run/halo/app/infra/properties/HaloProperties.java
  src/test/java/run/halo/app/infra/ExtensionResourceInitializerTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2278 Add all-api group for swagger
  src/main/java/run/halo/app/config/SwaggerConfig.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2282 fix: issue of post details page without meta_description variables
  src/main/java/run/halo/app/controller/content/model/PostModel.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#2279 Add label and field selector to Extension list API
  build.gradle
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/extension/ExtensionRouterFunctionFactory.java
  src/main/java/run/halo/app/extension/router/ExtensionCompositeRouterFunction.java
  src/main/java/run/halo/app/extension/router/ExtensionCreateHandler.java
  src/main/java/run/halo/app/extension/router/ExtensionDeleteHandler.java
  src/main/java/run/halo/app/extension/router/ExtensionGetHandler.java
  src/main/java/run/halo/app/extension/router/ExtensionListHandler.java
  src/main/java/run/halo/app/extension/router/ExtensionRouterFunctionFactory.java
  src/main/java/run/halo/app/extension/router/ExtensionUpdateHandler.java
  src/main/java/run/halo/app/extension/router/ListRequest.java
  src/main/java/run/halo/app/extension/router/QueryParamBuildUtil.java
  src/main/java/run/halo/app/extension/router/selector/FieldCriteriaPredicateConverter.java
  src/main/java/run/halo/app/extension/router/selector/LabelCriteriaPredicateConverter.java
  src/main/java/run/halo/app/extension/router/selector/Operator.java
  src/main/java/run/halo/app/extension/router/selector/SelectorConverter.java
  src/main/java/run/halo/app/extension/router/selector/SelectorCriteria.java
  src/main/java/run/halo/app/extension/router/selector/SelectorUtil.java
  src/test/java/run/halo/app/config/ExtensionConfigurationTest.java
  src/test/java/run/halo/app/extension/router/ExtensionCompositeRouterFunctionTest.java
  src/test/java/run/halo/app/extension/router/ExtensionCreateHandlerTest.java
  src/test/java/run/halo/app/extension/router/ExtensionDeleteHandlerTest.java
  src/test/java/run/halo/app/extension/router/ExtensionGetHandlerTest.java
  src/test/java/run/halo/app/extension/router/ExtensionListHandlerTest.java
  src/test/java/run/halo/app/extension/router/ExtensionRouterFunctionFactoryTest.java
  src/test/java/run/halo/app/extension/router/ExtensionUpdateHandlerTest.java
  src/test/java/run/halo/app/extension/router/PathPatternGeneratorTest.java
  src/test/java/run/halo/app/extension/router/selector/FieldCriteriaPredicateConverterTest.java
  src/test/java/run/halo/app/extension/router/selector/LabelCriteriaPredicateConverterTest.java
  src/test/java/run/halo/app/extension/router/selector/OperatorTest.java
  src/test/java/run/halo/app/extension/router/selector/SelectorConverterTest.java
  src/test/java/run/halo/app/extension/router/selector/SelectorUtilTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, kind/api-change, approved
