Repository halo-dev/halo, pull requests merged in 2022-12, with the labels that each got.

#2808 docs: update readme for Halo 2.0.0
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2833 Fix the problem that MySQL complains "Data too long for column 'data' at row 1"
  src/main/resources/schema-mysql.sql
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2840 docs: remove the downloads badge in README
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2835 Bump Halo version in gradle.properties
  gradle.properties
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2865 Add forgotten label for system-reserved roles
  src/main/java/run/halo/app/core/extension/Role.java
  src/main/java/run/halo/app/security/SuperAdminInitializer.java
  src/main/resources/extensions/system-default-role.yaml
Labels: kind/bug, lgtm, area/core, approved, release-note

#2871 Bump halo version to 2.1.0-SNAPSHOT for next release
  gradle.properties
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2872 Set docker image name properly when releasing
  .github/workflows/halo.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2879 Update Halo version to 2.0.1
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2899 feat: improve the quick start section of the readme
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2907 Silent prompt when plugins fail to load in development mode
  src/main/java/run/halo/app/plugin/HaloPluginManager.java
  src/main/java/run/halo/app/plugin/PluginDevelopmentInitializer.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2918 fix: single page does not count visits
  src/main/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategy.java
  src/test/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategyTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#2919 Fix the problem of getting stuck on VM exit
  src/main/java/run/halo/app/metrics/VisitLogWriter.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#2870 refactor: metrics to fix post visits cannot be migrated
  src/main/java/run/halo/app/content/Stats.java
  src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
  src/main/java/run/halo/app/core/extension/Counter.java
  src/main/java/run/halo/app/core/extension/content/Comment.java
  src/main/java/run/halo/app/core/extension/content/Constant.java
  src/main/java/run/halo/app/core/extension/endpoint/TrackerEndpoint.java
  src/main/java/run/halo/app/core/extension/reconciler/CommentReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/ReplyReconciler.java
  src/main/java/run/halo/app/event/post/DownvotedEvent.java
  src/main/java/run/halo/app/event/post/ReplyCreatedEvent.java
  src/main/java/run/halo/app/event/post/ReplyDeletedEvent.java
  src/main/java/run/halo/app/event/post/ReplyEvent.java
  src/main/java/run/halo/app/event/post/UpvotedEvent.java
  src/main/java/run/halo/app/event/post/VisitedEvent.java
  src/main/java/run/halo/app/event/post/VotedEvent.java
  src/main/java/run/halo/app/metrics/CounterMeterHandler.java
  src/main/java/run/halo/app/metrics/CounterService.java
  src/main/java/run/halo/app/metrics/CounterServiceImpl.java
  src/main/java/run/halo/app/metrics/ReplyEventReconciler.java
  src/main/java/run/halo/app/metrics/VisitedEventReconciler.java
  src/main/java/run/halo/app/metrics/VotedEventReconciler.java
  src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  src/main/java/run/halo/app/theme/finders/impl/SinglePageFinderImpl.java
  src/main/java/run/halo/app/theme/finders/vo/StatsVo.java
  src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
  src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
  src/test/java/run/halo/app/core/extension/reconciler/CommentReconcilerTest.java
  src/test/java/run/halo/app/metrics/CounterMeterHandlerTest.java
  src/test/java/run/halo/app/metrics/CounterServiceImplTest.java
  src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2936 perf: change the maximum limit of request body to 10MB
  src/main/resources/application.yaml
Labels: lgtm, approved, release-note, kind/improvement

#2940 fix: plugin logo cannot be loaded when it is not enabled
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/ReverseProxyReconciler.java
  src/test/java/run/halo/app/core/extension/reconciler/ReverseProxyReconcilerTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#2935 Support configuring Halo in working directory
  Dockerfile
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2923 feat: add author pages for theme-side
  src/main/java/run/halo/app/core/extension/User.java
  src/main/java/run/halo/app/core/extension/reconciler/UserReconciler.java
  src/main/java/run/halo/app/infra/AnonymousUserConst.java
  src/main/java/run/halo/app/theme/DefaultTemplateEnum.java
  src/main/java/run/halo/app/theme/finders/ContributorFinder.java
  src/main/java/run/halo/app/theme/finders/PostFinder.java
  src/main/java/run/halo/app/theme/finders/impl/ContributorFinderImpl.java
  src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  src/main/java/run/halo/app/theme/finders/vo/ContributorVo.java
  src/main/java/run/halo/app/theme/finders/vo/ListedPostVo.java
  src/main/java/run/halo/app/theme/finders/vo/ListedSinglePageVo.java
  src/main/java/run/halo/app/theme/finders/vo/UserVo.java
  src/main/java/run/halo/app/theme/router/PermalinkPatternProvider.java
  src/main/java/run/halo/app/theme/router/strategy/AuthorRouteStrategy.java
  src/test/java/run/halo/app/core/extension/reconciler/UserReconcilerTest.java
  src/test/java/run/halo/app/theme/finders/vo/UserVoTest.java
  src/test/java/run/halo/app/theme/router/strategy/AuthorRouteStrategyTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#2942 Support command-line arguments running with Docker
  Dockerfile
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2949 refactor: remove get root application context method from halo plugin manager
  src/main/java/run/halo/app/plugin/BasePlugin.java
  src/main/java/run/halo/app/plugin/HaloPluginManager.java
  src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2925 feat: supports exception page template for theme-side
  src/main/java/run/halo/app/infra/exception/handlers/GlobalErrorWebExceptionHandler.java
  src/main/java/run/halo/app/theme/ThemeResolver.java
  src/main/resources/templates/error/error.html
Labels: kind/feature, lgtm, area/core, approved, release-note

#2954 Fixed the problem that comment reply cannot be displayed in the front end
  src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#2959 feat: archives in descending order by month
  src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
Labels: lgtm, approved, release-note, kind/improvement

#2974 docs: update github workflow badge
  README.md
Labels: lgtm, release-note-none, approved, kind/improvement

#2956 chore: add @minliacom to reviewer list
  OWNERS
Labels: lgtm, release-note-none, approved, kind/improvement

#2957 Change log level to warn for optimistic locking failure error
  src/main/java/run/halo/app/extension/controller/DefaultController.java
Labels: lgtm, release-note-none, approved, kind/improvement

#2977 Bump version to 2.0.2-SNAPSHOT for next release
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#2981 Bump version to 2.0.3-SNAPSHOT for next release
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#2982 Update console ref to release-2.0 for current branch
  .github/workflows/halo.yaml
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#2970 fix: not clearing the template engine cache after upgrading the theme
  src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
  src/main/java/run/halo/app/theme/TemplateEngineManager.java
  src/main/java/run/halo/app/theme/ThemeResolver.java
  src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java
  src/test/java/run/halo/app/core/extension/theme/ThemeEndpointTest.java
Labels: lgtm, release-note-none, approved, kind/improvement

#2964 feat: add reset config API for theme and plugin
  src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
  src/main/java/run/halo/app/core/extension/theme/SettingUtils.java
  src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
  src/main/java/run/halo/app/core/extension/theme/ThemeService.java
  src/main/java/run/halo/app/core/extension/theme/ThemeServiceImpl.java
  src/main/resources/extensions/role-template-plugin.yaml
  src/main/resources/extensions/role-template-theme.yaml
  src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java
  src/test/java/run/halo/app/core/extension/theme/SettingUtilsTest.java
  src/test/java/run/halo/app/core/extension/theme/ThemeEndpointTest.java
  src/test/java/run/halo/app/core/extension/theme/ThemeServiceImplTest.java
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note

#2991 fix: default theme cannot be initialized in the jar distribution
  src/main/java/run/halo/app/infra/DefaultThemeInitializer.java
Labels: lgtm, release-note-none, approved

#3003 fix: page stats does not subscribe in finder
  src/main/java/run/halo/app/theme/finders/impl/SinglePageFinderImpl.java
  src/test/java/run/halo/app/theme/finders/impl/SinglePageFinderImplTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#3012 Clean up unnecessary code in GlobalErrorWebExceptionHandler
  src/main/java/run/halo/app/infra/exception/handlers/GlobalErrorWebExceptionHandler.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#3021 Persist and archive historical logs
  src/main/resources/application.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2995 Support querying sub-categories of any level
  src/main/java/run/halo/app/theme/finders/CategoryFinder.java
  src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
  src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
Labels: kind/feature, lgtm, kind/api-change, approved, release-note

#3031 Upgrade to spring boot 3.0.1
  build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2787 Support MariaDB Native Driver
  build.gradle
  src/main/resources/application-mariadb.yaml
Labels: lgtm, approved, release-note, kind/improvement

#3024 Fix invalid attachment role templates
  src/main/resources/extensions/role-template-attachment.yaml
Labels: kind/bug, lgtm, area/core, approved, release-note

#3028 feat: add annotation setting extension
  src/main/java/run/halo/app/core/extension/AnnotationSetting.java
  src/main/java/run/halo/app/core/extension/Theme.java
  src/main/java/run/halo/app/core/extension/reconciler/AnnotationSettingReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
  src/main/java/run/halo/app/core/extension/theme/ThemeServiceImpl.java
  src/main/java/run/halo/app/core/extension/theme/ThemeUtils.java
  src/main/java/run/halo/app/infra/SchemeInitializer.java
  src/main/resources/extensions/role-template-authenticated.yaml
  src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java
  src/test/java/run/halo/app/core/extension/theme/ThemeServiceImplTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#3051 chore: update default theme package
  src/main/resources/themes/theme-earth.zip
Labels: lgtm, approved, release-note, kind/improvement

#3067 Provide an endpoint to update user profile
  src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  src/main/resources/extensions/role-template-authenticated.yaml
  src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#3068 Avoid NPE problems when querying the list of posts in the console
  src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#3072 feat: add target attribute for menu item
  src/main/java/run/halo/app/core/extension/MenuItem.java
Labels: kind/feature, lgtm, approved, release-note

#3065 refactor: remove finalizer when resources deleted completely
  src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
  src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3074 Cache static resources, including plugin, theme, console, attachment
  src/main/java/run/halo/app/config/WebFluxConfig.java
  src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
  src/main/java/run/halo/app/theme/ThemeConfiguration.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3076 feat: add annotations expression object for thymeleaf
  src/main/java/run/halo/app/theme/dialect/HaloExpressionObjectFactory.java
  src/main/java/run/halo/app/theme/dialect/HaloProcessorDialect.java
  src/main/java/run/halo/app/theme/dialect/expression/Annotations.java
  src/main/java/run/halo/app/theme/finders/vo/CategoryTreeVo.java
  src/main/java/run/halo/app/theme/finders/vo/CategoryVo.java
  src/main/java/run/halo/app/theme/finders/vo/CommentVo.java
  src/main/java/run/halo/app/theme/finders/vo/ExtensionVoOperator.java
  src/main/java/run/halo/app/theme/finders/vo/ListedPostVo.java
  src/main/java/run/halo/app/theme/finders/vo/ListedSinglePageVo.java
  src/main/java/run/halo/app/theme/finders/vo/MenuItemVo.java
  src/main/java/run/halo/app/theme/finders/vo/MenuVo.java
  src/main/java/run/halo/app/theme/finders/vo/ReplyVo.java
  src/main/java/run/halo/app/theme/finders/vo/TagVo.java
  src/main/java/run/halo/app/theme/finders/vo/ThemeVo.java
  src/main/java/run/halo/app/theme/finders/vo/UserVo.java
  src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#3082 chore: bump theme-earth to 1.1.1
  src/main/resources/themes/theme-earth.zip
Labels: lgtm, release-note-none, approved, kind/improvement

#3087 Bump version to 2.2.0-SNAPSHOT for next iteration
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#3085 Update version to 2.0.4-SNAPSHOT for next iteration
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#3086 Bump version to 2.1.1-SNAPSHOT for next iteration
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved
