Repository halo-dev/halo, pull requests merged in 2022-05, with the labels that each got.

#1913 Pass IOException into exception stack instead of ignoring it
  src/main/java/run/halo/app/handler/file/LocalFileHandler.java
Labels: kind/bug, lgtm, area/core, approved

#1908 fix: Accessing the /install interface exposes the administrator interface address
  src/main/java/run/halo/app/controller/content/MainController.java
Labels: kind/bug, lgtm, approved

#1907 Update the path patterns of static files while refreshing
  src/main/java/run/halo/app/service/impl/StaticStorageServiceImpl.java
Labels: kind/feature, lgtm, approved

#1916 Set transaction isolation to read_uncommitted due to @Async
  src/main/java/run/halo/app/listener/comment/CommentEventListener.java
Labels: kind/bug, lgtm, area/core, approved

#1865 feat: Optimized word count for non-Chinese articles
  src/main/java/run/halo/app/model/entity/BasePost.java
  src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
  src/test/java/run/halo/app/service/impl/HTMLWordCountTest.java
Labels: lgtm, area/core, approved

#2071 Upgrade Spring Boot to 3.0.0-M2
  build.gradle
Labels: dependencies, lgtm, area/core, approved

#2076 docs: update README.md and CHANGELOG.md for new version
  CHANGELOG.md
  README.md
  gradle.properties
Labels: lgtm, approved, kind/documentation

#2077 fix: CHANGELOG.md typo
  CHANGELOG.md
Labels: lgtm, approved, kind/documentation

#2078 Add Pull Request template
  .github/pull_request_template.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2081 refactor: remove authorization filter and replace it with the RequestInfoAuthorizationManager
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/HealthyController.java
  src/main/java/run/halo/app/identity/HelloController.java
  src/main/java/run/halo/app/identity/TagController.java
  src/main/java/run/halo/app/identity/TestController.java
  src/main/java/run/halo/app/identity/authorization/RequestInfoAuthorizationManager.java
  src/test/java/run/halo/app/integration/security/RequestInfoAuthorizationManagerTest.java
  src/test/java/run/halo/app/integration/security/TestWebSecurityConfig.java
Labels: lgtm, release-note-none, area/core, approved

#2091 chore: add checkstyle rule
  config/checkstyle/checkstyle.xml
  src/main/java/run/halo/app/identity/authentication/ProviderSettings.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthentication.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationEntryPoint.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationFilter.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationToken.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenError.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenErrors.java
  src/main/java/run/halo/app/identity/authentication/verifier/JwtAuthenticationToken.java
  src/main/java/run/halo/app/identity/authorization/AuthorizingVisitor.java
  src/main/java/run/halo/app/identity/authorization/RequestInfoFactory.java
  src/main/java/run/halo/app/identity/authorization/RoleRef.java
  src/test/java/run/halo/app/authentication/verifyer/BearerTokenAuthenticationTest.java
  src/test/java/run/halo/app/authentication/verifyer/BearerTokenAuthenticationTokenTest.java
  src/test/java/run/halo/app/authentication/verifyer/BearerTokenErrorTest.java
  src/test/java/run/halo/app/authentication/verifyer/BearerTokenErrorsTest.java
  src/test/java/run/halo/app/authentication/verifyer/JwtAuthenticationProviderTest.java
  src/test/java/run/halo/app/authentication/verifyer/JwtGrantedAuthoritiesConverterTest.java
Labels: lgtm, release-note-none, approved, kind/documentation

#2086 Add support for Extension mechanism
  src/main/java/run/halo/app/extension/AbstractExtension.java
  src/main/java/run/halo/app/extension/DefaultExtensionClient.java
  src/main/java/run/halo/app/extension/Extension.java
  src/main/java/run/halo/app/extension/ExtensionClient.java
  src/main/java/run/halo/app/extension/ExtensionConverter.java
  src/main/java/run/halo/app/extension/ExtensionUtil.java
  src/main/java/run/halo/app/extension/GVK.java
  src/main/java/run/halo/app/extension/GroupKind.java
  src/main/java/run/halo/app/extension/GroupVersion.java
  src/main/java/run/halo/app/extension/GroupVersionKind.java
  src/main/java/run/halo/app/extension/JSONExtensionConverter.java
  src/main/java/run/halo/app/extension/Metadata.java
  src/main/java/run/halo/app/extension/Scheme.java
  src/main/java/run/halo/app/extension/Schemes.java
  src/main/java/run/halo/app/extension/exception/ExtensionConvertException.java
  src/main/java/run/halo/app/extension/exception/ExtensionException.java
  src/main/java/run/halo/app/extension/exception/SchemeNotFoundException.java
  src/main/java/run/halo/app/extension/store/ExtensionStore.java
  src/main/java/run/halo/app/extension/store/ExtensionStoreClient.java
  src/main/java/run/halo/app/extension/store/ExtensionStoreClientJPAImpl.java
  src/main/java/run/halo/app/extension/store/ExtensionStoreRepository.java
  src/test/java/run/halo/app/extension/AbstractExtensionTest.java
  src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
  src/test/java/run/halo/app/extension/ExtensionUtilTest.java
  src/test/java/run/halo/app/extension/FakeExtension.java
  src/test/java/run/halo/app/extension/GroupVersionTest.java
  src/test/java/run/halo/app/extension/JSONExtensionConverterTest.java
  src/test/java/run/halo/app/extension/SchemeTest.java
  src/test/java/run/halo/app/extension/SchemesTest.java
  src/test/java/run/halo/app/extension/store/ExtensionStoreClientJPAImplTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#1874 feat: uri encode processing for attachment paths when querying attachments
  src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
  src/test/java/run/halo/app/service/impl/AttachmentServiceImplTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#2093 Add JSON schema generator and validator
  build.gradle
  src/main/java/run/halo/app/extension/JSONExtensionConverter.java
  src/main/java/run/halo/app/extension/Metadata.java
  src/main/java/run/halo/app/extension/Scheme.java
  src/main/java/run/halo/app/extension/Schemes.java
  src/main/java/run/halo/app/extension/exception/SchemaViolationException.java
  src/test/java/run/halo/app/extension/ExtensionUtilTest.java
  src/test/java/run/halo/app/extension/JSONExtensionConverterTest.java
  src/test/java/run/halo/app/extension/SchemeTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2095 feat: add more parameters in mail template.
  src/main/java/run/halo/app/listener/comment/CommentEventListener.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2098 perf: change the resource address of the default comment component library to unpkg.com
  src/main/java/run/halo/app/model/properties/CommentProperties.java
  src/main/resources/templates/common/macro/global_macro.ftl
Labels: lgtm, approved, release-note, kind/improvement

#2102 Upgrade to Spring Boot 3.0.0-M3
  build.gradle
Labels: lgtm, release-note-none, approved, kind/improvement

#2105 Add support for link group and its sort
  src/main/java/run/halo/app/controller/admin/api/LinkController.java
  src/main/java/run/halo/app/model/params/LinkParam.java
  src/main/java/run/halo/app/repository/LinkRepository.java
  src/main/java/run/halo/app/service/impl/LinkServiceImpl.java
Labels: kind/feature, lgtm, kind/api-change, approved, release-note

#2108 feat: add default role binding lister and role getter
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/authorization/DefaultRoleBindingLister.java
  src/main/java/run/halo/app/identity/authorization/DefaultRoleGetter.java
  src/main/java/run/halo/app/identity/authorization/DefaultRuleResolver.java
  src/main/java/run/halo/app/identity/authorization/PolicyRule.java
  src/main/java/run/halo/app/identity/authorization/Role.java
  src/main/java/run/halo/app/identity/authorization/RoleBinding.java
  src/main/java/run/halo/app/identity/authorization/RoleBindingLister.java
  src/main/java/run/halo/app/infra/SchemeInitializer.java
  src/main/java/run/halo/app/infra/types/ObjectMeta.java
  src/main/java/run/halo/app/infra/types/TypeMeta.java
  src/test/java/run/halo/app/authorization/DefaultRoleBindingListerTest.java
  src/test/java/run/halo/app/authorization/RequestInfoResolverTest.java
  src/test/java/run/halo/app/integration/security/TestWebSecurityConfig.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2110 feat: add logout handler
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/authentication/verifier/AbstractOAuth2TokenAuthenticationToken.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationFilter.java
  src/main/java/run/halo/app/identity/authentication/verifier/JwtAccessTokenNonBlockedValidator.java
  src/main/java/run/halo/app/identity/entrypoint/Oauth2LogoutHandler.java
  src/test/java/run/halo/app/integration/security/LogoutHandlerTest.java
  src/test/java/run/halo/app/integration/security/TestWebSecurityConfig.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2111 Create unstructured Extension which can store any Extensions
  src/main/java/run/halo/app/extension/AbstractExtension.java
  src/main/java/run/halo/app/extension/DefaultExtensionClient.java
  src/main/java/run/halo/app/extension/Extension.java
  src/main/java/run/halo/app/extension/ExtensionOperator.java
  src/main/java/run/halo/app/extension/JSONExtensionConverter.java
  src/main/java/run/halo/app/extension/Metadata.java
  src/main/java/run/halo/app/extension/MetadataOperator.java
  src/main/java/run/halo/app/extension/Schemes.java
  src/main/java/run/halo/app/extension/Unstructured.java
  src/test/java/run/halo/app/extension/AbstractExtensionTest.java
  src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
  src/test/java/run/halo/app/extension/JSONExtensionConverterTest.java
  src/test/java/run/halo/app/extension/SchemesTest.java
  src/test/java/run/halo/app/extension/UnstructuredTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2104 Restrict file extension when importing markdown
  src/main/java/run/halo/app/controller/admin/api/BackupController.java
  src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2116 feat: add personal access token authentication mechanism
  build.gradle
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/apitoken/DefaultPersonalAccessTokenDecoder.java
  src/main/java/run/halo/app/identity/apitoken/PersonalAccessToken.java
  src/main/java/run/halo/app/identity/apitoken/PersonalAccessTokenAuthenticationToken.java
  src/main/java/run/halo/app/identity/apitoken/PersonalAccessTokenDecoder.java
  src/main/java/run/halo/app/identity/apitoken/PersonalAccessTokenException.java
  src/main/java/run/halo/app/identity/apitoken/PersonalAccessTokenProvider.java
  src/main/java/run/halo/app/identity/apitoken/PersonalAccessTokenTimestampValidator.java
  src/main/java/run/halo/app/identity/apitoken/PersonalAccessTokenType.java
  src/main/java/run/halo/app/identity/apitoken/PersonalAccessTokenUtils.java
  src/main/java/run/halo/app/identity/apitoken/PersonalTokenTypeUtils.java
  src/main/java/run/halo/app/identity/authentication/verifier/JwtProvidedDecoderAuthenticationManagerResolver.java
  src/main/java/run/halo/app/identity/authentication/verifier/TokenAuthenticationManagerResolver.java
  src/main/java/run/halo/app/identity/authorization/DefaultRuleResolver.java
  src/main/java/run/halo/app/infra/SchemeInitializer.java
  src/main/java/run/halo/app/infra/utils/Base62Utils.java
  src/main/java/run/halo/app/infra/utils/HaloUtils.java
  src/main/resources/apiToken.salt
  src/test/java/run/halo/app/infra/utils/Base62UtilsTest.java
  src/test/java/run/halo/app/integration/security/TestWebSecurityConfig.java
  src/test/resources/apiToken.salt
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2120 Replace AdoptOpenJDK docker image with Eclipse Temurin
  Dockerfile
Labels: lgtm, kind/deprecation, kind/cleanup, approved, release-note

#2122 feat: add yaml unstructured loader
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/infra/SchemeInitializer.java
  src/main/java/run/halo/app/infra/utils/JsonUtils.java
  src/main/java/run/halo/app/infra/utils/YamlUnstructuredLoader.java
  src/main/resources/extensions/rolesTemplates.yaml
  src/test/java/run/halo/app/infra/utils/JsonUtilsTest.java
  src/test/java/run/halo/app/infra/utils/YamlUnstructuredLoaderTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2119 refactor: rule resolver and role binding lister
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/authorization/DefaultRoleBindingLister.java
  src/main/java/run/halo/app/identity/authorization/DefaultRuleResolver.java
  src/main/java/run/halo/app/identity/authorization/NonResourceRuleInfo.java
  src/main/java/run/halo/app/identity/authorization/PolicyRuleInfo.java
  src/main/java/run/halo/app/identity/authorization/RequestInfoAuthorizationManager.java
  src/main/java/run/halo/app/identity/authorization/ResourceRuleInfo.java
  src/main/java/run/halo/app/identity/authorization/RoleBindingLister.java
  src/test/java/run/halo/app/authorization/DefaultRoleBindingListerTest.java
  src/test/java/run/halo/app/authorization/RequestInfoResolverTest.java
  src/test/java/run/halo/app/integration/security/TestWebSecurityConfig.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2128 feat: initial plugin implementation
  build.gradle
  src/main/java/run/halo/app/plugin/BasePlugin.java
  src/main/java/run/halo/app/plugin/ExtensionContextRegistry.java
  src/main/java/run/halo/app/plugin/HaloPluginManager.java
  src/main/java/run/halo/app/plugin/PluginApplicationContext.java
  src/main/java/run/halo/app/plugin/PluginApplicationEventBridgeDispatcher.java
  src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
  src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
  src/main/java/run/halo/app/plugin/PluginProperties.java
  src/main/java/run/halo/app/plugin/PluginRequestMappingManager.java
  src/main/java/run/halo/app/plugin/PluginStartingError.java
  src/main/java/run/halo/app/plugin/PropertyPluginStatusProvider.java
  src/main/java/run/halo/app/plugin/SharedEvent.java
  src/main/java/run/halo/app/plugin/SpringComponentsFinder.java
  src/main/java/run/halo/app/plugin/SpringExtensionFactory.java
  src/main/java/run/halo/app/plugin/event/HaloPluginStartedEvent.java
  src/main/java/run/halo/app/plugin/event/HaloPluginStateChangedEvent.java
  src/main/java/run/halo/app/plugin/event/HaloPluginStoppedEvent.java
  src/main/resources/application-dev.yaml
Labels: kind/feature, lgtm, release-note-none, area/core, approved
