Repository halo-dev/halo, pull requests merged in 2022-03, with the labels that each got.

#1690 Fix the leak of version number inference when create or update content patch
  src/main/java/run/halo/app/service/impl/ContentPatchLogServiceImpl.java
Labels: bug

#1695 Fix the problem jsonToCacheWrapper crashes when cache value is not JSON format
  src/main/java/run/halo/app/cache/AbstractStringCacheStore.java
  src/test/java/run/halo/app/cache/LevelCacheStoreTest.java
Labels: bug

#1669 Add post backup for contents and content_patch_logs
  src/main/java/run/halo/app/service/ContentPatchLogService.java
  src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
  src/main/java/run/halo/app/service/impl/ContentPatchLogServiceImpl.java
  src/main/java/run/halo/app/service/impl/ContentServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/main/java/run/halo/app/utils/VersionUtil.java
  src/test/java/run/halo/app/utils/VersionUtilTest.java
Labels: enhancement

#1698 Refactoring exception throw for backup import
  src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
Labels: enhancement

#1699 Create project infrastructure for halo-next
  .github/workflows/halo.yml
  build.gradle
  config/checkstyle/checkstyle.xml
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/run/halo/app/Application.java
  src/main/resources/application.yaml
  src/main/resources/banner.txt
  src/test/java/run/halo/app/ApplicationTests.java
Labels: enhancement

#1706 Disable standard streams of test logging
  build.gradle
Labels: enhancement

#1705 Fix the problem of theme version compatibility
  src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java
  src/main/java/run/halo/app/utils/Version.java
  src/main/java/run/halo/app/utils/VersionUtil.java
  src/test/java/run/halo/app/utils/VersionTest.java
  src/test/java/run/halo/app/utils/VersionUtilTest.java
Labels: bug

#1715 Fix the exception of content not found when empty sheet deleted
  src/main/java/run/halo/app/service/assembler/BasePostAssembler.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/main/java/run/halo/app/service/impl/SheetServiceImpl.java
Labels: bug

#1726 doc: update readme badges
  README.md
Labels: enhancement

#1716 Fix the problem of no EntityManager with actual transaction available for current thread then remove method called
  src/main/java/run/halo/app/service/impl/BaseCommentServiceImpl.java
  src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/main/java/run/halo/app/service/impl/SheetServiceImpl.java
Labels: bug

#1729 feat: Add comment assembler for theme render
  src/main/java/run/halo/app/controller/content/api/JournalController.java
  src/main/java/run/halo/app/controller/content/api/PostController.java
  src/main/java/run/halo/app/controller/content/api/SheetController.java
  src/main/java/run/halo/app/core/freemarker/tag/CommentTagDirective.java
  src/main/java/run/halo/app/service/assembler/comment/BaseCommentAssembler.java
  src/main/java/run/halo/app/service/assembler/comment/JournalCommentRenderAssembler.java
  src/main/java/run/halo/app/service/assembler/comment/PostCommentRenderAssembler.java
  src/main/java/run/halo/app/service/assembler/comment/SheetCommentRenderAssembler.java
  src/main/java/run/halo/app/service/base/BaseCommentService.java
  src/main/java/run/halo/app/service/impl/BaseCommentServiceImpl.java
  src/test/java/run/halo/app/it/PostCommentApiTest.java
Labels: bug

#1739 Journal supports receiving front-end rendering results
  src/main/java/run/halo/app/model/params/JournalParam.java
  src/main/java/run/halo/app/service/impl/JournalServiceImpl.java
Labels: enhancement

#1747 Reverse theme required version compatibility check
  src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java
Labels: bug

#1781 Fix the problem of post list is incomplete due to no recursive query categories
  src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java
  src/test/java/run/halo/app/listener/PostRefreshStatusListenerTest.java
Labels: kind/bug, lgtm, approved

#1786 Fix the redirected URL will be garbled when include Chinese
  src/main/java/run/halo/app/controller/content/ContentContentController.java
Labels: kind/bug, lgtm, approved

#1787 refactor: remove parameter assertion
  src/main/java/run/halo/app/cache/AbstractStringCacheStore.java
Labels: lgtm, approved

#1785 refactor: transition behavior of post state after category updated
  src/main/java/run/halo/app/event/category/CategoryUpdatedEvent.java
  src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java
  src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/test/java/run/halo/app/listener/PostRefreshStatusListenerTest.java
Labels: kind/bug, lgtm, approved

#1792 chore: Upgrade springboot to 2.5.11
  build.gradle
  settings.gradle
Labels: vulnerability, lgtm, area/core, approved

#1797 refactor: clear the deprecated attributes value of post content when prePersist and preUpdate
  src/main/java/run/halo/app/model/entity/BasePost.java
Labels: lgtm, area/core, kind/cleanup, approved
