Repository halo-dev/halo, pull requests merged in 2022-06, with the labels that each got.

#2131 refactor: policy rule constructor to avoid null values
  src/main/java/run/halo/app/identity/authorization/PolicyRule.java
  src/test/java/run/halo/app/identity/authorization/PolicyRuleTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2137 Fix front matter parsing error
  src/main/java/run/halo/app/utils/MarkdownUtils.java
  src/test/java/run/halo/app/service/impl/PostServiceImplTest.java
Labels: kind/bug, lgtm, approved, release-note

#2132 feat: add yaml descriptor finder for plugin
  src/main/java/run/halo/app/plugin/BasePlugin.java
  src/main/java/run/halo/app/plugin/Plugin.java
  src/main/java/run/halo/app/plugin/YamlPluginDescriptorFinder.java
  src/main/java/run/halo/app/plugin/YamlPluginFinder.java
  src/test/java/run/halo/app/plugin/YamlPluginDescriptorFinderTest.java
  src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
  src/test/resources/plugin/plugin.yaml
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2144 Enable CSRF token in Set-Cookie header
  src/main/java/run/halo/app/config/WebServerSecurityConfig.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2143 Filter reserved characters in file names
  src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
  src/main/java/run/halo/app/utils/FilenameUtils.java
  src/test/java/run/halo/app/utils/FilenameUtilsTest.java
Labels: kind/bug, lgtm, approved, release-note

#2145 Overwrite Jackson2Json decoder and encoder
  src/main/java/run/halo/app/config/WebFluxConfig.java
  src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/test/java/run/halo/app/config/ServerCodecTest.java
  src/test/resources/application.yaml
Labels: lgtm, release-note-none, area/core, kind/api-change, approved, kind/improvement

#2149 docs: add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2134 feat: add plugin life cycle management
  src/main/java/run/halo/app/infra/SchemeInitializer.java
  src/main/java/run/halo/app/plugin/HaloPluginManager.java
  src/main/java/run/halo/app/plugin/Plugin.java
  src/main/java/run/halo/app/plugin/PluginApplicationContext.java
  src/main/java/run/halo/app/plugin/PluginApplicationEventBridgeDispatcher.java
  src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
  src/main/java/run/halo/app/plugin/PluginLifeCycleManagerController.java
  src/main/java/run/halo/app/plugin/PluginService.java
  src/main/java/run/halo/app/plugin/PluginServiceImpl.java
  src/test/java/run/halo/app/plugin/PluginLifeCycleManagerControllerTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2151 feat: add reverse proxy router registry for plugin by reverse proxy rules
  src/main/java/run/halo/app/infra/utils/PathUtils.java
  src/main/java/run/halo/app/plugin/HaloPluginManager.java
  src/main/java/run/halo/app/plugin/PluginCompositeRouterFunction.java
  src/main/java/run/halo/app/plugin/PluginLoadedListener.java
  src/main/java/run/halo/app/plugin/event/HaloPluginLoadedEvent.java
  src/main/java/run/halo/app/plugin/resources/ReverseProxy.java
  src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
  src/test/java/run/halo/app/infra/utils/PathUtilsTest.java
  src/test/java/run/halo/app/plugin/PluginCompositeRouterFunctionTest.java
  src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactoryTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2154 feat: add plugin unstructured resource loader
  src/main/java/run/halo/app/plugin/HaloPluginManager.java
  src/main/java/run/halo/app/plugin/PluginInitializationLoadOnApplicationReady.java
  src/main/java/run/halo/app/plugin/PluginUnstructuredResourceLoader.java
  src/test/java/run/halo/app/plugin/PluginUnstructuredResourceLoaderTest.java
  src/test/resources/plugin/test-unstructured-resource-loader.jar
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2152 feat: plugin supports multiple ways of specifying licenses
  src/main/java/run/halo/app/plugin/Plugin.java
  src/main/java/run/halo/app/plugin/YamlPluginDescriptorFinder.java
  src/main/java/run/halo/app/plugin/YamlPluginFinder.java
  src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2158 Add feature to generate APIs for schemes automatically
  docs/security.puml
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/extension/AbstractExtension.java
  src/main/java/run/halo/app/extension/DefaultExtensionClient.java
  src/main/java/run/halo/app/extension/DefaultSchemeManager.java
  src/main/java/run/halo/app/extension/DefaultSchemeWatcherManager.java
  src/main/java/run/halo/app/extension/ExtensionCompositeRouterFunction.java
  src/main/java/run/halo/app/extension/ExtensionOperator.java
  src/main/java/run/halo/app/extension/ExtensionRouterFunctionFactory.java
  src/main/java/run/halo/app/extension/GroupVersionKind.java
  src/main/java/run/halo/app/extension/JSONExtensionConverter.java
  src/main/java/run/halo/app/extension/Metadata.java
  src/main/java/run/halo/app/extension/MetadataOperator.java
  src/main/java/run/halo/app/extension/Scheme.java
  src/main/java/run/halo/app/extension/SchemeManager.java
  src/main/java/run/halo/app/extension/SchemeWatcherManager.java
  src/main/java/run/halo/app/extension/Schemes.java
  src/main/java/run/halo/app/extension/Unstructured.java
  src/main/java/run/halo/app/extension/exception/ExtensionNotFoundException.java
  src/main/java/run/halo/app/infra/SchemeInitializer.java
  src/main/java/run/halo/app/plugin/PluginLoadedListener.java
  src/main/java/run/halo/app/security/authorization/PolicyRule.java
  src/test/java/run/halo/app/config/ExtensionConfigurationTest.java
  src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
  src/test/java/run/halo/app/extension/DefaultSchemeManagerTest.java
  src/test/java/run/halo/app/extension/DefaultSchemeWatcherManagerTest.java
  src/test/java/run/halo/app/extension/ExtensionCompositeRouterFunctionTest.java
  src/test/java/run/halo/app/extension/ExtensionCreateHandlerTest.java
  src/test/java/run/halo/app/extension/ExtensionGetHandlerTest.java
  src/test/java/run/halo/app/extension/ExtensionListHandlerTest.java
  src/test/java/run/halo/app/extension/ExtensionRouterFunctionFactoryTest.java
  src/test/java/run/halo/app/extension/FakeExtension.java
  src/test/java/run/halo/app/extension/JSONExtensionConverterTest.java
  src/test/java/run/halo/app/extension/MetadataOperatorTest.java
  src/test/java/run/halo/app/extension/PathPatternGeneratorTest.java
  src/test/java/run/halo/app/extension/SchemeTest.java
  src/test/java/run/halo/app/extension/SchemesTest.java
  src/test/java/run/halo/app/extension/UnstructuredTest.java
  src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, kind/api-change, approved

#2163 Add user support for authentication and authorization
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  src/main/java/run/halo/app/core/extension/Role.java
  src/main/java/run/halo/app/core/extension/RoleBinding.java
  src/main/java/run/halo/app/core/extension/User.java
  src/main/java/run/halo/app/core/extension/service/DefaultRoleBindingService.java
  src/main/java/run/halo/app/core/extension/service/DefaultRoleService.java
  src/main/java/run/halo/app/core/extension/service/RoleBindingService.java
  src/main/java/run/halo/app/core/extension/service/RoleService.java
  src/main/java/run/halo/app/core/extension/service/UserService.java
  src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
  src/main/java/run/halo/app/extension/GroupVersionKind.java
  src/main/java/run/halo/app/extension/JSONExtensionConverter.java
  src/main/java/run/halo/app/infra/SchemeInitializer.java
  src/main/java/run/halo/app/security/DefaultUserDetailService.java
  src/main/java/run/halo/app/security/SuperAdminInitializer.java
  src/main/java/run/halo/app/security/authorization/AuthorizingVisitor.java
  src/main/java/run/halo/app/security/authorization/DefaultRoleGetter.java
  src/main/java/run/halo/app/security/authorization/DefaultRuleResolver.java
  src/main/java/run/halo/app/security/authorization/PolicyRule.java
  src/main/java/run/halo/app/security/authorization/PolicyRuleList.java
  src/main/java/run/halo/app/security/authorization/RbacRequestEvaluation.java
  src/main/java/run/halo/app/security/authorization/RequestInfoAuthorizationManager.java
  src/main/java/run/halo/app/security/authorization/Role.java
  src/main/java/run/halo/app/security/authorization/RoleBinding.java
  src/main/java/run/halo/app/security/authorization/RoleGetter.java
  src/main/java/run/halo/app/security/authorization/RoleRef.java
  src/main/java/run/halo/app/security/authorization/RuleAccumulator.java
  src/main/java/run/halo/app/security/authorization/Subject.java
  src/test/java/run/halo/app/config/ExtensionConfigurationTest.java
  src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java
  src/test/java/run/halo/app/extension/GroupVersionKindTest.java
  src/test/java/run/halo/app/extension/JsonExtensionConverterTest.java
  src/test/java/run/halo/app/plugin/PluginLifeCycleManagerControllerTest.java
  src/test/java/run/halo/app/security/DefaultUserDetailServiceTest.java
  src/test/java/run/halo/app/security/SuperAdminInitializerTest.java
  src/test/java/run/halo/app/security/authentication/jwt/LoginTest.java
  src/test/java/run/halo/app/security/authorization/AuthorizationTest.java
  src/test/java/run/halo/app/security/authorization/DefaultRoleBindingServiceTest.java
  src/test/java/run/halo/app/security/authorization/PolicyRuleTest.java
  src/test/java/run/halo/app/security/authorization/RequestInfoResolverTest.java
Labels: kind/feature, lgtm, release-note-none, kind/api-change, approved

#2170 fix: locale for unit test of json extension converter
  src/test/java/run/halo/app/extension/JsonExtensionConverterTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2174 feat: add shared application context for plugin
  src/main/java/run/halo/app/plugin/PluginApplicationContext.java
  src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
  src/main/java/run/halo/app/plugin/PluginCompositeRouterFunction.java
  src/main/java/run/halo/app/plugin/SharedApplicationContext.java
  src/main/java/run/halo/app/plugin/SharedApplicationContextHolder.java
  src/test/java/run/halo/app/plugin/SharedApplicationContextHolderTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2175 Configure CORS for API endpoints
  src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  src/test/java/run/halo/app/config/CorsTest.java
Labels: lgtm, release-note-none, kind/api-change, approved, kind/improvement

#2180 Refine Swagger document for Extension APIs
  src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  src/main/java/run/halo/app/extension/ExtensionRouterFunctionFactory.java
  src/main/java/run/halo/app/extension/GroupVersionKind.java
  src/main/resources/application-dev.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2177 feat: add plugin status manage
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/core/extension/ReverseProxy.java
  src/main/java/run/halo/app/infra/SchemeInitializer.java
  src/main/java/run/halo/app/plugin/PluginInitializationLoadOnApplicationReady.java
  src/main/java/run/halo/app/plugin/PluginLifeCycleManagerController.java
  src/main/java/run/halo/app/plugin/PluginLoadedListener.java
  src/main/java/run/halo/app/plugin/PluginNotFoundException.java
  src/main/java/run/halo/app/plugin/PluginService.java
  src/main/java/run/halo/app/plugin/PluginServiceImpl.java
  src/main/java/run/halo/app/plugin/YamlPluginDescriptorFinder.java
  src/main/java/run/halo/app/plugin/YamlPluginFinder.java
  src/main/java/run/halo/app/plugin/resources/JsBundleRuleProvider.java
  src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
  src/test/java/run/halo/app/plugin/PluginLifeCycleManagerControllerTest.java
  src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
  src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactoryTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2185 fix: use the original name when uploading the attachment to upyun oss
  src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2183 refactor: plugin configuration loading to adapt to plugin development mode
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/plugin/HaloPluginManager.java
  src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
  src/main/java/run/halo/app/plugin/PluginConst.java
  src/main/java/run/halo/app/plugin/PluginLoadedListener.java
  src/main/java/run/halo/app/plugin/PluginServiceImpl.java
  src/main/java/run/halo/app/plugin/PluginUnstructuredResourceLoader.java
  src/main/java/run/halo/app/plugin/YamlPluginFinder.java
  src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
  src/test/java/run/halo/app/plugin/PluginUnstructuredResourceLoaderTest.java
  src/test/java/run/halo/app/plugin/YamlPluginDescriptorFinderTest.java
  src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
  src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactoryTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2187 Filter files with markdown extension while importing markdown
  src/main/java/run/halo/app/controller/admin/api/BackupController.java
Labels: kind/bug, lgtm, approved, release-note

#2190 Add an additional method to fetch Extension by GVK and name
  src/main/java/run/halo/app/extension/DefaultExtensionClient.java
  src/main/java/run/halo/app/extension/ExtensionClient.java
  src/main/java/run/halo/app/extension/Unstructured.java
  src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
  src/test/java/run/halo/app/extension/ExtensionCreateHandlerTest.java
  src/test/java/run/halo/app/extension/ExtensionDeleteHandlerTest.java
  src/test/java/run/halo/app/extension/ExtensionUpdateHandlerTest.java
  src/test/java/run/halo/app/extension/UnstructuredTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement
