Repository halo-dev/halo, pull requests merged in 2022-11, with the labels that each got.

#2646 perf: use the new formkit custom input for system setting forms schema
  src/main/resources/extensions/system-setting.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2648 fix: labels update for post and singlepage
  src/main/java/run/halo/app/content/permalinks/PostPermalinkPolicy.java
  src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
  src/test/java/run/halo/app/core/extension/reconciler/PostReconcilerTest.java
  src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#2641 refactor: permalink automatically appends external url if it is configured
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/content/permalinks/CategoryPermalinkPolicy.java
  src/main/java/run/halo/app/content/permalinks/PostPermalinkPolicy.java
  src/main/java/run/halo/app/content/permalinks/TagPermalinkPolicy.java
  src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
  src/test/java/run/halo/app/content/permalinks/CategoryPermalinkPolicyTest.java
  src/test/java/run/halo/app/content/permalinks/PostPermalinkPolicyTest.java
  src/test/java/run/halo/app/content/permalinks/TagPermalinkPolicyTest.java
  src/test/java/run/halo/app/core/extension/reconciler/SinglePageReconcilerTest.java
  src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2638 feat: support custom rendering templates configure through themes
  src/main/java/run/halo/app/core/extension/Theme.java
  src/main/java/run/halo/app/theme/router/ViewNameResolver.java
  src/main/java/run/halo/app/theme/router/strategy/CategoryRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/PostRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategy.java
  src/test/java/run/halo/app/core/extension/ThemeTest.java
  src/test/java/run/halo/app/theme/router/ViewNameResolverTest.java
  src/test/java/run/halo/app/theme/router/strategy/CategoryRouteStrategyTest.java
  src/test/java/run/halo/app/theme/router/strategy/PostRouteStrategyTest.java
  src/test/java/run/halo/app/theme/router/strategy/RouterStrategyTestSuite.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#2652 feat: create reverse proxy for logo when plugin created
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/infra/utils/PathUtils.java
  src/main/java/run/halo/app/plugin/resources/BundleResourceUtils.java
  src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
  src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistry.java
  src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
  src/test/java/run/halo/app/infra/utils/PathUtilsTest.java
  src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactoryTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2639 fix: cannot stop thread when system is interrupted
  src/main/java/run/halo/app/metrics/CounterMeterHandler.java
  src/main/java/run/halo/app/metrics/VisitLogWriter.java
  src/test/java/run/halo/app/metrics/VisitLogWriterTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note, kind/improvement

#2663 fix: while cycles cause high cpu usage
  src/main/java/run/halo/app/metrics/VisitLogWriter.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#2665 Build console with release tag when releasing
  .github/workflows/halo.yaml
Labels: lgtm, release-note-none, approved, kind/improvement

#2661 refactor: ThemeLinkBuilder needs to rely on external url
  src/main/java/run/halo/app/theme/TemplateEngineManager.java
  src/main/java/run/halo/app/theme/ThemeLinkBuilder.java
  src/test/java/run/halo/app/theme/ThemeLinkBuilderTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2660 refactor: add page size configuration for post
  src/main/java/run/halo/app/infra/SystemConfigurableEnvironmentFetcher.java
  src/main/java/run/halo/app/infra/SystemSetting.java
  src/main/java/run/halo/app/theme/finders/vo/SiteSettingVo.java
  src/main/java/run/halo/app/theme/router/strategy/ArchivesRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/CategoriesRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/CategoryRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/IndexRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/ModelConst.java
  src/main/java/run/halo/app/theme/router/strategy/TagRouteStrategy.java
  src/main/resources/extensions/system-setting.yaml
  src/test/java/run/halo/app/theme/router/strategy/RouterStrategyTestSuite.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2667 feat: add setup primary menu support
  src/main/java/run/halo/app/infra/SystemSetting.java
  src/main/java/run/halo/app/theme/finders/MenuFinder.java
  src/main/java/run/halo/app/theme/finders/impl/MenuFinderImpl.java
  src/main/resources/extensions/system-configurable-configmap.yaml
  src/test/java/run/halo/app/theme/finders/impl/MenuFinderImplTest.java
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note-action-required

#2669 feat: total pages returned from paging results
  src/main/java/run/halo/app/extension/ListResult.java
  src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
  src/test/java/run/halo/app/extension/ListResultTest.java
Labels: lgtm, area/core, kind/api-change, approved, release-note, kind/improvement

#2659 refactor: change from manual publishing to automatic publishing
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/content/ContentRequest.java
  src/main/java/run/halo/app/content/ContentService.java
  src/main/java/run/halo/app/content/ContentWrapper.java
  src/main/java/run/halo/app/content/ListedPost.java
  src/main/java/run/halo/app/content/ListedSinglePage.java
  src/main/java/run/halo/app/content/PostRequest.java
  src/main/java/run/halo/app/content/SinglePageRequest.java
  src/main/java/run/halo/app/content/impl/ContentServiceImpl.java
  src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
  src/main/java/run/halo/app/core/extension/Post.java
  src/main/java/run/halo/app/core/extension/SinglePage.java
  src/main/java/run/halo/app/core/extension/Snapshot.java
  src/main/java/run/halo/app/core/extension/endpoint/ContentEndpoint.java
  src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
  src/main/java/run/halo/app/core/extension/endpoint/SinglePageEndpoint.java
  src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
  src/main/java/run/halo/app/extension/ExtensionUtil.java
  src/main/java/run/halo/app/infra/utils/PathUtils.java
  src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  src/main/java/run/halo/app/theme/finders/impl/SinglePageFinderImpl.java
  src/main/java/run/halo/app/theme/finders/vo/PostVo.java
  src/main/java/run/halo/app/theme/finders/vo/SinglePageVo.java
  src/main/resources/extensions/system-configurable-configmap.yaml
  src/main/resources/extensions/system-setting.yaml
  src/test/java/run/halo/app/content/ContentRequestTest.java
  src/test/java/run/halo/app/content/ContentServiceTest.java
  src/test/java/run/halo/app/content/impl/PostServiceImplTest.java
  src/test/java/run/halo/app/core/extension/endpoint/PostEndpointTest.java
  src/test/java/run/halo/app/core/extension/reconciler/PostReconcilerTest.java
  src/test/java/run/halo/app/core/extension/reconciler/SinglePageReconcilerTest.java
  src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java
Labels: lgtm, area/core, kind/api-change, approved, release-note, kind/improvement

#2683 feat: add plugin finder for theme-side
  src/main/java/run/halo/app/theme/finders/PluginFinder.java
  src/main/java/run/halo/app/theme/finders/impl/PluginFinderImpl.java
  src/test/java/run/halo/app/theme/finders/impl/PluginFinderImplTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#2692 Bump Spring Boot to 3.0.0-RC2
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2693 Fix test issues on Windows
  src/main/java/run/halo/app/infra/utils/PathUtils.java
  src/main/java/run/halo/app/plugin/YamlPluginFinder.java
  src/test/java/run/halo/app/core/extension/SettingTest.java
  src/test/java/run/halo/app/plugin/PluginStartedListenerTest.java
  src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
  src/test/java/run/halo/app/theme/ThemeContextTest.java
  src/test/java/run/halo/app/theme/message/ThemeMessageResolutionUtilsTest.java
  src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java
Labels: lgtm, release-note-none, kind/cleanup, approved

#2675 Implement full-text search of posts with Lucene default
  build.gradle
  docs/full-text-search/README.md
  docs/full-text-search/algolia.png
  docs/full-text-search/meilisearch.jpg
  src/main/java/run/halo/app/config/HaloConfiguration.java
  src/main/java/run/halo/app/core/extension/Post.java
  src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
  src/main/java/run/halo/app/event/post/PostDeletedEvent.java
  src/main/java/run/halo/app/event/post/PostPublishedEvent.java
  src/main/java/run/halo/app/event/post/PostRecycledEvent.java
  src/main/java/run/halo/app/event/post/PostUnpublishedEvent.java
  src/main/java/run/halo/app/extension/ListResult.java
  src/main/java/run/halo/app/extension/Unstructured.java
  src/main/java/run/halo/app/infra/SchemeInitializedEvent.java
  src/main/java/run/halo/app/infra/SchemeInitializer.java
  src/main/java/run/halo/app/infra/SystemSetting.java
  src/main/java/run/halo/app/infra/utils/GenericClassUtils.java
  src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
  src/main/java/run/halo/app/plugin/extensionpoint/ExtensionGetter.java
  src/main/java/run/halo/app/search/IndicesEndpoint.java
  src/main/java/run/halo/app/search/IndicesInitializer.java
  src/main/java/run/halo/app/search/IndicesService.java
  src/main/java/run/halo/app/search/IndicesServiceImpl.java
  src/main/java/run/halo/app/search/SearchParam.java
  src/main/java/run/halo/app/search/SearchResult.java
  src/main/java/run/halo/app/search/extension/SearchEngine.java
  src/main/java/run/halo/app/search/post/LucenePostSearchService.java
  src/main/java/run/halo/app/search/post/PostDoc.java
  src/main/java/run/halo/app/search/post/PostEventListener.java
  src/main/java/run/halo/app/search/post/PostHit.java
  src/main/java/run/halo/app/search/post/PostSearchEndpoint.java
  src/main/java/run/halo/app/search/post/PostSearchService.java
  src/main/resources/extensions/searchengine-lucene.yaml
  src/test/java/run/halo/app/core/extension/PostTest.java
  src/test/java/run/halo/app/core/extension/endpoint/PostEndpointTest.java
  src/test/java/run/halo/app/infra/SystemSettingTest.java
  src/test/java/run/halo/app/security/SuperAdminInitializerTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#2698 docs: update readme for Halo 2.0.0-beta.1 and new slogan
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2701 Fix the problem of unpublishing and recycling posts by member of post manager
  src/main/resources/extensions/role-template-post.yaml
Labels: kind/bug, lgtm, area/core, approved, release-note

#2704 Initialize default theme when Halo starts up for the first time
  .gitignore
  src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
  src/main/java/run/halo/app/core/extension/theme/ThemeService.java
  src/main/java/run/halo/app/core/extension/theme/ThemeServiceImpl.java
  src/main/java/run/halo/app/core/extension/theme/ThemeUtils.java
  src/main/java/run/halo/app/infra/DefaultThemeInitializer.java
  src/main/java/run/halo/app/infra/DefaultThemeRootGetter.java
  src/main/java/run/halo/app/infra/ThemeRootGetter.java
  src/main/java/run/halo/app/infra/properties/HaloProperties.java
  src/main/java/run/halo/app/infra/properties/ThemeProperties.java
  src/main/java/run/halo/app/theme/ThemePathPolicy.java
  src/main/resources/extensions/system-configurable-configmap.yaml
  src/main/resources/themes/theme-earth.zip
  src/test/java/run/halo/app/core/extension/theme/ThemeEndpointTest.java
  src/test/java/run/halo/app/core/extension/theme/ThemeServiceImplTest.java
  src/test/java/run/halo/app/security/SuperAdminInitializerTest.java
  src/test/resources/themes/default/theme.yaml
  src/test/resources/themes/invalid-missing-manifest/i18n/default.properties
  src/test/resources/themes/invalid-missing-manifest/i18n/en.properties
  src/test/resources/themes/invalid-missing-manifest/templates/index.html
  src/test/resources/themes/invalid-missing-manifest/templates/timezone.html
  src/test/resources/themes/other/theme.yaml
Labels: kind/feature, lgtm, area/core, approved, release-note

#2705 Provide sort query param for sorting attachment
  src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
  src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  src/main/java/run/halo/app/extension/Comparators.java
  src/test/java/run/halo/app/extension/ComparatorsTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#2707 Prevent H2 from closing on exit to allow destruction
  src/main/resources/application.yaml
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#2712 fix: failed to build due to wrong type
  src/main/java/run/halo/app/search/IndicesServiceImpl.java
  src/main/java/run/halo/app/search/post/PostEventListener.java
  src/main/java/run/halo/app/theme/finders/PostFinder.java
  src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#2714 feat: support obtaining the configuration of halo.external-url for themes and plugins
  src/main/java/run/halo/app/plugin/SharedApplicationContextHolder.java
  src/main/java/run/halo/app/theme/SiteSettingVariablesAcquirer.java
  src/main/java/run/halo/app/theme/finders/vo/SiteSettingVo.java
  src/test/java/run/halo/app/theme/SiteSettingVariablesAcquirerTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2715 refactor: support chaining calls for flux and mono in javascript inline tag
  src/main/java/run/halo/app/theme/ReactivePropertyAccessor.java
  src/main/java/run/halo/app/theme/ReactiveSpelVariableExpressionEvaluator.java
  src/test/java/run/halo/app/theme/ReactiveFinderExpressionParserTests.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2718 Enable adding more workers for controller
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/extension/controller/ControllerBuilder.java
  src/main/java/run/halo/app/extension/controller/DefaultController.java
  src/main/java/run/halo/app/extension/gc/GarbageCollectorConfiguration.java
  src/main/resources/application-dev.yaml
  src/test/java/run/halo/app/extension/controller/DefaultControllerTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved, kind/improvement

#2720 Fix the problem of upgrading theme due to pipe closed
  src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
Labels: kind/bug, lgtm, kind/regression, release-note-none, area/core, approved

#2726 Bump up springdoc-openapi
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2728 Change working directory to .halo2
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/main/resources/extensions/attachment-local-policy.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2742 fix: inconsistent order of post for theme-side
  src/main/java/run/halo/app/theme/finders/impl/ContributorFinderImpl.java
  src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  src/main/java/run/halo/app/theme/finders/impl/SinglePageFinderImpl.java
  src/main/java/run/halo/app/theme/finders/impl/TagFinderImpl.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2752 Provide ungrouped query param to filter ungrouped attachments
  src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
  src/test/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpointTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2760 Ignore websocket protocol while proxying console
  src/main/java/run/halo/app/console/ConsoleProxyFilter.java
  src/main/java/run/halo/app/console/WebSocketServerWebExchangeMatcher.java
  src/test/java/run/halo/app/console/WebSocketServerWebExchangeMatcherTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2741 feat: add global error web exception handler
  src/main/java/run/halo/app/infra/exception/NotFoundException.java
  src/main/java/run/halo/app/infra/exception/handlers/ExceptionHandlingProblemDetailsHandler.java
  src/main/java/run/halo/app/infra/exception/handlers/GlobalErrorWebExceptionHandler.java
  src/main/java/run/halo/app/infra/exception/handlers/HaloErrorWebFluxAutoConfiguration.java
  src/main/java/run/halo/app/plugin/PluginNotFoundException.java
  src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
  src/test/java/run/halo/app/infra/exception/handlers/GlobalErrorWebExceptionHandlerTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#2759 refactor: check whether plugin has been loaded when startup
  src/main/java/run/halo/app/plugin/PluginDevelopmentInitializer.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2763 docs: update readme for Halo 2.0.0-rc.1 and new slogan
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2769 Upgrade to SpringDoc OpenAPI 2.0.0
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2768 Upgrade to Spring Boot 3.0.0
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2772 chore: upgrade to PF4J 3.8.0
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2737 Refactor reconcilers registration
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/CommentReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/MenuItemReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/MenuReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/ReverseProxyReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/RoleBindingReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/RoleReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/SystemSettingReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/TagReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/UserReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
  src/main/java/run/halo/app/extension/controller/ControllerBuilder.java
  src/main/java/run/halo/app/extension/controller/ControllerManager.java
  src/main/java/run/halo/app/extension/controller/DefaultControllerManager.java
  src/main/java/run/halo/app/extension/controller/Reconciler.java
  src/main/java/run/halo/app/extension/gc/GarbageCollectorConfiguration.java
  src/main/java/run/halo/app/extension/gc/GcControllerInitializer.java
  src/main/java/run/halo/app/extension/gc/GcReconciler.java
  src/test/java/run/halo/app/extension/controller/ControllerBuilderTest.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved, kind/improvement

#2746 feat: add approvedTime for comment and reply
  src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  src/main/java/run/halo/app/core/extension/Comment.java
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note

#2774 Delegate ReactiveExtensionClient for default implementation of ExtensionClient
  src/main/java/run/halo/app/extension/DefaultExtensionClient.java
  src/main/java/run/halo/app/extension/DelegateExtensionClient.java
  src/main/java/run/halo/app/extension/ExtensionClient.java
  src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, kind/cleanup, approved

#2788 chore: update issue templates for Halo 2.0
  .github/ISSUE_TEMPLATE/bug_report.en.yml
  .github/ISSUE_TEMPLATE/bug_report.zh.yml
  .github/ISSUE_TEMPLATE/feature_request.en.yml
  .github/ISSUE_TEMPLATE/feature_request.zh.yml
Labels: lgtm, release-note-none, approved, kind/improvement

#2745 refactor: cannot reload when settingName is not configured before
  src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
  src/main/java/run/halo/app/core/extension/theme/ThemeService.java
  src/main/java/run/halo/app/core/extension/theme/ThemeServiceImpl.java
  src/main/java/run/halo/app/infra/exception/AsyncRequestTimeoutException.java
  src/main/resources/extensions/role-template-theme.yaml
  src/test/java/run/halo/app/core/extension/theme/ThemeEndpointTest.java
  src/test/java/run/halo/app/core/extension/theme/ThemeServiceImplTest.java
Labels: lgtm, area/core, kind/api-change, approved, release-note, kind/improvement

#2753 Refine configuration for dev profile
  src/main/resources/application-dev.yaml
  src/main/resources/application-win.yaml
Labels: kind/support, lgtm, release-note-none, approved

#2791 Fix the problem that lucene crashes when searching for posts
  src/main/java/run/halo/app/event/post/PostDeletedEvent.java
  src/main/java/run/halo/app/event/post/PostEvent.java
  src/main/java/run/halo/app/event/post/PostPublishedEvent.java
  src/main/java/run/halo/app/event/post/PostRecycledEvent.java
  src/main/java/run/halo/app/event/post/PostUnpublishedEvent.java
  src/main/java/run/halo/app/extension/controller/DefaultController.java
  src/main/java/run/halo/app/search/post/LucenePostSearchService.java
  src/main/java/run/halo/app/search/post/PostDoc.java
  src/main/java/run/halo/app/search/post/PostEventListener.java
  src/main/java/run/halo/app/search/post/PostEventReconciler.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#2800 Simplify references in Attachment
  src/main/java/run/halo/app/core/extension/attachment/Attachment.java
  src/main/java/run/halo/app/core/extension/attachment/Policy.java
  src/main/java/run/halo/app/core/extension/attachment/PolicyTemplate.java
  src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
  src/main/java/run/halo/app/core/extension/attachment/endpoint/LocalAttachmentUploadHandler.java
  src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
  src/main/resources/extensions/attachment-local-policy.yaml
  src/test/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpointTest.java
Labels: lgtm, release-note-none, area/core, kind/api-change, approved, kind/improvement

#2801 feat: theme templates support global seo settings
  src/main/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessor.java
  src/main/java/run/halo/app/theme/dialect/GlobalSeoProcessor.java
  src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2795 Fix an optimistic lock error always appearing when restarting Halo
  src/main/java/run/halo/app/core/extension/reconciler/RoleReconciler.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2804 chore: temporarily disable JWT authentication function
  src/main/java/run/halo/app/Application.java
  src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  src/main/java/run/halo/app/infra/properties/JwtProperties.java
  src/main/java/run/halo/app/security/authentication/jwt/JwtAuthenticationConfigurer.java
  src/main/resources/app.key
  src/main/resources/app.pub
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
  src/test/java/run/halo/app/security/SuperAdminInitializerTest.java
  src/test/java/run/halo/app/security/authentication/jwt/JwtAuthenticationTest.java
  src/test/java/run/halo/app/security/authentication/jwt/LoginTest.java
  src/test/java/run/halo/app/security/authorization/AuthorizationTest.java
Labels: lgtm, release-note-none, area/core, kind/api-change, approved, kind/improvement

#2805 chore: update default theme package
  src/main/resources/themes/theme-earth.zip
Labels: lgtm, release-note-none, approved, kind/improvement

#2807 Allow migrating attachments from other places
  src/main/java/run/halo/app/config/WebFluxConfig.java
  src/main/java/run/halo/app/core/extension/attachment/Constant.java
  src/main/java/run/halo/app/core/extension/attachment/endpoint/LocalAttachmentUploadHandler.java
  src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
  src/main/java/run/halo/app/infra/properties/AttachmentProperties.java
  src/main/java/run/halo/app/infra/properties/HaloProperties.java
  src/main/resources/application.yaml
  src/main/resources/extensions/attachment-local-policy.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement
