Repository halo-dev/halo, pull requests merged in 2022-04, with the labels that each got.

#1806 Fix the NPE when deleting category
  src/main/java/run/halo/app/controller/content/auth/ContentAuthenticationManager.java
  src/test/java/run/halo/app/cache/LevelCacheStoreTest.java
  src/test/java/run/halo/app/service/impl/CategoryIntegrationTest.java
Labels: kind/bug, lgtm, area/core, approved

#1804 chore: issue template add hints on how to get logs
  .github/ISSUE_TEMPLATE/bug_report.en.yml
  .github/ISSUE_TEMPLATE/bug_report.zh.yml
Labels: lgtm, approved

#1811 Fix the problem of encrypted category displayed in query posts according to category
  src/main/java/run/halo/app/core/freemarker/tag/PostTagDirective.java
Labels: kind/bug, lgtm, area/core, approved

#1810 chore: issue templates add checklist
  .github/ISSUE_TEMPLATE/bug_report.en.yml
  .github/ISSUE_TEMPLATE/bug_report.zh.yml
Labels: lgtm, approved

#1812 Fix the problem of duplicate path separator in windows system
  src/main/java/run/halo/app/handler/file/FilePathDescriptor.java
  src/test/java/run/halo/app/handler/file/FilePathDescriptorTest.java
Labels: kind/bug, lgtm, area/core, approved

#1815 fix: update the posts encryption status synchronously after deleting the category
  src/main/java/run/halo/app/event/category/CategoryUpdatedEvent.java
  src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java
  src/main/java/run/halo/app/service/CategoryService.java
  src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
Labels: kind/bug, lgtm, area/core, approved

#1813 refactor: modify the frontMatter export format to yaml syntax
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/test/java/run/halo/app/utils/MarkdownUtilsTest.java
Labels: kind/bug, lgtm, approved

#1819 chore: upgrade spring boot to 2.5.12
  build.gradle
Labels: dependencies, lgtm, approved

#1821 fix: batch publishing does not refresh private status
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
Labels: kind/bug, lgtm, approved

#1820 fix: post modified in the recycle will be restored
  src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java
Labels: kind/bug, lgtm, approved

#1814 fix: the content cannot be saved problem when the patch status of V1 version of post content is recycle status
  src/main/java/run/halo/app/service/impl/ContentPatchLogServiceImpl.java
Labels: kind/bug, lgtm, area/core, approved

#1822 fix: posts in the recycle are not excluded when calculating posts under category
  src/main/java/run/halo/app/model/projection/CategoryIdPostStatusProjection.java
  src/main/java/run/halo/app/repository/PostCategoryRepository.java
  src/main/java/run/halo/app/service/impl/PostCategoryServiceImpl.java
Labels: kind/bug, lgtm, approved

#1823 fix: posts in the recycle are not excluded when calculating posts under tag
  src/main/java/run/halo/app/repository/PostTagRepository.java
Labels: kind/bug, lgtm, approved

#1824 fix: the encrypted post is in an incorrect state after being recovered from the recycle
  src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java
Labels: kind/bug, lgtm, approved

#1827 refactor: optimize post update listener code
  src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java
Labels: lgtm, approved

#1837 fix typo: eanbled to enabled
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: lgtm, approved

#1840 feat: add OWNERS file for prow
  OWNERS
Labels: lgtm

#1838 feat: Add security config for halo
  build.gradle
  src/main/java/run/halo/app/config/WebMvcConfig.java
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/authentication/OauthController.java
  src/main/java/run/halo/app/identity/entrypoint/JwtAccessDeniedHandler.java
  src/main/java/run/halo/app/identity/entrypoint/JwtAuthenticationEntryPoint.java
  src/main/java/run/halo/app/infra/properties/HaloProperties.java
  src/main/java/run/halo/app/infra/properties/JwtProperties.java
  src/main/java/run/halo/app/infra/utils/HaloUtils.java
  src/main/resources/app.key
  src/main/resources/app.pub
  src/main/resources/application.yaml
  src/test/java/run/halo/app/PathPrefixPredicateTest.java
  src/test/java/run/halo/app/integration/security/AuthenticationTest.java
  src/test/resources/app.key
  src/test/resources/app.pub
Labels: kind/feature, lgtm, area/core, approved

#1841 feat: add token provider
  build.gradle
  src/main/java/run/halo/app/identity/authentication/AccessToken.java
  src/main/java/run/halo/app/identity/authentication/JwtTokenProvider.java
  src/main/java/run/halo/app/identity/authentication/SecurityConstant.java
  src/main/java/run/halo/app/infra/properties/JwtProperties.java
  src/main/java/run/halo/app/infra/utils/HaloUtils.java
  src/test/java/run/halo/app/JwtTokenProviderTest.java
Labels: kind/feature, lgtm, area/core, approved

#1844 refactor: next line config
  .editorconfig
Labels: lgtm, approved

#1843 feat: Add JwtGenerator for authentication
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/authentication/Context.java
  src/main/java/run/halo/app/identity/authentication/DefaultOAuth2TokenContext.java
  src/main/java/run/halo/app/identity/authentication/JwtGenerator.java
  src/main/java/run/halo/app/identity/authentication/OAuth2TokenContext.java
  src/main/java/run/halo/app/identity/authentication/OAuth2TokenGenerator.java
  src/main/java/run/halo/app/identity/authentication/OAuth2TokenType.java
  src/main/java/run/halo/app/identity/authentication/ProviderContext.java
  src/main/java/run/halo/app/identity/authentication/ProviderSettings.java
  src/main/java/run/halo/app/infra/config/AbstractSettings.java
  src/main/java/run/halo/app/infra/config/ConfigurationSettingNames.java
  src/test/java/run/halo/app/authentication/JwtClaimsSetTest.java
  src/test/java/run/halo/app/authentication/JwtGeneratorTest.java
  src/test/java/run/halo/app/authentication/ProviderSettingsTest.java
Labels: kind/feature, lgtm, area/core, approved

#1846 feat: Add UsernamePasswordAuthenticationProvider and filter to authentication client password request
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/authentication/AccessToken.java
  src/main/java/run/halo/app/identity/authentication/JwtDaoAuthenticationProvider.java
  src/main/java/run/halo/app/identity/authentication/JwtGenerator.java
  src/main/java/run/halo/app/identity/authentication/JwtTokenProvider.java
  src/main/java/run/halo/app/identity/authentication/JwtUsernamePasswordAuthenticationFilter.java
  src/main/java/run/halo/app/identity/authentication/OAuth2AccessTokenAuthenticationToken.java
  src/main/java/run/halo/app/identity/authentication/OAuth2Authorization.java
  src/main/java/run/halo/app/identity/authentication/OAuth2AuthorizationService.java
  src/main/java/run/halo/app/identity/authentication/OauthController.java
  src/test/java/run/halo/app/JwtTokenProviderTest.java
  src/test/java/run/halo/app/PathPrefixPredicateTest.java
  src/test/java/run/halo/app/authentication/JwtUsernamePasswordAuthenticationFilterTests.java
Labels: kind/feature, lgtm, approved

#1852 feat: Add ProviderContextHolder for token generate
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/authentication/JwtDaoAuthenticationProvider.java
  src/main/java/run/halo/app/identity/authentication/ProviderContextFilter.java
  src/main/java/run/halo/app/identity/authentication/ProviderContextHolder.java
  src/test/java/run/halo/app/authentication/ProviderContextFilterTest.java
Labels: kind/feature, lgtm, area/core, approved

#1853 feat: Allow configuration for token and refresh token time-to-live
  src/main/java/run/halo/app/identity/authentication/JwtDaoAuthenticationProvider.java
  src/main/java/run/halo/app/identity/authentication/JwtGenerator.java
  src/main/java/run/halo/app/identity/authentication/OAuth2TokenContext.java
  src/main/java/run/halo/app/identity/authentication/ProviderSettings.java
  src/main/java/run/halo/app/infra/config/AbstractSettings.java
  src/main/java/run/halo/app/infra/config/ConfigurationSettingNames.java
  src/test/java/run/halo/app/authentication/JwtGeneratorTest.java
  src/test/java/run/halo/app/authentication/ProviderSettingsTest.java
Labels: kind/feature, lgtm, area/core, approved

#1854 feat: Add InMemoryOAuth2AuthorizationService for development or testing
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/authentication/InMemoryOAuth2AuthorizationService.java
  src/main/java/run/halo/app/identity/authentication/JwtDaoAuthenticationProvider.java
  src/main/java/run/halo/app/identity/authentication/OAuth2Authorization.java
  src/main/java/run/halo/app/identity/authentication/OAuth2AuthorizationService.java
  src/test/java/run/halo/app/authentication/InMemoryOAuth2AuthorizationServiceTest.java
Labels: kind/feature, lgtm, area/core, approved

#1856 feat: Add oauth2 refresh token authentication
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/authentication/DelegatingAuthenticationConverter.java
  src/main/java/run/halo/app/identity/authentication/JwtDaoAuthenticationProvider.java
  src/main/java/run/halo/app/identity/authentication/OAuth2AuthorizationGrantAuthenticationToken.java
  src/main/java/run/halo/app/identity/authentication/OAuth2EndpointUtils.java
  src/main/java/run/halo/app/identity/authentication/OAuth2RefreshTokenAuthenticationConverter.java
  src/main/java/run/halo/app/identity/authentication/OAuth2RefreshTokenAuthenticationProvider.java
  src/main/java/run/halo/app/identity/authentication/OAuth2RefreshTokenAuthenticationToken.java
  src/main/java/run/halo/app/identity/authentication/OAuth2TokenEndpointFilter.java
  src/test/java/run/halo/app/authentication/OAuth2RefreshTokenAuthenticationProviderTest.java
  src/test/java/run/halo/app/authentication/TestOAuth2Authorizations.java
Labels: kind/feature, lgtm, area/core, approved

#1860 Handle exception while sending test email
  src/main/java/run/halo/app/controller/admin/api/MailController.java
  src/main/java/run/halo/app/core/ControllerExceptionHandler.java
  src/main/java/run/halo/app/mail/AbstractMailService.java
Labels: kind/bug, lgtm, area/core, approved

#1859 chore: cleanup deprecated class
  src/main/java/run/halo/app/identity/authentication/Context.java
  src/main/java/run/halo/app/identity/authentication/DefaultOAuth2TokenContext.java
  src/main/java/run/halo/app/identity/authentication/JwtUsernamePasswordAuthenticationFilter.java
  src/main/java/run/halo/app/identity/authentication/OAuth2RefreshTokenAuthenticationConverter.java
  src/main/java/run/halo/app/identity/authentication/OAuth2TokenEndpointFilter.java
  src/main/java/run/halo/app/identity/authentication/OAuth2TokenGenerator.java
  src/main/java/run/halo/app/identity/authentication/OAuth2TokenType.java
  src/main/java/run/halo/app/identity/authentication/ProviderContext.java
  src/main/java/run/halo/app/identity/authentication/SecurityConstant.java
  src/test/java/run/halo/app/authentication/JwtUsernamePasswordAuthenticationFilterTests.java
Labels: lgtm, kind/cleanup, approved

#1861 feat: SMTP support configuration starttls
  src/main/java/run/halo/app/mail/AbstractMailService.java
  src/main/java/run/halo/app/model/properties/EmailProperties.java
Labels: kind/feature, lgtm, approved

#1863 chore: use providerSettings to create OAuth2TokenEndpointFilter
  src/main/java/run/halo/app/config/WebSecurityConfig.java
Labels: lgtm, approved

#1870 fix typo: swagger api operation title typo
  src/main/java/run/halo/app/controller/admin/api/PostController.java
Labels: lgtm, approved

#1864 feat: Add bearer token and bearer authentication
  src/main/java/run/halo/app/identity/authentication/verifier/AbstractOAuth2TokenAuthenticationToken.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthentication.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationToken.java
  src/test/java/run/halo/app/authentication/verifyer/BearerTokenAuthenticationTest.java
  src/test/java/run/halo/app/authentication/verifyer/BearerTokenAuthenticationTokenTest.java
Labels: kind/feature, lgtm, area/core, approved

#1868 feat: Add bearer token errors for rfc6750#section-3.1
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenError.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenErrorCodes.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenErrors.java
  src/test/java/run/halo/app/authentication/verifyer/BearerTokenErrorTest.java
  src/test/java/run/halo/app/authentication/verifyer/BearerTokenErrorsTest.java
Labels: kind/feature, lgtm, approved

#1867 temporarily stop database connection while backing up database files
  src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
Labels: lgtm, approved

#1869 feat: Add default bearer token resolver for rfc6750#section-2.1-2.3
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenResolver.java
  src/main/java/run/halo/app/identity/authentication/verifier/DefaultBearerTokenResolver.java
  src/test/java/run/halo/app/authentication/verifyer/DefaultBearerTokenResolverTest.java
Labels: kind/feature, lgtm, area/core, approved

#1873 fix: searching posts without related contents
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
Labels: kind/bug, lgtm, approved

#1871 feat: Add jwt token and provider for jwt authentication
  src/main/java/run/halo/app/identity/authentication/verifier/InvalidBearerTokenException.java
  src/main/java/run/halo/app/identity/authentication/verifier/JwtAuthenticationConverter.java
  src/main/java/run/halo/app/identity/authentication/verifier/JwtAuthenticationProvider.java
  src/main/java/run/halo/app/identity/authentication/verifier/JwtAuthenticationToken.java
  src/main/java/run/halo/app/identity/authentication/verifier/JwtGrantedAuthoritiesConverter.java
  src/test/java/run/halo/app/authentication/verifyer/JwtAuthenticationProviderTest.java
  src/test/java/run/halo/app/authentication/verifyer/JwtGrantedAuthoritiesConverterTest.java
  src/test/java/run/halo/app/authentication/verifyer/TestJwts.java
Labels: kind/feature, lgtm, area/core, approved

#1872 feat: Add bearer token authentication filter for bearer authentication
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationEntryPoint.java
  src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationFilter.java
Labels: kind/feature, lgtm, approved

#1876 feat: Add bearer token filter config for authentication
  src/main/java/run/halo/app/config/WebSecurityConfig.java
  src/main/java/run/halo/app/identity/HelloController.java
  src/main/java/run/halo/app/identity/authentication/verifier/JwtProvidedDecoderAuthenticationManagerResolver.java
Labels: kind/feature, lgtm, area/core, approved

#1878 feat: Add Principal attribute to authorizationBuilder when password authenticate successfully
  src/main/java/run/halo/app/identity/authentication/OAuth2PasswordAuthenticationProvider.java
Labels: kind/feature, lgtm, approved

#1890 Refine contribution.md to be clearly
  CONTRIBUTING.md
Labels: lgtm, approved, kind/documentation
