Repository halo-dev/halo, pull requests merged in 2022-10, with the labels that each got.

#2501 docs: remove readme documentation about running with jar
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2513 Add Pull Request template for default branch
  .github/pull_request_template.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2511 Bump version of Spring Boot & SpringDoc
  build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2517 fix: tracker counter api does not need authentication for theme
  src/main/resources/extensions/role-template-anonymous.yaml
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#2512 Support running Halo with MySQL and MariaDB database
  build.gradle
  src/main/resources/application-mysql.yaml
  src/main/resources/schema-mysql.sql
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2521 chore: rename the default location of the plugin's bundle resources to `console`
  src/main/java/run/halo/app/plugin/resources/JsBundleRuleProvider.java
Labels: lgtm, release-note-none, kind/api-change, approved, kind/improvement

#2518 fix: the exception of plugin context has been closed when plugin restart
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
  src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
  src/main/java/run/halo/app/plugin/BasePlugin.java
  src/main/java/run/halo/app/plugin/HaloPluginManager.java
  src/main/java/run/halo/app/plugin/SpringExtensionFactory.java
  src/test/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpointTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#2522 refactor: the way of router function register for reverse proxy
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/core/extension/reconciler/ReverseProxyReconciler.java
  src/main/java/run/halo/app/plugin/PluginCompositeRouterFunction.java
  src/main/java/run/halo/app/plugin/PluginConst.java
  src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
  src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistry.java
  src/test/java/run/halo/app/plugin/PluginCompositeRouterFunctionTest.java
  src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactoryTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2524 refactor: system role templates
  src/main/resources/extensions/role-template-authenticated.yaml
  src/main/resources/extensions/role-template-menu.yaml
  src/main/resources/extensions/role-template-plugin.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2527 docs: provides Halo 2.0 online demo environment
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2528 Refine logic of form login and logout
  docs/authentication/README.md
  src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  src/main/java/run/halo/app/security/DefaultUserDetailService.java
  src/main/java/run/halo/app/security/authentication/SecurityConfigurer.java
  src/main/java/run/halo/app/security/authentication/WebExchangeMatchers.java
  src/main/java/run/halo/app/security/authentication/formlogin/FormLoginConfigurer.java
  src/main/java/run/halo/app/security/authentication/jwt/JwtAuthenticationConfigurer.java
  src/main/java/run/halo/app/security/authentication/jwt/LoginAuthenticationFilter.java
  src/main/java/run/halo/app/security/authentication/logout/LogoutConfigurer.java
  src/test/java/run/halo/app/config/ExtensionConfigurationTest.java
  src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
  src/test/java/run/halo/app/security/DefaultUserDetailServiceTest.java
  src/test/java/run/halo/app/security/authentication/WebExchangeMatchersTest.java
  src/test/java/run/halo/app/security/authentication/jwt/JwtAuthenticationTest.java
  src/test/java/run/halo/app/security/authentication/jwt/LoginTest.java
  src/test/java/run/halo/app/security/authorization/AuthorizationTest.java
Labels: lgtm, area/core, kind/api-change, approved, release-note, kind/improvement

#2536 Continue extension updation if modification conflict occurs
  src/main/java/run/halo/app/infra/ExtensionResourceInitializer.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#2540 docs: remove changelog documentation
  CHANGELOG.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2546 Update README.md due to 2.0.0-alpha.2 released
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2566 feat: add upvote and downvote tracker
  src/main/java/run/halo/app/core/extension/Counter.java
  src/main/java/run/halo/app/core/extension/endpoint/TrackerEndpoint.java
  src/main/java/run/halo/app/metrics/CounterMeterHandler.java
  src/main/java/run/halo/app/metrics/MeterUtils.java
  src/main/java/run/halo/app/security/authorization/RbacRequestEvaluation.java
  src/main/resources/extensions/role-template-anonymous.yaml
  src/test/java/run/halo/app/metrics/MeterUtilsTest.java
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note

#2556 refactor: plugin js bundle file loading and routing rules
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
  src/main/java/run/halo/app/plugin/PluginConst.java
  src/main/java/run/halo/app/plugin/resources/BundleResourceUtils.java
  src/main/java/run/halo/app/plugin/resources/JsBundleRuleProvider.java
  src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
  src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
  src/test/java/run/halo/app/infra/utils/PathUtilsTest.java
  src/test/java/run/halo/app/plugin/resources/BundleResourceUtilsTest.java
  src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactoryTest.java
Labels: lgtm, area/core, kind/api-change, approved, release-note, kind/improvement

#2567 refactor: register method for reverse proxy registry
  src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistry.java
  src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistryTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2582 feat: add favicon head processor
  src/main/java/run/halo/app/theme/dialect/DefaultFaviconHeadProcessor.java
  src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#2587 refactor: get default menu
  src/main/java/run/halo/app/theme/finders/impl/MenuFinderImpl.java
  src/main/java/run/halo/app/theme/finders/vo/MenuItemVo.java
  src/main/java/run/halo/app/theme/finders/vo/MenuVo.java
  src/main/java/run/halo/app/theme/finders/vo/VisualizableTreeNode.java
  src/test/java/run/halo/app/theme/finders/impl/MenuFinderImplTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2574 feat: head tag supports extension for template
  src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
  src/main/java/run/halo/app/theme/dialect/TemplateHeadProcessor.java
  src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#2586 feat: add an API to list uninstalled themes
  src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
  src/main/java/run/halo/app/extension/ListResult.java
  src/main/java/run/halo/app/theme/ThemePathPolicy.java
  src/main/resources/extensions/role-template-theme.yaml
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note

#2563 Enable generating metadata name using generateName
  src/main/java/run/halo/app/extension/JSONExtensionConverter.java
  src/main/java/run/halo/app/extension/Metadata.java
  src/main/java/run/halo/app/extension/MetadataOperator.java
  src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  src/main/java/run/halo/app/extension/Unstructured.java
  src/test/java/run/halo/app/extension/JsonExtensionConverterTest.java
  src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#2592 refactor: theme list data conversion
  src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#2537 fix: list as tree in category finder
  src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
  src/main/java/run/halo/app/theme/finders/vo/CategoryTreeVo.java
  src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#2608 Make field metadata.name of extension required
  src/main/java/run/halo/app/extension/JSONExtensionConverter.java
  src/main/java/run/halo/app/extension/Metadata.java
  src/main/java/run/halo/app/extension/MetadataOperator.java
  src/main/java/run/halo/app/infra/utils/YamlUnstructuredLoader.java
  src/test/java/run/halo/app/extension/JsonExtensionConverterTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2609 refactor: rename stats to dashboard stats
  src/main/java/run/halo/app/core/extension/endpoint/StatsEndpoint.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2604 feat: add site stats finder for theme-side
  src/main/java/run/halo/app/theme/finders/SiteStatsFinder.java
  src/main/java/run/halo/app/theme/finders/impl/SiteStatsFinderImpl.java
  src/main/java/run/halo/app/theme/finders/vo/SiteStatsVo.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#2600 Provide an endpoint to upgrade theme
  src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
  src/main/java/run/halo/app/core/extension/theme/ThemeUtils.java
  src/main/java/run/halo/app/infra/utils/FileUtils.java
  src/test/java/run/halo/app/core/extension/theme/ThemeEndpointTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#2612 Use CopyOnWriteArrayList on SchemeManager
  src/main/java/run/halo/app/extension/DefaultSchemeManager.java
  src/main/java/run/halo/app/extension/DefaultSchemeWatcherManager.java
  src/main/java/run/halo/app/extension/controller/DefaultController.java
  src/test/java/run/halo/app/extension/DefaultSchemeManagerTest.java
  src/test/java/run/halo/app/extension/DefaultSchemeWatcherManagerTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#2615 fix: fail to save existing post with blank content
  src/main/java/run/halo/app/service/impl/ContentPatchLogServiceImpl.java
Labels: kind/bug, lgtm, release-note-none, approved

#2607 Fix the problem of deleting attachment on USS but failed
  src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#2601 refactor: cascade delete snapshots and comments when post or page deleted
  src/main/java/run/halo/app/config/ExtensionConfiguration.java
  src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
  src/main/java/run/halo/app/extension/ExtensionOperator.java
  src/main/java/run/halo/app/metrics/CounterService.java
  src/main/java/run/halo/app/metrics/CounterServiceImpl.java
  src/test/java/run/halo/app/core/extension/reconciler/SinglePageReconcilerTest.java
  src/test/java/run/halo/app/extension/ExtensionOperatorTest.java
  src/test/java/run/halo/app/metrics/CounterServiceImplTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#2613 refactor: files were not deleted when the plugin was uninstalled
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/infra/utils/FileUtils.java
  src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2620 Bump Spring Boot to 3.0.0-RC1
  build.gradle
  settings.gradle
  src/main/java/run/halo/app/security/CsrfConfigurer.java
  src/main/java/run/halo/app/security/authentication/pat/PatAuthenticationConverter.java
  src/main/java/run/halo/app/theme/ThemeConfiguration.java
  src/main/java/run/halo/app/theme/dialect/DefaultJava8TimeExpressionFactory.java
  src/main/java/run/halo/app/theme/dialect/ThemeJava8TimeDialect.java
  src/test/java/run/halo/app/theme/dialect/ThemeJava8TimeDialectIntegrationTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2623 fix: issue of abnormal sorting in the aggregation query interface
  src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
  src/main/java/run/halo/app/theme/finders/impl/CommentFinderImpl.java
Labels: kind/bug, lgtm, approved, release-note

#2598 feat: provides the route of the post archive page for theme-side
  src/main/java/run/halo/app/core/extension/Post.java
  src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  src/main/java/run/halo/app/infra/utils/HaloUtils.java
  src/main/java/run/halo/app/theme/finders/PostFinder.java
  src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  src/main/java/run/halo/app/theme/finders/vo/PostArchiveVo.java
  src/main/java/run/halo/app/theme/finders/vo/PostArchiveYearMonthVo.java
  src/main/java/run/halo/app/theme/router/PermalinkHttpGetRouter.java
  src/main/java/run/halo/app/theme/router/RadixRouterTree.java
  src/main/java/run/halo/app/theme/router/strategy/ArchivesRouteStrategy.java
  src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java
  src/test/java/run/halo/app/theme/router/strategy/IndexRouteStrategyTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#2625 refactor: plugin reconciler to fix entry path when optimistic lock occurred
  src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/plugin/PluginBeforeStopSyncListener.java
  src/main/java/run/halo/app/theme/router/PermalinkRefreshHandler.java
  src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2626 refactor: fill in the name of the rendered template as the template id to the view model
  src/main/java/run/halo/app/theme/dialect/PostTemplateHeadProcessor.java
  src/main/java/run/halo/app/theme/dialect/TemplateGlobalHeadProcessor.java
  src/main/java/run/halo/app/theme/router/strategy/CategoriesRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/CategoryRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/IndexRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/ModelConst.java
  src/main/java/run/halo/app/theme/router/strategy/PermalinkPredicates.java
  src/main/java/run/halo/app/theme/router/strategy/PostRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/TagRouteStrategy.java
  src/main/java/run/halo/app/theme/router/strategy/TagsRouteStrategy.java
  src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#2624 Provide an endpoint to upgrade plugin
  src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  src/main/java/run/halo/app/infra/utils/FileUtils.java
  src/main/resources/extensions/role-template-plugin.yaml
  src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
  src/test/java/run/halo/app/infra/utils/FileNameUtilsTest.java
  src/test/java/run/halo/app/infra/utils/FileUtilsTest.java
  src/test/java/run/halo/app/security/DefaultUserDetailServiceTest.java
  src/test/resources/folder-to-zip/examplefile
  src/test/resources/plugin/plugin-0.0.2/plugin.yaml
Labels: kind/feature, lgtm, area/core, approved, release-note

#2630 chore: disable thymeleaf cache in dev profile
  src/main/resources/application-dev.yaml
Labels: lgtm, approved, release-note, kind/improvement

#2628 Bump SpringDoc to 2.0.0-RC1
  build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2631 Bump jasync-r2dbc-mysql to 2.1.7
  build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2629 refactor: use LinkedHashMultimap to replace MultiValueMap
  src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistry.java
  src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistryTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2632 refactor: ignore trailing separator for permalink router
  src/main/java/run/halo/app/theme/router/RadixRouterTree.java
  src/main/java/run/halo/app/theme/router/strategy/ArchivesRouteStrategy.java
  src/test/java/run/halo/app/theme/router/RadixRouterTreeTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#2634 Update README.md due to 2.0.0-alpha.3 released
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#2636 feat: support obtaining the previous post and next post according to post name
  src/main/java/run/halo/app/theme/finders/PostFinder.java
  src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  src/main/java/run/halo/app/theme/finders/vo/NavigationPostVo.java
  src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note
