Repository halo-dev/halo, pull requests merged in 2022-02, with the labels that each got.

#1636 perf: add password reset field verification
  src/main/java/run/halo/app/controller/admin/api/AdminController.java
  src/main/java/run/halo/app/model/params/ResetPasswordParam.java
  src/main/java/run/halo/app/model/params/ResetPasswordSendCodeParam.java
  src/main/java/run/halo/app/service/AdminService.java
  src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
  src/test/java/run/halo/app/controller/AdminControllerTest.java
Labels: enhancement

#1617 Split post content to new table and support content version control
  build.gradle
  src/main/java/run/halo/app/controller/admin/api/PostController.java
  src/main/java/run/halo/app/controller/admin/api/SheetController.java
  src/main/java/run/halo/app/controller/content/ContentFeedController.java
  src/main/java/run/halo/app/controller/content/api/PostController.java
  src/main/java/run/halo/app/controller/content/api/SheetController.java
  src/main/java/run/halo/app/controller/content/model/PostModel.java
  src/main/java/run/halo/app/controller/content/model/SheetModel.java
  src/main/java/run/halo/app/model/dto/post/BasePostDetailDTO.java
  src/main/java/run/halo/app/model/dto/post/BasePostSimpleDTO.java
  src/main/java/run/halo/app/model/entity/BasePost.java
  src/main/java/run/halo/app/model/entity/Content.java
  src/main/java/run/halo/app/model/entity/ContentPatchLog.java
  src/main/java/run/halo/app/model/params/PostParam.java
  src/main/java/run/halo/app/model/params/SheetParam.java
  src/main/java/run/halo/app/repository/ContentPatchLogRepository.java
  src/main/java/run/halo/app/repository/ContentRepository.java
  src/main/java/run/halo/app/repository/base/BasePostRepository.java
  src/main/java/run/halo/app/service/ContentPatchLogService.java
  src/main/java/run/halo/app/service/ContentService.java
  src/main/java/run/halo/app/service/base/BasePostService.java
  src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
  src/main/java/run/halo/app/service/impl/ContentPatchLogServiceImpl.java
  src/main/java/run/halo/app/service/impl/ContentServiceImpl.java
  src/main/java/run/halo/app/service/impl/PostServiceImpl.java
  src/main/java/run/halo/app/service/impl/SheetServiceImpl.java
  src/main/java/run/halo/app/utils/JsonUtils.java
  src/main/java/run/halo/app/utils/PatchUtils.java
  src/main/resources/migration/V6__migrate_create_contents_table.sql
  src/test/java/run/halo/app/repository/ContentPatchLogRepositoryTest.java
  src/test/java/run/halo/app/service/impl/ContentPatchLogServiceImplTest.java
Labels: enhancement

#1668 Content add front-end rendering options
  src/main/java/run/halo/app/controller/admin/api/PostController.java
  src/main/java/run/halo/app/controller/admin/api/SheetController.java
  src/main/java/run/halo/app/controller/content/model/SheetModel.java
  src/main/java/run/halo/app/model/params/BasePostParam.java
  src/main/java/run/halo/app/model/params/PostContentParam.java
  src/main/java/run/halo/app/model/params/PostParam.java
  src/main/java/run/halo/app/model/params/SheetParam.java
  src/main/java/run/halo/app/service/base/BasePostService.java
  src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
  src/main/java/run/halo/app/utils/PatchUtils.java
  src/test/java/run/halo/app/model/params/PostParamTest.java
Labels: enhancement

#1680 feat: add api for delete photos in batch
  src/main/java/run/halo/app/controller/admin/api/PhotoController.java
Labels: enhancement

#1679 feat: add api for update photos in batch
  src/main/java/run/halo/app/controller/admin/api/PhotoController.java
  src/main/java/run/halo/app/model/params/PhotoParam.java
Labels: enhancement

#1677 Bump spring boot to 2.5.10
  build.gradle
Labels: dependencies

#1686 fix: Post and sheet content is empty in the Content API
  src/main/java/run/halo/app/controller/content/api/PostController.java
  src/main/java/run/halo/app/controller/content/api/SheetController.java
Labels: bug
