Repository halo-dev/halo, pull requests merged in 2023-10, with the labels that each got.

#4681 Prevent Lucene search engine updates from being interrupted
  application/src/main/java/run/halo/app/search/post/LucenePostSearchService.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#4678 fix: incorrect truncation of CSS resource reads
  application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#4685 fix: compatible email are empty when comment notification triggered
  application/src/main/java/run/halo/app/content/comment/ReplyNotificationSubscriptionHelper.java
  application/src/main/java/run/halo/app/notification/EmailNotifier.java
  application/src/main/resources/extensions/notification.yaml
Labels: kind/bug, lgtm, area/core, approved, release-note

#4688 feat: add loading state for switch component
  console/packages/components/src/components/switch/Switch.vue
  console/packages/components/src/components/switch/__tests__/Switch.spec.ts
  console/src/modules/system/plugins/components/entity-fields/SwitchField.vue
Labels: kind/feature, lgtm, approved, area/console, release-note

#4686 feat: add encryption setting for email notifier
  application/src/main/java/run/halo/app/notification/EmailNotifier.java
  application/src/main/resources/extensions/notification.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#4689 feat: make attachment list item operations extendable
  console/docs/extension-points/entity-listitem-operation.md
  console/packages/shared/src/types/plugin.ts
  console/src/modules/contents/attachments/AttachmentList.vue
  console/src/modules/contents/attachments/components/AttachmentListItem.vue
  console/src/modules/contents/attachments/composables/use-attachment.ts
Labels: kind/feature, lgtm, approved, area/console, release-note

#4680 feat: support configuring notifier for different notification reason types
  application/src/main/java/run/halo/app/notification/UserNotificationPreference.java
  application/src/main/java/run/halo/app/notification/UserNotificationPreferenceService.java
  application/src/main/java/run/halo/app/notification/UserNotificationPreferenceServiceImpl.java
  application/src/main/java/run/halo/app/notification/endpoint/UserNotificationPreferencesEndpoint.java
  application/src/main/resources/extensions/role-template-authenticated.yaml
  application/src/test/java/run/halo/app/notification/endpoint/UserNotificationPreferencesEndpointTest.java
  console/packages/api-client/src/.openapi-generator/FILES
  console/packages/api-client/src/api/api-notification-halo-run-v1alpha1-notification-api.ts
  console/packages/api-client/src/models/index.ts
  console/packages/api-client/src/models/notifier-info.ts
  console/packages/api-client/src/models/reason-type-info.ts
  console/packages/api-client/src/models/reason-type-notifier-collection-request.ts
  console/packages/api-client/src/models/reason-type-notifier-matrix-item.ts
  console/packages/api-client/src/models/reason-type-notifier-matrix.ts
  console/packages/api-client/src/models/reason-type-notifier-request.ts
  console/src/locales/en.yaml
  console/src/locales/zh-CN.yaml
  console/src/locales/zh-TW.yaml
  console/src/modules/system/users/UserDetail.vue
  console/src/modules/system/users/tabs/NotificationPreferences.vue
Labels: kind/feature, lgtm, area/core, approved, area/console, release-note

#4694 feat: display add icon when user avatar is not setting
  console/src/modules/system/users/components/UserAvatar.vue
Labels: lgtm, approved, area/console, release-note, kind/improvement

#4698 chore: bump @halo-dev/components version to 1.9.0
  console/packages/components/package.json
Labels: lgtm, release-note-none, approved, area/console, kind/improvement

#4699 chore: bump app store plugin version to 1.0.0-beta.2
  application/build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#4700 chore: bump default theme version to 1.6.0
  application/src/main/resources/themes/theme-earth.zip
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#4695 fix: incorrect unsubscribe link for email notification
  application/src/main/java/run/halo/app/notification/DefaultNotificationCenter.java
  application/src/main/java/run/halo/app/notification/EmailNotifier.java
  application/src/main/java/run/halo/app/notification/endpoint/SubscriptionRouter.java
  application/src/test/java/run/halo/app/notification/endpoint/SubscriptionRouterTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#4701 Fix the problem that OAuth2 users cannot create PATs
  application/src/main/java/run/halo/app/security/authentication/pat/impl/UserScopedPatHandlerImpl.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#4703 chore: modify the name in the notification template
  application/src/main/java/run/halo/app/notification/EmailNotifier.java
  application/src/main/resources/extensions/notification-templates.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#4709 Prepare for next development 2.11.0
  README.md
  console/package.json
  console/packages/api-client/package.json
  console/packages/components/package.json
  console/packages/shared/package.json
  gradle.properties
Labels: lgtm, release-note-none, kind/cleanup, approved

#4702 refactor: refactor the repeater component using the schema approach
  console/docs/custom-formkit-input/README.md
  console/src/formkit/formkit.config.ts
  console/src/formkit/inputs/repeater/AddButton.vue
  console/src/formkit/inputs/repeater/Repeater.vue
  console/src/formkit/inputs/repeater/features/repeats.ts
  console/src/formkit/inputs/repeater/index.ts
  console/src/formkit/inputs/repeater/repeaterSection.ts
  console/src/formkit/inputs/repeater/sections/index.ts
  console/src/formkit/theme.ts
Labels: lgtm, approved, area/console, release-note, kind/improvement

#4717 Fix typo of authentication document
  docs/authentication/README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#4746 fix: plugin extension tab cannot be displayed when only having plugin view permissions
  console/src/modules/system/plugins/PluginDetail.vue
Labels: kind/bug, lgtm, approved, area/console, release-note

#4758 Upgrade to Spring Boot 3.1.5
  application/build.gradle
  platform/application/build.gradle
Labels: lgtm, kind/cleanup, approved, release-note

#4745 refactor: provide API for change plugin motion status synchronously
  application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  application/src/main/resources/extensions/role-template-plugin.yaml
Labels: lgtm, area/core, approved, area/console, release-note, kind/improvement

#4736 fix: incorrect results when filtering unpublished posts
  application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#4747 refactor: use new api to change plugin status
  console/packages/api-client/src/.openapi-generator/FILES
  console/packages/api-client/src/api/api-console-halo-run-v1alpha1-plugin-api.ts
  console/packages/api-client/src/models/contributor-vo.ts
  console/packages/api-client/src/models/index.ts
  console/packages/api-client/src/models/plugin-running-state-request.ts
  console/src/modules/system/plugins/composables/use-plugin.ts
  console/src/modules/system/plugins/tabs/Detail.vue
  console/src/views/system/SetupInitialData.vue
Labels: lgtm, release-note-none, approved, area/console, kind/improvement

#4772 fix: resolve the issue of occasional blank annotation and error occurrences
  console/src/components/form/AnnotationsForm.vue
Labels: kind/bug, lgtm, approved, release-note

#4777 fix: cannot change the user's own avatar
  console/src/modules/system/users/components/UserAvatar.vue
Labels: kind/bug, lgtm, approved, release-note

#4773 fix: change the ref parameter type in the list method of comment finder api to map
  application/src/main/java/run/halo/app/theme/finders/CommentFinder.java
  application/src/main/java/run/halo/app/theme/finders/impl/CommentFinderImpl.java
Labels: kind/bug, lgtm, release-note-none, approved

#4775 refactor: autofill if post is published but no publish time
  application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  application/src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#4785 fix: correct the tooltip of view type in the Attachments page
  console/src/modules/contents/attachments/AttachmentList.vue
Labels: kind/bug, lgtm, approved, release-note
