Repository halo-dev/halo, pull requests merged in 2023-06, with the labels that each got.

#4019 chore: update default theme to 1.4.0
  application/src/main/resources/themes/theme-earth.zip
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#4020 Set open mode of indices to CREATE_OR_APPEND
  application/src/main/java/run/halo/app/search/post/LucenePostSearchService.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#4021 chore: release 2.6.0
  console/package.json
  console/packages/api-client/package.json
  console/packages/components/package.json
  console/packages/shared/package.json
Labels: lgtm, release-note-none, area/core, approved

#4026 Bump Halo to 2.7.0-SNAPSHOT
  README.md
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#4027 Bump Halo to 2.6.1
  .github/workflows/halo.yaml
  README.md
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#4031 Fix the meta description with special characters causing the page to display abnormally
  application/src/main/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessor.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#4043 Support configuration properties mechanism for plugin in Halo core
  application/src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
  docs/developer-guide/plugin-configuration-properties.md
Labels: kind/feature, lgtm, area/core, approved, release-note, area/plugin

#4052 Fix AttachmentReconciler repeated execution
  application/src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
Labels: kind/bug, lgtm, approved, release-note

#4072 fix: file path traversal vulnerability in theme and plugin resource APIs
  application/src/main/java/run/halo/app/plugin/resources/BundleResourceUtils.java
  application/src/main/java/run/halo/app/theme/ThemeConfiguration.java
  application/src/test/java/run/halo/app/plugin/resources/BundleResourceUtilsTest.java
  application/src/test/java/run/halo/app/theme/ThemeConfigurationTest.java
Labels: kind/bug, vulnerability, lgtm, area/core, approved, release-note

#4076 Adapt workflow for release-2.5 branch
  .github/workflows/halo.yaml
  README.md
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#4081 chore: bump google guava version to 32.0.1-jre
  application/build.gradle
  platform/application/build.gradle
Labels: lgtm, area/core, approved, release-note

#4062 Add rate limiter for login endpoint
  api/build.gradle
  application/build.gradle
  application/src/main/java/run/halo/app/infra/exception/Exceptions.java
  application/src/main/java/run/halo/app/infra/exception/ThemeAlreadyExistsException.java
  application/src/main/java/run/halo/app/infra/utils/IpAddressUtils.java
  application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordAuthenticator.java
  application/src/main/resources/application.yaml
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/test/java/run/halo/app/infra/utils/IpAddressUtilsTest.java
  console/src/components/login/LoginForm.vue
  platform/application/build.gradle
Labels: kind/feature, lgtm, area/core, approved, release-note

#4085 perf: remove html lang attribute in console
  console/index.html
Labels: lgtm, approved, area/console, release-note, kind/improvement

#4066 perf: disallow repeated clicks when third-party login
  console/src/components/login/SocialAuthProviderItem.vue
  console/src/components/login/SocialAuthProviders.vue
Labels: lgtm, approved, area/console, release-note, kind/improvement

#4056 feat: add support for selecting the parent category when creating a new category
  console/src/locales/en.yaml
  console/src/locales/zh-CN.yaml
  console/src/locales/zh-TW.yaml
  console/src/modules/contents/posts/categories/CategoryList.vue
  console/src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  console/src/modules/contents/posts/categories/components/CategoryListItem.vue
Labels: kind/feature, lgtm, approved, area/console, release-note

#4101 Fix the problem of logging in successfully even if request not permitted
  application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordAuthenticator.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#4096 Exclude WebSocket request when serving console index
  application/src/main/java/run/halo/app/config/WebFluxConfig.java
  application/src/main/java/run/halo/app/console/ConsoleProxyFilter.java
  application/src/main/java/run/halo/app/console/WebSocketRequestPredicate.java
  application/src/main/java/run/halo/app/console/WebSocketServerWebExchangeMatcher.java
  application/src/main/java/run/halo/app/console/WebSocketUtils.java
  application/src/test/java/run/halo/app/console/WebSocketUtilsTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#4099 Refactor setting of problem detail type
  application/src/main/java/run/halo/app/infra/exception/Exceptions.java
  application/src/main/java/run/halo/app/infra/exception/handlers/ProblemDetailErrorAttributes.java
  application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordAuthenticator.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/test/resources/config/i18n/messages.properties
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#4103 chore: bump formkit version to 0.17.3
  console/package.json
  console/pnpm-lock.yaml
  console/src/formkit/plugins/required-asterisk.ts
  console/src/formkit/plugins/stop-implicit-submission.ts
Labels: lgtm, approved, area/console, release-note, kind/improvement

#4106 fix: modal height issue in ios devices
  console/package.json
  console/pnpm-lock.yaml
  console/postcss.config.js
  console/src/App.vue
Labels: lgtm, approved, area/console, release-note, kind/improvement

#4108 feat: add mouse hover style to the default type of button
  console/packages/components/src/components/button/Button.vue
Labels: lgtm, approved, area/console, release-note, kind/improvement

#4115 perf: improve the text length style of the comment subject ref title
  console/src/modules/contents/comments/components/CommentListItem.vue
Labels: lgtm, release-note-none, approved, area/console, kind/improvement

#4084 feat: add rate limiter for comment endpoint
  application/src/main/java/run/halo/app/theme/endpoint/CommentFinderEndpoint.java
  application/src/main/resources/application.yaml
  application/src/test/java/run/halo/app/theme/endpoint/CommentFinderEndpointTest.java
Labels: kind/feature, lgtm, approved, release-note

#4105 chore: improve the console project infrastructure
  console/.eslintrc.cjs
  console/env.d.ts
  console/package.json
  console/packages/components/env.d.ts
  console/packages/components/package.json
  console/packages/components/src/components/dialog/interface.ts
  console/packages/components/tsconfig.app.json
  console/packages/components/tsconfig.json
  console/packages/components/tsconfig.node.json
  console/packages/components/tsconfig.vite-config.json
  console/packages/components/vite.config.ts
  console/packages/shared/env.d.ts
  console/packages/shared/package.json
  console/packages/shared/tsconfig.app.json
  console/packages/shared/tsconfig.json
  console/packages/shared/tsconfig.node.json
  console/packages/shared/tsconfig.vite-config.json
  console/packages/shared/vite.config.ts
  console/pnpm-lock.yaml
  console/src/components/menu/RoutesMenu.tsx
  console/src/modules/contents/attachments/components/AttachmentSelectorModal.vue
  console/src/modules/contents/posts/widgets/PostStatsWidget.vue
  console/src/modules/dashboard/Dashboard.vue
  console/src/modules/interface/menus/utils/__tests__/__snapshots__/index.spec.ts.snap
  console/src/modules/interface/menus/utils/__tests__/index.spec.ts
  console/src/modules/interface/themes/components/ThemeUploadModal.vue
  console/src/modules/interface/themes/components/preview/ThemePreviewModal.vue
  console/src/modules/interface/themes/layouts/ThemeLayout.vue
  console/src/modules/system/plugins/components/PluginUploadModal.vue
  console/src/modules/system/plugins/layouts/PluginLayout.vue
  console/src/modules/system/settings/layouts/SystemSettingsLayout.vue
  console/tsconfig.app.json
  console/tsconfig.json
  console/tsconfig.node.json
  console/tsconfig.vite-config.json
Labels: lgtm, approved, area/console, release-note, kind/improvement

#4112 feat: add permission settings to dashboard widgets
  console/src/modules/dashboard/Dashboard.vue
  console/src/utils/permission.ts
Labels: lgtm, approved, area/console, release-note, kind/improvement

#4039 feat: make comment subject ref provider extensible
  console/docs/extension-points/comment-subject-ref.md
  console/packages/shared/src/index.ts
  console/packages/shared/src/states/comment-subject-ref.ts
  console/packages/shared/src/types/plugin.ts
  console/src/modules/contents/comments/components/CommentListItem.vue
Labels: kind/feature, lgtm, approved, area/console, release-note, area/plugin

#4070 Fix the problem that the username does not exist when the username does not exist
  application/src/main/java/run/halo/app/security/DefaultUserDetailService.java
  application/src/test/java/run/halo/app/security/DefaultUserDetailServiceTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#4116 fix: dropdown options cannot be clicked in some mobile devices
  console/packages/components/src/components/dropdown/Dropdown.vue
  console/packages/components/src/components/dropdown/DropdownItem.vue
  console/packages/components/src/components/dropdown/index.ts
  console/packages/components/src/components/dropdown/symbols.ts
  console/src/components/dropdown-selector/CategoryDropdownSelector.vue
  console/src/components/dropdown-selector/TagDropdownSelector.vue
  console/src/components/dropdown-selector/UserDropdownSelector.vue
  console/src/modules/contents/attachments/components/AttachmentGroupList.vue
  console/src/modules/interface/themes/components/components/ThemeListItem.vue
  console/src/modules/system/plugins/components/PluginListItem.vue
Labels: lgtm, approved, area/console, release-note, kind/improvement

#4114 refactor: add legacy option for useClipboard hook to solve compatibility issues
  console/src/modules/contents/attachments/composables/use-attachment.ts
  console/src/modules/system/actuator/Actuator.vue
Labels: lgtm, approved, area/console, release-note, kind/improvement

#4063 feat: add redirect support for social auth provider
  console/src/components/login/SocialAuthProviderItem.vue
Labels: kind/feature, lgtm, approved, area/console, release-note

#4091 Add support for caching template rendering result
  api/build.gradle
  application/src/main/java/run/halo/app/cache/CacheEndpoint.java
  application/src/main/java/run/halo/app/cache/CacheWebFilter.java
  application/src/main/java/run/halo/app/cache/CachedResponse.java
  application/src/main/java/run/halo/app/config/CacheConfiguration.java
  application/src/main/java/run/halo/app/infra/properties/CacheProperties.java
  application/src/main/java/run/halo/app/infra/properties/HaloProperties.java
  application/src/main/java/run/halo/app/theme/HaloViewResolver.java
  application/src/main/resources/application.yaml
  console/packages/api-client/src/.openapi-generator/FILES
  console/packages/api-client/src/api.ts
  console/packages/api-client/src/api/v1alpha1-cache-api.ts
  console/packages/api-client/src/models/secret.ts
  console/src/locales/en.yaml
  console/src/locales/zh-CN.yaml
  console/src/locales/zh-TW.yaml
  console/src/modules/dashboard/widgets/QuickLinkWidget.vue
  console/src/utils/api-client.ts
  docs/cache/page.md
Labels: kind/feature, lgtm, area/core, approved, release-note

#4129 refactor: simplify request exception handling
  console/src/components/login/LoginForm.vue
  console/src/locales/en.yaml
  console/src/locales/zh-CN.yaml
  console/src/locales/zh-TW.yaml
  console/src/utils/api-client.ts
Labels: lgtm, release-note-none, approved, area/console, kind/improvement

#4135 Apply rate limiter for replying a comment
  application/src/main/java/run/halo/app/theme/endpoint/CommentFinderEndpoint.java
  application/src/main/resources/application.yaml
  application/src/test/java/run/halo/app/theme/endpoint/CommentFinderEndpointTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#4136 Upgrade Spring Boot to 3.1.1
  application/build.gradle
  gradle.properties
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#4139 Check X-Real-IP header when obtaining client IP
  application/src/main/java/run/halo/app/infra/utils/IpAddressUtils.java
  application/src/test/java/run/halo/app/infra/utils/IpAddressUtilsTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#4126 feat: add support for inserting external media resources to the default editor
  console/src/components/editor/DefaultEditor.vue
  console/src/locales/en.yaml
  console/src/locales/zh-CN.yaml
  console/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, area/console, release-note, area/editor

#4069 refactor: content page meta tags now override global injected
  api/src/main/java/run/halo/app/theme/dialect/TemplateHeadProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/DuplicateMetaTagProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/GlobalSeoProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/TemplateGlobalHeadProcessor.java
  application/src/test/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessorIntegrationTest.java
  application/src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java
  application/src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#4128 Add rate limiter for signing up
  application/src/main/java/run/halo/app/theme/endpoint/PublicUserEndpoint.java
  application/src/main/resources/application.yaml
  application/src/test/java/run/halo/app/theme/endpoint/PublicUserEndpointTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#4104 feat: support for obtaining the newest comments on theme-side
  .editorconfig
  api/src/main/java/run/halo/app/core/extension/content/Comment.java
  application/src/main/java/run/halo/app/theme/finders/CommentFinder.java
  application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
  application/src/main/java/run/halo/app/theme/finders/vo/CommentVo.java
Labels: kind/feature, lgtm, area/core, approved, area/theme, release-note

#4146 chore: bump @halo-dev/richtext-editor version to alpha 24
  console/package.json
  console/pnpm-lock.yaml
Labels: lgtm, release-note-none, area/console, kind/improvement

#4151 Enable configuration caching with separate names
  application/src/main/java/run/halo/app/cache/PageCacheWebFilter.java
  application/src/main/java/run/halo/app/config/CacheConfiguration.java
  application/src/main/java/run/halo/app/infra/properties/CacheProperties.java
  application/src/main/java/run/halo/app/infra/properties/HaloProperties.java
  application/src/main/java/run/halo/app/theme/HaloViewResolver.java
  application/src/main/resources/application.yaml
  console/src/modules/dashboard/widgets/QuickLinkWidget.vue
  docs/cache/page.md
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#4150 feat: support obtaining the raw external URL configuration
  api/src/main/java/run/halo/app/infra/ExternalUrlSupplier.java
  application/src/main/java/run/halo/app/infra/HaloPropertiesExternalUrlSupplier.java
  application/src/test/java/run/halo/app/infra/HaloPropertiesExternalUrlSupplierTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#4153 Add role template for managing cache
  application/src/main/java/run/halo/app/cache/CacheEndpoint.java
  application/src/main/resources/extensions/role-template-cache.yaml
  console/packages/api-client/src/api/v1alpha1-cache-api.ts
  console/src/locales/en.yaml
  console/src/locales/zh-CN.yaml
  console/src/locales/zh-TW.yaml
  console/src/modules/dashboard/widgets/QuickLinkWidget.vue
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#4159 chore: update preset plugins
  application/build.gradle
Labels: lgtm, release-note-none, area/core, approved, area/plugin

#4155 fix: creating a draft cannot be displayed in the post list
  application/src/main/java/run/halo/app/content/AbstractContentService.java
  application/src/main/java/run/halo/app/theme/router/PreviewRouterFunction.java
Labels: lgtm, release-note-none, approved

#4158 chore: release 2.7.0
  console/package.json
  console/packages/api-client/package.json
  console/packages/components/package.json
  console/packages/shared/package.json
Labels: lgtm, release-note-none, approved

#4168 Prepare for next release 2.8.0
  README.md
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved
