Repository halo-dev/halo, pull requests merged in 2023-02, with the labels that each got.

#3201 Bump Halo version to 2.3.0-SNAPSHOT for main branch
  README.md
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#3202 Bump Halo to 2.2.1-SNAPSHOT for release-2.2 branch
  README.md
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#3198 fix: plugin disappeared after plugin with same name reinstalled
  src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  src/main/java/run/halo/app/infra/exception/PluginInstallationException.java
  src/main/resources/config/i18n/messages.properties
  src/main/resources/config/i18n/messages_zh.properties
Labels: kind/bug, lgtm, area/core, approved, release-note

#3210 Fix the problem that publishing post always fails
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/core/extension/Role.java
  src/main/java/run/halo/app/extension/Metadata.java
  src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  src/main/java/run/halo/app/extension/Unstructured.java
  src/main/java/run/halo/app/extension/controller/ControllerBuilder.java
  src/main/java/run/halo/app/extension/controller/DefaultDelayQueue.java
  src/main/java/run/halo/app/extension/controller/DefaultQueue.java
  src/main/java/run/halo/app/extension/controller/RequestQueue.java
  src/main/java/run/halo/app/extension/gc/GcReconciler.java
  src/main/java/run/halo/app/infra/ConditionList.java
  src/main/java/run/halo/app/metrics/ReplyEventReconciler.java
  src/main/java/run/halo/app/metrics/VisitedEventReconciler.java
  src/main/java/run/halo/app/metrics/VotedEventReconciler.java
  src/main/java/run/halo/app/plugin/PluginCreatedEventReconciler.java
  src/main/java/run/halo/app/search/post/PostEventReconciler.java
  src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java
  src/test/java/run/halo/app/extension/controller/DefaultDelayQueueTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3219 Refine exception message of duplicate key
  src/main/java/run/halo/app/extension/store/ReactiveExtensionStoreClientImpl.java
  src/main/java/run/halo/app/infra/exception/DuplicateNameException.java
  src/main/resources/config/i18n/messages.properties
  src/main/resources/config/i18n/messages_zh.properties
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3238 Reduce the number of queries to resolve theme
  src/main/java/run/halo/app/infra/exception/handlers/HaloErrorWebExceptionHandler.java
  src/main/java/run/halo/app/theme/HaloViewResolver.java
  src/main/java/run/halo/app/theme/ThemeContextBasedVariablesAcquirer.java
  src/main/java/run/halo/app/theme/ThemeResolver.java
  src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3235 fix: plugin status check to prevent inconsistent status
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#3236 fix: default value cannot be read when the setting is not created because of asynchrony
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3261 Fix random list problem of tags and categories
  src/main/java/run/halo/app/content/impl/PostServiceImpl.java
Labels: kind/bug, lgtm, approved, release-note

#3256 docs: update readme
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#3243 refactor: lru cache key for template engine manager
  src/main/java/run/halo/app/theme/TemplateEngineManager.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#3280 perf: refine display name of system default role
  src/main/resources/extensions/system-default-role.yaml
Labels: lgtm, approved, release-note, kind/improvement

#3292 chore: add @LIlGG to reviewers list
  OWNERS
Labels: lgtm, release-note-none, approved, kind/improvement

#3293 perf: associate ghost user with posts on user deletion.
  src/main/java/run/halo/app/content/Contributor.java
  src/main/java/run/halo/app/content/impl/PostServiceImpl.java
Labels: kind/bug, lgtm, release-note-none, approved

#3305 Auto rename attachment if it exists
  src/main/java/run/halo/app/core/extension/attachment/endpoint/LocalAttachmentUploadHandler.java
  src/main/java/run/halo/app/infra/utils/FileNameUtils.java
  src/test/java/run/halo/app/infra/utils/FileNameUtilsTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3295 fix: incorrect number of comments
  src/main/java/run/halo/app/core/extension/reconciler/CommentReconciler.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#3314 refactor: status update when setting not found
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#3322 fix: route for the tag is not registered when halo starts
  src/main/java/run/halo/app/core/extension/reconciler/TagReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/TagRouteReconciler.java
  src/test/java/run/halo/app/core/extension/reconciler/TagReconcilerTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#3320 Add custom endpoint for listing user conditionally
  src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
Labels: kind/bug, lgtm, release-note-none, approved

#3345 feat: open actuator logfile endpoint for prod
  src/main/resources/application.yaml
Labels: kind/feature, lgtm, release-note-none, approved

#3350 Refine problem detail when plugin is already installed
  src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  src/main/java/run/halo/app/infra/exception/PluginAlreadyExistsException.java
  src/main/resources/config/i18n/messages.properties
  src/main/resources/config/i18n/messages_zh.properties
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3351 feat: add database endpoint for actuator
  src/main/java/run/halo/app/actuator/DatabaseInfoContributor.java
Labels: kind/feature, lgtm, release-note-none, approved

#3344 fix: initializes a ghost user by default to replace that the users that has been deleted
  src/main/java/run/halo/app/content/Contributor.java
  src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  src/main/resources/extensions/user.yaml
Labels: kind/bug, lgtm, release-note-none, approved

#3368 Bump up checkout and setup-java actions
  .github/workflows/halo.yaml
Labels: lgtm, release-note-none, kind/cleanup, approved

#3355 feat: plugin supports configuration when not started
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/infra/Condition.java
  src/main/java/run/halo/app/infra/ConditionList.java
  src/main/java/run/halo/app/plugin/PluginBeforeStopSyncListener.java
  src/main/java/run/halo/app/plugin/PluginConst.java
  src/main/java/run/halo/app/plugin/PluginExtensionLoaderUtils.java
  src/main/java/run/halo/app/plugin/PluginStartedListener.java
  src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
  src/test/java/run/halo/app/plugin/PluginStartedListenerTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note, area/plugin

#3362 Discard watch when extension status is changed only
  src/main/java/run/halo/app/extension/JSONExtensionConverter.java
  src/main/java/run/halo/app/extension/JsonExtension.java
  src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  src/test/java/run/halo/app/extension/JsonExtensionTest.java
  src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#3379 Upgrade to Spring Boot 3.0.3
  build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#3373 refactor: APIs returns ghost users when user is deleted
  src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  src/main/java/run/halo/app/content/comment/OwnerInfo.java
  src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
  src/main/java/run/halo/app/core/extension/service/UserService.java
  src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
  src/main/java/run/halo/app/theme/finders/impl/CommentFinderImpl.java
  src/main/java/run/halo/app/theme/finders/impl/ContributorFinderImpl.java
  src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
  src/test/java/run/halo/app/theme/finders/impl/CommentFinderImplTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3385 Report test result using Jacoco plugin
  .github/workflows/halo.yaml
  README.md
  build.gradle
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#3388 fix: i18n unit test
  src/test/java/run/halo/app/infra/exception/handlers/I18nExceptionTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#3372 feat: add role information for user-related custom endpoint
  src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  src/main/java/run/halo/app/core/extension/service/DefaultRoleService.java
  src/main/java/run/halo/app/core/extension/service/RoleService.java
  src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
  src/main/resources/extensions/role-template-user.yaml
  src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
  src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note

#3381 refactor: add version flag to plugin static assets
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3386 chore: add finalizer for ghost and anonymous users
  src/main/resources/extensions/user.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#3363 refactor: default is approved to reply to comments on the console-side
  src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  src/main/java/run/halo/app/core/extension/endpoint/CommentEndpoint.java
  src/main/java/run/halo/app/theme/endpoint/CommentFinderEndpoint.java
  src/test/java/run/halo/app/theme/endpoint/CommentFinderEndpointTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3370 fix: exclude ghost and anonymous user when counting users
  src/main/java/run/halo/app/core/extension/User.java
  src/main/java/run/halo/app/core/extension/endpoint/StatsEndpoint.java
  src/main/resources/extensions/user.yaml
Labels: kind/bug, lgtm, approved, release-note

#3415 docs: fix command of docker run
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#3414 fix: template rendering missing template_id model data
  src/main/java/run/halo/app/theme/router/factories/PostRouteFactory.java
  src/test/java/run/halo/app/theme/router/factories/PostRouteFactoryTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#3413 fix: post page size configuration not work
  src/main/java/run/halo/app/theme/router/factories/ArchiveRouteFactory.java
  src/main/java/run/halo/app/theme/router/factories/AuthorPostsRouteFactory.java
  src/main/java/run/halo/app/theme/router/factories/CategoryPostRouteFactory.java
  src/main/java/run/halo/app/theme/router/factories/IndexRouteFactory.java
  src/main/java/run/halo/app/theme/router/factories/RouteFactory.java
  src/main/java/run/halo/app/theme/router/factories/TagPostRouteFactory.java
  src/test/java/run/halo/app/theme/router/factories/RouteFactoryTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#3394 Provide an endpoint to get plugin presets
  .gitignore
  src/main/java/run/halo/app/core/extension/Plugin.java
  src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  src/main/java/run/halo/app/core/extension/service/PluginService.java
  src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
  src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
  src/main/java/run/halo/app/plugin/YamlPluginFinder.java
  src/main/resources/extensions/role-template-plugin.yaml
  src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
  src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
  src/test/java/run/halo/app/plugin/YamlPluginDescriptorFinderTest.java
  src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
  src/test/resources/presets/plugins/fake-plugin.jar
Labels: kind/feature, lgtm, area/core, approved, release-note

#3366 feat: add stats to the user-sdie comments api
  src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  src/main/java/run/halo/app/content/comment/CommentStats.java
  src/main/java/run/halo/app/content/comment/ListedComment.java
  src/main/java/run/halo/app/content/comment/ListedReply.java
  src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  src/main/java/run/halo/app/theme/finders/impl/CommentFinderImpl.java
  src/main/java/run/halo/app/theme/finders/vo/CommentStatsVo.java
  src/main/java/run/halo/app/theme/finders/vo/CommentVo.java
  src/main/java/run/halo/app/theme/finders/vo/ReplyVo.java
  src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
  src/test/java/run/halo/app/theme/finders/impl/CommentFinderImplTest.java
Labels: kind/feature, lgtm, approved, release-note

#3421 chore: disable the visit log writer
  src/main/java/run/halo/app/core/extension/endpoint/TrackerEndpoint.java
  src/main/java/run/halo/app/metrics/VisitLogWriter.java
  src/test/java/run/halo/app/metrics/VisitLogWriterTest.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#3390 fix: theme status phase is always FAILED even if version of Halo is satisfied
  src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
  src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3422 refactor: add retry operation to single page publishing
  src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
  src/main/java/run/halo/app/core/extension/endpoint/SinglePageEndpoint.java
  src/test/java/run/halo/app/core/extension/endpoint/PostEndpointTest.java
  src/test/java/run/halo/app/core/extension/endpoint/SinglePageEndpointTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement
