Repository halo-dev/halo, pull requests merged in 2023-01, with the labels that each got.

#3098 Refine docker-run command in README.md
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#3101 feat: add the lastModifyTime attribute for post and single page
  src/main/java/run/halo/app/core/extension/content/Post.java
  src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
  src/test/java/run/halo/app/core/extension/reconciler/PostReconcilerTest.java
  src/test/java/run/halo/app/core/extension/reconciler/SinglePageReconcilerTest.java
Labels: lgtm, approved, release-note, kind/improvement

#3108 refactor: support extending jar directories for plugin class loader
  src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
  src/main/java/run/halo/app/plugin/PluginProperties.java
  src/main/resources/application-dev.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3102 feat: display unapproved comments created by the current user
  src/main/java/run/halo/app/theme/finders/impl/CommentFinderImpl.java
  src/test/java/run/halo/app/theme/finders/impl/CommentFinderImplTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3130 Adapt spring.web.resources.cache configuration
  src/main/java/run/halo/app/config/WebFluxConfig.java
  src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
  src/main/java/run/halo/app/theme/ThemeConfiguration.java
  src/main/resources/application-dev.yaml
  src/main/resources/application.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#3146 Simplify TemplateEngine due to upgrade of thymeleaf
  src/main/java/run/halo/app/theme/TemplateEngineManager.java
  src/main/java/run/halo/app/theme/engine/HaloTemplateEngine.java
  src/main/java/run/halo/app/theme/engine/SpringTemplateEngine.java
  src/main/java/run/halo/app/theme/engine/SpringWebFluxTemplateEngine.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#3148 improve the sorting rules for themes side posts using publishTime
  src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3149 feat: update default comment sorter
  src/main/java/run/halo/app/content/comment/CommentSorter.java
  src/test/java/run/halo/app/content/comment/CommentSorterTest.java
Labels: kind/feature, lgtm, approved, release-note, kind/improvement

#3158 improve the sorting rules of archives by using reverse year order
  src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3150 feat: support validate requires version for theme
  src/main/java/run/halo/app/core/extension/Theme.java
  src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
  src/main/java/run/halo/app/core/extension/theme/ThemeServiceImpl.java
  src/main/resources/config/i18n/messages.properties
  src/main/resources/config/i18n/messages_zh.properties
  src/test/java/run/halo/app/core/extension/ThemeTest.java
  src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java
  src/test/java/run/halo/app/core/extension/theme/ThemeServiceImplTest.java
Labels: kind/feature, lgtm, kind/api-change, approved, release-note

#3166 Fix the problem of not using error template in theme
  src/main/java/run/halo/app/infra/exception/handlers/HaloErrorWebExceptionHandler.java
  src/main/java/run/halo/app/infra/utils/FilePathUtils.java
  src/main/java/run/halo/app/theme/TemplateEngineManager.java
  src/main/java/run/halo/app/theme/ThemeConfiguration.java
  src/main/java/run/halo/app/theme/ThemeResolver.java
  src/main/java/run/halo/app/theme/engine/DefaultThemeTemplateAvailabilityProvider.java
  src/main/java/run/halo/app/theme/engine/ThemeTemplateAvailabilityProvider.java
  src/test/java/run/halo/app/theme/engine/DefaultThemeTemplateAvailabilityProviderTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#3161 refactor: initialize default config value by settings after plugin installation
  src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  src/main/java/run/halo/app/plugin/PluginCreatedEventReconciler.java
  src/main/java/run/halo/app/plugin/event/PluginCreatedEvent.java
  src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3179 Fix the problem of slug name with percent sign when publishing post
  src/main/java/run/halo/app/theme/router/RadixRouterTree.java
  src/test/java/run/halo/app/theme/router/RadixRouterTreeTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#3176 Upgrade Spring Boot to 3.0.2
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3135 feat: add some APIs to separate theme-related Setting and ConfigMap permissions
  src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
  src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
  src/main/resources/extensions/role-template-theme.yaml
  src/test/java/run/halo/app/core/extension/theme/ThemeEndpointTest.java
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note

#3142 feat: add some APIs to separate plugin-related Setting and ConfigMap permissions
  src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  src/main/resources/extensions/role-template-plugin.yaml
  src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
Labels: lgtm, area/core, kind/api-change, approved, release-note, kind/improvement

#3168 perf: optimize snapshot queries for post and single page
  src/main/java/run/halo/app/content/AbstractContentService.java
  src/main/java/run/halo/app/content/ContentService.java
  src/main/java/run/halo/app/content/PostService.java
  src/main/java/run/halo/app/content/SinglePageService.java
  src/main/java/run/halo/app/content/impl/ContentServiceImpl.java
  src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
  src/main/java/run/halo/app/core/extension/endpoint/ContentEndpoint.java
  src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
  src/main/java/run/halo/app/core/extension/endpoint/SinglePageEndpoint.java
  src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
  src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  src/main/java/run/halo/app/theme/finders/impl/SinglePageFinderImpl.java
  src/main/resources/extensions/role-template-post.yaml
  src/main/resources/extensions/role-template-singlepage.yaml
  src/test/java/run/halo/app/content/ContentServiceTest.java
  src/test/java/run/halo/app/content/impl/ContentServiceImplTest.java
  src/test/java/run/halo/app/content/impl/PostServiceImplTest.java
  src/test/java/run/halo/app/core/extension/reconciler/PostReconcilerTest.java
  src/test/java/run/halo/app/core/extension/reconciler/SinglePageReconcilerTest.java
  src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java
  src/test/java/run/halo/app/theme/finders/impl/SinglePageFinderImplTest.java
Labels: lgtm, area/core, kind/api-change, approved, release-note, kind/improvement

#3182 Provide system config endpoint
  build.gradle
  src/main/java/run/halo/app/Application.java
  src/main/java/run/halo/app/actuator/GlobalInfoEndpoint.java
  src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  src/main/java/run/halo/app/infra/SystemSetting.java
  src/main/resources/application.yaml
  src/main/resources/extensions/role-template-anonymous.yaml
  src/test/java/run/halo/app/infra/SystemSettingTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#3185 Add spring-context-indexer to speed up startup
  build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#3186 Upgrade SpringDoc to 2.0.2
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3192 Upgrade jasync-sql to 2.1.23
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3191 Upgrade pf4j to 3.9.0
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3190 Upgrade Lucene to 9.5.0
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#3194 Fix the problem of not initializing default theme correctly
  src/main/java/run/halo/app/core/extension/Theme.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved
