Repository halo-dev/halo, pull requests merged in 2024-04, with the labels that each got.

#5642 feat: add gravatar url into annotation of spec of comment for anonymous
  api/src/main/java/run/halo/app/core/extension/content/Comment.java
  application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
  application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceIntegrationTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#5658 refactor: optimize query for category association posts count to prevent blocking due to large data
  api/src/main/java/run/halo/app/core/extension/content/Post.java
  application/src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
  application/src/test/java/run/halo/app/core/extension/reconciler/CategoryReconcilerIntegrationTest.java
  application/src/test/java/run/halo/app/core/extension/reconciler/CategoryReconcilerTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5672 chore: update reviewers for OWNERS file
  OWNERS
Labels: lgtm, release-note-none, approved

#5593 refactor: post tag management page
  ui/console-src/modules/contents/posts/tags/TagList.vue
  ui/console-src/modules/contents/posts/tags/components/TagListItem.vue
  ui/console-src/modules/contents/posts/tags/composables/use-post-tag.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5681 feat: add line-height setting feature for the default editor
  ui/packages/editor/src/extensions/paragraph/index.ts
  ui/packages/editor/src/extensions/search-and-replace/index.ts
  ui/packages/editor/src/locales/en.yaml
  ui/packages/editor/src/locales/zh-CN.yaml
Labels: kind/feature, lgtm, approved, release-note, area/editor

#5656 refactor: optimize the query for subscriptions
  application/src/main/java/run/halo/app/notification/DefaultNotificationCenter.java
  application/src/test/java/run/halo/app/notification/DefaultNotificationCenterTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5659 refactor: optimize data acquisition from previous to next posts in a post
  application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5614 feat: support sorting posts by views and comment count
  api/src/main/java/run/halo/app/core/extension/content/Post.java
  application/src/main/java/run/halo/app/content/Stats.java
  application/src/main/java/run/halo/app/core/extension/reconciler/PostCounterReconciler.java
  application/src/main/java/run/halo/app/event/post/PostStatsChangedEvent.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/metrics/PostStatsUpdater.java
  ui/console-src/modules/contents/posts/PostList.vue
  ui/src/locales/en.yaml
  ui/src/locales/es.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, area/core, approved, area/console, release-note

#5690 feat: hide registration-related options when allowRegistration is disabled
  application/src/main/resources/extensions/system-setting.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5695 fix: the details of the attachment may be empty
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentDetailModal.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#5696 feat: change the tab title to the site title of the website
  application/src/main/java/run/halo/app/actuator/GlobalInfoEndpoint.java
  ui/console-src/views/system/Login.vue
  ui/src/components/base-app/BaseApp.vue
  ui/src/types/actuator.ts
Labels: kind/feature, lgtm, area/core, approved, release-note, area/ui

#5685 feat: add the clear format function to the default rich text editor
  ui/packages/editor/src/dev/App.vue
  ui/packages/editor/src/extensions/clear-format/index.ts
  ui/packages/editor/src/extensions/index.ts
  ui/packages/editor/src/locales/en.yaml
  ui/packages/editor/src/locales/zh-CN.yaml
  ui/src/components/editor/DefaultEditor.vue
Labels: kind/feature, lgtm, approved, release-note, area/editor

#5666 pref: limit the datetime year of the post or page to four digits
  ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
  ui/console-src/modules/contents/posts/components/PostSettingModal.vue
  ui/uc-src/modules/contents/posts/components/PostSettingForm.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5680 pref: optimize the rich text editor link paste logic
  ui/packages/editor/package.json
  ui/packages/editor/src/extensions/link/LinkBubbleButton.vue
  ui/packages/editor/src/extensions/link/index.ts
  ui/pnpm-lock.yaml
  ui/src/components/editor/DefaultEditor.vue
Labels: lgtm, approved, release-note, kind/improvement, area/editor, area/ui

#5697 feat: set selectedRole as required when creating a new user
  ui/console-src/modules/system/users/components/UserCreationModal.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5717 Upgrade SpringDoc to 2.5.0
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#5698 fix: layout height triggers page background color not fully filling scroll area
  ui/console-src/layouts/BasicLayout.vue
  ui/src/components/base-app/BaseApp.vue
  ui/uc-src/layouts/BasicLayout.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#5682 pref: optimize the pop-up mode of toolbar submenu
  ui/packages/editor/src/components/EditorHeader.vue
  ui/packages/editor/src/components/toolbar/ToolbarItem.vue
Labels: lgtm, approved, release-note, kind/improvement, area/editor

#5603 feat: add the format brush extension to the default rich text editor
  ui/packages/editor/src/dev/App.vue
  ui/packages/editor/src/extensions/format-brush/index.ts
  ui/packages/editor/src/extensions/format-brush/util.ts
  ui/packages/editor/src/extensions/index.ts
  ui/packages/editor/src/locales/en.yaml
  ui/packages/editor/src/locales/zh-CN.yaml
  ui/packages/editor/src/styles/format-brush.scss
  ui/packages/editor/src/styles/index.scss
  ui/src/components/editor/DefaultEditor.vue
Labels: kind/feature, lgtm, approved, release-note, area/editor, area/ui

#5737 fix: code block content insertion location error
  ui/packages/editor/src/extensions/code-block/code-block.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor

#5683 pref: optimize the toolbar space and fold the same type of function
  ui/packages/editor/src/extensions/text-align/index.ts
  ui/packages/editor/src/extensions/text/index.ts
  ui/packages/editor/src/locales/en.yaml
  ui/packages/editor/src/locales/zh-CN.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/editor

#5655 chore: bump tiptap version to 2.3.0
  ui/package.json
  ui/packages/editor/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5723 feat: refine fields in theme detail page
  ui/console-src/modules/interface/themes/ThemeDetail.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5724 feat: refine fields in plugin detail page
  ui/console-src/modules/system/plugins/tabs/Detail.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5746 fix: paginated data queries by expand
  application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  application/src/main/java/run/halo/app/notification/DefaultNotificationCenter.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#5748 feat: add original password verification for password change
  api-docs/openapi/v3_0/aggregated.json
  application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  application/src/main/java/run/halo/app/core/extension/service/UserService.java
  application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
  application/src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java
  ui/console-src/modules/system/users/components/UserPasswordChangeModal.vue
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-user-api.ts
  ui/packages/api-client/src/models/change-own-password-request.ts
  ui/packages/api-client/src/models/index.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/profile/components/PasswordChangeModal.vue
Labels: kind/feature, lgtm, area/core, approved, release-note

#5671 refactor: refine statistical approach for tallying posts by category association
  api/src/main/java/run/halo/app/core/extension/content/Post.java
  application/src/main/java/run/halo/app/content/AbstractEventReconciler.java
  application/src/main/java/run/halo/app/content/CategoryPostCountUpdater.java
  application/src/main/java/run/halo/app/content/TagPostCountUpdater.java
  application/src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
  application/src/test/java/run/halo/app/content/CategoryPostCountUpdaterTest.java
  application/src/test/java/run/halo/app/core/extension/reconciler/CategoryReconcilerIntegrationTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5768 chore: upgrade the api-testing (e2e) to v0.0.16
  e2e/Dockerfile
Labels: lgtm, release-note-none, approved

#5708 refactor: optimize comment reconciliation for better performance and efficiency
  api/src/main/java/run/halo/app/core/extension/content/Comment.java
  api/src/main/java/run/halo/app/core/extension/content/Reply.java
  application/src/main/java/run/halo/app/core/extension/reconciler/CommentReconciler.java
  application/src/main/java/run/halo/app/core/extension/reconciler/ReplyReconciler.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#5727 feat: add the order of the posts according to last modify time
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  ui/console-src/modules/contents/posts/PostList.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, area/core, release-note, area/ui

#5770 Downgrade pf4j to 3.10.0
  platform/application/build.gradle
Labels: kind/bug, lgtm, approved, release-note, area/plugin

#5757 feat: invalidate all sessions of a user after password changed
  api/build.gradle
  application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
  application/src/main/java/run/halo/app/event/user/PasswordChangedEvent.java
  application/src/main/java/run/halo/app/security/session/InMemoryReactiveIndexedSessionRepository.java
  application/src/main/java/run/halo/app/security/session/ReactiveIndexedSessionRepository.java
  application/src/main/java/run/halo/app/security/session/SessionInvalidationListener.java
  application/src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java
  application/src/test/java/run/halo/app/security/session/InMemoryReactiveIndexedSessionRepositoryTest.java
  ui/uc-src/modules/profile/components/PasswordChangeModal.vue
Labels: kind/feature, lgtm, area/core, approved, do-not-merge/hold, release-note

#5791 chore: rm deprecated attr MAINTAINER
  Dockerfile
Labels: lgtm, kind/deprecation, do-not-merge/release-note-label-needed, approved

#5763 feat: add extension points for user detail tab
  ui/console-src/modules/system/users/UserDetail.vue
  ui/console-src/modules/system/users/tabs/Detail.vue
  ui/packages/shared/src/index.ts
  ui/packages/shared/src/states/user-tab.ts
  ui/packages/shared/src/types/plugin.ts
  ui/uc-src/modules/profile/Profile.vue
  ui/uc-src/modules/profile/tabs/Detail.vue
  ui/uc-src/modules/profile/tabs/NotificationPreferences.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#5794 refactor: implementation of browser tab title
  ui/console-src/views/system/Login.vue
  ui/index.html
  ui/src/components/base-app/BaseApp.vue
  ui/src/composables/use-title.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5800 fix: comment and reply observed version for status
  application/src/main/java/run/halo/app/core/extension/reconciler/CommentReconciler.java
  application/src/main/java/run/halo/app/core/extension/reconciler/ReplyReconciler.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#5796 feat: toast the http request error
  ui/src/utils/api-client.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5662 Add WebSocket support in plugins
  api/src/main/java/run/halo/app/core/endpoint/WebSocketEndpoint.java
  application/src/main/java/run/halo/app/config/WebFluxConfig.java
  application/src/main/java/run/halo/app/console/WebSocketUtils.java
  application/src/main/java/run/halo/app/core/endpoint/WebSocketEndpointManager.java
  application/src/main/java/run/halo/app/core/endpoint/WebSocketHandlerMapping.java
  application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
  application/src/main/java/run/halo/app/security/authorization/RequestInfoFactory.java
  application/src/test/java/run/halo/app/config/WebFluxConfigTest.java
  application/src/test/java/run/halo/app/core/endpoint/WebSocketHandlerMappingTest.java
  application/src/test/java/run/halo/app/security/authorization/RequestInfoResolverTest.java
  docs/plugin/websocket.md
Labels: kind/feature, lgtm, area/core, approved, release-note, area/plugin

#5520 feat: show the startup status of the plugin
  ui/console-src/modules/system/plugins/PluginList.vue
  ui/console-src/modules/system/plugins/components/PluginListItem.vue
  ui/console-src/modules/system/plugins/composables/use-plugin.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note, area/ui

#5783 feat: add verified badge for email field in profile detail page
  ui/console-src/modules/system/users/tabs/Detail.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/profile/tabs/Detail.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5755 feat: add issues field for plugin and theme manifest
  api-docs/openapi/v3_0/aggregated.json
  api/src/main/java/run/halo/app/core/extension/Plugin.java
  api/src/main/java/run/halo/app/core/extension/Theme.java
  ui/console-src/modules/interface/themes/ThemeDetail.vue
  ui/console-src/modules/system/plugins/tabs/Detail.vue
  ui/packages/api-client/src/models/plugin-spec.ts
  ui/packages/api-client/src/models/theme-spec.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note, area/ui

#5777 refactor: optimize comment and reply deletion
  application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  application/src/test/java/run/halo/app/content/comment/CommentServiceImplIntegrationTest.java
  application/src/test/java/run/halo/app/content/comment/ReplyServiceImplIntegrationTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#5784 feat: add tab shortcut function to the default editor table
  ui/packages/editor/src/extensions/table/index.ts
  ui/packages/editor/src/extensions/table/util.ts
Labels: kind/feature, lgtm, approved, release-note, area/editor

#5793 fix: excel tables copied into editor become images
  ui/src/components/editor/extensions/upload/index.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor, area/ui

#5818 fix: the post admin does not have tag list permissions
  application/src/main/resources/extensions/role-template-tag.yaml
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#5819 fix: permissions for post content versions
  application/src/main/resources/extensions/role-template-post.yaml
  application/src/main/resources/extensions/role-template-singlepage.yaml
Labels: kind/bug, lgtm, area/core, approved, release-note

#5809 Fix potential github action smells
  .github/workflows/halo.yaml
Labels: lgtm, release-note-none, approved, kind/improvement

#5822 feat: add cleanup feature for post snapshots
  ui/console-src/modules/contents/pages/SinglePageSnapshots.vue
  ui/console-src/modules/contents/pages/components/SnapshotListItem.vue
  ui/console-src/modules/contents/posts/PostSnapshots.vue
  ui/console-src/modules/contents/posts/components/SnapshotListItem.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, release-note-none, approved, area/ui

#5823 fix: update post with retry
  application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  application/src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#5820 chore: specify expose port in dockerfile
  Dockerfile
Labels: lgtm, release-note-none, approved

#5839 chore: bump preset plugins version
  application/build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#5838 fix: show plugin error message
  ui/console-src/modules/system/plugins/components/PluginListItem.vue
  ui/console-src/modules/system/plugins/composables/use-plugin.ts
Labels: kind/bug, lgtm, release-note-none, approved, area/ui
