Repository halo-dev/halo, pull requests merged in 2024-06, with the labels that each got.

#6028 Fix the problem that bundle files can be generated arbitrarily
  application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  application/src/main/java/run/halo/app/core/extension/service/PluginService.java
  application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
  application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
  application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved, area/plugin

#6032 Prepare for developing 2.17.0
  README.md
  gradle.properties
  ui/packages/api-client/package.json
  ui/packages/components/package.json
  ui/packages/editor/package.json
  ui/packages/shared/package.json
  ui/packages/ui-plugin-bundler-kit/package.json
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6033 Upgrade to Gradle 8.8
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#6035 fix: missing default values for system settings
  application/src/main/resources/extensions/system-configurable-configmap.yaml
Labels: kind/bug, lgtm, area/core, approved, release-note

#6043 Fix concurrent issue during bundle file concurrent generation testing
  application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/failing-test

#6040 fix: content offset caused by empty slot
  ui/packages/components/src/components/tag/Tag.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6049 Fix the problem that theme assets could not be found after the first initialization
  application/src/main/java/run/halo/app/theme/config/ThemeWebFluxConfigurer.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6052 Move post events into api modules
  api/src/main/java/run/halo/app/event/post/PostDeletedEvent.java
  api/src/main/java/run/halo/app/event/post/PostEvent.java
  api/src/main/java/run/halo/app/event/post/PostPublishedEvent.java
  api/src/main/java/run/halo/app/event/post/PostUnpublishedEvent.java
  api/src/main/java/run/halo/app/event/post/PostUpdatedEvent.java
  api/src/main/java/run/halo/app/event/post/PostVisibleChangedEvent.java
  api/src/main/java/run/halo/app/plugin/SharedEvent.java
  application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  application/src/main/java/run/halo/app/event/post/PostDeletedEvent.java
  application/src/main/java/run/halo/app/event/post/PostEvent.java
  application/src/main/java/run/halo/app/event/post/PostPublishedEvent.java
  application/src/main/java/run/halo/app/event/post/PostUnpublishedEvent.java
  application/src/main/java/run/halo/app/event/post/PostUpdatedEvent.java
  application/src/main/java/run/halo/app/event/post/PostVisibleChangedEvent.java
Labels: lgtm, release-note-none, area/core, kind/improvement, area/plugin

#6073 Fix the problem that bundle files are not changed in development mode
  application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
  application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
Labels: lgtm, kind/regression, release-note-none, approved, area/plugin

#6062 fix: default editor focus setting failure
  ui/src/components/editor/DefaultEditor.vue
Labels: kind/bug, lgtm, approved, release-note, area/editor, area/ui

#6059 fix: ensure pasted content auto-generates title id
  ui/packages/editor/src/extensions/heading/index.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor

#6089 pref: improve code block styling in editor
  ui/packages/editor/src/extensions/code-block/CodeBlockViewRenderer.vue
  ui/packages/editor/src/extensions/code-block/code-block.ts
  ui/packages/editor/src/index.ts
  ui/packages/editor/src/locales/en.yaml
  ui/packages/editor/src/locales/zh-CN.yaml
  ui/packages/editor/src/styles/base.scss
  ui/packages/editor/src/styles/index.scss
  ui/packages/editor/src/styles/node-select.scss
Labels: lgtm, approved, release-note, kind/improvement, area/editor

#6090 pref: default code block indentation from Tab to 2 Spaces in editor
  ui/packages/editor/src/extensions/code-block/code-block.ts
Labels: lgtm, approved, release-note, kind/improvement, area/editor

#6084 docs: add image linked to video in README.md
  README.md
Labels: lgtm, release-note-none, approved

#6071 feat: add import and export theme configuration
  ui/console-src/modules/interface/themes/ThemeDetail.vue
  ui/console-src/modules/interface/themes/composables/use-theme.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6081 Add support for publishing events among plugins
  application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
  application/src/main/java/run/halo/app/plugin/DefaultSharedEventListenerRegistry.java
  application/src/main/java/run/halo/app/plugin/HaloSharedEventDelegator.java
  application/src/main/java/run/halo/app/plugin/PluginApplicationContext.java
  application/src/main/java/run/halo/app/plugin/PluginSharedEventDelegator.java
  application/src/main/java/run/halo/app/plugin/SharedEventDispatcher.java
  application/src/main/java/run/halo/app/plugin/SharedEventListenerRegistry.java
  application/src/test/java/run/halo/app/plugin/SharedEventDispatcherTest.java
  docs/plugin/shared-event.md
Labels: kind/feature, lgtm, release-note-none, area/core, approved, area/plugin

#6064 fix: a verified email can be reused
  application/src/main/java/run/halo/app/core/extension/reconciler/UserReconciler.java
  application/src/main/java/run/halo/app/core/extension/service/UserService.java
  application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
  application/src/main/java/run/halo/app/core/extension/service/impl/EmailVerificationServiceImpl.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/test/java/run/halo/app/core/extension/reconciler/UserReconcilerTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6106 feat: support setting rendering templates for related posts on category
  api-docs/openapi/v3_0/aggregated.json
  api/src/main/java/run/halo/app/core/extension/content/Category.java
  application/src/main/java/run/halo/app/theme/router/factories/PostRouteFactory.java
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  ui/packages/api-client/src/models/category-spec.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, area/core, approved, release-note

#6031 Add support for patching extensions
  api-docs/openapi/v3_0/aggregated.json
  api/src/main/java/run/halo/app/extension/JsonExtension.java
  api/src/main/java/run/halo/app/extension/ReactiveExtensionClient.java
  api/src/main/java/run/halo/app/extension/index/FunctionalIndexAttribute.java
  api/src/main/java/run/halo/app/extension/index/FunctionalMultiValueIndexAttribute.java
  api/src/test/java/run/halo/app/extension/index/FunctionalMultiValueIndexAttributeTest.java
  application/src/main/java/run/halo/app/config/SwaggerConfig.java
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  application/src/main/java/run/halo/app/extension/router/ExtensionPatchHandler.java
  application/src/main/java/run/halo/app/extension/router/ExtensionRouterFunctionFactory.java
  application/src/main/java/run/halo/app/extension/router/JsonPatch.java
  application/src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java
  application/src/test/java/run/halo/app/extension/router/ExtensionRouterFunctionFactoryTest.java
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api/auth-halo-run-v1alpha1-auth-provider-api.ts
  ui/packages/api-client/src/api/auth-halo-run-v1alpha1-user-connection-api.ts
  ui/packages/api-client/src/api/content-halo-run-v1alpha1-category-api.ts
  ui/packages/api-client/src/api/content-halo-run-v1alpha1-comment-api.ts
  ui/packages/api-client/src/api/content-halo-run-v1alpha1-post-api.ts
  ui/packages/api-client/src/api/content-halo-run-v1alpha1-reply-api.ts
  ui/packages/api-client/src/api/content-halo-run-v1alpha1-single-page-api.ts
  ui/packages/api-client/src/api/content-halo-run-v1alpha1-snapshot-api.ts
  ui/packages/api-client/src/api/content-halo-run-v1alpha1-tag-api.ts
  ui/packages/api-client/src/api/metrics-halo-run-v1alpha1-counter-api.ts
  ui/packages/api-client/src/api/migration-halo-run-v1alpha1-backup-api.ts
  ui/packages/api-client/src/api/notification-halo-run-v1alpha1-notification-api.ts
  ui/packages/api-client/src/api/notification-halo-run-v1alpha1-notification-template-api.ts
  ui/packages/api-client/src/api/notification-halo-run-v1alpha1-notifier-descriptor-api.ts
  ui/packages/api-client/src/api/notification-halo-run-v1alpha1-reason-api.ts
  ui/packages/api-client/src/api/notification-halo-run-v1alpha1-reason-type-api.ts
  ui/packages/api-client/src/api/notification-halo-run-v1alpha1-subscription-api.ts
  ui/packages/api-client/src/api/plugin-halo-run-v1alpha1-extension-definition-api.ts
  ui/packages/api-client/src/api/plugin-halo-run-v1alpha1-extension-point-definition-api.ts
  ui/packages/api-client/src/api/plugin-halo-run-v1alpha1-plugin-api.ts
  ui/packages/api-client/src/api/plugin-halo-run-v1alpha1-reverse-proxy-api.ts
  ui/packages/api-client/src/api/plugin-halo-run-v1alpha1-search-engine-api.ts
  ui/packages/api-client/src/api/security-halo-run-v1alpha1-personal-access-token-api.ts
  ui/packages/api-client/src/api/storage-halo-run-v1alpha1-attachment-api.ts
  ui/packages/api-client/src/api/storage-halo-run-v1alpha1-group-api.ts
  ui/packages/api-client/src/api/storage-halo-run-v1alpha1-policy-api.ts
  ui/packages/api-client/src/api/storage-halo-run-v1alpha1-policy-template-api.ts
  ui/packages/api-client/src/api/theme-halo-run-v1alpha1-theme-api.ts
  ui/packages/api-client/src/api/v1alpha1-annotation-setting-api.ts
  ui/packages/api-client/src/api/v1alpha1-config-map-api.ts
  ui/packages/api-client/src/api/v1alpha1-menu-api.ts
  ui/packages/api-client/src/api/v1alpha1-menu-item-api.ts
  ui/packages/api-client/src/api/v1alpha1-role-api.ts
  ui/packages/api-client/src/api/v1alpha1-role-binding-api.ts
  ui/packages/api-client/src/api/v1alpha1-secret-api.ts
  ui/packages/api-client/src/api/v1alpha1-setting-api.ts
  ui/packages/api-client/src/api/v1alpha1-user-api.ts
  ui/packages/api-client/src/models/add-operation.ts
  ui/packages/api-client/src/models/copy-operation.ts
  ui/packages/api-client/src/models/index.ts
  ui/packages/api-client/src/models/json-patch-inner.ts
  ui/packages/api-client/src/models/move-operation.ts
  ui/packages/api-client/src/models/remove-operation.ts
  ui/packages/api-client/src/models/replace-operation.ts
  ui/packages/api-client/src/models/test-operation.ts
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#6110 Upgrade SpringBoot to 3.3.1
  build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6083 feat: add preventParentPostCascadeQuery option to control visibility of child category posts
  api-docs/openapi/v3_0/aggregated.json
  api/src/main/java/run/halo/app/core/extension/content/Category.java
  application/src/main/java/run/halo/app/content/CategoryService.java
  application/src/main/java/run/halo/app/content/PostQuery.java
  application/src/main/java/run/halo/app/content/impl/CategoryServiceImpl.java
  application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  application/src/main/java/run/halo/app/theme/finders/vo/CategoryTreeVo.java
  application/src/main/java/run/halo/app/theme/finders/vo/CategoryVo.java
  application/src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
  application/src/test/resources/categories/independent-post-count.json
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  ui/console-src/modules/contents/posts/categories/components/CategoryListItem.vue
  ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-post-api.ts
  ui/packages/api-client/src/api/uc-api-content-halo-run-v1alpha1-post-api.ts
  ui/packages/api-client/src/models/category-spec.ts
  ui/src/locales/en.yaml
  ui/src/locales/es.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, area/core, approved, release-note

#6039 refactor: index mechanism to enhance overall performance
  api/src/main/java/run/halo/app/extension/ListOptions.java
  api/src/main/java/run/halo/app/extension/controller/RequestSynchronizer.java
  api/src/main/java/run/halo/app/extension/index/IndexDescriptor.java
  api/src/main/java/run/halo/app/extension/index/IndexEntry.java
  api/src/main/java/run/halo/app/extension/index/IndexEntryOperator.java
  api/src/main/java/run/halo/app/extension/index/IndexEntryOperatorImpl.java
  api/src/main/java/run/halo/app/extension/index/IndexedQueryEngine.java
  api/src/main/java/run/halo/app/extension/index/Indexer.java
  api/src/main/java/run/halo/app/extension/index/query/All.java
  api/src/main/java/run/halo/app/extension/index/query/And.java
  api/src/main/java/run/halo/app/extension/index/query/Between.java
  api/src/main/java/run/halo/app/extension/index/query/EqualQuery.java
  api/src/main/java/run/halo/app/extension/index/query/GreaterThanQuery.java
  api/src/main/java/run/halo/app/extension/index/query/InQuery.java
  api/src/main/java/run/halo/app/extension/index/query/IsNotNull.java
  api/src/main/java/run/halo/app/extension/index/query/IsNull.java
  api/src/main/java/run/halo/app/extension/index/query/LessThanQuery.java
  api/src/main/java/run/halo/app/extension/index/query/Not.java
  api/src/main/java/run/halo/app/extension/index/query/NotEqual.java
  api/src/main/java/run/halo/app/extension/index/query/Or.java
  api/src/main/java/run/halo/app/extension/index/query/QueryIndexView.java
  api/src/main/java/run/halo/app/extension/index/query/QueryIndexViewImpl.java
  api/src/main/java/run/halo/app/extension/index/query/StringContains.java
  api/src/main/java/run/halo/app/extension/index/query/StringEndsWith.java
  api/src/main/java/run/halo/app/extension/index/query/StringStartsWith.java
  api/src/test/java/run/halo/app/extension/controller/RequestSynchronizerTest.java
  api/src/test/java/run/halo/app/extension/index/query/InQueryTest.java
  api/src/test/java/run/halo/app/extension/index/query/IndexViewDataSet.java
  api/src/test/java/run/halo/app/extension/index/query/IsNotNullTest.java
  api/src/test/java/run/halo/app/extension/index/query/QueryIndexViewImplTest.java
  api/src/test/java/run/halo/app/extension/index/query/StringContainsTest.java
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  application/src/main/java/run/halo/app/extension/index/DefaultIndexer.java
  application/src/main/java/run/halo/app/extension/index/IndexEntryImpl.java
  application/src/main/java/run/halo/app/extension/index/IndexedQueryEngineImpl.java
  application/src/test/java/run/halo/app/content/PostQueryTest.java
  application/src/test/java/run/halo/app/extension/index/DefaultIndexerTest.java
  application/src/test/java/run/halo/app/extension/index/IndexEntryImplTest.java
  application/src/test/java/run/halo/app/extension/index/IndexEntryOperatorImplTest.java
  application/src/test/java/run/halo/app/extension/index/IndexedQueryEngineImplTest.java
  application/src/test/java/run/halo/app/extension/index/query/AndTest.java
  application/src/test/java/run/halo/app/extension/index/query/IndexViewDataSet.java
  application/src/test/java/run/halo/app/extension/index/query/QueryFactoryTest.java
  application/src/test/java/run/halo/app/extension/index/query/QueryIndexViewImplTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6114 fix: not remembering the selected editor
  ui/console-src/modules/contents/pages/SinglePageEditor.vue
  ui/console-src/modules/contents/posts/PostEditor.vue
  ui/src/components/dropdown-selector/EditorProviderSelector.vue
  ui/src/composables/use-editor-extension-points.ts
  ui/uc-src/modules/contents/posts/PostEditor.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6115 fix: not remembering the selected attachment policy in upload modal
  ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6112 Refactor comment data update using the patch api
  ui/console-src/modules/contents/comments/CommentList.vue
  ui/console-src/modules/contents/comments/components/CommentListItem.vue
  ui/console-src/modules/contents/comments/components/ReplyListItem.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6113 refactor: simplify the plugin startup logic
  ui/console-src/modules/system/plugins/components/installation-tabs/LocalUpload.vue
  ui/console-src/modules/system/plugins/components/installation-tabs/RemoteDownload.vue
  ui/console-src/modules/system/plugins/composables/use-plugin.ts
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6111 Refactor attachment moving using the patch api
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentGroupBadge.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6133 chore: bump mariadb driver to 1.2.1 to fix crash issue
  gradle.properties
  platform/application/build.gradle
Labels: kind/bug, lgtm, area/core, approved, release-note

#6120 fix: resolve phantom dependency issue for iconify
  ui/package.json
  ui/pnpm-lock.yaml
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6136 fix: incorrect root path in API client requests
  ui/packages/api-client/entry/api-client.ts
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6134 Refactor ExtensionGetter for enabling or disabling extensions
  api/src/main/java/run/halo/app/infra/SystemSetting.java
  application/src/main/java/run/halo/app/notification/DefaultNotificationSender.java
  application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
  application/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionGetter.java
  application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordDelegatingAuthenticationManager.java
  application/src/main/java/run/halo/app/theme/dialect/CommentEnabledVariableProcessor.java
  application/src/main/java/run/halo/app/theme/finders/impl/PostPublicQueryServiceImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/SinglePageConversionServiceImpl.java
  application/src/main/java/run/halo/app/webfilter/AdditionalWebFilterChainProxy.java
  application/src/test/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetterTest.java
  application/src/test/java/run/halo/app/theme/dialect/CommentElementTagProcessorTest.java
  application/src/test/java/run/halo/app/theme/dialect/CommentEnabledVariableProcessorTest.java
  application/src/test/java/run/halo/app/theme/finders/impl/PostPublicQueryServiceImplTest.java
  application/src/test/java/run/halo/app/theme/finders/impl/SinglePageConversionServiceImplTest.java
Labels: lgtm, release-note-none, area/core, kind/api-change, approved, kind/improvement

#6128 feat: add avatar group component
  ui/console-src/modules/contents/_components/ContributorList.vue
  ui/packages/components/.storybook/main.ts
  ui/packages/components/src/components/avatar/Avatar.vue
  ui/packages/components/src/components/avatar/AvatarGroup.stories.ts
  ui/packages/components/src/components/avatar/AvatarGroup.vue
  ui/packages/components/src/components/avatar/index.ts
  ui/packages/components/src/components/avatar/interface.ts
  ui/uc-src/modules/contents/posts/components/PostListItem.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6123 feat: support batch publish/unpublish posts
  ui/console-src/modules/contents/posts/PostList.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6143 chore: upgrade pf4j version to 3.12.0
  platform/application/build.gradle
Labels: kind/bug, lgtm, area/core, approved, release-note

#6122 refactor: preserve post title when opening settings
  ui/console-src/modules/contents/pages/SinglePageEditor.vue
  ui/console-src/modules/contents/posts/PostEditor.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6139 refactor: remove phone field for user form
  ui/console-src/modules/system/users/components/UserCreationModal.vue
  ui/console-src/modules/system/users/components/UserEditingModal.vue
  ui/uc-src/modules/profile/components/ProfileEditingModal.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6138 refactor: hide move group button when no attachment groups are present
  ui/console-src/modules/contents/attachments/AttachmentList.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6147 fix: autosave content feature not working
  ui/console-src/modules/system/roles/RoleDetail.vue
  ui/packages/components/src/components/avatar/Avatar.vue
  ui/packages/editor/src/dev/App.vue
  ui/src/composables/use-content-cache.ts
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6117 feat: range selection feature to default editor
  ui/packages/editor/src/dev/App.vue
  ui/packages/editor/src/extensions/code-block/code-block.ts
  ui/packages/editor/src/extensions/columns/columns.ts
  ui/packages/editor/src/extensions/index.ts
  ui/packages/editor/src/extensions/range-selection/index.ts
  ui/packages/editor/src/extensions/range-selection/range-selection.ts
  ui/packages/editor/src/extensions/table/index.ts
  ui/packages/editor/src/extensions/table/table-row.ts
  ui/packages/editor/src/styles/index.scss
  ui/packages/editor/src/styles/range-selection.scss
  ui/src/components/editor/DefaultEditor.vue
Labels: kind/feature, lgtm, approved, release-note, area/editor

#6148 refactor: add builder for list options
  api/src/main/java/run/halo/app/extension/ListOptions.java
  api/src/main/java/run/halo/app/extension/router/selector/LabelSelector.java
  api/src/main/java/run/halo/app/extension/router/selector/SetMatcher.java
  api/src/test/java/run/halo/app/extension/ListOptionsTest.java
  api/src/test/java/run/halo/app/extension/router/selector/LabelSelectorTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6145 refactor: add list options for sync all synchronizer
  api/src/main/java/run/halo/app/extension/ExtensionMatcher.java
  api/src/main/java/run/halo/app/extension/WatcherExtensionMatchers.java
  api/src/main/java/run/halo/app/extension/controller/ControllerBuilder.java
  api/src/main/java/run/halo/app/extension/controller/RequestSynchronizer.java
  api/src/test/java/run/halo/app/extension/controller/RequestSynchronizerTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6131 feat: implement persistent token based remember me mechanism
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_extension.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
  api/src/main/java/run/halo/app/core/extension/RememberMeToken.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/PersistentRememberMeTokenRepository.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/PersistentRememberMeTokenRepositoryImpl.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/PersistentTokenBasedRememberMeServices.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/RememberMeTokenRevoker.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/RememberTokenCleaner.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/TokenBasedRememberMeServices.java
  application/src/test/java/run/halo/app/security/authentication/rememberme/PersistentTokenBasedRememberMeServicesTest.java
  application/src/test/java/run/halo/app/security/authentication/rememberme/RememberTokenCleanerTest.java
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api.ts
  ui/packages/api-client/src/api/remember-me-token-v1alpha1-api.ts
  ui/packages/api-client/src/models/index.ts
  ui/packages/api-client/src/models/remember-me-token-list.ts
  ui/packages/api-client/src/models/remember-me-token-spec.ts
  ui/packages/api-client/src/models/remember-me-token.ts
Labels: kind/feature, lgtm, area/core, approved, release-note

#6146 feat: add dynamic list input
  ui/docs/custom-formkit-input/README.md
  ui/src/formkit/formkit.config.ts
  ui/src/formkit/inputs/list/AddButton.vue
  ui/src/formkit/inputs/list/features/lists.ts
  ui/src/formkit/inputs/list/index.ts
  ui/src/formkit/inputs/list/listSection.ts
  ui/src/formkit/inputs/list/sections/index.ts
  ui/src/formkit/theme.ts
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6142 feat: add batch setting for partial post fields
  ui/console-src/modules/contents/posts/PostList.vue
  ui/console-src/modules/contents/posts/components/PostBatchSettingModal.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6151 chore: add vscode settings.json
  ui/.vscode/extensions.json
  ui/.vscode/settings.json
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6150 pref: editor iframe risk with src tag
  ui/packages/editor/src/extensions/iframe/BubbleItemIframeLink.vue
  ui/packages/editor/src/extensions/iframe/IframeView.vue
  ui/packages/editor/src/extensions/iframe/index.ts
  ui/packages/editor/src/utils/is-allowed-uri.ts
Labels: lgtm, approved, release-note, kind/improvement, area/editor

#6103 feat: add gap cursor for top-level block nodes in default editor
  ui/packages/editor/package.json
  ui/packages/editor/src/extensions/code-block/code-block.ts
  ui/packages/editor/src/extensions/columns/columns.ts
  ui/packages/editor/src/extensions/gap-cursor/gap-cursor-selection.ts
  ui/packages/editor/src/extensions/gap-cursor/index.ts
  ui/packages/editor/src/extensions/index.ts
  ui/packages/editor/src/extensions/paragraph/index.ts
  ui/packages/editor/src/extensions/table/index.ts
  ui/packages/editor/src/styles/gap-cursor.scss
  ui/packages/editor/src/styles/index.scss
  ui/packages/editor/src/utils/delete-node.ts
  ui/packages/editor/src/utils/isNodeEmpty.ts
  ui/pnpm-lock.yaml
Labels: kind/feature, lgtm, approved, release-note, area/editor

#6141 refactor: enhance cache management in plugin setting config
  api/src/main/java/run/halo/app/plugin/PluginConfigUpdatedEvent.java
  api/src/main/java/run/halo/app/plugin/PluginContext.java
  application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
  application/src/main/java/run/halo/app/plugin/DefaultPluginGetter.java
  application/src/main/java/run/halo/app/plugin/DefaultReactiveSettingFetcher.java
  application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
  application/src/main/java/run/halo/app/plugin/PluginGetter.java
  application/src/main/java/run/halo/app/plugin/SharedApplicationContext.java
  application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
  application/src/main/java/run/halo/app/plugin/SpringPluginFactory.java
  application/src/test/java/run/halo/app/plugin/DefaultSettingFetcherTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note, sig/docs, area/plugin

#6116 feat: support hide categories and posts from the list
  api-docs/openapi/v3_0/aggregated.json
  api/src/main/java/run/halo/app/core/extension/content/Category.java
  api/src/main/java/run/halo/app/core/extension/content/Post.java
  api/src/main/java/run/halo/app/extension/index/query/NotEqual.java
  application/src/main/java/run/halo/app/content/AbstractEventReconciler.java
  application/src/main/java/run/halo/app/content/CategoryPostCountUpdater.java
  application/src/main/java/run/halo/app/content/CategoryService.java
  application/src/main/java/run/halo/app/content/PostHideFromListStateUpdater.java
  application/src/main/java/run/halo/app/content/TagPostCountUpdater.java
  application/src/main/java/run/halo/app/content/impl/CategoryServiceImpl.java
  application/src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
  application/src/main/java/run/halo/app/event/post/CategoryHiddenStateChangeEvent.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  application/src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  ui/console-src/modules/contents/posts/categories/components/CategoryListItem.vue
  ui/packages/api-client/src/models/category-spec.ts
  ui/packages/api-client/src/models/post-status.ts
  ui/packages/api-client/src/models/single-page-status.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, tide/merge-method-merge, area/core, approved, release-note

#6153 fix: resolve style issues caused by changing the order of CSS imports
  ui/src/setup/setupStyles.ts
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6137 feat: add management and view pages for extension points
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  ui/console-src/modules/system/plugins/PluginExtensionPointSettings.vue
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionListItem.vue
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionMultiInstanceView.vue
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionSingletonView.vue
  ui/console-src/modules/system/plugins/composables/use-extension-definition-fetch.ts
  ui/console-src/modules/system/plugins/module.ts
  ui/packages/api-client/entry/api-client.ts
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6082 Refactor search engine and improve document extensibility
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_extension.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_public.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
  api/src/main/java/run/halo/app/core/extension/content/Post.java
  api/src/main/java/run/halo/app/search/HaloDocument.java
  api/src/main/java/run/halo/app/search/HaloDocumentsProvider.java
  api/src/main/java/run/halo/app/search/SearchEngine.java
  api/src/main/java/run/halo/app/search/SearchOption.java
  api/src/main/java/run/halo/app/search/SearchParam.java
  api/src/main/java/run/halo/app/search/SearchResult.java
  api/src/main/java/run/halo/app/search/event/HaloDocumentAddRequestEvent.java
  api/src/main/java/run/halo/app/search/event/HaloDocumentDeleteRequestEvent.java
  api/src/main/java/run/halo/app/search/event/HaloDocumentRebuildRequestEvent.java
  api/src/main/java/run/halo/app/search/post/PostDoc.java
  api/src/main/java/run/halo/app/search/post/PostHit.java
  api/src/main/java/run/halo/app/search/post/PostSearchService.java
  api/src/test/java/run/halo/app/core/extension/content/PostTest.java
  application/src/main/java/run/halo/app/config/HaloConfiguration.java
  application/src/main/java/run/halo/app/infra/exception/RequestBodyValidationException.java
  application/src/main/java/run/halo/app/search/HaloDocumentEventsListener.java
  application/src/main/java/run/halo/app/search/IndexEndpoint.java
  application/src/main/java/run/halo/app/search/IndicesEndpoint.java
  application/src/main/java/run/halo/app/search/IndicesInitializer.java
  application/src/main/java/run/halo/app/search/IndicesService.java
  application/src/main/java/run/halo/app/search/IndicesServiceImpl.java
  application/src/main/java/run/halo/app/search/SearchEngineUnavailableException.java
  application/src/main/java/run/halo/app/search/extension/SearchEngine.java
  application/src/main/java/run/halo/app/search/lucene/LuceneSearchEngine.java
  application/src/main/java/run/halo/app/search/post/LucenePostSearchService.java
  application/src/main/java/run/halo/app/search/post/PostEventReconciler.java
  application/src/main/java/run/halo/app/search/post/PostEventsListener.java
  application/src/main/java/run/halo/app/search/post/PostHaloDocumentsProvider.java
  application/src/main/java/run/halo/app/search/post/PostSearchEndpoint.java
  application/src/main/resources/extensions/extension-definitions.yaml
  application/src/main/resources/extensions/extensionpoint-definitions.yaml
  application/src/main/resources/extensions/searchengine-lucene.yaml
  application/src/main/resources/extensions/system-configurable-configmap.yaml
  application/src/test/java/run/halo/app/config/HaloConfigurationTest.java
  application/src/test/java/run/halo/app/search/HaloDocumentEventsListenerTest.java
  application/src/test/java/run/halo/app/search/IndexEndpointTest.java
  application/src/test/java/run/halo/app/search/IndicesEndpointTest.java
  application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineIntegrationTest.java
  application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineTest.java
  application/src/test/java/run/halo/app/search/post/PostEventsListenerTest.java
  application/src/test/java/run/halo/app/search/post/PostHaloDocumentsProviderTest.java
  application/src/test/resources/application.yaml
  docs/extension-points/search-engine.md
  platform/application/build.gradle
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api.ts
  ui/packages/api-client/src/api/index-v1alpha1-public-api.ts
  ui/packages/api-client/src/api/indices-v1alpha1-console-api.ts
  ui/packages/api-client/src/api/post-v1alpha1-public-api.ts
  ui/packages/api-client/src/models/halo-document.ts
  ui/packages/api-client/src/models/index.ts
  ui/packages/api-client/src/models/search-option.ts
  ui/packages/api-client/src/models/search-result.ts
Labels: lgtm, area/core, kind/api-change, approved, release-note, kind/improvement

#6156 Fix the problem of not being able to autowire settingFetcher bean in plugin
  application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
Labels: kind/bug, lgtm, tide/merge-method-merge, release-note-none, area/core, approved, area/plugin

#6160 Use top-level interface of session repository
  application/src/main/java/run/halo/app/security/device/DeviceEndpoint.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6165 fix: clear extension definition options after switching extension points
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionSingletonView.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6162 pref: block-level content actively sets fakeSelection
  ui/packages/editor/src/extensions/audio/index.ts
  ui/packages/editor/src/extensions/code-block/code-block.ts
  ui/packages/editor/src/extensions/columns/column.ts
  ui/packages/editor/src/extensions/iframe/index.ts
  ui/packages/editor/src/extensions/image/index.ts
  ui/packages/editor/src/extensions/range-selection/index.ts
  ui/packages/editor/src/extensions/table/index.ts
  ui/packages/editor/src/extensions/table/table-cell.ts
  ui/packages/editor/src/extensions/table/table-header.ts
  ui/packages/editor/src/extensions/table/table-row.ts
  ui/packages/editor/src/extensions/video/index.ts
Labels: lgtm, release-note-none, approved, kind/improvement, area/editor

#6167 docs: update readme for api client package
  ui/packages/api-client/README.md
Labels: lgtm, release-note-none, approved, kind/documentation, area/ui

#6168 fix: vue injection warn
  ui/packages/components/src/components/avatar/Avatar.vue
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6173 fix: spelling errors in sorting criteria for query categories
  application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6174 Fix the problem of enabling 2FA unexpectedly
  application/src/main/java/run/halo/app/security/DefaultUserDetailService.java
  application/src/test/java/run/halo/app/security/DefaultUserDetailServiceTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6177 pref: add folding function to code blocks
  ui/packages/editor/src/extensions/code-block/CodeBlockViewRenderer.vue
  ui/packages/editor/src/extensions/code-block/code-block.ts
Labels: lgtm, approved, release-note, kind/improvement, area/editor

#6175 refactor: improve the content area width of the editor for low-resolution screens
  ui/packages/editor/src/styles/base.scss
Labels: lgtm, approved, release-note, kind/improvement, area/editor, area/ui

#6179 fix: text style in extension point definition page
  ui/console-src/modules/system/plugins/PluginExtensionPointSettings.vue
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6170 pref: add the option to open a new window to the picture jump link
  ui/packages/editor/src/extensions/image/BubbleItemImageHref.vue
Labels: lgtm, approved, release-note, kind/improvement, area/editor

#6140 feat: add secret select input
  ui/docs/custom-formkit-input/README.md
  ui/src/constants/annotations.ts
  ui/src/formkit/formkit.config.ts
  ui/src/formkit/inputs/secret/SecretSelect.vue
  ui/src/formkit/inputs/secret/components/SecretCreationModal.vue
  ui/src/formkit/inputs/secret/components/SecretEditModal.vue
  ui/src/formkit/inputs/secret/components/SecretForm.vue
  ui/src/formkit/inputs/secret/components/SecretListItem.vue
  ui/src/formkit/inputs/secret/components/SecretListModal.vue
  ui/src/formkit/inputs/secret/composables/use-secrets-fetch.ts
  ui/src/formkit/inputs/secret/index.ts
  ui/src/formkit/inputs/secret/sections/index.ts
  ui/src/formkit/inputs/secret/types/index.ts
  ui/src/formkit/theme.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note, sig/docs, area/ui

#6178 feat: add support for setting an owner for posts
  ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
  ui/console-src/modules/contents/pages/components/SinglePageListItem.vue
  ui/console-src/modules/contents/posts/DeletedPostList.vue
  ui/console-src/modules/contents/posts/components/PostBatchSettingModal.vue
  ui/console-src/modules/contents/posts/components/PostSettingModal.vue
  ui/console-src/modules/contents/posts/components/entity-fields/ContributorsField.vue
  ui/env.d.ts
  ui/src/components/user/PostContributorList.vue
  ui/src/formkit/formkit.config.ts
  ui/src/formkit/inputs/user-select.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/contents/posts/components/PostListItem.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6135 feat: add method to find path of a specified node in a category tree
  application/src/main/java/run/halo/app/theme/finders/CategoryFinder.java
  application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
  application/src/main/java/run/halo/app/theme/finders/vo/CategoryTreeVo.java
  application/src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note, sig/docs

#6169 chore: add types path to ui-plugin-bunlder-kit package.json
  ui/packages/ui-plugin-bundler-kit/package.json
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6180 refactor: optimize the extension watch parameters to always be of real type
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  application/src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6187 Fix the unstable integration test of Lucene search engine
  application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineIntegrationTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/failing-test

#6188 Upgrade Lucene to 9.11.1
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#6185 Remove deprecated ExtensionComponentsFinder
  application/src/main/java/run/halo/app/content/comment/CommentNotificationReasonPublisher.java
  application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  application/src/main/java/run/halo/app/core/extension/service/impl/DefaultAttachmentService.java
  application/src/main/java/run/halo/app/plugin/ExtensionComponentsFinder.java
  application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
  application/src/test/java/run/halo/app/content/comment/CommentNotificationReasonPublisherTest.java
  application/src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
  application/src/test/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpointTest.java
  application/src/test/java/run/halo/app/theme/dialect/CommentElementTagProcessorTest.java
  application/src/test/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessorIntegrationTest.java
  application/src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6190 refactor: translate extension point descriptions to simplified chinese
  application/src/main/resources/extensions/extension-definitions.yaml
  application/src/main/resources/extensions/extensionpoint-definitions.yaml
  application/src/main/resources/static/images/extension-points/lucene.png
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6201 Rectify role templates about PAT and 2FA endpoints
  application/src/main/resources/extensions/role-template-authenticated.yaml
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6203 feat: restrict deletion of the primary menu
  ui/console-src/modules/interface/menus/components/MenuList.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6200 fix: breadcrumbs for hidden category can not be displayed
  application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
  application/src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
Labels: kind/bug, lgtm, area/core, approved, area/theme, release-note

#6108 refactor: remove page cache feature
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_extension.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
  api/src/main/java/run/halo/app/theme/router/ModelConst.java
  application/src/main/java/run/halo/app/cache/CacheEndpoint.java
  application/src/main/java/run/halo/app/cache/CachedResponse.java
  application/src/main/java/run/halo/app/cache/PageCacheWebFilter.java
  application/src/main/java/run/halo/app/config/CacheConfiguration.java
  application/src/main/java/run/halo/app/config/HaloConfiguration.java
  application/src/main/java/run/halo/app/infra/properties/HaloProperties.java
  application/src/main/java/run/halo/app/theme/HaloViewResolver.java
  application/src/main/resources/application.yaml
  application/src/main/resources/extensions/role-template-cache.yaml
  ui/console-src/modules/dashboard/widgets/QuickLinkWidget.vue
  ui/packages/api-client/entry/api-client.ts
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, area/core, kind/api-change, approved, release-note, sig/docs

#6202 Make front-end scripts compatible with Windows environment
  ui/package.json
Labels: lgtm, release-note-none, approved

#6204 fix: incorrect post display when linking or unlinking hidden categories
  application/src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
  application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6196 fix: resolve issue with secret input saving additional data
  ui/src/formkit/inputs/secret/components/SecretForm.vue
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6205 feat: add slug generation rules to post saving feature in the post editing page
  ui/console-src/modules/contents/posts/PostEditor.vue
  ui/uc-src/modules/contents/posts/PostEditor.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6207 fix: causing API to be pending when plugin startup encounters an error
  application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
Labels: lgtm, area/core, approved, release-note, kind/improvement, area/plugin

#6216 Fix the problem of fetching old value from plugin setting fetcher
  application/src/main/java/run/halo/app/plugin/DefaultReactiveSettingFetcher.java
  application/src/test/java/run/halo/app/plugin/DefaultSettingFetcherTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note, area/plugin
