Repository halo-dev/halo, pull requests merged in 2024-03, with the labels that each got.

#5437 fix: rich text editor reuploads images or videos repeatedly during redraws
  ui/src/components/editor/extensions/image/ImageView.vue
  ui/src/components/editor/extensions/video/VideoView.vue
Labels: kind/bug, lgtm, approved, release-note, area/editor, area/ui

#5434 fix: error editing post when img component has file attribute
  ui/src/components/editor/extensions/image/index.ts
  ui/src/components/editor/extensions/video/index.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor, area/ui

#5448 Prepare for developing 2.14
  README.md
  gradle.properties
  ui/packages/api-client/package.json
  ui/packages/components/package.json
  ui/packages/editor/package.json
  ui/packages/shared/package.json
  ui/packages/ui-plugin-bundler-kit/package.json
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#5450 Mark the security policy for version 1.x as unsupported
  SECURITY.md
Labels: lgtm, release-note-none, kind/cleanup, approved

#5443 feat: add select all shortcut function to the table
  ui/packages/editor/src/extensions/table/index.ts
Labels: kind/feature, lgtm, approved, release-note, area/editor, area/ui

#5452 fix: query mismatch with non-intersecting OR and nested AND condition
  api/src/main/java/run/halo/app/extension/index/query/And.java
  api/src/test/java/run/halo/app/extension/index/query/AndTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#5459 chore: update the link to view notifications in the email template
  application/src/main/java/run/halo/app/notification/EmailNotifier.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#5462 Upgrade PF4J to 3.11.0
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#5477 pref: remove nofollow from the default editor link
  ui/packages/editor/src/extensions/link/index.ts
Labels: lgtm, approved, release-note, kind/improvement, area/editor, area/ui

#5453 refactor: using index mechanisms to optimize comment queries
  api/src/main/java/run/halo/app/core/extension/content/Comment.java
  api/src/main/java/run/halo/app/extension/index/query/QueryFactory.java
  application/src/main/java/run/halo/app/content/comment/CommentQuery.java
  application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/theme/endpoint/CommentFinderEndpoint.java
  application/src/main/java/run/halo/app/theme/finders/CommentPublicQueryService.java
  application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
  application/src/test/java/run/halo/app/content/comment/CommentQueryTest.java
  application/src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
  application/src/test/java/run/halo/app/theme/endpoint/CommentFinderEndpointTest.java
  application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImplTest.java
  application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceIntegrationTest.java
  ui/console-src/modules/contents/comments/CommentList.vue
  ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-comment-api.ts
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5471 chore: bump overlayscrollbars version to 2.5.0
  ui/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5495 fix: default sort policy of attachment groups
  ui/console-src/modules/contents/attachments/composables/use-attachment-group.ts
  ui/src/formkit/inputs/attachment-group-select.ts
Labels: kind/bug, lgtm, approved, release-note, area/ui

#5496 feat: add download feature for attachment
  ui/console-src/modules/contents/attachments/components/AttachmentListItem.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#5494 feat: attachments supports sorting by display name
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note, area/ui

#5422 refactor: optimize the update method for the number of tag associated with posts
  api/src/main/java/run/halo/app/core/extension/content/Post.java
  api/src/main/java/run/halo/app/core/extension/content/Tag.java
  application/src/main/java/run/halo/app/content/TagPostCountUpdater.java
  application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  application/src/main/java/run/halo/app/core/extension/reconciler/TagReconciler.java
  application/src/main/java/run/halo/app/event/post/PostDeletedEvent.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/test/java/run/halo/app/core/extension/reconciler/TagReconcilerTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5499 Set source and target compatibility to Java 17
  api/build.gradle
  application/build.gradle
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#5497 refactor: optimize reply queries using index mechanisms
  application/src/main/java/run/halo/app/content/comment/CommentQuery.java
  application/src/main/java/run/halo/app/content/comment/ReplyQuery.java
  application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  application/src/main/java/run/halo/app/core/extension/endpoint/ReplyEndpoint.java
  application/src/main/java/run/halo/app/core/extension/reconciler/ReplyReconciler.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/metrics/ReplyEventReconciler.java
  application/src/main/java/run/halo/app/theme/finders/CommentPublicQueryService.java
  application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
  application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImplTest.java
  application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceIntegrationTest.java
  ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-comment-api.ts
  ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-reply-api.ts
  ui/packages/api-client/src/models/plugin-status.ts
  ui/packages/api-client/src/models/tag-status.ts
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5421 pref: refactor default editor audio block upload logic
  ui/src/components/editor/DefaultEditor.vue
  ui/src/components/editor/components/EditorLinkObtain.vue
  ui/src/components/editor/extensions/audio/AudioView.vue
  ui/src/components/editor/extensions/audio/index.ts
  ui/src/components/editor/extensions/index.ts
  ui/src/components/editor/utils/upload.ts
Labels: lgtm, approved, release-note, kind/improvement, area/editor, area/ui

#5472 fix: unable to manually fill in the publish time
  ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
  ui/console-src/modules/contents/posts/components/PostSettingModal.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#5479 fix: error occurs when the link is purely numerical
  ui/packages/editor/src/extensions/link/index.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor, area/ui

#5507 revert: changes to the return value type of And query
  api/src/main/java/run/halo/app/extension/index/query/QueryFactory.java
Labels: lgtm, release-note-none, area/core, approved

#5511 Collect Gradle plugin versions into root build.gradle
  api/build.gradle
  application/build.gradle
  build.gradle
  platform/application/build.gradle
  ui/build.gradle
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#5509 chore: redefine the actuator page as the overview page
  ui/console-src/layouts/BasicLayout.vue
  ui/console-src/modules/system/overview/Overview.vue
  ui/console-src/modules/system/overview/module.ts
  ui/src/locales/en.yaml
  ui/src/locales/es.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#5489 fix: missing notifier descriptors permissions in notification role template
  application/src/main/resources/extensions/role-template-notification.yaml
  application/src/main/resources/extensions/role-template-setting.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/bug, lgtm, area/core, approved, release-note

#5498 chore: optimize and reorganize code for post and page service
  application/src/main/java/run/halo/app/content/ListedPost.java
  application/src/main/java/run/halo/app/content/ListedSinglePage.java
  application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  application/src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#5504 refactor: simplify the code of reconciler for comment and optimize performance
  application/src/main/java/run/halo/app/content/comment/CommentService.java
  application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  application/src/main/java/run/halo/app/content/comment/ReplyService.java
  application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  application/src/main/java/run/halo/app/core/extension/reconciler/CommentReconciler.java
  application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  application/src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
  application/src/main/java/run/halo/app/event/post/CommentUnreadReplyCountChangedEvent.java
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  application/src/main/java/run/halo/app/extension/index/DefaultExtensionIterator.java
  application/src/main/java/run/halo/app/extension/index/ExtensionPaginatedLister.java
  application/src/main/java/run/halo/app/metrics/ReplyEventReconciler.java
  application/src/test/java/run/halo/app/content/comment/ReplyServiceTest.java
  application/src/test/java/run/halo/app/core/extension/reconciler/CommentReconcilerTest.java
  application/src/test/java/run/halo/app/extension/index/DefaultExtensionIteratorTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#5505 feat: add support for fetching replies alongside comment list
  application/src/main/java/run/halo/app/theme/endpoint/CommentFinderEndpoint.java
  application/src/main/java/run/halo/app/theme/finders/CommentPublicQueryService.java
  application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
  application/src/main/java/run/halo/app/theme/finders/vo/CommentVo.java
  application/src/main/java/run/halo/app/theme/finders/vo/CommentWithReplyVo.java
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note

#5465 feat: add a title input box in the editor
  ui/console-src/composables/use-slugify.ts
  ui/console-src/modules/contents/pages/SinglePageEditor.vue
  ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
  ui/console-src/modules/contents/posts/PostEditor.vue
  ui/console-src/modules/contents/posts/components/PostSettingModal.vue
  ui/packages/editor/src/components/Editor.vue
  ui/packages/editor/src/extensions/search-and-replace/SearchAndReplacePlugin.ts
  ui/packages/editor/src/styles/base.scss
  ui/src/components/editor/DefaultEditor.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/contents/posts/PostEditor.vue
  ui/uc-src/modules/contents/posts/components/PostCreationModal.vue
Labels: kind/feature, lgtm, approved, release-note, area/editor, area/ui

#5516 feat: improve the help tips for system setting options
  application/src/main/resources/extensions/system-setting.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5524 fix: sequence inconsistency in the comment list on the theme side
  application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#5523 fix: an extra line is added to the inline block
  ui/src/components/editor/components/InlineBlockBox.vue
  ui/src/components/editor/extensions/audio/AudioView.vue
  ui/src/components/editor/extensions/image/ImageView.vue
  ui/src/components/editor/extensions/video/VideoView.vue
Labels: kind/bug, lgtm, approved, release-note, area/editor, area/ui

#5531 feat: add Dart syntax highlighting for the code blocks in the editor
  ui/packages/editor/src/extensions/code-block/lowlight.ts
Labels: kind/feature, lgtm, approved, release-note, area/editor

#5526 pref: create while searching for tags or categories
  ui/src/formkit/inputs/category-select/CategorySelect.vue
  ui/src/formkit/inputs/tag-select/TagSelect.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5533 Upgrade Gradle to 8.6
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#5537 fix: duplicate scroller issue in post edit page
  ui/packages/editor/src/components/Editor.vue
Labels: kind/bug, lgtm, approved, release-note, area/editor

#5529 feat: comments from users with comment management permission could exempt from review
  application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  application/src/main/java/run/halo/app/security/authorization/AuthorityUtils.java
  application/src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
Labels: lgtm, area/core, approved, area/comment, release-note, kind/improvement

#5568 Upgrade Spring Boot to 3.2.4
  build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#5569 Upgrade SpringDoc to 2.4.0
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#5351 Add configuration option for email sender address apart from SMTP username
  application/src/main/java/run/halo/app/notification/EmailNotifier.java
  application/src/main/resources/extensions/notification.yaml
Labels: kind/bug, lgtm, kind/api-change, approved, release-note-action-required

#5521 pref: optimize the help style of some formkit components
  ui/src/formkit/theme.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5585 feat: add image editor feature for attachment upload component
  ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/components/upload/UppyUpload.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note, area/ui

#5580 chore: create shared common chunks during the ui build
  ui/src/vite/config-builder.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5578 feat: add retry mechanism for saving posts on the UC end
  ui/uc-src/modules/contents/posts/PostEditor.vue
  ui/uc-src/modules/contents/posts/components/PostCreationModal.vue
  ui/uc-src/modules/contents/posts/components/PostSettingEditModal.vue
  ui/uc-src/modules/contents/posts/composables/use-post-update-mutate.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5464 feat: add verification function to the notification settings for the mailbox
  application/src/main/java/run/halo/app/notification/EmailNotifier.java
  application/src/main/java/run/halo/app/notification/EmailSenderHelper.java
  application/src/main/java/run/halo/app/notification/EmailSenderHelperImpl.java
  application/src/main/java/run/halo/app/notification/endpoint/EmailConfigValidationEndpoint.java
  application/src/main/resources/extensions/notification.yaml
  application/src/main/resources/extensions/role-template-notification.yaml
  ui/docs/custom-formkit-input/README.md
  ui/src/formkit/formkit.config.ts
  ui/src/formkit/inputs/verify-form/VerificationButton.vue
  ui/src/formkit/inputs/verify-form/features/index.ts
  ui/src/formkit/inputs/verify-form/index.ts
  ui/src/formkit/theme.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, area/core, approved, release-note, area/ui

#5594 fix: selecting the previous post leads to a negative page
  ui/console-src/modules/contents/posts/PostList.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#5596 fix: unable to modify the publish time of post in the uc
  application/src/main/java/run/halo/app/endpoint/uc/content/UcPostEndpoint.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#5577 refactor: rendering conditions for plugin installation components
  ui/console-src/modules/system/plugins/PluginList.vue
  ui/console-src/modules/system/plugins/components/PluginInstallationModal.vue
  ui/console-src/modules/system/plugins/components/PluginListItem.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5590 fix: error occurs when opening attachment library in the uc
  ui/src/components/editor/DefaultEditor.vue
  ui/src/components/editor/components/EditorLinkObtain.vue
  ui/src/components/editor/extensions/image/index.ts
  ui/src/components/editor/utils/upload.ts
Labels: kind/bug, lgtm, approved, release-note, area/ui

#5570 fix: resolving the issue of the draggable extension not working in the editor
  ui/packages/editor/docs/extension.md
  ui/packages/editor/src/extensions/draggable/index.ts
  ui/packages/editor/src/types/index.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor

#5602 refactor: ignore case when matching editor raw types
  ui/console-src/modules/contents/pages/SinglePageEditor.vue
  ui/console-src/modules/contents/posts/PostEditor.vue
  ui/uc-src/modules/contents/posts/PostEditor.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#5599 docs: delete unnecessary options.
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#5609 fix: wrong router navigation when redirect to /uc
  ui/console-src/router/guards/auth-check.ts
Labels: kind/bug, lgtm, approved, release-note, area/ui

#5604 refactor: reduce the number of failures due to conflict post update
  application/src/main/java/run/halo/app/content/AbstractContentService.java
  application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  application/src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
  application/src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
  application/src/main/java/run/halo/app/core/extension/endpoint/SinglePageEndpoint.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#5601 refactor: simplify the dialogs title
  ui/console-src/modules/contents/attachments/components/AttachmentGroupList.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5626 chore: update display name of default attachment policy
  application/src/main/resources/extensions/attachment-local-policy.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5595 refactor: hide the custom annotations form by defaults
  ui/src/components/form/AnnotationsForm.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui
