Repository halo-dev/halo, pull requests merged in 2024-10, with the labels that each got.

#6740 Redirect to user center if authenticated users access login and signup pages
  application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/security/ExceptionSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/RedirectAccessDeniedHandler.java
  application/src/main/java/run/halo/app/security/authorization/NotAuthenticatedAuthorizationManager.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6749 fix: prevent hidden English characters in post title input
  ui/src/components/editor/DefaultEditor.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6752 fix: correct formatting issues in DefaultEditor component
  ui/src/components/editor/DefaultEditor.vue
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#6755 Upgrade to Gradle 8.10.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6761 Add Gradle plugin to discover dependency updates
  api/build.gradle
  application/build.gradle
  build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6762 Upgrade to Guava 33.3.1-jre
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#6763 Upgrade to Lucene 9.12.0
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#6764 chore: bump vue version to 3.5.11
  ui/package.json
  ui/packages/components/package.json
  ui/packages/editor/package.json
  ui/packages/shared/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6765 Upgrade to jsoup 1.18.1
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#6757 refactor: enhance login page styling for improved UX
  application/src/main/resources/static/styles/main.css
  application/src/main/resources/templates/gateway_modules/common_fragments.html
  application/src/main/resources/templates/gateway_modules/login_fragments.html
  application/src/main/resources/templates/signup.html
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6753 refactor: exclude indices directory during backup
  application/src/main/java/run/halo/app/migration/impl/MigrationServiceImpl.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6751 feat: add link prefetch for logo resource on login page
  application/src/main/resources/templates/gateway_modules/layout.html
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6735 feat: disallow deletion of system-protected attachment policies
  application/src/main/resources/extensions/attachment-local-policy.yaml
  ui/console-src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  ui/src/constants/finalizers.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6766 fix: resolve issue with logout functionality in Console not working
  ui/console-src/layouts/BasicLayout.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/layouts/BasicLayout.vue
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6776 refactor: remove redirect-on-login setting option from role editing form
  ui/console-src/modules/system/roles/components/RoleEditingModal.vue
  ui/src/constants/annotations.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, kind/api-change, approved, release-note, area/ui

#6777 chore: bump tiptap version to 2.8.x
  ui/package.json
  ui/packages/editor/package.json
  ui/packages/editor/src/extensions/audio/AudioView.vue
  ui/packages/editor/src/extensions/iframe/IframeView.vue
  ui/packages/editor/src/extensions/image/ImageView.vue
  ui/packages/editor/src/extensions/video/VideoView.vue
  ui/pnpm-lock.yaml
  ui/src/components/editor/extensions/image/ImageView.vue
  ui/src/components/editor/extensions/video/VideoView.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6701 fix: unique index conflict issue after backup restoration preventing startup
  application/src/main/java/run/halo/app/migration/impl/MigrationServiceImpl.java
  application/src/test/java/run/halo/app/migration/impl/MigrationServiceImplTest.java
  ui/console-src/modules/system/backup/tabs/Restore.vue
  ui/packages/components/src/components/dialog/Dialog.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/bug, lgtm, area/core, approved, release-note, sig/docs

#6775 feat: add support to check access permissions for /console
  ui/console-src/router/guards/permission.ts
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6729 feat: support deleting posts in user center
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
  application/src/main/java/run/halo/app/content/PostService.java
  application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  application/src/main/java/run/halo/app/core/endpoint/uc/UcPostEndpoint.java
  application/src/main/resources/extensions/role-template-uc-content.yaml
  ui/packages/api-client/src/api/post-v1alpha1-uc-api.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/contents/posts/components/PostListItem.vue
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note

#6771 feat: refine i18n for login method selection button
  application/src/main/resources/templates/gateway_modules/login_fragments.html
  application/src/main/resources/templates/gateway_modules/login_fragments.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_en.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_es.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_zh_TW.properties
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6779 Customize authorization exchange separately
  application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/security/authorization/AuthorizationExchangeConfigurers.java
  application/src/main/java/run/halo/app/security/authorization/NotAuthenticatedAuthorizationManager.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6781 pref: remove anonymous and ghost users from the userSelect
  ui/src/formkit/inputs/user-select.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6787 fix: resolve issue with code input can not displaying fullscreen in modal component
  ui/packages/components/src/components/modal/Modal.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6786 Fix the problem of not being able to resolve headers correctly
  application/src/main/resources/application.yaml
  application/src/test/java/run/halo/app/XForwardHeaderTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6795 chore: add LIlGG as a approver
  OWNERS
Labels: lgtm, release-note-none

#6788 fix: JavaScript error on signup page
  application/src/main/resources/templates/gateway_modules/form_fragments.html
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6791 refactor: improve error message styling for reset password form
  application/src/main/resources/templates/gateway_modules/form_fragments.html
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6794 chore: bump preset theme version
  application/src/main/resources/themes/theme-earth.zip
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6797 Redirect to user center after authenticating successfully
  application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordHandler.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6785 fix: style issue of the fullscreen button in Code input
  ui/src/formkit/inputs/code/CodeInput.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6789 fix: can not display error message for duplicate username during signup
  application/src/main/resources/templates/gateway_modules/form_fragments.html
  application/src/main/resources/templates/gateway_modules/form_fragments.properties
  application/src/main/resources/templates/gateway_modules/form_fragments_en.properties
  application/src/main/resources/templates/gateway_modules/form_fragments_es.properties
  application/src/main/resources/templates/gateway_modules/form_fragments_zh_TW.properties
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6780 feat: add login link to signup page
  application/src/main/resources/templates/gateway_modules/common_fragments.html
  application/src/main/resources/templates/gateway_modules/common_fragments.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_en.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_es.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_zh_TW.properties
  application/src/main/resources/templates/gateway_modules/login_fragments.html
  application/src/main/resources/templates/gateway_modules/login_fragments.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_en.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_es.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_zh_TW.properties
  application/src/main/resources/templates/login.html
  application/src/main/resources/templates/signup.html
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6798 Xor CSRF token
  application/src/main/java/run/halo/app/security/CsrfConfigurer.java
  application/src/test/java/run/halo/app/infra/exception/handlers/I18nExceptionTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6801 refactor: prevent password field from displaying encrypted text
  application/src/main/resources/templates/login_local.html
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6803 Refactor password reset for extensibility
  application/src/main/java/run/halo/app/core/user/service/impl/EmailPasswordRecoveryServiceImpl.java
  application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java
  application/src/main/java/run/halo/app/security/preauth/DefaultPasswordResetAvailabilityProviders.java
  application/src/main/java/run/halo/app/security/preauth/EmailPasswordResetAvailabilityProvider.java
  application/src/main/java/run/halo/app/security/preauth/PasswordResetAvailabilityProvider.java
  application/src/main/java/run/halo/app/security/preauth/PasswordResetAvailabilityProviders.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthEmailPasswordResetEndpoint.java
  application/src/main/resources/application.yaml
  application/src/main/resources/static/images/password-reset-methods/email.svg
  application/src/main/resources/static/styles/main.css
  application/src/main/resources/templates/gateway_modules/common_fragments.html
  application/src/main/resources/templates/gateway_modules/common_fragments.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_en.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_es.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_zh_TW.properties
  application/src/main/resources/templates/gateway_modules/form_fragments.html
  application/src/main/resources/templates/gateway_modules/login_fragments.html
  application/src/main/resources/templates/login_local.html
  application/src/main/resources/templates/password-reset/email/reset.html
  application/src/main/resources/templates/password-reset/email/reset.properties
  application/src/main/resources/templates/password-reset/email/reset_en.properties
  application/src/main/resources/templates/password-reset/email/reset_es.properties
  application/src/main/resources/templates/password-reset/email/reset_zh_TW.properties
  application/src/main/resources/templates/password-reset/email/send.html
  application/src/main/resources/templates/password-reset/email/send.properties
  application/src/main/resources/templates/password-reset/email/send_en.properties
  application/src/main/resources/templates/password-reset/email/send_es.properties
  application/src/main/resources/templates/password-reset/email/send_zh_TW.properties
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6804 refactor: unified validation for username and password format
  application/src/main/java/run/halo/app/core/endpoint/console/UserEndpoint.java
  application/src/main/java/run/halo/app/core/user/service/SignUpData.java
  application/src/main/java/run/halo/app/core/user/service/UserServiceImpl.java
  application/src/main/java/run/halo/app/infra/ValidationUtils.java
  application/src/main/java/run/halo/app/infra/exception/UnsatisfiedAttributeValueException.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/test/java/run/halo/app/core/endpoint/console/EmailVerificationCodeTest.java
  application/src/test/java/run/halo/app/core/user/service/UserServiceImplTest.java
  application/src/test/java/run/halo/app/infra/ValidationUtilsTest.java
  ui/console-src/modules/system/users/components/UserCreationModal.vue
  ui/console-src/modules/system/users/components/UserPasswordChangeModal.vue
  ui/src/constants/regex.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/profile/components/PasswordChangeModal.vue
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6806 fix: username length validation in user creation form is not working
  ui/console-src/modules/system/users/components/UserCreationModal.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6811 fix: avoid NPE by skipping nonexistent notifiers in user preferences
  application/src/main/java/run/halo/app/notification/endpoint/UserNotificationPreferencesEndpoint.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6812 Fix the problem of accessing logout page without authentication
  application/src/main/java/run/halo/app/security/authorization/AuthorizationExchangeConfigurers.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6807 feat: improve password confirmation validation for forms
  application/src/main/resources/static/js/main.js
  application/src/main/resources/templates/gateway_modules/common_fragments.html
  application/src/main/resources/templates/gateway_modules/common_fragments.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_en.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_es.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_zh_TW.properties
  application/src/main/resources/templates/gateway_modules/form_fragments.html
  application/src/main/resources/templates/setup.html
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6813 refactor: update login-related page templates structure
  application/src/main/resources/templates/challenges/two-factor/totp.html
  application/src/main/resources/templates/gateway_fragments/common.html
  application/src/main/resources/templates/gateway_fragments/common.properties
  application/src/main/resources/templates/gateway_fragments/common_en.properties
  application/src/main/resources/templates/gateway_fragments/common_es.properties
  application/src/main/resources/templates/gateway_fragments/common_zh_TW.properties
  application/src/main/resources/templates/gateway_fragments/input.html
  application/src/main/resources/templates/gateway_fragments/layout.html
  application/src/main/resources/templates/gateway_fragments/login.html
  application/src/main/resources/templates/gateway_fragments/login.properties
  application/src/main/resources/templates/gateway_fragments/login_en.properties
  application/src/main/resources/templates/gateway_fragments/login_es.properties
  application/src/main/resources/templates/gateway_fragments/login_zh_TW.properties
  application/src/main/resources/templates/gateway_fragments/logout.html
  application/src/main/resources/templates/gateway_fragments/logout.properties
  application/src/main/resources/templates/gateway_fragments/logout_en.properties
  application/src/main/resources/templates/gateway_fragments/logout_es.properties
  application/src/main/resources/templates/gateway_fragments/logout_zh_TW.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset.html
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_en.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_es.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_zh_TW.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_send.html
  application/src/main/resources/templates/gateway_fragments/password_reset_email_send.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_send_en.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_send_es.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_send_zh_TW.properties
  application/src/main/resources/templates/gateway_fragments/signup.html
  application/src/main/resources/templates/gateway_fragments/signup.properties
  application/src/main/resources/templates/gateway_fragments/signup_en.properties
  application/src/main/resources/templates/gateway_fragments/signup_es.properties
  application/src/main/resources/templates/gateway_fragments/signup_zh_TW.properties
  application/src/main/resources/templates/gateway_fragments/totp.html
  application/src/main/resources/templates/gateway_fragments/totp.properties
  application/src/main/resources/templates/gateway_fragments/totp_en.properties
  application/src/main/resources/templates/gateway_fragments/totp_es.properties
  application/src/main/resources/templates/gateway_fragments/totp_zh_TW.properties
  application/src/main/resources/templates/gateway_modules/form_fragments.html
  application/src/main/resources/templates/gateway_modules/form_fragments.properties
  application/src/main/resources/templates/gateway_modules/form_fragments_en.properties
  application/src/main/resources/templates/gateway_modules/form_fragments_es.properties
  application/src/main/resources/templates/gateway_modules/form_fragments_zh_TW.properties
  application/src/main/resources/templates/gateway_modules/login_fragments.html
  application/src/main/resources/templates/gateway_modules/login_fragments.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_en.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_es.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_zh_TW.properties
  application/src/main/resources/templates/login.html
  application/src/main/resources/templates/login_local.html
  application/src/main/resources/templates/logout.html
  application/src/main/resources/templates/password-reset/email/reset.html
  application/src/main/resources/templates/password-reset/email/send.html
  application/src/main/resources/templates/setup.html
  application/src/main/resources/templates/signup.html
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6808 chore: restrict username and password length during user registration
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_extension.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
  application/src/main/java/run/halo/app/core/endpoint/console/UserEndpoint.java
  application/src/main/java/run/halo/app/core/user/service/SignUpData.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/main/resources/templates/gateway_fragments/signup.html
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6810 refactor: improve ui of logout page
  application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
  application/src/main/resources/templates/gateway_fragments/logout.html
  application/src/main/resources/templates/gateway_fragments/logout.properties
  application/src/main/resources/templates/gateway_fragments/logout_en.properties
  application/src/main/resources/templates/gateway_fragments/logout_es.properties
  application/src/main/resources/templates/gateway_fragments/logout_zh_TW.properties
  application/src/main/resources/templates/logout.html
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6814 feat: improve built-in auth providers' i18n
  ui/console-src/modules/system/auth-providers/components/AuthProviderListItem.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6816 feat: improve built-in auth providers' i18n in detail page
  ui/console-src/modules/system/auth-providers/AuthProviderDetail.vue
  ui/console-src/modules/system/auth-providers/components/AuthProviderListItem.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6709 refactor: head and footer tag injection to skip error pages
  application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/HaloProcessorDialect.java
  application/src/main/java/run/halo/app/theme/dialect/InjectionExcluderProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/TemplateFooterElementTagProcessor.java
  application/src/test/java/run/halo/app/theme/dialect/InjectionExcluderProcessorTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6706 perf: replace concatMap to flatMapSequential to improve parallelism and efficiency
  application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  application/src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
  application/src/main/java/run/halo/app/plugin/PluginServiceImpl.java
  application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
  application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/ContributorFinderImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/PostPublicQueryServiceImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/SinglePageConversionServiceImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/TagFinderImpl.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6817 Support redirecting to URI with fragment
  application/src/main/java/run/halo/app/security/HaloServerRequestCache.java
  application/src/test/java/run/halo/app/security/HaloServerRequestCacheTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6819 refactor: support locale-based validation messages based on users language
  application/src/main/java/run/halo/app/core/endpoint/console/UserEndpoint.java
  application/src/main/java/run/halo/app/infra/ValidationUtils.java
  application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthEndpoint.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthSignUpEndpoint.java
  application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6809 refactor: improve ui of login page
  application/src/main/resources/static/styles/main.css
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6820 refactor: improve password hint text on reset password page
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_en.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_es.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_zh_TW.properties
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6822 fix: correct display of email verification message toast
  application/src/main/resources/templates/gateway_fragments/signup.html
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6823 Add globalInfo into templates model
  application/src/main/java/run/halo/app/security/preauth/PreAuthEmailPasswordResetEndpoint.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthTwoFactorEndpoint.java
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset.html
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_en.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_es.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_zh_TW.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_send.html
  application/src/main/resources/templates/gateway_fragments/password_reset_email_send.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_send_en.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_send_es.properties
  application/src/main/resources/templates/gateway_fragments/password_reset_email_send_zh_TW.properties
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6829 Do not cache template result for pre-auth pages
  api/src/main/java/run/halo/app/theme/router/ModelConst.java
  application/src/main/java/run/halo/app/infra/utils/HaloUtils.java
  application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthEmailPasswordResetEndpoint.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthLoginEndpoint.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthSignUpEndpoint.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthTwoFactorEndpoint.java
  application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
  application/src/main/java/run/halo/app/theme/HaloViewResolver.java
  application/src/test/java/run/halo/app/infra/utils/HaloUtilsTest.java
  application/src/test/java/run/halo/app/theme/ThemeIntegrationTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6830 Disable CSRF protection for actuator endpoints
  application/src/main/java/run/halo/app/security/CsrfConfigurer.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6831 Add globalInfo into logout page
  application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6836 chore: add prettier-plugin-organize-imports plugin to organize imports
  ui/.vscode/settings.json
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/comments/components/CommentListItem.vue
  ui/console-src/modules/contents/comments/components/ReplyListItem.vue
  ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
  ui/console-src/modules/system/plugins/components/entity-fields/ReloadField.vue
  ui/console-src/modules/system/users/components/UserCreationModal.vue
  ui/package.json
  ui/pnpm-lock.yaml
  ui/prettier.config.cjs
  ui/src/components/editor/DefaultEditor.vue
  ui/src/formkit/inputs/select/MultipleSelect.vue
  ui/src/formkit/inputs/select/SelectDropdownContainer.vue
  ui/uc-src/modules/profile/tabs/Devices.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6839 refactor: improve accessibility for login page
  application/src/main/resources/templates/gateway_fragments/common.html
  application/src/main/resources/templates/gateway_fragments/login.html
  application/src/main/resources/templates/login_local.html
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6840 Fix the problem of being able to configure invalid external URL
  application/src/main/java/run/halo/app/infra/properties/HaloProperties.java
  application/src/test/java/run/halo/app/PathPrefixPredicateTest.java
  application/src/test/java/run/halo/app/infra/properties/HaloPropertiesTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6832 refactor: improve login page ui
  application/src/main/resources/static/styles/main.css
  application/src/main/resources/templates/signup.html
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6844 Preserve remember-me option after authentication failure
  application/src/main/java/run/halo/app/security/authentication/rememberme/TokenBasedRememberMeServices.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/WebSessionRememberMeRequestCache.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthLoginEndpoint.java
  application/src/main/resources/templates/gateway_fragments/login.html
Labels: kind/bug, lgtm, area/core, approved, release-note

#6842 fix: vertical images are rotated to horizontal when generating thumbnails
  api/build.gradle
  application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java
  platform/application/build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6855 chore: ignore preset plugin installation errors to avoid initialization failure
  application/src/main/java/run/halo/app/plugin/PluginServiceImpl.java
Labels: lgtm, release-note-none, area/core, approved

#6857 Fill operation ID while building setup route
  application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6849 refactor: remove underline in h2 warning alert
  ui/src/components/alerts/H2WarningAlert.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6852 fix: not redirect to /console after setup
  application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6853 fix: set default value for attachment storage policy in user center
  application/src/main/resources/extensions/system-configurable-configmap.yaml
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6856 feat: support toast a message for backend exceptions when sending emails
  application/src/main/resources/templates/gateway_fragments/signup.html
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6848 feat: add H2 database usage warning for setup page
  application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
  application/src/main/resources/templates/setup.html
  application/src/main/resources/templates/setup.properties
  application/src/main/resources/templates/setup_en.properties
  application/src/main/resources/templates/setup_es.properties
  application/src/main/resources/templates/setup_zh_TW.properties
Labels: tide/merge-method-merge, release-note-none, area/core, kind/improvement

#6846 refactor: auth provider sorting logic for better maintainability and clarity
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_extension.api_v1alpha1.json
  api/src/main/java/run/halo/app/core/extension/AuthProvider.java
  api/src/main/java/run/halo/app/extension/Unstructured.java
  api/src/main/java/run/halo/app/infra/SystemSetting.java
  application/src/main/java/run/halo/app/security/AuthProviderService.java
  application/src/main/java/run/halo/app/security/AuthProviderServiceImpl.java
  application/src/main/java/run/halo/app/security/ListedAuthProvider.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthLoginEndpoint.java
  application/src/test/java/run/halo/app/security/AuthProviderServiceImplTest.java
  ui/console-src/modules/system/auth-providers/AuthProviders.vue
  ui/console-src/modules/system/auth-providers/components/AuthProvidersSection.vue
  ui/console-src/modules/system/auth-providers/module.ts
  ui/console-src/modules/system/users/UserList.vue
  ui/packages/api-client/src/models/auth-provider-spec.ts
  ui/packages/api-client/src/models/listed-auth-provider.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: tide/merge-method-merge, area/core, release-note, kind/improvement

#6860 chore: bump preset theme version
  application/src/main/resources/themes/theme-earth.zip
Labels: release-note-none, area/core, kind/improvement

#6861 fix: retain legacy enabled field for auth provider setting
  api/src/main/java/run/halo/app/infra/SystemSetting.java
  application/src/test/java/run/halo/app/security/AuthProviderServiceImplTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6862 Fix the problem of redirecting to previous URI with fragment after authenticated
  application/src/main/java/run/halo/app/security/HaloServerRequestCache.java
  application/src/test/java/run/halo/app/security/HaloServerRequestCacheTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6865 fix: preventing access to login page after Halo setup
  application/src/main/java/run/halo/app/security/AuthProviderServiceImpl.java
  application/src/main/resources/extensions/system-configurable-configmap.yaml
  application/src/test/java/run/halo/app/security/AuthProviderServiceImplTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6869 Fix the problem of not being able to disconnect OAuth2 user
  application/src/main/resources/extensions/role-template-authenticated.yaml
Labels: kind/bug, lgtm, area/core, approved, release-note

#6870 Fix the problem of not being able to create PAT for OAuth2 user
  application/src/main/java/run/halo/app/security/authentication/pat/impl/UserScopedPatHandlerImpl.java
  application/src/main/java/run/halo/app/security/authorization/AuthorityUtils.java
  application/src/test/java/run/halo/app/security/authorization/AuthorityUtilsTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6874 docs: update readme for 2.20
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#6876 docs: add gitpod link for readme
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#6877 fix: missing ServerWebExchange in plugin template processor extension
  application/src/main/java/run/halo/app/theme/dialect/CommentElementTagProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/HaloPostTemplateHandler.java
  application/src/main/java/run/halo/app/theme/dialect/SecureTemplateContextWrapper.java
  application/src/main/java/run/halo/app/theme/dialect/SecureTemplateWebContext.java
  application/src/main/java/run/halo/app/theme/dialect/TemplateFooterElementTagProcessor.java
  application/src/test/java/run/halo/app/theme/dialect/HaloPostTemplateHandlerTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6880 Expose user and role services into plugins
  api/src/main/java/run/halo/app/core/user/service/RoleService.java
  api/src/main/java/run/halo/app/core/user/service/SignUpData.java
  api/src/main/java/run/halo/app/core/user/service/UserService.java
  api/src/main/java/run/halo/app/infra/ValidationUtils.java
  application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
Labels: kind/feature, lgtm, approved, release-note, area/plugin

#6878 Refactor PAT authentication by making it standalone
  application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/security/SecurityWebFiltersConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/jwt/JwtAuthenticationConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/jwt/LoginAuthenticationConverter.java
  application/src/main/java/run/halo/app/security/authentication/jwt/LoginAuthenticationFailureHandler.java
  application/src/main/java/run/halo/app/security/authentication/jwt/LoginAuthenticationManager.java
  application/src/main/java/run/halo/app/security/authentication/jwt/LoginAuthenticationSuccessHandler.java
  application/src/main/java/run/halo/app/security/authentication/pat/PatAuthenticationConverter.java
  application/src/main/java/run/halo/app/security/authentication/pat/PatAuthenticationManager.java
  application/src/main/java/run/halo/app/security/authentication/pat/PatEndpoint.java
  application/src/main/java/run/halo/app/security/authentication/pat/PatSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/pat/PatServerWebExchangeMatcher.java
  application/src/main/java/run/halo/app/security/authentication/pat/UserScopedPatHandlerImpl.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6881 chore: bump app store plugin version
  application/build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6885 Expose ReactiveUserDetailsService to authentication plugins
  application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6889 fix: prevent initialization failure when theme directory already exists
  application/src/main/java/run/halo/app/theme/service/ThemeServiceImpl.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6896 Fix the problem of not redirecting to corresponding login page after authentication failure
  application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordHandler.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6895 Bind sign up data instead of building by hand
  api/src/main/java/run/halo/app/core/user/service/SignUpData.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthSignUpEndpoint.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6897 fix: modify name column charset to make it case-sensitive for MySQL
  application/src/main/resources/schema-mariadb.sql
  application/src/main/resources/schema-mysql.sql
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6902 fix: can not return to post list after publishing when re-logged in
  ui/console-src/modules/contents/pages/SinglePageEditor.vue
  ui/console-src/modules/contents/posts/PostEditor.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6912 fix: resolve button height overflow in signup form on older Safari
  application/src/main/resources/static/styles/main.css
Labels: kind/bug, lgtm, area/core, approved, release-note

#6915 Exclude console and uc assets in security configuration
  application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6914 fix: post slug generation not following selected strategy
  ui/console-src/composables/use-slugify.ts
  ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  ui/console-src/modules/contents/posts/components/PostSettingModal.vue
  ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
  ui/uc-src/modules/contents/posts/components/PostSettingForm.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6917 chore: remove unused dependencies and configuration files
  .gitattributes
  ui/.changeset/README.md
  ui/.changeset/config.json
  ui/.changeset/pre.json
  ui/.eslintrc.cjs
  ui/OWNERS
  ui/cypress.json
  ui/cypress/fixtures/example.json
  ui/cypress/integration/example.spec.ts
  ui/cypress/plugins/index.ts
  ui/cypress/plugins/tsconfig.json
  ui/cypress/support/commands.ts
  ui/cypress/support/index.ts
  ui/cypress/tsconfig.json
  ui/package.json
  ui/packages/components/tsconfig.node.json
  ui/packages/shared/tsconfig.node.json
  ui/pnpm-lock.yaml
  ui/tailwind.config.cjs
  ui/tsconfig.node.json
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6898 fix: path match rules for grouped OpenAPI
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_extension.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_public.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
  application/src/main/java/run/halo/app/infra/config/SwaggerConfig.java
  application/src/main/java/run/halo/app/notification/endpoint/SubscriptionRouter.java
  application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
  ui/packages/api-client/entry/api-client.ts
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api.ts
  ui/packages/api-client/src/api/default-api.ts
  ui/packages/api-client/src/api/notification-v1alpha1-public-api.ts
  ui/packages/api-client/src/api/system-v1alpha1-public-api.ts
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6920 Support nested configuration properties
  application/src/main/java/run/halo/app/infra/properties/ConsoleProperties.java
  application/src/main/java/run/halo/app/infra/properties/HaloProperties.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6921 Support pushing Docker image into Fit2Cloud Docker Registry
  .github/actions/docker-buildx-push/action.yaml
  .github/workflows/halo.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6923 chore: update action.yaml
  .github/actions/docker-buildx-push/action.yaml
Labels: release-note-none, area/core, kind/cleanup

#6925 Configure registry while login to Fit2Cloud Docker Registry
  .github/actions/docker-buildx-push/action.yaml
Labels: release-note-none, area/core, kind/cleanup

#6933 fix: remove httpOnly from language cookie to allow JS to access current language
  application/src/main/java/run/halo/app/infra/webfilter/LocaleChangeWebFilter.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6922 fix: missing deleted index in list method of single page finder
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6926 fix: prioritize login page route to prevent single page override
  application/src/main/java/run/halo/app/security/preauth/PreAuthEmailPasswordResetEndpoint.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthLoginEndpoint.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthSignUpEndpoint.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthTwoFactorEndpoint.java
  application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6940 Update version to 2.20.8-SNAPSHOT
  gradle.properties
Labels: release-note-none, area/core, kind/cleanup

#6945 Support hooking user creation
  api/src/main/java/run/halo/app/core/user/service/UserPostCreatingHandler.java
  api/src/main/java/run/halo/app/core/user/service/UserPreCreatingHandler.java
  application/src/main/java/run/halo/app/core/user/service/impl/UserServiceImpl.java
  application/src/test/java/run/halo/app/core/user/service/impl/UserServiceImplTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#6952 Upgrade to Spring Boot 3.4.0-RC1
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6956 feat: add supports for displaying jpeg icon in attachments list
  ui/src/components/icon/AttachmentFileTypeIcon.vue
Labels: lgtm, approved, release-note, kind/improvement

#6951 feat: add support for creating a new group when uploading attachments
  ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6939 Rearrange order of security configurers
  application/src/main/java/run/halo/app/security/CorsConfigurer.java
  application/src/main/java/run/halo/app/security/CsrfConfigurer.java
  application/src/main/java/run/halo/app/security/ExceptionSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/SecurityWebFiltersConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/login/LoginSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/oauth2/OAuth2SecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/RememberMeConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSecurityConfigurer.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6964 fix: prevent undefined key name when creating Secret
  ui/src/formkit/inputs/secret/SecretSelect.vue
  ui/src/formkit/inputs/secret/components/SecretCreationModal.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6959 feat: add name existence check before creating attachment group and storage policy
  ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
  ui/console-src/modules/contents/attachments/components/AttachmentGroupList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement

#6963 feat: add grant permission and user deletion features to user detail page
  ui/console-src/modules/system/users/UserDetail.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement

#6972 refactor: hide essential notifications to prevent accidental disabling
  api/src/main/java/run/halo/app/extension/MetadataUtil.java
  application/src/main/java/run/halo/app/notification/endpoint/UserNotificationPreferencesEndpoint.java
  application/src/main/resources/extensions/notification.yaml
  application/src/test/java/run/halo/app/notification/endpoint/UserNotificationPreferencesEndpointTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6978 docs: Update README.md
  README.md
Labels: lgtm, approved, kind/documentation

#6981 Support customizing CORS configuration
  application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java
  application/src/main/java/run/halo/app/security/CorsConfigurer.java
Labels: lgtm, area/core, approved, release-note, sig/docs, kind/improvement

#6982 Bump version to 2.20.9-SNAPSHOT
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_extension.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_public.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
  gradle.properties
Labels: lgtm, release-note-none, kind/cleanup, approved
