Repository halo-dev/halo, pull requests merged in 2024-11, with the labels that each got.

#7011 Use task list for issue and pr checks
  .github/ISSUE_TEMPLATE/bug_report.en.yml
  .github/ISSUE_TEMPLATE/bug_report.zh.yml
  .github/ISSUE_TEMPLATE/feature_request.en.yml
  .github/ISSUE_TEMPLATE/feature_request.zh.yml
Labels: lgtm, release-note-none, kind/cleanup, approved

#7010 docs: Update README.md
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#7024 chore: bump preset plugins version
  application/build.gradle
Labels: area/core, release-note, kind/improvement

#7049 fix: new tags showing null post count on theme
  application/src/main/java/run/halo/app/core/reconciler/TagReconciler.java
  application/src/main/java/run/halo/app/theme/finders/vo/TagVo.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7057 Remove template engine after upgrading theme
  application/src/main/java/run/halo/app/theme/TemplateEngineManager.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#7060 Upgrade to Spring Boot 3.4.0
  build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#7062 Upgrade to Gradle 8.11
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#7069 chore: bump tiptap version to 2.10.x
  ui/package.json
  ui/packages/editor/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, approved, release-note, area/ui

#7037 feat: add multi-role assignment support for users
  ui/console-src/layouts/BasicLayout.vue
  ui/console-src/modules/system/roles/RoleDetail.vue
  ui/console-src/modules/system/users/UserDetail.vue
  ui/console-src/modules/system/users/UserList.vue
  ui/console-src/modules/system/users/components/GrantPermissionModal.vue
  ui/console-src/modules/system/users/components/RolesView.vue
  ui/console-src/modules/system/users/tabs/Detail.vue
  ui/console-src/router/guards/permission.ts
  ui/src/formkit/inputs/role-select.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/layouts/BasicLayout.vue
  ui/uc-src/modules/profile/tabs/Detail.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#7031 refactor: add uniqueness check for local thumbnail original links and dimensions to avoid duplication
  application/src/main/java/run/halo/app/core/attachment/extension/LocalThumbnail.java
  application/src/main/java/run/halo/app/core/attachment/impl/LocalThumbnailServiceImpl.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/test/java/run/halo/app/core/attachment/impl/LocalThumbnailServiceImplTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7075 feat: improve role template i18n
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#7076 fix: post annotations form layout issues in Chrome browser
  ui/src/components/form/AnnotationsForm.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#7078 feat: add empty state for restore by backups
  ui/console-src/modules/system/backup/tabs/Restore.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#7077 fix: resolve concurrency issue causing duplicate thumbnail generation
  application/src/main/java/run/halo/app/core/attachment/ThumbnailMigration.java
  application/src/main/java/run/halo/app/core/attachment/impl/ThumbnailServiceImpl.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/test/java/run/halo/app/core/attachment/impl/ThumbnailServiceImplTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7079 fix: restrict thumbnail generation to images in the attachment library
  application/src/main/java/run/halo/app/content/HtmlThumbnailSrcsetInjector.java
  application/src/main/java/run/halo/app/core/attachment/ThumbnailService.java
  application/src/main/java/run/halo/app/core/attachment/impl/ThumbnailServiceImpl.java
  application/src/main/java/run/halo/app/core/endpoint/theme/ThumbnailEndpoint.java
  application/src/main/java/run/halo/app/theme/finders/impl/ThumbnailFinderImpl.java
  application/src/test/java/run/halo/app/core/endpoint/theme/ThumbnailEndpointTest.java
  application/src/test/java/run/halo/app/theme/finders/impl/ThumbnailFinderImplTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7081 chore: add packageManager for corepack
  ui/package.json
Labels: lgtm, approved, release-note, kind/improvement, area/ui
