Repository halo-dev/halo, pull requests merged in 2024-07, with the labels that each got.

#6225 chore: bump preset plugins version
  application/build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6227 Upgrade SpringDoc to 2.6.0
  build.gradle
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#6220 feat: add disabled state styling to checkboxes
  ui/src/styles/tailwind.css
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6228 feat: refine 2fa-related i18n
  ui/src/components/login/MfaForm.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/profile/Profile.vue
  ui/uc-src/modules/profile/tabs/TwoFactor.vue
  ui/uc-src/modules/profile/tabs/components/PasswordValidationForm.vue
  ui/uc-src/modules/profile/tabs/components/TotpConfigureModal.vue
  ui/uc-src/modules/profile/tabs/components/TotpDeletionModal.vue
  ui/uc-src/modules/profile/tabs/components/TwoFactorDisableModal.vue
  ui/uc-src/modules/profile/tabs/components/TwoFactorEnableModal.vue
Labels: kind/feature, lgtm, release-note-none, approved, area/ui

#6231 refactor: refine extension settings page
  ui/console-src/modules/system/plugins/PluginExtensionPointSettings.vue
  ui/console-src/modules/system/plugins/PluginList.vue
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionMultiInstanceView.vue
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionSingletonView.vue
  ui/console-src/modules/system/plugins/module.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6176 feat: add LoginHandlerEnhancer for enhanced login processing
  api/src/main/java/run/halo/app/security/LoginHandlerEnhancer.java
  application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
  application/src/main/java/run/halo/app/security/LoginHandlerEnhancerImpl.java
  application/src/main/java/run/halo/app/security/authentication/login/LoginSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordHandler.java
  application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/twofactor/totp/TotpAuthenticationFilter.java
Labels: lgtm, release-note-none, area/core, approved, sig/docs, kind/improvement

#6230 chore: compatibility support for null for sort parameter of listAll
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
Labels: lgtm, release-note-none, area/core, approved

#6229 chore: regenerate API client
  ui/package.json
  ui/packages/api-client/package.json
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api/cache-v1alpha1-console-api.ts
  ui/packages/api-client/src/api/console-api-security-halo-run-v1alpha1-device-api.ts
  ui/packages/api-client/src/api/security-halo-run-v1alpha1-device-api.ts
  ui/packages/api-client/src/api/uc-api-security-halo-run-v1alpha1-device-api.ts
  ui/packages/api-client/src/api/v1alpha1-v1alpha1-api.ts
  ui/packages/api-client/src/models/post-hit.ts
  ui/packages/api-client/src/models/post-hits.ts
  ui/packages/api-client/src/models/v1alpha1-list.ts
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#6234 Allow plugin to listen the event the plugin has started
  api/src/main/java/run/halo/app/plugin/event/PluginStartedEvent.java
  application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
  application/src/main/java/run/halo/app/plugin/event/HaloPluginStateChangedEvent.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#6237 refactor: refine permissions of extension settings page
  ui/console-src/modules/system/plugins/PluginList.vue
  ui/console-src/modules/system/plugins/module.ts
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6233 feat: add plugin detail modal as global component
  ui/console-src/modules/system/plugins/PluginDetail.vue
  ui/console-src/modules/system/plugins/components/PluginDetailModal.vue
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionListItem.vue
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionSingletonView.vue
  ui/console-src/modules/system/plugins/components/tabs/Detail.vue
  ui/console-src/modules/system/plugins/components/tabs/Setting.vue
  ui/console-src/modules/system/plugins/composables/use-plugin.ts
  ui/console-src/modules/system/plugins/module.ts
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6239 Expose search service for plugin
  api/src/main/java/run/halo/app/search/SearchService.java
  application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
  application/src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
  application/src/main/java/run/halo/app/search/IndexEndpoint.java
  application/src/main/java/run/halo/app/search/SearchServiceImpl.java
  application/src/test/java/run/halo/app/plugin/DefaultPluginApplicationContextFactoryTest.java
  application/src/test/java/run/halo/app/search/IndexEndpointTest.java
  application/src/test/java/run/halo/app/search/SearchServiceImplTest.java
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note, area/plugin

#6241 Fix the problem of null type of search result
  application/src/main/java/run/halo/app/search/lucene/LuceneSearchEngine.java
  application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineIntegrationTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6236 feat: enhance PluginFinder to support check plugin availability by version
  application/src/main/java/run/halo/app/theme/finders/PluginFinder.java
  application/src/main/java/run/halo/app/theme/finders/impl/PluginFinderImpl.java
  application/src/test/java/run/halo/app/theme/finders/impl/PluginFinderImplTest.java
Labels: kind/feature, lgtm, area/core, approved, area/theme, release-note, sig/docs

#6191 feat: add TemplateFooterProcessor extension point for extending footer tag content in theme
  api/src/main/java/run/halo/app/theme/dialect/TemplateFooterProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/TemplateFooterElementTagProcessor.java
  application/src/main/resources/extensions/extensionpoint-definitions.yaml
  application/src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java
  application/src/test/java/run/halo/app/theme/dialect/TemplateFooterElementTagProcessorTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note, sig/docs

#6240 fix: resolve styling issue for checkbox when disabled
  ui/src/formkit/theme.ts
  ui/src/styles/tailwind.css
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6242 Add support to disable two-factor authentication
  application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java
  application/src/main/java/run/halo/app/security/DefaultUserDetailService.java
  application/src/test/java/run/halo/app/security/DefaultUserDetailServiceTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6238 fix: handle plugin entry file loading when cache temp directory is cleared
  application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
  application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
Labels: kind/bug, lgtm, approved, release-note, area/plugin

#6223 feat: tag and category add save and continue button
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
  ui/src/locales/en.yaml
  ui/src/locales/es.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note

#6245 chore: cleanup deprecated extension yaml
  application/src/main/java/run/halo/app/search/PostDocUtils.java
  application/src/main/resources/extensions/extension-definitions.yaml
  application/src/main/resources/extensions/role-template-uc-content.yaml
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6097 fix: the e2e script exit code handling is incorrect
  e2e/Dockerfile
  e2e/start.sh
  e2e/testsuite.yaml
Labels: kind/bug, lgtm, release-note-none, approved

#6253 chore: upgrade api-testing to v0.0.17
  e2e/Dockerfile
Labels: lgtm, release-note-none, approved

#6244 chore: cleanup buildParametersFromType for QueryParamBuildUtil
  api/src/main/java/run/halo/app/extension/router/QueryParamBuildUtil.java
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#6243 chore: cleanup deprecated constructor for base plugin
  api/src/main/java/run/halo/app/plugin/BasePlugin.java
  application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
  application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
  application/src/main/java/run/halo/app/plugin/HaloPluginWrapper.java
  application/src/main/java/run/halo/app/plugin/SpringPlugin.java
  application/src/main/java/run/halo/app/plugin/event/HaloPluginLoadedEvent.java
Labels: lgtm, kind/cleanup, approved, release-note, area/plugin

#6259 Prepare for developing 2.18.0
  README.md
  gradle.properties
  ui/packages/api-client/package.json
  ui/packages/components/package.json
  ui/packages/editor/package.json
  ui/packages/shared/package.json
  ui/packages/ui-plugin-bundler-kit/package.json
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6261 Build and run using IntelliJ IDEA after building ui
  application/build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6269 Support obtaining plugins root in plugins
  api/src/main/java/run/halo/app/plugin/PluginsRootGetter.java
  application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
  application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
  application/src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
  application/src/main/java/run/halo/app/plugin/PluginProperties.java
  application/src/main/java/run/halo/app/plugin/PluginsRootGetterImpl.java
  application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
  application/src/main/resources/application.yaml
  application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
  application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
  application/src/test/java/run/halo/app/plugin/DefaultPluginApplicationContextFactoryTest.java
  application/src/test/java/run/halo/app/plugin/PluginsRootGetterImplTest.java
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note, area/plugin

#6271 chore: keep the pluginWrapper bean for compatibility
  api/src/main/java/run/halo/app/plugin/BasePlugin.java
  application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
Labels: lgtm, release-note-none, area/core, approved

#6274 Respond 409 for operation conflict instead of 500
  application/src/main/java/run/halo/app/infra/exception/Exceptions.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/test/java/run/halo/app/infra/exception/handlers/I18nExceptionTest.java
  application/src/test/resources/application.yaml
  application/src/test/resources/config/i18n/messages.properties
Labels: lgtm, release-note-none, area/core, kind/api-change, approved, kind/improvement

#6275 refactor: remove IP address judgment for device management
  application/src/main/java/run/halo/app/security/device/DeviceServiceImpl.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6278 Allow E2E testing to fail
  .github/workflows/halo.yaml
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6277 chore: mark deprecated constructor for base plugin
  api/src/main/java/run/halo/app/plugin/BasePlugin.java
Labels: lgtm, approved, release-note

#6276 fix: resolve potential exception during bulk image upload in post creation
  ui/console-src/modules/contents/pages/SinglePageEditor.vue
  ui/console-src/modules/contents/posts/PostEditor.vue
  ui/uc-src/modules/contents/posts/PostEditor.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6281 [release-2.17] chore: mark deprecated constructor for base plugin
  api/src/main/java/run/halo/app/plugin/BasePlugin.java
Labels: lgtm, approved, release-note

#6268 fix: bubble menu not appearing when crossing lines in editor
  ui/packages/editor/src/extensions/text/index.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor

#6297 Add before and after security web filters
  api/src/main/java/run/halo/app/security/AfterSecurityWebFilter.java
  api/src/main/java/run/halo/app/security/BeforeSecurityWebFilter.java
  application/src/main/java/run/halo/app/security/SecurityWebFiltersConfigurer.java
  docs/extension-points/authentication.md
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note, area/plugin

#6298 Use AuthenticationWebFilter for remember-me mechanism
  application/src/main/java/run/halo/app/security/authentication/rememberme/RememberMeAuthenticationFilter.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/RememberMeConfigurer.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6265 feat: add support for video thumbnail preview in the attachment library
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentError.vue
  ui/console-src/modules/contents/attachments/components/AttachmentLoading.vue
  ui/src/components/video/LazyVideo.vue
Labels: kind/feature, lgtm, approved, release-note

#6252 Add devcontainer support
  .devcontainer/devcontainer.json
  .github/dependabot.yml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6323 Fix the problem of not being able to rebuild search index
  application/src/main/java/run/halo/app/search/lucene/LuceneSearchEngine.java
  application/src/main/java/run/halo/app/search/post/PostHaloDocumentsProvider.java
  application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineTest.java
  application/src/test/java/run/halo/app/search/post/PostHaloDocumentsProviderTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6310 chore: bump preset plugins version
  application/build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6329 Fix the problem where automatic login using remember-me token could fail
  application/src/main/java/run/halo/app/security/authentication/rememberme/PersistentTokenBasedRememberMeServices.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6327 chore: bump tiptap version to 2.5.1
  ui/package.json
  ui/packages/editor/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/editor, area/ui

#6309 Improve timezone information in login notification
  application/src/main/java/run/halo/app/security/device/NewDeviceLoginListener.java
  application/src/main/resources/extensions/notification-templates.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6340 Respond 404 for non-exist theme resources instead of 500
  application/src/main/java/run/halo/app/theme/config/ThemeWebFluxConfigurer.java
  application/src/test/java/run/halo/app/config/WebFluxConfigTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6347 fix: enter key causing focus loss in default editor title during composition input
  ui/src/components/editor/DefaultEditor.vue
Labels: kind/bug, lgtm, approved, release-note, area/editor

#6334 Fix the problem that plugins without jar file may not be deleted
  application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
  application/src/test/java/run/halo/app/plugin/HaloPluginManagerTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note, area/plugin

#6374 [release-2.17] Fix the problem that plugins without jar file may not be deleted
  application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
  application/src/test/java/run/halo/app/plugin/HaloPluginManagerTest.java
Labels: lgtm, approved, release-note

#6365 feat: share ExtensionGetter Bean with plugins for extension retrieval
  api/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionGetter.java
  application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
Labels: lgtm, area/core, approved, release-note, sig/docs, kind/improvement

#6375 chore: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.en.yml
  .github/ISSUE_TEMPLATE/bug_report.zh.yml
  .github/ISSUE_TEMPLATE/feature_request.en.yml
  .github/ISSUE_TEMPLATE/feature_request.zh.yml
Labels: lgtm, release-note-none, area/core, approved

#6379 chore: compatibility for deprecated buildParametersFromType method with deprecation log
  api/src/main/java/run/halo/app/extension/router/QueryParamBuildUtil.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6388 feat: add the first line indent to the Tab shortcut key
  ui/packages/editor/src/extensions/indent/index.ts
Labels: kind/feature, lgtm, approved, release-note, area/editor

#6402 refactor: change the number of queried attachments in the selector modal
  ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6403 chore: bump tiptap version to 2.5.7
  application/src/main/resources/extensions/system-setting.yaml
  ui/package.json
  ui/packages/editor/package.json
  ui/packages/editor/src/extensions/commands-menu/commands.ts
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6406 feat: add retry mechanism for publishing posts in user center
  ui/uc-src/modules/contents/posts/PostEditor.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6407 refactor: remove padding style from editor column block
  ui/packages/editor/src/extensions/columns/column.ts
  ui/packages/editor/src/extensions/columns/columns.ts
  ui/packages/editor/src/styles/columns.scss
Labels: lgtm, approved, release-note, kind/improvement, area/editor

#6408 fix: list items require multiple backspace presses to delete
  ui/packages/editor/src/extensions/indent/index.ts
  ui/packages/editor/src/extensions/paragraph/index.ts
  ui/packages/editor/src/utils/isListActive.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor

#6387 fix: solve the problem that highlighting will prevent the keys
  ui/packages/editor/src/extensions/color/index.ts
  ui/packages/editor/src/extensions/font-size/index.ts
  ui/packages/editor/src/extensions/highlight/index.ts
  ui/packages/editor/src/extensions/index.ts
  ui/packages/editor/src/extensions/text-style/index.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor

#6411 fix: remove unused code in system-setting.yaml
  application/src/main/resources/extensions/system-setting.yaml
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6414 Refine debug logs of querying extensions
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6417 fix: NPE when saving system configuration
  application/src/main/java/run/halo/app/plugin/DefaultReactiveSettingFetcher.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6348 feat: add extension point for excerpt generation
  api/src/main/java/run/halo/app/content/ExcerptGenerator.java
  application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
  application/src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
  application/src/main/resources/extensions/extensionpoint-definitions.yaml
  application/src/test/java/run/halo/app/core/extension/reconciler/PostReconcilerTest.java
  application/src/test/java/run/halo/app/core/extension/reconciler/SinglePageReconcilerTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note, sig/docs
