Repository halo-dev/halo, pull requests merged in 2024-12, with the labels that each got.

#7099 Upgrade to PF4J 3.13.0
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#7106 chore: standardize request parsing to use a single path handler
  application/src/main/java/run/halo/app/security/authorization/RequestInfoFactory.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#7100 perf: add caching for system configuration fetcher to enhance performance
  application/src/main/java/run/halo/app/core/endpoint/console/SystemConfigEndpoint.java
  application/src/main/java/run/halo/app/core/reconciler/SystemSettingReconciler.java
  application/src/main/java/run/halo/app/infra/SystemConfigurableEnvironmentFetcher.java
  application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
  application/src/test/java/run/halo/app/core/reconciler/SystemSettingReconcilerTest.java
  application/src/test/java/run/halo/app/infra/SystemConfigurableEnvironmentFetcherTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7102 perf: add caching for extension getter to enhance performance
  application/src/main/java/run/halo/app/plugin/extensionpoint/AbstractDefinitionGetter.java
  application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
  application/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionDefinitionGetter.java
  application/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionDefinitionGetterImpl.java
  application/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionPointDefinitionGetter.java
  application/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionPointDefinitionGetterImpl.java
  application/src/test/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetterTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7108 chore: remove vue devtools
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/vite/config-builder.ts
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#7094 fix: optional plugin dependencies not working correctly
  application/src/main/java/run/halo/app/core/reconciler/PluginReconciler.java
  application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
  application/src/main/java/run/halo/app/plugin/OptionalDependentResolver.java
  application/src/main/java/run/halo/app/plugin/PluginApplicationContext.java
  application/src/main/java/run/halo/app/plugin/PluginService.java
  application/src/main/java/run/halo/app/plugin/PluginServiceImpl.java
  application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
  application/src/test/java/run/halo/app/core/reconciler/PluginReconcilerTest.java
  application/src/test/java/run/halo/app/plugin/OptionalDependentResolverTest.java
  application/src/test/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetterTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#7103 feat: add system info getter for plugin
  api/src/main/java/run/halo/app/infra/SystemInfo.java
  api/src/main/java/run/halo/app/infra/SystemInfoGetter.java
  application/src/main/java/run/halo/app/infra/SystemInfoGetterImpl.java
  application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
Labels: lgtm, area/core, approved, release-note, sig/docs, kind/improvement

#7114 Fix failing checks of staging repository when releasing to Maven
  api/build.gradle
  buildSrc/src/main/groovy/halo.publish.gradle
  platform/application/build.gradle
  platform/plugin/build.gradle
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#7092 refactor: replace md5 with sha256 for commenter email hash
  application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
  application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceIntegrationTest.java
Labels: kind/feature, lgtm, approved, release-note, kind/improvement

#7128 chore: inject Object.hasOwn polyfill for Console and UC
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/vite/config-builder.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#7127 feat: support display HTML format in API error responses
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/components/upload/UppyUpload.vue
  ui/src/setup/setupApiClient.ts
  ui/src/utils/modal.ts
Labels: kind/feature, lgtm, approved, release-note, area/ui

#7123 chore: bump vite version to 6.0.3
  ui/package.json
  ui/packages/components/vite.config.ts
  ui/packages/editor/src/styles/index.scss
  ui/packages/editor/vite.lib.config.ts
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7142 refactor: optimize axios interceptor text/html content type detection
  ui/src/setup/setupApiClient.ts
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7122 fix: prevent data clearing on FormKit component unmount
  ui/console-src/modules/interface/themes/ThemeSetting.vue
  ui/console-src/modules/system/plugins/components/tabs/Setting.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui
