Repository halo-dev/halo, pull requests merged in 2024-09, with the labels that each got.

#6564 refactor: add warning alert for H2 database on data initialization page
  ui/console-src/views/system/Setup.vue
  ui/console-src/views/system/SetupInitialData.vue
  ui/src/components/alerts/H2WarningAlert.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6563 refactor: change scalingMethod parameter to automatic for thumbnail generation
  application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6566 fix: solving the issue of the default editor format brush being incorectly filtered
  ui/packages/editor/src/extensions/clear-format/index.ts
  ui/packages/editor/src/extensions/format-brush/index.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor

#6571 fix: formkit selector not listening to data after defaulting to first option
  ui/src/formkit/inputs/select/SelectMain.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6570 Fix the problem that Lucene lock is held by VM
  application/src/main/java/run/halo/app/search/lucene/LuceneSearchEngine.java
  application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6582 refactor: preserve original image if smaller than requested thumbnail size
  application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6587 fix: resolve error when adding tables in default editor
  ui/src/components/editor/composables/use-extension.ts
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6590 docs: add documentation for formkit select allowCreate property
  ui/docs/custom-formkit-input/README.md
Labels: lgtm, release-note-none, area/docs, approved, kind/documentation

#6591 pref: add parameter to formkit select component for remote search by specific field
  ui/docs/custom-formkit-input/README.md
  ui/src/formkit/inputs/select/SelectMain.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6595 fix: resolve issue with disabled property in options not working
  ui/src/formkit/inputs/select/SelectMain.vue
  ui/src/formkit/inputs/select/SelectOption.vue
  ui/src/formkit/inputs/select/isFalse.ts
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6597 fix: skip thumbnail generation for GIF images
  application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6602 fix: formkit select component not emitting event or updating selection on value change
  ui/src/formkit/inputs/select/SelectContainer.vue
  ui/src/formkit/inputs/select/SelectMain.vue
  ui/src/formkit/inputs/select/isFalse.ts
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6610 [release-2.19] fix: formkit select component not emitting event or updating selection on value change
  ui/src/formkit/inputs/select/SelectContainer.vue
  ui/src/formkit/inputs/select/SelectMain.vue
  ui/src/formkit/inputs/select/isFalse.ts
Labels: lgtm, approved, release-note

#6612 Prevent null role while getting permissions
  application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6629 fix: resolve incorrect display of options in formkit selector with async data
  ui/src/formkit/inputs/select/SelectDropdownContainer.vue
  ui/src/formkit/inputs/select/SelectMain.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6631 [release-2.19] fix: resolve incorrect display of options in formkit selector with async data
  ui/src/formkit/inputs/select/SelectDropdownContainer.vue
  ui/src/formkit/inputs/select/SelectMain.vue
Labels: lgtm, approved, release-note

#6628 refactor: optimize request headers when generating thumbnails from URI
  application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java
  application/src/main/java/run/halo/app/core/attachment/reconciler/AttachmentReconciler.java
  application/src/main/java/run/halo/app/core/attachment/reconciler/LocalThumbnailsReconciler.java
  application/src/test/java/run/halo/app/core/attachment/ThumbnailGeneratorTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6638 Expose CryptoService and RateLimiterRegistry to plugins
  api/src/main/java/run/halo/app/security/authentication/CryptoService.java
  application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
Labels: kind/feature, lgtm, area/core, approved, release-note, sig/docs, area/plugin

#6641 Update attachment permalink only when handler is available
  application/src/main/java/run/halo/app/core/attachment/reconciler/AttachmentReconciler.java
Labels: lgtm, area/core, approved, release-note, kind/improvement, area/plugin

#6642 feat: add menu select form item
  ui/docs/custom-formkit-input/README.md
  ui/src/formkit/formkit.config.ts
  ui/src/formkit/inputs/menu-select.ts
Labels: kind/feature, lgtm, approved, release-note, sig/docs, area/ui

#6647 Fix the problem of resolving locale context by language parameter
  application/src/main/java/run/halo/app/theme/ThemeLocaleContextResolver.java
  application/src/test/java/run/halo/app/theme/ThemeLocaleContextResolverTest.java
Labels: kind/bug, lgtm, approved, area/theme, release-note

#6639 Trigger attachment status update on storage policy config change
  api/src/main/java/run/halo/app/core/extension/attachment/Policy.java
  application/src/main/java/run/halo/app/core/attachment/PolicyConfigChangeDetector.java
  application/src/main/java/run/halo/app/core/attachment/reconciler/PolicyReconciler.java
  application/src/main/resources/extensions/attachment-local-policy.yaml
  application/src/test/java/run/halo/app/core/attachment/PolicyConfigChangeDetectorTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6622 refactor: prevent replies to comments that are pending approval
  application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  application/src/main/java/run/halo/app/infra/exception/RequestRestrictedException.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6607 pref: improve hover and pre-selection state for formkit select
  ui/src/formkit/inputs/select/SelectOption.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6651 Simplify ThemeLocaleContextResolver
  application/src/main/java/run/halo/app/theme/ThemeLocaleContextResolver.java
  application/src/test/java/run/halo/app/theme/ThemeLocaleContextResolverTest.java
Labels: lgtm, release-note-none, approved, area/theme, kind/improvement

#6656 fix: correct ordered list styling issue in editor
  ui/packages/editor/src/styles/base.scss
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6658 Support changing locale using query language
  application/src/main/java/run/halo/app/webfilter/LocaleChangeWebFilter.java
  application/src/test/java/run/halo/app/webfilter/LocaleChangeWebFilterTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6648 Support resolving i18n message with standard way
  application/src/main/java/run/halo/app/theme/message/ThemeMessageResolver.java
  application/src/test/java/run/halo/app/theme/message/ThemeMessageResolutionUtilsTest.java
  application/src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java
  application/src/test/resources/themes/default/i18n/default.properties
  application/src/test/resources/themes/default/i18n/zh.properties
  application/src/test/resources/themes/default/templates/index.html
  application/src/test/resources/themes/default/templates/index.properties
  application/src/test/resources/themes/default/templates/index_zh.properties
Labels: kind/feature, lgtm, approved, area/theme, release-note, sig/docs

#6660 refactor: remove trailing slash in site url for notification
  application/src/main/java/run/halo/app/notification/DefaultNotificationTemplateRender.java
  application/src/test/java/run/halo/app/notification/DefaultNotificationTemplateRenderTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6671 chore: cleanup subscription integration test
  application/src/test/java/run/halo/app/notification/SubscriptionServiceIntegrationTest.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6573 Generate JS and CSS bundle with fixed buffer size
  application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6670 Provide ElementTagProcessor to handle element tag in plugin
  api/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionGetter.java
  api/src/main/java/run/halo/app/theme/dialect/ElementTagPostProcessor.java
  application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
  application/src/main/java/run/halo/app/theme/dialect/HaloPostTemplateHandler.java
  application/src/main/java/run/halo/app/theme/dialect/HaloProcessorDialect.java
  application/src/test/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetterTest.java
  application/src/test/java/run/halo/app/theme/ReactiveFinderExpressionParserTests.java
  application/src/test/java/run/halo/app/theme/dialect/CommentElementTagProcessorTest.java
  application/src/test/java/run/halo/app/theme/dialect/HaloPostTemplateHandlerTest.java
Labels: kind/feature, lgtm, approved, release-note, area/plugin

#6677 feat: add Halo version variable to theme model
  application/src/main/java/run/halo/app/theme/SiteSettingVariablesAcquirer.java
  application/src/main/java/run/halo/app/theme/finders/vo/SiteSettingVo.java
  application/src/test/java/run/halo/app/theme/SiteSettingVariablesAcquirerTest.java
Labels: kind/feature, lgtm, approved, area/theme, release-note, sig/docs

#6678 chore: replace deprecated Version methods with updated API
  application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
  application/src/main/java/run/halo/app/infra/DefaultSystemVersionSupplier.java
  application/src/main/java/run/halo/app/infra/utils/VersionUtils.java
  application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
  application/src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java
  application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
  application/src/test/java/run/halo/app/core/extension/theme/ThemeServiceImplTest.java
  application/src/test/java/run/halo/app/infra/DefaultSystemVersionSupplierTest.java
Labels: lgtm, release-note-none, area/core, approved

#6580 Add chunked transfer support for rendering templates
  application/src/main/java/run/halo/app/theme/HaloViewResolver.java
  application/src/main/java/run/halo/app/theme/engine/HaloTemplateEngine.java
  application/src/main/resources/application.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6680 Make ApplicationContext inaccessible in ITemplateContext
  application/src/main/java/run/halo/app/theme/dialect/CommentElementTagProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/HaloPostTemplateHandler.java
  application/src/main/java/run/halo/app/theme/dialect/SecureTemplateContext.java
  application/src/main/java/run/halo/app/theme/dialect/TemplateFooterElementTagProcessor.java
  application/src/test/java/run/halo/app/theme/dialect/HaloPostTemplateHandlerTest.java
Labels: lgtm, release-note-none, area/core, kind/api-change, approved, kind/improvement, area/plugin

#6679 Make ApplicationContext inaccessible in ServerWebExchange
  application/src/main/java/run/halo/app/config/WebFluxConfig.java
  application/src/main/java/run/halo/app/infra/SecureRequestMappingHandlerAdapter.java
  application/src/main/java/run/halo/app/infra/SecureServerRequest.java
  application/src/main/java/run/halo/app/infra/SecureServerWebExchange.java
  application/src/main/java/run/halo/app/plugin/AggregatedRouterFunction.java
  application/src/main/java/run/halo/app/plugin/DefaultPluginRouterFunctionRegistry.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement, area/plugin

#6686 Refactor ReactivePropertyAccessor by wrapping existing PropertyAccessor
  application/src/main/java/run/halo/app/infra/utils/ReactiveUtils.java
  application/src/main/java/run/halo/app/theme/ReactivePropertyAccessor.java
  application/src/main/java/run/halo/app/theme/ReactiveSpelVariableExpressionEvaluator.java
  application/src/main/java/run/halo/app/theme/dialect/EvaluationContextEnhancer.java
  application/src/main/java/run/halo/app/theme/dialect/HaloProcessorDialect.java
  application/src/main/java/run/halo/app/theme/dialect/JsonNodePropertyAccessorBoundariesProcessor.java
  application/src/test/java/run/halo/app/theme/ReactiveFinderExpressionParserTests.java
Labels: lgtm, release-note-none, area/core, approved, area/theme, kind/improvement

#6695 chore: remove unused code related to system configMap
  ui/console-src/main.ts
  ui/console-src/modules/system/settings/tabs/Setting.vue
  ui/console-src/stores/system-configmap.ts
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#6687 Upgrade to Spring Boot 3.4.0-M3
  application/src/main/java/run/halo/app/theme/dialect/EvaluationContextEnhancer.java
  application/src/test/java/run/halo/app/config/ExtensionConfigurationTest.java
  application/src/test/java/run/halo/app/config/WebFluxConfigTest.java
  application/src/test/java/run/halo/app/content/CategoryPostCountUpdaterTest.java
  application/src/test/java/run/halo/app/content/PostIntegrationTests.java
  application/src/test/java/run/halo/app/content/comment/CommentServiceImplIntegrationTest.java
  application/src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
  application/src/test/java/run/halo/app/content/comment/ReplyServiceImplIntegrationTest.java
  application/src/test/java/run/halo/app/core/endpoint/console/EmailVerificationCodeTest.java
  application/src/test/java/run/halo/app/core/endpoint/console/UserEndpointIntegrationTest.java
  application/src/test/java/run/halo/app/plugin/DefaultPluginApplicationContextFactoryTest.java
  application/src/test/java/run/halo/app/plugin/DefaultSettingFetcherTest.java
  application/src/test/java/run/halo/app/security/AuthProviderServiceImplTest.java
  application/src/test/java/run/halo/app/security/SuperAdminInitializerTest.java
  application/src/test/java/run/halo/app/security/authorization/AuthorizationTest.java
  application/src/test/java/run/halo/app/theme/ThemeIntegrationTest.java
  application/src/test/java/run/halo/app/theme/ViewNameResolverTest.java
  application/src/test/java/run/halo/app/theme/dialect/GeneratorMetaProcessorTest.java
  application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImplTest.java
  application/src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java
  application/src/test/java/run/halo/app/theme/router/PreviewRouterFunctionTest.java
  build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#6673 fix: correct file mime type validation parameter to restore functionality
  application/src/main/java/run/halo/app/core/attachment/endpoint/LocalAttachmentUploadHandler.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6696 chore: bump vue version to 3.5
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  ui/console-src/modules/interface/themes/components/preview/ThemePreviewModal.vue
  ui/console-src/modules/system/users/components/UserPasswordChangeModal.vue
  ui/console-src/views/system/Setup.vue
  ui/package.json
  ui/packages/api-client/package.json
  ui/packages/components/package.json
  ui/packages/components/src/components/dialog/Dialog.stories.ts
  ui/packages/components/src/components/dropdown/Draopdown.stories.ts
  ui/packages/components/src/components/dropdown/Dropdown.vue
  ui/packages/components/src/components/dropdown/DropdownItem.vue
  ui/packages/components/tsconfig.app.json
  ui/packages/editor/package.json
  ui/packages/shared/package.json
  ui/pnpm-lock.yaml
  ui/src/components/image/LazyImage.vue
  ui/src/components/video/LazyVideo.vue
  ui/tsconfig.app.json
  ui/uc-src/modules/contents/posts/components/PostSettingForm.vue
  ui/uc-src/modules/profile/components/PasswordChangeModal.vue
  ui/uc-src/modules/profile/components/PersonalAccessTokenCreationModal.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6705 Support obtaining ServerWebExchange in ContextView
  application/src/main/java/run/halo/app/infra/config/WebFluxConfig.java
  application/src/test/java/run/halo/app/config/WebFluxConfigTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#6704 refactor: unified empty state UI action button styles
  ui/console-src/modules/contents/comments/CommentList.vue
  ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
  ui/console-src/modules/contents/pages/SinglePageList.vue
  ui/console-src/modules/contents/posts/DeletedPostList.vue
  ui/console-src/modules/contents/posts/PostList.vue
  ui/console-src/modules/contents/posts/categories/CategoryList.vue
  ui/console-src/modules/contents/posts/tags/TagList.vue
  ui/console-src/modules/interface/menus/Menus.vue
  ui/console-src/modules/interface/menus/components/MenuList.vue
  ui/console-src/modules/interface/themes/components/list-tabs/InstalledThemes.vue
  ui/console-src/modules/interface/themes/components/list-tabs/NotInstalledThemes.vue
  ui/console-src/modules/interface/themes/layouts/ThemeLayout.vue
  ui/uc-src/modules/contents/posts/PostList.vue
  ui/uc-src/modules/profile/tabs/PersonalAccessTokens.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6708 refactor: simplify page title of deleted page
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6707 refactor: remove async loading logic for editor
  ui/src/components/editor/utils/upload.ts
  ui/src/composables/use-editor-extension-points.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6661 feat: support JSON-based retrieval and update for theme and plugin configs
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  application/src/main/java/run/halo/app/core/endpoint/console/PluginEndpoint.java
  application/src/main/java/run/halo/app/core/user/service/SettingConfigService.java
  application/src/main/java/run/halo/app/core/user/service/impl/SettingConfigServiceImpl.java
  application/src/main/java/run/halo/app/infra/utils/SettingUtils.java
  application/src/main/java/run/halo/app/theme/endpoint/ThemeEndpoint.java
  application/src/main/resources/extensions/role-template-plugin.yaml
  application/src/main/resources/extensions/role-template-theme.yaml
  application/src/test/java/run/halo/app/core/endpoint/console/PluginEndpointTest.java
  application/src/test/java/run/halo/app/theme/endpoint/ThemeEndpointTest.java
  ui/console-src/modules/interface/themes/ThemeSetting.vue
  ui/console-src/modules/system/plugins/components/tabs/Setting.vue
  ui/packages/api-client/src/api/plugin-v1alpha1-console-api.ts
  ui/packages/api-client/src/api/theme-v1alpha1-console-api.ts
Labels: lgtm, area/core, kind/api-change, approved, release-note, kind/improvement

#6712 refactor: remove login-related pages from UI project
  ui/console-src/layouts/BasicLayout.vue
  ui/console-src/router/guards/auth-check.ts
  ui/console-src/router/guards/check-states.ts
  ui/console-src/router/guards/permission.ts
  ui/console-src/router/routes.config.ts
  ui/console-src/views/system/Binding.vue
  ui/console-src/views/system/Login.vue
  ui/console-src/views/system/Redirect.vue
  ui/console-src/views/system/ResetPassword.vue
  ui/src/components/login/LoginForm.vue
  ui/src/components/login/LoginModal.vue
  ui/src/components/login/MfaForm.vue
  ui/src/components/login/SocialAuthProviderItem.vue
  ui/src/components/login/SocialAuthProviders.vue
  ui/src/components/signup/SignupForm.vue
  ui/src/layouts/GatewayLayout.vue
  ui/src/locales/en.yaml
  ui/src/locales/es.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/src/setup/setupApiClient.ts
  ui/src/stores/user.ts
  ui/uc-src/layouts/BasicLayout.vue
  ui/uc-src/router/routes.config.ts
  ui/uc-src/views/ResetPassword.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6688 fix: resolve 403 error on menu page when system config access is missing
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  application/src/main/java/run/halo/app/core/endpoint/SystemConfigEndpoint.java
  application/src/main/resources/extensions/role-template-menu.yaml
  ui/console-src/modules/interface/menus/components/MenuList.vue
  ui/packages/api-client/entry/api-client.ts
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api.ts
  ui/packages/api-client/src/api/system-config-v1alpha1-console-api.ts
Labels: kind/feature, lgtm, tide/merge-method-merge, area/core, approved, release-note

#6693 fix: resolve issue with editor not detecting image paste in Firefox
  ui/src/components/editor/extensions/upload/index.ts
  ui/src/components/editor/utils/upload.ts
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6694 fix: resolve issue with underline not displaying in input field
  ui/src/formkit/theme.ts
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6698 fix: thumbnail generation for URI string containing spaces
  application/src/main/java/run/halo/app/theme/finders/impl/ThumbnailFinderImpl.java
  application/src/test/java/run/halo/app/theme/finders/impl/ThumbnailFinderImplTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6699 chore: reorganize package structure for content stats updater
  application/src/main/java/run/halo/app/content/comment/AbstractCommentService.java
  application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  application/src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
  application/src/main/java/run/halo/app/content/stats/PostStatsUpdater.java
  application/src/main/java/run/halo/app/content/stats/ReplyEventReconciler.java
  application/src/main/java/run/halo/app/content/stats/TagPostCountUpdater.java
  application/src/main/java/run/halo/app/content/stats/VisitedEventReconciler.java
  application/src/main/java/run/halo/app/content/stats/VotedEventReconciler.java
  application/src/main/java/run/halo/app/core/counter/CounterService.java
  application/src/main/java/run/halo/app/core/counter/CounterServiceImpl.java
  application/src/main/java/run/halo/app/core/counter/MeterUtils.java
  application/src/main/java/run/halo/app/core/reconciler/CommentReconciler.java
  application/src/main/java/run/halo/app/core/reconciler/PostCounterReconciler.java
  application/src/main/java/run/halo/app/core/reconciler/PostReconciler.java
  application/src/main/java/run/halo/app/core/reconciler/SinglePageReconciler.java
  application/src/main/java/run/halo/app/event/post/PostStatsChangedEvent.java
  application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/PostPublicQueryServiceImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/SinglePageConversionServiceImpl.java
  application/src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
  application/src/test/java/run/halo/app/core/counter/MeterUtilsTest.java
  application/src/test/java/run/halo/app/core/reconciler/SinglePageReconcilerTest.java
  application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImplTest.java
  application/src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java
Labels: lgtm, release-note-none, area/core, approved

#6727 feat: remove the button for viewing passwords in the Edge browser
  application/src/main/resources/static/styles/main.css
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6728 chore: regenerate api client for login-related
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_extension.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_public.api_v1alpha1.json
  ui/packages/api-client/entry/api-client.ts
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api.ts
  ui/packages/api-client/src/api/login-api.ts
  ui/packages/api-client/src/api/user-v1alpha1-public-api.ts
  ui/packages/api-client/src/models/auth-provider-spec.ts
  ui/packages/api-client/src/models/index.ts
  ui/packages/api-client/src/models/password-reset-email-request.ts
  ui/packages/api-client/src/models/public-key-response.ts
  ui/packages/api-client/src/models/register-verify-email-request.ts
  ui/packages/api-client/src/models/reset-password-request.ts
  ui/packages/api-client/src/models/sign-up-request.ts
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6726 feat: refine i18n resources for login-related page
  application/src/main/resources/static/js/main.js
  application/src/main/resources/templates/challenges/two-factor/totp.properties
  application/src/main/resources/templates/challenges/two-factor/totp_es.properties
  application/src/main/resources/templates/challenges/two-factor/totp_zh_TW.properties
  application/src/main/resources/templates/gateway_modules/common_fragments.html
  application/src/main/resources/templates/gateway_modules/common_fragments.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_en.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_es.properties
  application/src/main/resources/templates/gateway_modules/common_fragments_zh_TW.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_en.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_es.properties
  application/src/main/resources/templates/gateway_modules/login_fragments_zh_TW.properties
  application/src/main/resources/templates/login_es.properties
  application/src/main/resources/templates/login_local_es.properties
  application/src/main/resources/templates/login_local_zh_TW.properties
  application/src/main/resources/templates/login_zh_TW.properties
  application/src/main/resources/templates/logout_es.properties
  application/src/main/resources/templates/logout_zh_TW.properties
  application/src/main/resources/templates/password-reset-link.html
  application/src/main/resources/templates/password-reset-link_es.properties
  application/src/main/resources/templates/password-reset-link_zh_TW.properties
  application/src/main/resources/templates/password-reset.html
  application/src/main/resources/templates/password-reset_es.properties
  application/src/main/resources/templates/password-reset_zh_TW.properties
  application/src/main/resources/templates/signup.html
  application/src/main/resources/templates/signup.properties
  application/src/main/resources/templates/signup_en.properties
  application/src/main/resources/templates/signup_es.properties
  application/src/main/resources/templates/signup_zh_TW.properties
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6730 Fix the inaccessible problem of signup page
  application/src/main/java/run/halo/app/core/user/service/SignUpData.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthSignUpEndpoint.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/main/resources/templates/signup.html
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6689 feat: add config option to allow disabling Basic authentication
  application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java
  application/src/main/resources/application-dev.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6737 feat: add support for setting uniqueId in Dialog to prevent duplicate creation
  ui/packages/components/src/components/dialog/Dialog.stories.ts
  ui/packages/components/src/components/dialog/Dialog.vue
  ui/packages/components/src/components/dialog/dialog-manager.ts
  ui/packages/components/src/components/dialog/interface.ts
  ui/packages/components/src/components/modal/Modal.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6734 Support unbinding OAuth2User from Halo side
  api/src/main/java/run/halo/app/event/user/UserConnectionDisconnectedEvent.java
  application/src/main/java/run/halo/app/core/endpoint/uc/UserConnectionEndpoint.java
  application/src/main/java/run/halo/app/core/user/service/UserConnectionService.java
  application/src/main/java/run/halo/app/core/user/service/impl/UserConnectionServiceImpl.java
  application/src/main/resources/extensions/role-template-authenticated.yaml
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#6736 Support redirecting to page according to query after authenticated
  application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
  application/src/main/java/run/halo/app/security/DefaultServerAuthenticationEntryPoint.java
  application/src/main/java/run/halo/app/security/ExceptionSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/HaloServerRequestCache.java
  application/src/main/java/run/halo/app/security/authentication/twofactor/TotpAuthenticationSuccessHandler.java
  application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthenticationEntryPoint.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthLoginEndpoint.java
  application/src/test/java/run/halo/app/security/DefaultServerAuthenticationEntryPointTest.java
  application/src/test/java/run/halo/app/security/HaloServerRequestCacheTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6738 feat: add login expiration notification
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/src/setup/setupApiClient.ts
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui
