Repository halo-dev/halo, pull requests merged in 2024-02, with the labels that each got.

#5299 Prepare for 2.13.0 development
  README.md
  console/packages/api-client/package.json
  console/packages/components/package.json
  console/packages/editor/package.json
  console/packages/shared/package.json
  console/packages/ui-plugin-bundler-kit/package.json
  gradle.properties
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#5304 Support building Docker image with major version tag
  .github/actions/docker-buildx-push/action.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#5311 Compatible with negative page number and size
  api/src/main/java/run/halo/app/extension/PageRequestImpl.java
  api/src/test/java/run/halo/app/extension/PageRequestImplTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#5323 fix: failure in data query due to reconciler triggered by uncommitted transaction
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  application/src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#5325 fix: possible incorrect result set obtained by Gc synchronizer when sartup
  application/src/main/java/run/halo/app/extension/gc/GcSynchronizer.java
  application/src/main/java/run/halo/app/extension/index/IndexedQueryEngineImpl.java
Labels: kind/bug, lgtm, area/core, approved

#5332 chore: remove unnecessary indices build process for lucene on startup
  application/src/main/java/run/halo/app/search/IndicesInitializer.java
Labels: lgtm, area/core, kind/cleanup, approved

#5340 Bump actions' versions for muting warning from GitHub workflow
  .github/actions/docker-buildx-push/action.yaml
  .github/actions/setup-env/action.yaml
  .github/workflows/halo.yaml
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#5341 Upgrade Halo runtime environment to JRE 21
  Dockerfile
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5347 chore: rename console to ui in some files
  .dockerignore
  ui/package.json
  ui/packages/api-client/package.json
  ui/packages/components/package.json
  ui/packages/editor/package.json
  ui/packages/shared/package.json
  ui/packages/ui-plugin-bundler-kit/package.json
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#5353 Improve traditional Chinese translation
  ui/src/locales/zh-TW.yaml
Labels: lgtm, release-note-none, approved, kind/improvement

#5359 docs: update the branch name from `master` to `main` in contribution.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#5349 Refactor AdditionalWebFilter load
  application/src/main/java/run/halo/app/config/WebFluxConfig.java
  application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/security/DynamicMatcherSecurityWebFilterChain.java
  application/src/main/java/run/halo/app/webfilter/AdditionalWebFilterChainProxy.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#5364 Bump pnpm/action-setup version to 3.0.0
  .github/actions/setup-env/action.yaml
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#5348 Move username-password authentication into security filter chain
  application/src/main/java/run/halo/app/security/authentication/login/LoginSecurityConfigurer.java
  application/src/main/resources/extensions/extension-definitions.yaml
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#5369 fix: fail to fetch correct user avatar
  ui/src/components/user-avatar/UserAvatar.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#5370 fix: fix the error when saving settings for posts in the uc
  ui/uc-src/modules/contents/posts/PostEditor.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#5374 Keep length of PAT stable
  application/src/main/java/run/halo/app/security/authentication/jwt/JwtScopesAndRolesGrantedAuthoritiesConverter.java
  application/src/main/java/run/halo/app/security/authentication/pat/PatAuthenticationManager.java
  application/src/main/java/run/halo/app/security/authentication/pat/impl/UserScopedPatHandlerImpl.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5363 refactor: optimize old attachment query parameters using index
  api/src/main/java/run/halo/app/extension/index/query/Not.java
  api/src/main/java/run/halo/app/extension/index/query/QueryFactory.java
  api/src/test/java/run/halo/app/extension/index/query/QueryFactoryTest.java
  application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/test/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpointTest.java
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentGroupList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  ui/console-src/modules/contents/attachments/composables/use-attachment.ts
  ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-attachment-api.ts
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5376 fix: refine error message of the plugin already exists
  application/src/main/resources/config/i18n/messages_zh.properties
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#5365 fix: resolve the issue of text editing not being effective before the table
  ui/packages/editor/src/extensions/table/index.ts
Labels: kind/bug, lgtm, approved, area/console, release-note, area/editor

#5382 chore: bump tiptap version to 2.2.3
  ui/package.json
  ui/packages/editor/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5383 chore: bump axios version to 1.6.x
  ui/package.json
  ui/packages/api-client/package.json
  ui/pnpm-lock.yaml
  ui/src/components/editor/utils/upload.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5384 chore: bump vue related packages version
  ui/package.json
  ui/packages/components/package.json
  ui/packages/components/src/components/modal/Modal.vue
  ui/packages/editor/package.json
  ui/packages/shared/package.json
  ui/pnpm-lock.yaml
  ui/tsconfig.app.json
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5392 refactor: add cache control for reverse proxy resources
  application/src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5400 Fix the problem of being unable to login when 2FA was enabled but TOTP was not configured
  application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSettings.java
  application/src/test/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSettingsTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#5402 Upgrade Spring Boot to 3.2.3
  application/build.gradle
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#5404 Fix the problem of updating plugin extensions incorrectly
  application/src/main/java/run/halo/app/plugin/PluginStartedListener.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved, area/plugin

#5302 pref: refactor default editor video block upload logic
  ui/packages/editor/src/extensions/video/index.ts
  ui/src/components/editor/DefaultEditor.vue
  ui/src/components/editor/components/EditorLinkObtain.vue
  ui/src/components/editor/components/index.ts
  ui/src/components/editor/extensions/image/ImageView.vue
  ui/src/components/editor/extensions/index.ts
  ui/src/components/editor/extensions/upload/index.ts
  ui/src/components/editor/extensions/video/VideoView.vue
  ui/src/components/editor/extensions/video/index.ts
  ui/src/components/editor/utils/upload.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, area/console, release-note, kind/improvement, area/editor

#5407 chore: update issue template
  .github/ISSUE_TEMPLATE/bug_report.en.yml
  .github/ISSUE_TEMPLATE/bug_report.zh.yml
Labels: lgtm, release-note-none, approved, kind/improvement

#5396 refactor: optimize user query using index
  api/src/main/java/run/halo/app/core/extension/User.java
  application/src/main/java/run/halo/app/core/extension/endpoint/StatsEndpoint.java
  application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  application/src/main/java/run/halo/app/infra/DefaultInitializationStateGetter.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
  application/src/test/java/run/halo/app/infra/InitializationStateGetterTest.java
  ui/console-src/modules/system/users/UserList.vue
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5312 refactor: only select the required index fields when build query index view
  api/src/main/java/run/halo/app/extension/index/query/LogicalQuery.java
  api/src/main/java/run/halo/app/extension/index/query/QueryFactory.java
  api/src/main/java/run/halo/app/extension/index/query/SimpleQuery.java
  api/src/test/java/run/halo/app/extension/index/query/QueryFactoryTest.java
  application/src/main/java/run/halo/app/extension/index/IndexedQueryEngineImpl.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5413 refactor: layout of login related page
  ui/console-src/layouts/GatewayLayout.vue
  ui/console-src/modules/system/users/Login.vue
  ui/console-src/modules/system/users/module.ts
  ui/console-src/router/routes.config.ts
  ui/console-src/views/system/Binding.vue
  ui/console-src/views/system/Login.vue
  ui/console-src/views/system/ResetPassword.vue
  ui/console-src/views/system/Setup.vue
  ui/uc-src/views/ResetPassword.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5361 Check dependencies while installing and upgrading plugins
  application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
  application/src/main/java/run/halo/app/infra/exception/PluginDependencyException.java
  application/src/main/java/run/halo/app/plugin/YamlPluginDescriptorFinder.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5414 refactor: optimize notification and subscription query using index
  api/src/test/java/run/halo/app/core/extension/notification/SubscriptionTest.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/notification/DefaultNotificationCenter.java
  application/src/main/java/run/halo/app/notification/DefaultNotificationService.java
  application/src/main/java/run/halo/app/notification/ReasonNotificationTemplateSelectorImpl.java
  application/src/main/java/run/halo/app/notification/UserNotificationQuery.java
  application/src/main/java/run/halo/app/notification/endpoint/UserNotificationEndpoint.java
  application/src/test/java/run/halo/app/notification/DefaultNotificationCenterTest.java
  application/src/test/java/run/halo/app/notification/ReasonNotificationTemplateSelectorImplTest.java
  ui/console-src/modules/system/users/widgets/NotificationWidget.vue
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api/api-halo-run-v1alpha1-user-api.ts
  ui/packages/api-client/src/api/api-notification-halo-run-v1alpha1-notification-api.ts
  ui/packages/api-client/src/base.ts
  ui/packages/api-client/src/configuration.ts
  ui/packages/api-client/src/models/sign-up-request.ts
  ui/uc-src/modules/notifications/Notifications.vue
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5395 chore: bump formkit version to 1.5.x
  ui/env.d.ts
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/formkit/inputs/attachment-group-select.ts
  ui/src/formkit/inputs/attachment-policy-select.ts
  ui/src/formkit/inputs/attachment/index.ts
  ui/src/formkit/inputs/category-checkbox.ts
  ui/src/formkit/inputs/category-select/index.ts
  ui/src/formkit/inputs/menu-checkbox.ts
  ui/src/formkit/inputs/menu-item-select.ts
  ui/src/formkit/inputs/menu-radio.ts
  ui/src/formkit/inputs/post-select.ts
  ui/src/formkit/inputs/repeater/index.ts
  ui/src/formkit/inputs/repeater/repeaterSection.ts
  ui/src/formkit/inputs/role-select.ts
  ui/src/formkit/inputs/singlePage-select.ts
  ui/src/formkit/inputs/tag-checkbox.ts
  ui/src/formkit/inputs/tag-select/index.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5423 chore: bump preset plugins version
  application/build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement
