Repository halo-dev/halo, pull requests merged in 2024-08, with the labels that each got.

#6390 feat: add file size and type restriction for local file uploads
  api/build.gradle
  api/src/main/java/run/halo/app/infra/FileCategoryMatcher.java
  api/src/main/java/run/halo/app/infra/utils/FileTypeDetectUtils.java
  application/src/main/java/run/halo/app/core/extension/attachment/endpoint/LocalAttachmentUploadHandler.java
  application/src/main/java/run/halo/app/infra/exception/FileSizeExceededException.java
  application/src/main/java/run/halo/app/infra/exception/FileTypeNotAllowedException.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/main/resources/extensions/attachment-local-policy.yaml
  application/src/test/java/run/halo/app/infra/utils/FileTypeDetectUtilsTest.java
  platform/application/build.gradle
Labels: kind/feature, lgtm, area/core, approved, release-note

#6427 chore: remove incorrect index declaration
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6441 chore: update afdian url
  .github/FUNDING.yml
  README.md
Labels: lgtm, release-note-none, kind/cleanup, approved

#6440 chore: bump typescript version to 5.5.x
  ui/package.json
  ui/packages/api-client/package.json
  ui/pnpm-lock.yaml
  ui/src/components/form/AnnotationsForm.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6438 feat: make comment and reply list item operations extendable
  ui/console-src/modules/contents/comments/components/CommentListItem.vue
  ui/console-src/modules/contents/comments/components/ReplyListItem.vue
  ui/docs/extension-points/entity-listitem-operation.md
  ui/packages/shared/src/types/plugin.ts
Labels: kind/feature, lgtm, approved, area/console, release-note

#6446 feat: support for previewing avif images in attachments
  ui/src/utils/image.ts
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6442 Support filtering search result by types, ownerNames, categoryNames and tagNames
  api/src/main/java/run/halo/app/search/SearchOption.java
  application/src/main/java/run/halo/app/search/lucene/LuceneSearchEngine.java
  application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineIntegrationTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6447 fix: saving settings in theme preview returns to homepage
  ui/console-src/modules/interface/themes/components/preview/ThemePreviewModal.vue
  ui/src/components/preview/UrlPreviewModal.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#6445 fix: backspace on empty line doesn’t return to previous list item
  ui/packages/editor/src/extensions/paragraph/index.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor

#6449 pref: pin save button to the bottom of the page in theme preview
  ui/console-src/modules/interface/themes/components/preview/ThemePreviewModal.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6457 chore: update github issue templates
  .github/ISSUE_TEMPLATE/bug_report.en.yml
  .github/ISSUE_TEMPLATE/bug_report.zh.yml
Labels: lgtm, release-note-none, approved

#6463 refactor: improve part of the page operation logic using the patch api
  ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
  ui/console-src/modules/contents/pages/SinglePageList.vue
  ui/console-src/modules/contents/pages/components/SinglePageListItem.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6453 feat: add full-screen support to code input
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/formkit/inputs/code/CodeInput.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6461 refactor: use patch api to refactor category drag-and-drop sorting feature
  ui/console-src/modules/contents/posts/categories/CategoryList.vue
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6464 refactor: improve part of the post operation logic using the patch api
  ui/console-src/modules/contents/posts/DeletedPostList.vue
  ui/console-src/modules/contents/posts/components/PostListItem.vue
  ui/console-src/modules/contents/posts/components/entity-fields/VisibleField.vue
Labels: lgtm, approved, kind/improvement, area/ui

#6470 feat: add prompt for users to reload page after plugin update
  application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
  ui/console-src/modules/system/plugins/components/PluginListItem.vue
  ui/console-src/modules/system/plugins/components/entity-fields/ReloadField.vue
  ui/console-src/setup/setupModules.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/setup/setupModules.ts
Labels: lgtm, tide/merge-method-merge, area/core, release-note, kind/improvement

#6462 refactor: use patch api to refactor menu drag-and-drop sorting feature
  ui/console-src/modules/interface/menus/Menus.vue
  ui/console-src/modules/interface/menus/components/MenuItemEditingModal.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6480 refactor: optimize user creation
  application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  application/src/main/java/run/halo/app/core/extension/service/UserService.java
  application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6482 chore: bump vite-related dependencies
  ui/package.json
  ui/packages/api-client/package.json
  ui/packages/components/package.json
  ui/packages/editor/package.json
  ui/packages/shared/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6481 chore: cleanup unused index for notification
  api-docs/openapi/v3_0/aggregated.json
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/notification/UserNotificationQuery.java
  ui/packages/api-client/src/api/notification-v1alpha1-uc-api.ts
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6471 Fix the problem that roles could not be granted sometimes
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api/src/main/java/run/halo/app/core/extension/RoleBinding.java
  api/src/main/java/run/halo/app/core/extension/User.java
  api/src/main/java/run/halo/app/extension/ExtensionUtil.java
  application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  application/src/main/java/run/halo/app/core/extension/reconciler/RoleBindingReconciler.java
  application/src/main/java/run/halo/app/core/extension/reconciler/UserReconciler.java
  application/src/main/java/run/halo/app/core/extension/service/DefaultRoleService.java
  application/src/main/java/run/halo/app/core/extension/service/RoleService.java
  application/src/main/java/run/halo/app/core/extension/service/UserService.java
  application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/security/DefaultUserDetailService.java
  application/src/main/java/run/halo/app/security/authorization/AuthorityUtils.java
  application/src/main/java/run/halo/app/security/authorization/DefaultRuleResolver.java
  application/src/test/java/run/halo/app/core/extension/RoleBindingTest.java
  application/src/test/java/run/halo/app/core/extension/endpoint/UserEndpointIntegrationTest.java
  application/src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
  application/src/test/java/run/halo/app/core/extension/reconciler/RoleBindingReconcilerTest.java
  application/src/test/java/run/halo/app/core/extension/reconciler/UserReconcilerTest.java
  application/src/test/java/run/halo/app/core/extension/service/DefaultRoleServiceTest.java
  application/src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java
  application/src/test/java/run/halo/app/security/DefaultUserDetailServiceTest.java
  application/src/test/java/run/halo/app/security/authorization/AuthorityUtilsTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note, kind/improvement

#6486 Add support for restoring from backup root
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  application/src/main/java/run/halo/app/migration/BackupFile.java
  application/src/main/java/run/halo/app/migration/MigrationEndpoint.java
  application/src/main/java/run/halo/app/migration/MigrationService.java
  application/src/main/java/run/halo/app/migration/impl/MigrationServiceImpl.java
  application/src/main/resources/extensions/role-template-migration.yaml
  application/src/test/java/run/halo/app/migration/impl/MigrationServiceImplTest.java
  ui/console-src/modules/system/backup/tabs/Restore.vue
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api/migration-v1alpha1-console-api.ts
  ui/packages/api-client/src/models/backup-file.ts
  ui/packages/api-client/src/models/index.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, tide/merge-method-merge, area/core, approved, area/console, release-note

#6491 fix: previous and next post links included hidden posts
  application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6492 chore: remove transactional annotation
  application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  application/src/main/java/run/halo/app/extension/store/ReactiveExtensionStoreClientImpl.java
  application/src/main/java/run/halo/app/migration/impl/MigrationServiceImpl.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6483 fix: correct device information update during account switch
  application/src/main/java/run/halo/app/security/device/DeviceServiceImpl.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6499 pref: use whitelist for allowed href values
  ui/packages/editor/src/extensions/link/index.ts
Labels: lgtm, approved, release-note, kind/improvement, area/editor

#6498 refactor: improve conditions for determining if a plugin needs to be reloaded
  ui/console-src/modules/system/plugins/components/entity-fields/ReloadField.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6503 chore: upgrade tiptap to 2.6.5
  ui/package.json
  ui/packages/editor/package.json
  ui/packages/editor/src/extensions/table/index.ts
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6506 fix: correct API endpoints related to backup issues
  ui/console-src/modules/system/backup/components/BackupListItem.vue
  ui/console-src/modules/system/backup/tabs/Restore.vue
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6505 feat: add filter options for attachment selector component
  ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  ui/console-src/modules/contents/attachments/components/selector-providers/components/AttachmentSelectorListItem.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6504 feat: support changing attachment display name
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentDetailModal.vue
  ui/console-src/modules/contents/attachments/components/DisplayNameEditForm.vue
  ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6502 feat: add H2 database usage warning to setup page
  ui/console-src/modules/system/overview/Overview.vue
  ui/console-src/router/routes.config.ts
  ui/console-src/views/system/Setup.vue
  ui/src/components/alerts/H2WarningAlert.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6511 Respond not found if no theme template found
  application/build.gradle
  application/src/main/java/run/halo/app/theme/CompositeTemplateResolver.java
  application/src/main/java/run/halo/app/theme/HaloViewResolver.java
  application/src/main/java/run/halo/app/theme/TemplateEngineManager.java
  application/src/test/java/run/halo/app/theme/CompositeTemplateResolverTest.java
  application/src/test/java/run/halo/app/theme/ThemeIntegrationTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6512 Upgrade Spring Boot to 3.3.3
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6428 refactor: editor code block to be extensible by plugins
  ui/packages/editor/package.json
  ui/packages/editor/src/dev/App.vue
  ui/packages/editor/src/extensions/code-block/CodeBlockSelect.vue
  ui/packages/editor/src/extensions/code-block/CodeBlockViewRenderer.vue
  ui/packages/editor/src/extensions/code-block/code-block.ts
  ui/packages/editor/src/extensions/code-block/index.ts
  ui/packages/editor/src/extensions/code-block/lowlight.ts
  ui/packages/editor/src/extensions/index.ts
  ui/packages/editor/src/index.ts
  ui/packages/editor/src/styles/base.scss
  ui/pnpm-lock.yaml
  ui/src/components/editor/DefaultEditor.vue
  ui/src/components/editor/composables/use-extension.ts
Labels: lgtm, approved, release-note, kind/improvement, area/editor, area/ui

#6364 feat: API to save external links as attachments
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
  api/src/main/java/run/halo/app/core/extension/service/AttachmentService.java
  application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
  application/src/main/java/run/halo/app/core/extension/service/impl/DefaultAttachmentService.java
  application/src/main/java/run/halo/app/endpoint/uc/content/UcPostAttachmentEndpoint.java
  application/src/main/java/run/halo/app/infra/DefaultReactiveUrlDataBufferFetcher.java
  application/src/main/java/run/halo/app/infra/ReactiveUrlDataBufferFetcher.java
  application/src/main/java/run/halo/app/infra/utils/FileNameUtils.java
  application/src/main/resources/extensions/role-template-attachment.yaml
  application/src/main/resources/extensions/role-template-uc-content.yaml
  application/src/test/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpointTest.java
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api/attachment-v1alpha1-console-api.ts
  ui/packages/api-client/src/api/attachment-v1alpha1-uc-api.ts
  ui/packages/api-client/src/models/index.ts
  ui/packages/api-client/src/models/upload-from-url-request.ts
Labels: kind/feature, lgtm, area/core, kind/api-change, approved, release-note

#6515 Fix "Missing exception attribute in ServerWebExchange" error after upgrading Spring Boot 3.3.3
  application/src/main/java/run/halo/app/infra/exception/handlers/ProblemDetailErrorAttributes.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6514 chore: update Halo official website URL
  application/src/main/resources/extensions/authproviders.yaml
  ui/README.md
  ui/packages/components/src/components/avatar/Avatar.stories.ts
  ui/packages/components/src/components/modal/Modal.stories.ts
  ui/src/components/common/AppDownloadAlert.vue
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6516 chore: update default theme version to 1.9.0
  application/src/main/resources/themes/theme-earth.zip
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#6517 chore: bump preset plugins version
  application/build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6473 refactor: enhance formkit select component to support additional features
  ui/docs/custom-formkit-input/README.md
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/formkit/formkit.config.ts
  ui/src/formkit/inputs/attachment-group-select.ts
  ui/src/formkit/inputs/attachment-policy-select.ts
  ui/src/formkit/inputs/menu-item-select.ts
  ui/src/formkit/inputs/post-select.ts
  ui/src/formkit/inputs/role-select.ts
  ui/src/formkit/inputs/select/MultipleOverflow.vue
  ui/src/formkit/inputs/select/MultipleOverflowItem.vue
  ui/src/formkit/inputs/select/MultipleSelect.vue
  ui/src/formkit/inputs/select/MultipleSelectItem.vue
  ui/src/formkit/inputs/select/MultipleSelectSearchInput.vue
  ui/src/formkit/inputs/select/MultipleSelectSelector.vue
  ui/src/formkit/inputs/select/SelectContainer.vue
  ui/src/formkit/inputs/select/SelectDropdownContainer.vue
  ui/src/formkit/inputs/select/SelectMain.vue
  ui/src/formkit/inputs/select/SelectOption.vue
  ui/src/formkit/inputs/select/SelectOptionItem.vue
  ui/src/formkit/inputs/select/SelectSearchInput.vue
  ui/src/formkit/inputs/select/SelectSelector.vue
  ui/src/formkit/inputs/select/index.ts
  ui/src/formkit/inputs/select/sections/index.ts
  ui/src/formkit/inputs/singlePage-select.ts
  ui/src/formkit/inputs/user-select.ts
  ui/src/formkit/theme.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6507 refactor: add post-index build validation to ensure data count matches index
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  application/src/main/java/run/halo/app/extension/index/DefaultExtensionIterator.java
  application/src/main/java/run/halo/app/extension/index/ExtensionIterator.java
  application/src/main/java/run/halo/app/extension/store/ReactiveExtensionStoreClient.java
  application/src/main/java/run/halo/app/extension/store/ReactiveExtensionStoreClientImpl.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6454 feat: implement new mechanisms for generating and managing attachment thumbnails
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_extension.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
  api/build.gradle
  api/src/main/java/run/halo/app/core/attachment/ThumbnailProvider.java
  api/src/main/java/run/halo/app/core/attachment/ThumbnailSize.java
  api/src/main/java/run/halo/app/core/extension/attachment/Attachment.java
  application/src/main/java/run/halo/app/content/HtmlThumbnailSrcsetInjector.java
  application/src/main/java/run/halo/app/content/PostContentThumbnailHandler.java
  application/src/main/java/run/halo/app/core/attachment/AttachmentRootGetter.java
  application/src/main/java/run/halo/app/core/attachment/AttachmentUtils.java
  application/src/main/java/run/halo/app/core/attachment/LocalThumbnailProvider.java
  application/src/main/java/run/halo/app/core/attachment/LocalThumbnailService.java
  application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java
  application/src/main/java/run/halo/app/core/attachment/ThumbnailService.java
  application/src/main/java/run/halo/app/core/attachment/ThumbnailSigner.java
  application/src/main/java/run/halo/app/core/attachment/impl/AttachmentRootGetterImpl.java
  application/src/main/java/run/halo/app/core/attachment/impl/LocalThumbnailServiceImpl.java
  application/src/main/java/run/halo/app/core/attachment/impl/ThumbnailServiceImpl.java
  application/src/main/java/run/halo/app/core/attachment/reconciler/AttachmentReconciler.java
  application/src/main/java/run/halo/app/core/attachment/reconciler/LocalThumbnailsReconciler.java
  application/src/main/java/run/halo/app/core/extension/attachment/LocalThumbnail.java
  application/src/main/java/run/halo/app/core/extension/attachment/Thumbnail.java
  application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
  application/src/main/java/run/halo/app/core/extension/attachment/endpoint/LocalAttachmentUploadHandler.java
  application/src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
  application/src/main/java/run/halo/app/infra/DefaultExternalLinkProcessor.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/theme/endpoint/ThumbnailEndpoint.java
  application/src/main/java/run/halo/app/theme/finders/ThumbnailFinder.java
  application/src/main/java/run/halo/app/theme/finders/impl/ThumbnailFinderImpl.java
  application/src/main/resources/extensions/extension-definitions.yaml
  application/src/main/resources/extensions/extensionpoint-definitions.yaml
  application/src/main/resources/extensions/role-template-anonymous.yaml
  application/src/test/java/run/halo/app/content/HtmlThumbnailSrcsetInjectorTest.java
  application/src/test/java/run/halo/app/core/attachment/AttachmentUtilsTest.java
  application/src/test/java/run/halo/app/core/attachment/ThumbnailGeneratorTest.java
  application/src/test/java/run/halo/app/core/attachment/ThumbnailSignerTest.java
  application/src/test/java/run/halo/app/core/attachment/impl/AttachmentRootGetterImplTest.java
  application/src/test/java/run/halo/app/core/attachment/impl/LocalThumbnailServiceImplTest.java
  application/src/test/java/run/halo/app/core/attachment/impl/ThumbnailServiceImplTest.java
  application/src/test/java/run/halo/app/infra/DefaultExternalLinkProcessorTest.java
  platform/application/build.gradle
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentDetailModal.vue
  ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api.ts
  ui/packages/api-client/src/api/local-thumbnail-v1alpha1-api.ts
  ui/packages/api-client/src/api/thumbnail-v1alpha1-api.ts
  ui/packages/api-client/src/api/thumbnail-v1alpha1-public-api.ts
  ui/packages/api-client/src/models/index.ts
  ui/packages/api-client/src/models/local-thumbnail-list.ts
  ui/packages/api-client/src/models/local-thumbnail-spec.ts
  ui/packages/api-client/src/models/local-thumbnail-status.ts
  ui/packages/api-client/src/models/local-thumbnail.ts
  ui/packages/api-client/src/models/thumbnail-list.ts
  ui/packages/api-client/src/models/thumbnail-spec.ts
  ui/packages/api-client/src/models/thumbnail.ts
Labels: kind/feature, lgtm, tide/merge-method-merge, area/core, approved, release-note

#6526 fix: wrong condition in h2 warning alert
  ui/src/components/alerts/H2WarningAlert.vue
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6530 Fix the incorrect list options builder while listing aggregated roles
  application/src/main/java/run/halo/app/core/extension/service/DefaultRoleService.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/test/java/run/halo/app/security/authorization/AuthorizationTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6532 Fix the problem that return empty result while listing users
  application/src/main/java/run/halo/app/core/extension/service/DefaultRoleService.java
  application/src/test/java/run/halo/app/core/extension/service/DefaultRoleServiceTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6529 refactor: optimize user filter component to support remote search
  ui/src/components/filter/UserFilterDropdown.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6531 feat: add unified parameter list method for post finder
  application/src/main/java/run/halo/app/infra/utils/SortUtils.java
  application/src/main/java/run/halo/app/theme/finders/PostFinder.java
  application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  application/src/test/java/run/halo/app/infra/utils/SortUtilsTest.java
  application/src/test/java/run/halo/app/theme/finders/impl/PostFinderImplIntegrationTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note, sig/docs

#6533 chore: rename thumbnail parameter from width to size for clarity
  application/src/main/java/run/halo/app/core/attachment/AttachmentUtils.java
  application/src/main/java/run/halo/app/core/attachment/LocalThumbnailService.java
  application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java
  application/src/main/java/run/halo/app/core/attachment/ThumbnailSigner.java
  application/src/main/java/run/halo/app/core/attachment/impl/LocalThumbnailServiceImpl.java
  application/src/main/java/run/halo/app/core/attachment/impl/ThumbnailServiceImpl.java
  application/src/main/java/run/halo/app/core/extension/attachment/LocalThumbnail.java
  application/src/main/java/run/halo/app/theme/endpoint/ThumbnailEndpoint.java
  application/src/main/java/run/halo/app/theme/finders/ThumbnailFinder.java
  application/src/main/java/run/halo/app/theme/finders/impl/ThumbnailFinderImpl.java
  application/src/test/java/run/halo/app/core/attachment/AttachmentUtilsTest.java
  application/src/test/java/run/halo/app/core/attachment/ThumbnailSignerTest.java
  application/src/test/java/run/halo/app/core/attachment/impl/LocalThumbnailServiceImplTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6525 pref: implement business selector using new selector component
  ui/src/formkit/inputs/attachment-group-select.ts
  ui/src/formkit/inputs/attachment-policy-select.ts
  ui/src/formkit/inputs/menu-item-select.ts
  ui/src/formkit/inputs/post-select.ts
  ui/src/formkit/inputs/role-select.ts
  ui/src/formkit/inputs/select/SelectMain.vue
  ui/src/formkit/inputs/singlePage-select.ts
  ui/src/formkit/inputs/user-select.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6536 fix: resolve incorrect parameters in fomkit select remote request
  ui/src/formkit/inputs/select/SelectMain.vue
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6539 refactor: simplify post settings form fields
  ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
  ui/console-src/modules/contents/posts/components/PostSettingModal.vue
  ui/uc-src/modules/contents/posts/components/PostSettingForm.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#6540 Cleanup code with SortableRequest
  api/src/main/java/run/halo/app/extension/ExtensionUtil.java
  api/src/main/java/run/halo/app/extension/router/SortableRequest.java
  application/src/main/java/run/halo/app/content/PostQuery.java
  application/src/main/java/run/halo/app/content/SinglePageQuery.java
  application/src/main/java/run/halo/app/content/comment/CommentQuery.java
  application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  application/src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
  application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
  application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  application/src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
  application/src/main/java/run/halo/app/core/extension/endpoint/TagEndpoint.java
  application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/theme/endpoint/SinglePageQueryEndpoint.java
  application/src/main/java/run/halo/app/theme/finders/SinglePageConversionService.java
  application/src/main/java/run/halo/app/theme/finders/SinglePageFinder.java
  application/src/main/java/run/halo/app/theme/finders/impl/SinglePageConversionServiceImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/SinglePageFinderImpl.java
  application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
  application/src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
  application/src/test/java/run/halo/app/theme/endpoint/SinglePageQueryEndpointTest.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved, kind/improvement

#6543 Fix the problem of LockObtainFailedException while performing a rolling update
  application/src/main/java/run/halo/app/search/lucene/LuceneSearchEngine.java
  application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#6544 fix: post list sorting parameter not working
  application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
  application/src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6542 refactor: optimize comment and reply logic to reduce duplicate code
  application/src/main/java/run/halo/app/content/comment/AbstractCommentService.java
  application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6538 feat: add default selection option to formkit select component
  ui/docs/custom-formkit-input/README.md
  ui/src/formkit/inputs/attachment-group-select.ts
  ui/src/formkit/inputs/attachment-policy-select.ts
  ui/src/formkit/inputs/menu-item-select.ts
  ui/src/formkit/inputs/post-select.ts
  ui/src/formkit/inputs/role-select.ts
  ui/src/formkit/inputs/select/SelectContainer.vue
  ui/src/formkit/inputs/select/SelectMain.vue
  ui/src/formkit/inputs/select/index.ts
  ui/src/formkit/inputs/singlePage-select.ts
  ui/src/formkit/inputs/user-select.ts
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6545 Make slug of single page be not unique
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#6547 chore: set up preview release with pkg.pr.new
  .github/workflows/packages-preview-release.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6548 fix: prevent anonymous extensions from being filtered due to duplicate names
  ui/src/components/editor/DefaultEditor.vue
Labels: kind/bug, lgtm, approved, release-note, area/editor

#6550 refactor: improve axios instance parameters
  ui/packages/api-client/entry/api-client.ts
  ui/packages/api-client/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6551 fix: resolve error when deleting images in default editor
  ui/packages/editor/src/components/bubble/BubbleItem.vue
  ui/packages/editor/src/extensions/paragraph/index.ts
  ui/packages/editor/src/utils/isNodeEmpty.ts
  ui/src/components/editor/extensions/audio/AudioView.vue
  ui/src/components/editor/extensions/image/ImageView.vue
  ui/src/components/editor/extensions/video/VideoView.vue
Labels: kind/bug, lgtm, approved, release-note, area/editor, area/ui

#6555 refactor: optimize key comparator for indicates key sort
  api/src/main/java/run/halo/app/extension/index/KeyComparator.java
  api/src/test/java/run/halo/app/extension/index/KeyComparatorTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6556 refactor: redirect to original image if thumbnail is inaccessible
  application/src/main/java/run/halo/app/core/attachment/impl/LocalThumbnailServiceImpl.java
  application/src/main/java/run/halo/app/theme/endpoint/ThumbnailEndpoint.java
  application/src/test/java/run/halo/app/theme/endpoint/ThumbnailEndpointTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement
