Repository halo-dev/halo, pull requests merged in 2024-05, with the labels that each got.

#5856 Prepare for developing 2.16.0
  README.md
  gradle.properties
  ui/packages/api-client/package.json
  ui/packages/components/package.json
  ui/packages/editor/package.json
  ui/packages/shared/package.json
  ui/packages/ui-plugin-bundler-kit/package.json
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#5857 Support excluding node_modules for idea IDE
  ui/build.gradle
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#5855 Fix the problem that some plugins could not be used after upgrading dependent plugin
  application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
  application/src/main/java/run/halo/app/plugin/SpringPluginManager.java
  application/src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
Labels: kind/bug, lgtm, area/core, approved, area/plugin

#5880 fix: changes to Unstructured metadata do not take effect
  api/src/main/java/run/halo/app/extension/Unstructured.java
  application/src/test/java/run/halo/app/extension/UnstructuredTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#5874 Fix the problem of not being able to initialize preset plugins
  application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  application/src/main/java/run/halo/app/plugin/SpringPlugin.java
  application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note, area/plugin

#5910 fix: style issue of dialog component icon
  ui/packages/components/src/components/dialog/Dialog.vue
Labels: lgtm, area/core, approved, release-note, area/ui

#5911 feat: Add title slot to alert component
  ui/packages/components/src/components/alert/Alert.vue
Labels: kind/feature, lgtm, area/core, approved, release-note, area/ui

#5909 fix: remove close button for reserved alert in role detail page
  ui/console-src/modules/system/roles/RoleDetail.vue
Labels: lgtm, area/core, approved, release-note, area/ui

#5887 Fix the problem where extensions were not changed but still updated
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  application/src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#5917 fix: secret data cannot be used in YAML
  application/src/main/java/run/halo/app/extension/JSONExtensionConverter.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#5893 feat: support filtering attachments in the library by file media type
  api-docs/openapi/v3_0/aggregated.json
  application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  ui/console-src/modules/contents/attachments/composables/use-attachment.ts
  ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-attachment-api.ts
  ui/src/locales/en.yaml
  ui/src/locales/es.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, area/core, approved, release-note, area/ui

#5906 feat: add an API to invalidate theme template cache
  api-docs/openapi/v3_0/aggregated.json
  application/src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
  application/src/main/resources/extensions/role-template-theme.yaml
  ui/console-src/modules/interface/themes/ThemeDetail.vue
  ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-theme-api.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, area/core, approved, area/theme, release-note

#5920 chore: bump vite to 5.x
  ui/package.json
  ui/packages/api-client/.prettierrc.js
  ui/packages/components/prettier.config.js
  ui/packages/editor/prettier.config.js
  ui/packages/shared/prettier.config.js
  ui/packages/ui-plugin-bundler-kit/.prettierrc.cjs
  ui/pnpm-lock.yaml
  ui/postcss.config.cjs
  ui/prettier.config.cjs
  ui/src/components/editor/DefaultEditor.vue
  ui/tailwind.config.cjs
  ui/tsconfig.node.json
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5928 fix: cursor misalignment when scrolling through the table
  ui/packages/editor/src/extensions/table/index.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor

#5803 fix: incorrect column width calculation after merging cells in the table
  ui/packages/editor/src/extensions/table/table-cell.ts
  ui/packages/editor/src/extensions/table/table-header.ts
Labels: kind/bug, lgtm, approved, release-note, area/editor

#5931 refactor: original should be removed when session id changed
  application/src/main/java/run/halo/app/security/session/InMemoryReactiveIndexedSessionRepository.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#5950 Upgrade PF4J to 3.11.1
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note, area/plugin

#5951 chore: bump tiptap version to 2.4.0
  ui/package.json
  ui/packages/editor/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5903 refactor: automatically approve comments or replies after admin replied it
  application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5914 refactor: optimize auth provider sorting with drag-and-drop support
  api-docs/openapi/v3_0/aggregated.json
  api/src/main/java/run/halo/app/core/extension/AuthProvider.java
  application/src/main/java/run/halo/app/security/AuthProviderServiceImpl.java
  ui/console-src/modules/system/auth-providers/AuthProviders.vue
  ui/console-src/modules/system/auth-providers/components/AuthProviderListItem.vue
  ui/package.json
  ui/packages/api-client/src/models/auth-provider-spec.ts
  ui/pnpm-lock.yaml
Labels: kind/feature, lgtm, area/core, approved, release-note, area/ui

#5937 refactor: add default sort for extension listing
  api/src/main/java/run/halo/app/extension/router/SortableRequest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5905 refactor: email notifications are now sent only to verified email addresses
  application/src/main/java/run/halo/app/notification/DefaultSubscriberEmailResolver.java
  application/src/test/java/run/halo/app/notification/DefaultSubscriberEmailResolverTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5953 chore: bump pnpm version to 9
  .github/actions/setup-env/action.yaml
  ui/README.md
  ui/pnpm-lock.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5956 Ignore includeSubdomains for hsts header
  application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  application/src/test/java/run/halo/app/config/SecurityConfigTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5957 refactor: improve code base of menu-related
  ui/console-src/modules/interface/menus/Menus.vue
  ui/console-src/modules/interface/menus/components/MenuEditingModal.vue
  ui/console-src/modules/interface/menus/components/MenuItemEditingModal.vue
  ui/console-src/modules/interface/menus/components/MenuItemListItem.vue
  ui/console-src/modules/interface/menus/components/MenuList.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#5936 pref: optimize code block backspace shortcut key logic
  ui/packages/editor/src/extensions/code-block/code-block.ts
Labels: lgtm, approved, release-note, kind/improvement, area/editor

#5938 fix: deleting selected text in a list with the backspace key causes the list to revert
  ui/packages/editor/src/extensions/indent/index.ts
  ui/packages/editor/src/styles/base.scss
Labels: kind/bug, lgtm, approved, release-note, area/editor

#5958 refactor: improve code base of post category-related
  ui/console-src/modules/contents/posts/categories/CategoryList.vue
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  ui/console-src/modules/contents/posts/categories/components/CategoryListItem.vue
  ui/console-src/modules/contents/posts/categories/composables/use-post-category.ts
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/vite/config-builder.ts
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#5961 Unify security configurations into one
  application/src/main/java/run/halo/app/config/HaloAnonymousAuthenticationWebFilter.java
  application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/theme/dialect/HaloSpringSecurityDialect.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#5959 refactor: improve code base of post tag-related
  ui/console-src/modules/contents/posts/tags/TagList.vue
  ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#5965 chore: bump up vue-related version
  ui/console-src/modules/interface/themes/layouts/ThemeLayout.vue
  ui/package.json
  ui/packages/components/package.json
  ui/packages/components/src/components/alert/Alert.vue
  ui/packages/components/src/components/dropdown/Dropdown.vue
  ui/packages/components/src/components/dropdown/index.ts
  ui/packages/components/src/components/tooltip/index.ts
  ui/packages/components/vite.config.ts
  ui/packages/editor/package.json
  ui/packages/editor/src/components/block/BlockActionButton.vue
  ui/packages/editor/src/components/block/BlockActionInput.vue
  ui/packages/editor/src/components/bubble/BubbleItem.vue
  ui/packages/editor/src/components/toolbar/ToolbarItem.vue
  ui/packages/editor/src/extensions/link/LinkBubbleButton.vue
  ui/packages/shared/package.json
  ui/packages/shared/vite.config.ts
  ui/pnpm-lock.yaml
  ui/src/components/editor/DefaultEditor.vue
  ui/src/setup/setupComponents.ts
  ui/src/vite/config-builder.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5967 refactor: improve code base of attachment-related
  ui/console-src/composables/use-setting-form.ts
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
  ui/console-src/modules/contents/attachments/components/AttachmentGroupList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentListItem.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPermalinkList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
  ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  ui/console-src/modules/contents/attachments/composables/use-attachment-group.ts
  ui/console-src/modules/contents/attachments/composables/use-attachment-policy.ts
  ui/console-src/modules/contents/attachments/composables/use-attachment.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5972 refactor: simplify the code of reply creation modal
  ui/console-src/modules/contents/comments/components/CommentListItem.vue
  ui/console-src/modules/contents/comments/components/ReplyCreationModal.vue
  ui/console-src/modules/contents/comments/components/ReplyListItem.vue
  ui/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#5960 refactor: layout of reset password page
  ui/console-src/router/routes.config.ts
  ui/src/layouts/GatewayLayout.vue
  ui/uc-src/router/routes.config.ts
  ui/uc-src/views/ResetPassword.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#5966 refactor: logic of theme management modal
  ui/console-src/modules/interface/themes/components/ThemeListModal.vue
  ui/console-src/modules/interface/themes/components/list-tabs/InstalledThemes.vue
  ui/console-src/modules/interface/themes/layouts/ThemeLayout.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5968 refactor: logic of singlePage setting modal
  ui/console-src/modules/contents/pages/SinglePageEditor.vue
  ui/console-src/modules/contents/pages/SinglePageList.vue
  ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5975 refactor: improve code base of user-related
  ui/console-src/modules/system/users/UserDetail.vue
  ui/console-src/modules/system/users/UserList.vue
  ui/console-src/modules/system/users/components/UserCreationModal.vue
  ui/console-src/modules/system/users/components/UserEditingModal.vue
  ui/console-src/modules/system/users/components/UserPasswordChangeModal.vue
  ui/src/components/login/LoginModal.vue
  ui/uc-src/modules/profile/Profile.vue
  ui/uc-src/modules/profile/components/PasswordChangeModal.vue
  ui/uc-src/modules/profile/components/ProfileEditingModal.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5976 refactor: improve visible condition of global search component
  ui/console-src/layouts/BasicLayout.vue
  ui/src/components/global-search/GlobalSearchModal.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#5979 Upgrade SpringBoot to 3.3.0
  build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#5978 Refactor CryptoService for simplifying RSA key generation
  application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/security/authentication/CryptoService.java
  application/src/main/java/run/halo/app/security/authentication/impl/RsaKeyService.java
  application/src/main/java/run/halo/app/security/authentication/login/LoginAuthenticationConverter.java
  application/src/main/java/run/halo/app/security/authentication/login/LoginSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/login/PublicKeyRouteBuilder.java
  application/src/main/java/run/halo/app/security/authentication/login/RsaKeyScheduledGenerator.java
  application/src/main/java/run/halo/app/security/authentication/login/impl/RsaKeyService.java
  application/src/main/java/run/halo/app/security/authentication/pat/DefaultPatJwkSupplier.java
  application/src/main/java/run/halo/app/security/authentication/pat/PatAuthenticationManager.java
  application/src/main/java/run/halo/app/security/authentication/pat/PatJwkSupplier.java
  application/src/main/java/run/halo/app/security/authentication/pat/impl/UserScopedPatHandlerImpl.java
  application/src/test/java/run/halo/app/security/authentication/impl/RsaKeyServiceTest.java
  application/src/test/java/run/halo/app/security/authentication/login/LoginAuthenticationConverterTest.java
  application/src/test/java/run/halo/app/security/authentication/login/PublicKeyRouteBuilderTest.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#5982 fix: color style issue of code block in post content snapshot page
  ui/console-src/modules/contents/posts/components/SnapshotContent.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#5929 feat: add remember-me mechanism to enhance user login experience
  application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java
  application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/login/LoginSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordHandler.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/CookieSignatureKeyResolver.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/DefaultCookieSignatureKeyResolver.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/RememberMeAuthenticationFilter.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/RememberMeAuthenticationManager.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/RememberMeConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/RememberMeCookieResolver.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/RememberMeCookieResolverImpl.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/RememberMeServices.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/TokenBasedRememberMeServices.java
  application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/twofactor/totp/TotpAuthenticationFilter.java
  application/src/test/java/run/halo/app/security/authentication/rememberme/TokenBasedRememberMeServicesTest.java
  ui/console-src/layouts/BasicLayout.vue
  ui/src/components/login/LoginForm.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/layouts/BasicLayout.vue
Labels: kind/feature, lgtm, area/core, approved, release-note

#5981 chore: provide post content retrieval bean for plugins
  api/src/main/java/run/halo/app/content/ContentWrapper.java
  api/src/main/java/run/halo/app/content/PatchUtils.java
  api/src/main/java/run/halo/app/content/PostContentService.java
  application/src/main/java/run/halo/app/content/PostContentServiceImpl.java
  application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
Labels: lgtm, area/core, approved, release-note, kind/improvement, area/plugin

#5984 refactor: improve code base of role-related
  ui/console-src/modules/system/roles/RoleDetail.vue
  ui/console-src/modules/system/roles/RoleList.vue
  ui/console-src/modules/system/roles/components/RoleEditingModal.vue
  ui/console-src/modules/system/users/UserList.vue
  ui/console-src/modules/system/users/components/GrantPermissionModal.vue
  ui/src/composables/use-role.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5900 Refactor plugin reconciliation for dependency mechanism
  api-docs/openapi/v3_0/aggregated.json
  api/src/main/java/run/halo/app/core/extension/Plugin.java
  api/src/main/java/run/halo/app/infra/Condition.java
  api/src/main/java/run/halo/app/infra/ConditionList.java
  application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
  application/src/main/java/run/halo/app/core/extension/service/PluginService.java
  application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
  application/src/main/java/run/halo/app/infra/exception/PluginDependenciesNotEnabledException.java
  application/src/main/java/run/halo/app/infra/exception/PluginDependentsNotDisabledException.java
  application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
  application/src/main/java/run/halo/app/plugin/PluginConst.java
  application/src/main/java/run/halo/app/plugin/SpringPluginManager.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
  application/src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
  application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
  application/src/test/java/run/halo/app/infra/ConditionListTest.java
  ui/console-src/modules/system/plugins/components/PluginConditionsModal.vue
  ui/console-src/modules/system/plugins/components/PluginListItem.vue
  ui/console-src/modules/system/plugins/composables/use-plugin.ts
  ui/console-src/modules/system/plugins/tabs/Detail.vue
  ui/packages/api-client/src/models/condition.ts
  ui/packages/api-client/src/models/plugin-status.ts
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement, area/plugin

#5993 fix: update initial values when form data changes
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
  ui/console-src/modules/interface/menus/components/MenuEditingModal.vue
  ui/console-src/modules/interface/menus/components/MenuItemEditingModal.vue
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#5985 feat: add retry feature for update last read time of comment
  ui/console-src/modules/contents/comments/components/CommentListItem.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#5987 refactor: logic of publishing post
  ui/console-src/modules/contents/pages/SinglePageList.vue
  ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
  ui/console-src/modules/contents/posts/PostEditor.vue
  ui/console-src/modules/contents/posts/PostList.vue
  ui/console-src/modules/contents/posts/components/PostListItem.vue
  ui/console-src/modules/contents/posts/components/PostSettingModal.vue
  ui/console-src/modules/contents/posts/components/entity-fields/PublishStatusField.vue
  ui/uc-src/modules/contents/posts/PostList.vue
  ui/uc-src/modules/contents/posts/components/PostListItem.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5995 feat: record the plugin query conditions in the route query parameters
  ui/console-src/modules/system/plugins/PluginList.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#5996 refactor: improve ui/ux of attachment group and policy selector
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentGroupBadge.vue
  ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
  ui/console-src/modules/contents/attachments/components/AttachmentGroupList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPolicyBadge.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
  ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5997 chore: bump uppy version
  ui/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#5994 refactor: typing component template refs for VModal
  ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
  ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
  ui/console-src/modules/contents/comments/components/ReplyCreationModal.vue
  ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
  ui/console-src/modules/interface/menus/components/MenuEditingModal.vue
  ui/console-src/modules/interface/menus/components/MenuItemEditingModal.vue
  ui/console-src/modules/interface/themes/components/ThemeListModal.vue
  ui/console-src/modules/system/plugins/components/PluginInstallationModal.vue
  ui/console-src/modules/system/roles/components/RoleEditingModal.vue
  ui/console-src/modules/system/users/components/GrantPermissionModal.vue
  ui/console-src/modules/system/users/components/UserCreationModal.vue
  ui/console-src/modules/system/users/components/UserEditingModal.vue
  ui/console-src/modules/system/users/components/UserPasswordChangeModal.vue
  ui/src/components/global-search/GlobalSearchModal.vue
  ui/src/components/login/LoginModal.vue
  ui/uc-src/modules/contents/posts/components/PostCreationModal.vue
  ui/uc-src/modules/contents/posts/components/PostSettingEditModal.vue
  ui/uc-src/modules/profile/components/EmailVerifyModal.vue
  ui/uc-src/modules/profile/components/PasswordChangeModal.vue
  ui/uc-src/modules/profile/components/PersonalAccessTokenCreationModal.vue
  ui/uc-src/modules/profile/components/ProfileEditingModal.vue
  ui/uc-src/modules/profile/tabs/components/TotpConfigureModal.vue
  ui/uc-src/modules/profile/tabs/components/TotpDeletionModal.vue
  ui/uc-src/modules/profile/tabs/components/TwoFactorDisableModal.vue
  ui/uc-src/modules/profile/tabs/components/TwoFactorEnableModal.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#6007 Fix the problem the PAT could not be created or restored while logging in with remember-me
  application/src/main/java/run/halo/app/security/authentication/pat/impl/UserScopedPatHandlerImpl.java
  application/src/main/java/run/halo/app/security/authorization/AuthorityUtils.java
  application/src/test/java/run/halo/app/security/authorization/AuthorityUtilsTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#6006 Fix the problem where extension point might not be obtained when the plugin was started
  application/src/main/java/run/halo/app/plugin/SpringComponentsFinder.java
  application/src/test/java/run/halo/app/plugin/SpringComponentsFinderTest.java
  application/src/test/resources/plugin/plugin-for-finder/META-INF/plugin-components.idx
  application/src/test/resources/plugin/test-plugin-components.idx
Labels: kind/bug, lgtm, area/core, approved, release-note, area/plugin

#6012 feat: add version for themes and plugins when copying overview information
  ui/console-src/modules/system/overview/Overview.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6020 refactor: refine i18n prompts for themes
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6019 chore: revert @uppy/xhr-upload version to 3.6.0
  ui/package.json
  ui/pnpm-lock.yaml
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6018 feat: enable asynchronous resolving for UI extension points
  ui/console-src/modules/contents/attachments/components/AttachmentSelectorModal.vue
  ui/console-src/modules/contents/comments/components/CommentListItem.vue
  ui/console-src/modules/interface/themes/components/ThemeListModal.vue
  ui/console-src/modules/system/backup/Backups.vue
  ui/console-src/modules/system/plugins/PluginDetail.vue
  ui/console-src/modules/system/plugins/components/PluginInstallationModal.vue
  ui/console-src/modules/system/users/UserDetail.vue
  ui/packages/shared/src/types/plugin.ts
  ui/src/components/editor/DefaultEditor.vue
  ui/src/composables/use-editor-extension-points.ts
  ui/uc-src/modules/profile/Profile.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#6015 Refactor cache control for static resources
  application/src/main/java/run/halo/app/config/WebFluxConfig.java
  application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
  application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
  application/src/main/java/run/halo/app/plugin/PluginConst.java
  application/src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
  application/src/main/java/run/halo/app/theme/ThemeConfiguration.java
  application/src/main/java/run/halo/app/theme/config/ThemeConfiguration.java
  application/src/main/java/run/halo/app/theme/config/ThemeWebFluxConfigurer.java
  application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
  application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
  application/src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactoryTest.java
  application/src/test/java/run/halo/app/theme/ThemeConfigurationTest.java
  application/src/test/resources/plugin/plugin-for-reverseproxy/static/test.txt
Labels: lgtm, area/core, approved, release-note, kind/improvement

#6011 refactor: use index mechanism to query extension point definitions
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#6021 fix: dropdown component auto-destruction issue
  ui/packages/components/src/components/dropdown/Dropdown.vue
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#6022 chore: remove unnecessary env
  ui/.env.development
  ui/.env.production
  ui/console-src/composables/use-global-info.ts
  ui/console-src/layouts/BasicLayout.vue
  ui/console-src/modules/interface/themes/components/preview/ThemePreviewModal.vue
  ui/console-src/modules/system/overview/Overview.vue
  ui/console-src/setup/setupModules.ts
  ui/src/components/login/LoginForm.vue
  ui/src/components/login/MfaForm.vue
  ui/src/components/upload/UppyUpload.vue
  ui/src/stores/global-info.ts
  ui/src/utils/api-client.ts
  ui/uc-src/layouts/BasicLayout.vue
  ui/uc-src/modules/profile/tabs/Detail.vue
  ui/uc-src/setup/setupModules.ts
  ui/vite.config.ts
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui
