Repository halo-dev/halo, pull requests merged in 2025-07, with the labels that each got.

#7595 refactor: pass NODE_ENV for vite config in ui plugin bunlder kit
  ui/packages/ui-plugin-bundler-kit/src/vite.ts
Labels: lgtm, release-note-none, approved, kind/improvement, area/plugin, area/ui

#7598 refactor: make toolbox button expandable on click in editor
  ui/packages/editor/src/components/EditorHeader.vue
  ui/packages/editor/src/components/toolbar/ToolbarItem.vue
Labels: lgtm, approved, release-note, kind/improvement, area/editor, area/ui

#7599 fix: prevent code input content from being obscured in fullscreen mode
  ui/src/components/codemirror/Codemirror.vue
  ui/src/formkit/inputs/code/CodeInput.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#7582 refactor: exclude post preview page from data tracking
  application/src/main/java/run/halo/app/theme/dialect/HaloTrackerProcessor.java
  application/src/main/java/run/halo/app/theme/router/PreviewRouterFunction.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#7613 chore: upgrade tiptap to 2.24.1
  application/src/main/java/run/halo/app/theme/dialect/HaloTrackerProcessor.java
  ui/package.json
  ui/packages/editor/package.json
  ui/packages/editor/src/extensions/draggable/index.ts
  ui/packages/editor/src/extensions/table/util.ts
  ui/pnpm-lock.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/editor

#7614 chore: bump halo packages version
  ui/packages/api-client/package.json
  ui/packages/ui-plugin-bundler-kit/package.json
Labels: release-note-none, area/ui

#7619 docs: Add GitCode badge
  README.md
Labels: lgtm, do-not-merge/release-note-label-needed

#7632 Add ClawCloud one-click deployment button to README
  README.md
Labels: lgtm, release-note-none, approved, kind/documentation

#7616 feat: add slug existence check when creating categories and tags
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
  ui/src/formkit/inputs/category-select/CategorySelect.vue
  ui/src/formkit/inputs/tag-select/TagSelect.vue
  ui/src/locales/_missing_translations_es.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#7640 Upgrade to Spring Boot 3.5.4
  gradle/libs.versions.toml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7643 Fix the problem that notification might not work anymore
  application/src/main/java/run/halo/app/notification/DefaultNotificationCenter.java
  application/src/main/java/run/halo/app/notification/DefaultNotificationSender.java
  application/src/main/java/run/halo/app/notification/NotificationTrigger.java
  application/src/test/java/run/halo/app/notification/DefaultNotificationSenderTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement
