Repository halo-dev/halo, pull requests merged in 2025-02, with the labels that each got.

#7226 docs: add a suggestion for using 1Panel in README.md
  README.md
Labels: lgtm, do-not-merge/release-note-label-needed, approved

#7236 Upgrade to Spring Boot 3.4.3
  build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#7237 Upgrade to R2DBC MySQL 1.4.0
  gradle.properties
Labels: kind/bug, lgtm, area/core, approved, release-note

#7239 Update deprecated default string function
  api/src/main/java/run/halo/app/core/extension/Theme.java
  api/src/main/java/run/halo/app/theme/router/PageUrlUtils.java
  application/src/main/java/run/halo/app/content/SinglePageQuery.java
  application/src/main/java/run/halo/app/content/comment/CommentEmailOwner.java
  application/src/main/java/run/halo/app/core/reconciler/ReverseProxyReconciler.java
  application/src/main/java/run/halo/app/security/authorization/RequestInfo.java
  application/src/main/java/run/halo/app/security/authorization/RequestInfoFactory.java
Labels: lgtm, release-note-none, kind/cleanup, approved
