Repository halo-dev/halo, pull requests merged in 2025-03, with the labels that each got.

#7253 chore: update issue templates config
  .github/ISSUE_TEMPLATE/config.yml
Labels: lgtm, release-note-none, approved

#7257 fix: move cache after doFinally to ensure effective concurrency control
  application/src/main/java/run/halo/app/core/attachment/impl/ThumbnailServiceImpl.java
  application/src/test/java/run/halo/app/core/attachment/impl/ThumbnailServiceImplTest.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#7261 Enable Virtual Thread when running on JVM 21
  Dockerfile
  api/src/main/java/run/halo/app/extension/controller/DefaultController.java
  api/src/test/java/run/halo/app/extension/controller/DefaultControllerTest.java
  application/src/main/resources/application.yaml
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#7258 refactor: modify plugin class loading order to follow parent delegation mechanism
  application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
  application/src/main/java/run/halo/app/plugin/SpringPlugin.java
  application/src/main/java/run/halo/app/plugin/loader/DevPluginLoader.java
  application/src/main/java/run/halo/app/plugin/loader/HaloPluginClassLoader.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7268 feat: add support for one-click revocation of login status of other devices
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/profile/tabs/Devices.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#7272 feat: add device loss warning tips in 2FA setup page
  ui/src/locales/_missing_translations_es.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/profile/tabs/components/TotpConfigureModal.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#7275 fix: resolve file extension validation failure issue in editor uploads
  application/src/main/java/run/halo/app/core/attachment/endpoint/LocalAttachmentUploadHandler.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#7276 feat: add image thumbnail support for single pages
  application/src/main/java/run/halo/app/content/PageContentThumbnailHandler.java
  application/src/main/resources/extensions/extension-definitions.yaml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7278 fix: resolve issue of duplicate image uploads in default editor
  ui/src/components/editor/extensions/audio/AudioView.vue
  ui/src/components/editor/extensions/image/ImageView.vue
  ui/src/components/editor/extensions/video/VideoView.vue
Labels: kind/bug, lgtm, approved, release-note, area/editor

#7279 refactor: restrict author page access to users with post permission
  application/src/main/java/run/halo/app/security/authorization/AuthorityUtils.java
  application/src/main/java/run/halo/app/theme/router/factories/AuthorPostsRouteFactory.java
  application/src/test/java/run/halo/app/theme/router/factories/AuthorPostsRouteFactoryTest.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7281 Fix the pending problem of requesting console and uc pages in dev mode
  application/src/main/java/run/halo/app/infra/config/WebFluxConfig.java
  application/src/main/java/run/halo/app/infra/console/ProxyFilter.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#7282 feat: add batch delete and mark-as-read supports for notifications
  ui/src/locales/_missing_translations_es.yaml
  ui/src/locales/_missing_translations_zh-CN.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/notifications/Notifications.vue
  ui/uc-src/modules/notifications/components/NotificationListItem.vue
  ui/uc-src/modules/notifications/module.ts
Labels: kind/feature, lgtm, approved, release-note, area/ui

#7273 feat: add support for disabling/enabling user accounts
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api/src/main/java/run/halo/app/core/user/service/UserService.java
  api/src/main/java/run/halo/app/security/device/DeviceService.java
  application/src/main/java/run/halo/app/core/endpoint/console/ConsoleUserEndpoint.java
  application/src/main/java/run/halo/app/core/user/service/impl/UserServiceImpl.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordHandler.java
  application/src/main/java/run/halo/app/security/device/DeviceServiceImpl.java
  application/src/main/resources/templates/gateway_fragments/login.html
  application/src/main/resources/templates/gateway_fragments/login.properties
  application/src/main/resources/templates/gateway_fragments/login_en.properties
  application/src/main/resources/templates/gateway_fragments/login_es.properties
  application/src/main/resources/templates/gateway_fragments/login_zh_TW.properties
  ui/console-src/modules/system/users/UserDetail.vue
  ui/console-src/modules/system/users/UserList.vue
  ui/console-src/modules/system/users/components/UserListItem.vue
  ui/console-src/modules/system/users/composables/use-user.ts
  ui/packages/api-client/src/api/user-v1alpha1-console-api.ts
  ui/src/locales/_missing_translations_es.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note, area/ui

#7284 Turn off logging of TemplateEngine
  application/src/main/java/run/halo/app/theme/engine/HaloTemplateEngine.java
  application/src/main/resources/application-dev.yaml
  application/src/main/resources/application.yaml
Labels: kind/bug, lgtm, area/core, approved, release-note

#7288 feat: add favicon to login page
  application/src/main/resources/templates/gateway_fragments/layout.html
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7290 Revert "refactor: modify plugin class loading order to follow parent delegation mechanism (#7258)"
  application/src/main/java/run/halo/app/plugin/DevPluginLoader.java
  application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
  application/src/main/java/run/halo/app/plugin/SpringPlugin.java
  application/src/main/java/run/halo/app/plugin/loader/HaloPluginClassLoader.java
Labels: lgtm, kind/cleanup, approved, release-note

#7291 chore: add exception information to log output when the plugin fails to start
  application/src/main/java/run/halo/app/core/reconciler/PluginReconciler.java
Labels: lgtm, release-note-none, approved, kind/improvement

#7303 Add timeout for blocking Extension client
  application/src/main/java/run/halo/app/extension/DelegateExtensionClient.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#7304 Fix the problem of unit test failure under Java 21
  api/src/main/java/run/halo/app/extension/controller/DefaultController.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#7305 Upgrade to Spring Boot 3.4.4
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7301 Support randomizing local attachment filename
  application/src/main/java/run/halo/app/core/attachment/endpoint/LocalAttachmentUploadHandler.java
  application/src/main/java/run/halo/app/infra/utils/FileNameUtils.java
  application/src/main/resources/extensions/attachment-local-policy.yaml
  application/src/test/java/run/halo/app/core/attachment/endpoint/LocalAttachmentUploadHandlerTest.java
Labels: kind/feature, lgtm, area/core, approved, release-note

#7313 fix: resolve issue of duplicate post creation
  ui/uc-src/modules/contents/posts/PostEditor.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui
