Repository halo-dev/halo, pull requests merged in 2025-04, with the labels that each got.

#7321 Fix the NPE while post content is null
  application/src/main/java/run/halo/app/core/reconciler/PostReconciler.java
  application/src/test/java/run/halo/app/core/reconciler/PostReconcilerTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#7323 Fix the repeat registration with the email already verified
  api/src/main/java/run/halo/app/core/user/service/UserService.java
  application/src/main/java/run/halo/app/core/user/service/impl/UserServiceImpl.java
  application/src/main/java/run/halo/app/infra/exception/EmailAlreadyTakenException.java
  application/src/main/java/run/halo/app/security/preauth/PreAuthSignUpEndpoint.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/test/java/run/halo/app/core/user/service/impl/UserServiceImplTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#7328 fix: resolve editor styling issues in Safari browser
  ui/packages/editor/src/components/EditorBubbleMenu.vue
  ui/packages/editor/src/components/EditorHeader.vue
  ui/packages/editor/src/components/bubble/BubbleItem.vue
  ui/packages/editor/src/extensions/commands-menu/CommandsView.vue
  ui/packages/editor/src/extensions/link/LinkBubbleButton.vue
  ui/packages/editor/src/styles/base.scss
Labels: kind/bug, lgtm, approved, release-note, area/editor, area/ui

#7322 Add support for sec:authorize attribute of Thymeleaf
  application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/theme/config/ThemeConfiguration.java
  application/src/main/java/run/halo/app/theme/dialect/HaloSpringSecurityDialect.java
  application/src/test/java/run/halo/app/theme/dialect/HaloSpringSecurityDialectTest.java
Labels: lgtm, area/core, approved, area/theme, release-note, kind/improvement

#7341 Extract PAT operation with service
  api/src/main/java/run/halo/app/security/PersonalAccessToken.java
  application/src/main/java/run/halo/app/core/user/service/PatService.java
  application/src/main/java/run/halo/app/core/user/service/impl/PatServiceImpl.java
  application/src/main/java/run/halo/app/security/authentication/pat/PatAuthenticationConverter.java
  application/src/main/java/run/halo/app/security/authentication/pat/UserScopedPatHandlerImpl.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#7343 chore: restrict packages-preview-release job to current repo only
  .github/workflows/packages-preview-release.yaml
Labels: lgtm, release-note-none, kind/cleanup, approved

#7350 fix: resolve issue with categoryName parameter not working in postFinder.list()
  application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
Labels: kind/bug, lgtm, approved, release-note

#7331 feat: support route pattern /categories/{categorySlug}/{postSlug} for post access
  application/src/main/java/run/halo/app/content/PostService.java
  application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
  application/src/main/java/run/halo/app/content/permalinks/PostPermalinkPolicy.java
  application/src/main/java/run/halo/app/core/reconciler/CategoryReconciler.java
  application/src/main/java/run/halo/app/theme/router/ThemeCompositeRouterFunction.java
  application/src/main/java/run/halo/app/theme/router/factories/PostRouteFactory.java
  application/src/main/resources/extensions/system-setting.yaml
  application/src/test/java/run/halo/app/content/permalinks/PostPermalinkPolicyTest.java
Labels: kind/feature, lgtm, approved, release-note

#7351 Support impersonating other users for super admin
  application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
  application/src/main/java/run/halo/app/security/HaloRedirectAuthenticationSuccessHandler.java
  application/src/main/java/run/halo/app/security/HaloServerRequestCache.java
  application/src/main/java/run/halo/app/security/authorization/AuthorizationExchangeConfigurers.java
  application/src/main/java/run/halo/app/security/switchuser/SwitchUserConfigurer.java
  application/src/test/java/run/halo/app/security/switchuser/SwitchUserConfigurerTest.java
Labels: kind/feature, lgtm, release-note-none, area/core, approved

#7353 Disable CSRF check for PAT authentication
  application/src/main/java/run/halo/app/security/CsrfConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/pat/PatAuthenticationConverter.java
  application/src/test/java/run/halo/app/security/CsrfSecurityTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#7364 Remove unused application startup steps buffer
  application/src/main/java/run/halo/app/Application.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#7371 Prevent data conflicts caused by database case sensitivity as possible
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#7378 refactor: add chunked execution mechanism for post batch operations
  ui/console-src/modules/contents/posts/DeletedPostList.vue
  ui/console-src/modules/contents/posts/PostList.vue
  ui/console-src/modules/contents/posts/components/PostBatchSettingModal.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#7381 feat: add support for multiple roles during user creation
  ui/console-src/modules/system/users/components/UserCreationModal.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#7382 fix: equals and hash code for unstructured metadata
  api/src/main/java/run/halo/app/extension/Unstructured.java
Labels: kind/bug, lgtm, release-note-none, area/core, approved

#7387 Upgrade to Gradle 8.13
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7386 Upgrade to Spring Boot 3.4.5
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7388 Revert "Remove unused application startup steps buffer"
  application/src/main/java/run/halo/app/Application.java
Labels: lgtm, release-note-none, approved

#7390 Support resolving javadoc for SpringDoc
  api/build.gradle
  application/build.gradle
  platform/application/build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#7365 feat: support configuring default locale in system setting
  api/src/main/java/run/halo/app/infra/SystemSetting.java
  application/src/main/java/run/halo/app/infra/SystemConfigurableEnvironmentFetcher.java
  application/src/main/java/run/halo/app/infra/actuator/GlobalInfoServiceImpl.java
  application/src/main/java/run/halo/app/infra/config/WebFluxConfig.java
  application/src/main/java/run/halo/app/infra/webfilter/LocaleChangeWebFilter.java
  application/src/main/java/run/halo/app/notification/DefaultNotificationCenter.java
  application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
  application/src/main/java/run/halo/app/theme/ThemeLocaleContextResolver.java
  application/src/main/java/run/halo/app/theme/UserLocaleRequestAttributeWriteFilter.java
  application/src/main/java/run/halo/app/theme/finders/vo/SiteSettingVo.java
  application/src/main/resources/extensions/system-setting.yaml
  application/src/main/resources/static/styles/main.css
  application/src/main/resources/templates/setup.html
  application/src/main/resources/templates/setup.properties
  application/src/main/resources/templates/setup_en.properties
  application/src/main/resources/templates/setup_es.properties
  application/src/main/resources/templates/setup_zh_TW.properties
  application/src/test/java/run/halo/app/notification/DefaultNotificationCenterTest.java
  application/src/test/java/run/halo/app/webfilter/LocaleChangeWebFilterTest.java
  ui/console-src/modules/system/settings/tabs/Setting.vue
Labels: kind/feature, lgtm, area/core, approved, release-note
