Repository halo-dev/halo, pull requests merged in 2025-08, with the labels that each got.

#7650 chore: downgrade rolldown-vite to fix chunk issue
  ui/package.json
  ui/pnpm-lock.yaml
Labels: kind/bug, release-note, area/ui

#7658 Ingore build directory while linting ui project
  ui/eslint.config.ts
Labels: kind/bug, release-note-none, area/ui

#7657 Upgrade to Gradle 9.0.0
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#7665 Refactor SEO meta tag processors and update help texts for ui
  api/src/main/java/run/halo/app/theme/Constant.java
  application/src/main/java/run/halo/app/theme/dialect/GlobalSeoProcessor.java
  application/src/main/java/run/halo/app/theme/dialect/IndexSeoProcessor.java
  application/src/main/java/run/halo/app/theme/router/factories/CategoryPostRouteFactory.java
  application/src/main/resources/extensions/system-setting.yaml
  application/src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, area/core, approved

#7678 Fix the problem of memory leak caused by thymeleaf
  application/build.gradle
  application/libs/thymeleaf-spring6-3.1.4-rc.1+halo.2.21.6.jar
Labels: kind/bug, lgtm, area/core, approved, release-note

#7682 Allow <s> tag and class attribute on <code> in comments
  application/src/main/java/run/halo/app/content/comment/AbstractCommentService.java
Labels: lgtm, approved

#7683 Optimize comment notification template to support rich text rendering
  application/src/main/resources/extensions/notification-templates.yaml
  ui/console-src/modules/dashboard/widgets/presets/users/NotificationWidget.vue
  ui/uc-src/modules/notifications/Notifications.vue
  ui/uc-src/modules/notifications/components/NotificationContent.vue
  ui/uc-src/modules/notifications/components/NotificationListItem.vue
Labels: kind/feature, lgtm, release-note-none, area/core, approved, area/ui

#7687 Add external asset transfer for editor attachments
  ui/src/components/editor/composables/use-attachment.ts
  ui/src/components/editor/extensions/audio/AudioView.vue
  ui/src/components/editor/extensions/image/ImageView.vue
  ui/src/components/editor/extensions/upload/index.ts
  ui/src/components/editor/extensions/video/VideoView.vue
  ui/src/components/editor/utils/upload.ts
  ui/src/locales/_missing_translations_es.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note, area/editor, area/ui

#7684 Fix role dependency handling in role editing form
  ui/console-src/modules/system/roles/components/RoleEditingModal.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#7688 Support async permission checks in route menu generator
  ui/console-src/layouts/BasicLayout.vue
  ui/console-src/modules/system/tools/Tools.vue
  ui/env.d.ts
  ui/src/components/menu/MenuLoading.vue
  ui/src/composables/use-route-menu-generator.ts
  ui/uc-src/layouts/BasicLayout.vue
Labels: kind/feature, lgtm, approved, release-note, area/ui

#7679 Add support for hidden comments
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  api-docs/openapi/v3_0/apis_public.api_v1alpha1.json
  api/src/main/java/run/halo/app/core/user/service/UserService.java
  application/src/main/java/run/halo/app/content/comment/CommentRequest.java
  application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
  application/src/main/java/run/halo/app/content/comment/ReplyRequest.java
  application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
  application/src/main/java/run/halo/app/core/endpoint/theme/CommentFinderEndpoint.java
  application/src/main/java/run/halo/app/core/user/service/impl/UserServiceImpl.java
  application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
  application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceIntegrationTest.java
  ui/console-src/modules/contents/comments/components/CommentDetailModal.vue
  ui/console-src/modules/contents/comments/components/CommentListItem.vue
  ui/console-src/modules/contents/comments/components/ReplyDetailModal.vue
  ui/console-src/modules/contents/comments/components/ReplyListItem.vue
  ui/packages/api-client/src/api/post-v1alpha1-console-api.ts
  ui/packages/api-client/src/models/comment-request.ts
  ui/packages/api-client/src/models/reply-request.ts
  ui/src/locales/_missing_translations_es.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, release-note-none, area/core

#7703 Fix pending comments calculation in post list item
  ui/console-src/modules/contents/pages/components/entity-fields/TitleField.vue
  ui/console-src/modules/contents/posts/components/entity-fields/TitleField.vue
  ui/console-src/modules/dashboard/widgets/presets/posts/components/PostListItem.vue
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#7704 Bump rolldown-vite to 7.1.4
  ui/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, approved, area/ui

#7725 Set context ClassLoader to plugin ClassLoader for correct class loading operations
  application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
  application/src/test/java/run/halo/app/plugin/DefaultPluginApplicationContextFactoryTest.java
Labels: kind/bug, lgtm, approved, release-note, area/plugin
