Repository halo-dev/halo, pull requests merged in 2025-01, with the labels that each got.

#7149 fix: XSS vulnerability due to polyglot file type upload
  api/src/main/java/run/halo/app/infra/utils/FileTypeDetectUtils.java
  application/src/main/java/run/halo/app/core/attachment/endpoint/LocalAttachmentUploadHandler.java
  application/src/main/resources/config/i18n/messages.properties
  application/src/main/resources/config/i18n/messages_zh.properties
  application/src/test/java/run/halo/app/infra/utils/FileTypeDetectUtilsTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#7174 refactor: clear the template cache after uninstalling the theme
  application/src/main/java/run/halo/app/core/reconciler/ThemeReconciler.java
  application/src/test/java/run/halo/app/core/reconciler/ThemeReconcilerTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#7171 feat: add retry mechanism for publishing posts on the UC end
  ui/uc-src/modules/contents/posts/components/PostCreationModal.vue
  ui/uc-src/modules/contents/posts/components/PostListItem.vue
  ui/uc-src/modules/contents/posts/composables/use-post-publish-mutate.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#7199 fix: failure to create notification templates in themes
  application/src/main/java/run/halo/app/theme/service/ThemeServiceImpl.java
  application/src/test/java/run/halo/app/theme/service/ThemeServiceImplTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#7200 refactor: generate summaries only for content changes
  api/src/main/java/run/halo/app/core/extension/content/Constant.java
  application/src/main/java/run/halo/app/core/reconciler/PostReconciler.java
  application/src/main/java/run/halo/app/core/reconciler/SinglePageReconciler.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7207 Upgrade to SpringDoc to 2.8.3
  platform/application/build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#7209 chore: bump axios version to 1.7.9
  ui/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#7208 Upgrade to Spring Boot 3.4.1
  build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#7211 chore: bump tiptap version to 2.11.x
  ui/package.json
  ui/packages/editor/package.json
  ui/packages/editor/src/extensions/code-block/CodeBlockSelect.vue
  ui/packages/editor/src/extensions/table/index.ts
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#7210 chore: bump vue-related dependencies
  ui/package.json
  ui/packages/components/package.json
  ui/packages/editor/package.json
  ui/packages/shared/package.json
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#7215 Upgrade to Spring Boot 3.4.2
  build.gradle
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#7218 fix: prevent extension-point list from being obscured at bottom
  ui/console-src/modules/system/plugins/PluginExtensionPointSettings.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui
