Repository halo-dev/halo, pull requests merged in 2025-09, with the labels that each got.

#7726 fix: resolve the pagination issue of the select formkit component using remote data
  ui/src/formkit/inputs/select/SelectMain.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#7752 Upgrade Lucene to version 10.3.0
  gradle/libs.versions.toml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7765 Update Docker image name and tags for Fit2Cloud registry
  .github/workflows/halo.yaml
  application/build.gradle
Labels: kind/bug, release-note-none, area/core

#7768 Refactor build tasks to improve UI distribution and cleanup processes
  application/build.gradle
  ui/build.gradle
Labels: kind/bug, release-note-none, area/core

#7774 Upgrade Spring Boot version to 3.5.6
  gradle/libs.versions.toml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7749 Enable auto-height for textarea fields in forms
  application/src/main/resources/extensions/system-setting.yaml
  ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
  ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
  ui/console-src/modules/contents/posts/components/PostSettingModal.vue
  ui/console-src/modules/system/users/components/UserCreationModal.vue
  ui/console-src/modules/system/users/components/UserEditingModal.vue
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/formkit/formkit.config.ts
  ui/uc-src/modules/contents/posts/components/PostSettingForm.vue
  ui/uc-src/modules/profile/components/ProfileEditingModal.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#7775 Improve navigation logic after publishing content
  ui/console-src/modules/contents/pages/SinglePageEditor.vue
  ui/console-src/modules/contents/posts/PostEditor.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#7762 Remove vite-plugin-pwa from dev dependencies
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/vite/config-builder.ts
Labels: release-note-none, kind/cleanup, approved, area/ui
