Repository halo-dev/halo, pull requests merged in 2025-05, with the labels that each got.

#7407 Use Argon2 password encoder as default to remove password limit
  api/build.gradle
  application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
  application/src/test/java/run/halo/app/config/SecurityConfigTest.java
  platform/application/build.gradle
Labels: kind/bug, lgtm, area/core, approved, release-note

#7408 Fix SwitchUserGrantedAuthority deserialization error
  application/src/main/java/run/halo/app/security/jackson2/HaloSecurityJackson2Module.java
  application/src/main/java/run/halo/app/security/jackson2/SwitchUserGrantedAuthorityMixIn.java
  application/src/test/java/run/halo/app/security/jackson2/HaloSecurityJacksonModuleTest.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#7413 Enable configuration properties by scanning
  application/src/main/java/run/halo/app/Application.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#7414 feat：support sorting tags by post count
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  ui/console-src/modules/contents/posts/tags/TagList.vue
  ui/src/locales/_missing_translations_es.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, lgtm, approved, release-note

#7419 Fix potential twice theme route handler invocations
  application/src/main/java/run/halo/app/theme/router/ThemeCompositeRouterFunction.java
  application/src/main/java/run/halo/app/theme/router/factories/PostRouteFactory.java
Labels: kind/bug, lgtm, area/core, approved, release-note

#7418 Add support for redirection on logout
  application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7417 Rearrange system initialization by phase
  api/src/main/java/run/halo/app/extension/Scheme.java
  application/src/main/java/run/halo/app/content/AbstractEventReconciler.java
  application/src/main/java/run/halo/app/content/stats/PostStatsUpdater.java
  application/src/main/java/run/halo/app/content/stats/ReplyEventReconciler.java
  application/src/main/java/run/halo/app/content/stats/VisitedEventReconciler.java
  application/src/main/java/run/halo/app/content/stats/VotedEventReconciler.java
  application/src/main/java/run/halo/app/core/attachment/ThumbnailMigration.java
  application/src/main/java/run/halo/app/extension/DefaultSchemeManager.java
  application/src/main/java/run/halo/app/extension/DefaultSchemeWatcherManager.java
  application/src/main/java/run/halo/app/extension/JSONExtensionConverter.java
  application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
  application/src/main/java/run/halo/app/extension/SchemeWatcherManager.java
  application/src/main/java/run/halo/app/extension/availability/IndexBuildStateHealthIndicator.java
  application/src/main/java/run/halo/app/extension/controller/ControllerManager.java
  application/src/main/java/run/halo/app/extension/controller/DefaultControllerManager.java
  application/src/main/java/run/halo/app/extension/event/IndexerBuiltEvent.java
  application/src/main/java/run/halo/app/extension/event/SchemeAddedEvent.java
  application/src/main/java/run/halo/app/extension/event/SchemeRemovedEvent.java
  application/src/main/java/run/halo/app/extension/gc/GcControllerInitializer.java
  application/src/main/java/run/halo/app/extension/index/DefaultExtensionIterator.java
  application/src/main/java/run/halo/app/extension/index/IndexSpecRegistryImpl.java
  application/src/main/java/run/halo/app/extension/index/IndexerInitializer.java
  application/src/main/java/run/halo/app/extension/router/ExtensionCompositeRouterFunction.java
  application/src/main/java/run/halo/app/infra/ExtensionResourceInitializer.java
  application/src/main/java/run/halo/app/infra/InitializationPhase.java
  application/src/main/java/run/halo/app/infra/SchemeInitializer.java
  application/src/main/java/run/halo/app/infra/config/ExtensionConfiguration.java
  application/src/main/java/run/halo/app/notification/SubscriptionMigration.java
  application/src/main/java/run/halo/app/theme/router/ThemeCompositeRouterFunction.java
  application/src/main/resources/META-INF/spring.factories
  application/src/test/java/run/halo/app/extension/DefaultSchemeManagerTest.java
  application/src/test/java/run/halo/app/extension/JsonExtensionConverterTest.java
  application/src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java
  application/src/test/java/run/halo/app/extension/router/ExtensionCompositeRouterFunctionTest.java
  application/src/test/java/run/halo/app/infra/ExtensionResourceInitializerTest.java
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#7425 refactor: improve type definitions for editor extension
  ui/packages/editor/docs/extension.md
  ui/packages/editor/src/components/EditorBubbleMenu.vue
  ui/packages/editor/src/components/EditorHeader.vue
  ui/packages/editor/src/components/index.ts
  ui/packages/editor/src/components/toolbar/ToolbarItem.vue
  ui/packages/editor/src/extensions/audio/index.ts
  ui/packages/editor/src/extensions/commands-menu/CommandsView.vue
  ui/packages/editor/src/extensions/commands-menu/commands.ts
  ui/packages/editor/src/extensions/draggable/index.ts
  ui/packages/editor/src/extensions/iframe/index.ts
  ui/packages/editor/src/extensions/image/index.ts
  ui/packages/editor/src/extensions/paragraph/index.ts
  ui/packages/editor/src/extensions/table/index.ts
  ui/packages/editor/src/extensions/text/index.ts
  ui/packages/editor/src/extensions/video/index.ts
  ui/packages/editor/src/index.ts
  ui/packages/editor/src/types/index.ts
Labels: lgtm, approved, release-note, area/plugin, area/editor

#7423 refactor: improve drag-and-drop sorting feature for menu items
  ui/console-src/modules/contents/posts/categories/components/__tests__/CategoryEditingModal.spec.ts
  ui/console-src/modules/interface/menus/Menus.vue
  ui/console-src/modules/interface/menus/components/MenuItemEditingModal.vue
  ui/console-src/modules/interface/menus/components/MenuItemListItem.vue
  ui/console-src/modules/interface/menus/utils/__tests__/__snapshots__/index.spec.ts.snap
  ui/console-src/modules/interface/menus/utils/__tests__/index.spec.ts
  ui/console-src/modules/interface/menus/utils/index.ts
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/vite/config-builder.ts
  ui/vitest.config.ts
Labels: approved, release-note, kind/improvement, area/ui

#7433 Fix the deprecation warning of support for convention-base @Component names
  api/src/main/java/run/halo/app/theme/finders/Finder.java
Labels: lgtm, release-note-none, approved, kind/improvement

#7430 Remove wrong cache of pattern matchers
  application/src/main/java/run/halo/app/theme/router/ThemeCompositeRouterFunction.java
  application/src/main/java/run/halo/app/theme/router/factories/PostRouteFactory.java
  application/src/test/java/run/halo/app/theme/router/factories/PostRouteFactoryTest.java
Labels: kind/bug, area/core, release-note

#7429 Show stack trace while failing to start plugin
  application/src/main/java/run/halo/app/core/reconciler/PluginReconciler.java
  ui/console-src/modules/system/plugins/components/PluginConditionsModal.vue
  ui/console-src/modules/system/plugins/components/tabs/Detail.vue
Labels: release-note-none, area/core, kind/improvement, area/plugin

#7434 chore: bump ui packages version
  ui/packages/api-client/package.json
  ui/packages/components/package.json
  ui/packages/editor/package.json
  ui/packages/shared/package.json
  ui/packages/ui-plugin-bundler-kit/package.json
Labels: release-note-none, area/ui

#7446 Refactor processResources with creating a new copy task
  application/build.gradle
Labels: lgtm, release-note-none, area/core, approved, kind/improvement

#7451 Set Java 21 as minimal version
  .github/actions/setup-env/action.yaml
  api/build.gradle
  application/build.gradle
Labels: lgtm, area/core, approved, kind/improvement

#7450 Upgrade to Gradle 8.14
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: area/core, kind/cleanup

#7449 Refactor dependencies and plugins with version catelog
  api/build.gradle
  application/build.gradle
  application/src/test/java/run/halo/app/infra/utils/FileTypeDetectUtilsTest.java
  application/src/test/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessorIntegrationTest.java
  build.gradle
  gradle/libs.versions.toml
  platform/application/build.gradle
  ui/build.gradle
Labels: area/core, kind/improvement

#7383 refactor: improve entity component layout for better device responsiveness
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  ui/console-src/modules/contents/comments/CommentList.vue
  ui/console-src/modules/contents/comments/components/CommentListItem.vue
  ui/console-src/modules/contents/comments/components/ReplyCreationModal.vue
  ui/console-src/modules/contents/comments/components/ReplyListItem.vue
  ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
  ui/console-src/modules/contents/pages/SinglePageList.vue
  ui/console-src/modules/contents/posts/DeletedPostList.vue
  ui/console-src/modules/contents/posts/PostList.vue
  ui/console-src/modules/contents/posts/categories/CategoryList.vue
  ui/console-src/modules/contents/posts/components/entity-fields/TitleField.vue
  ui/console-src/modules/contents/posts/tags/TagList.vue
  ui/console-src/modules/contents/posts/widgets/RecentPublishedWidget.vue
  ui/console-src/modules/interface/menus/Menus.vue
  ui/console-src/modules/interface/menus/components/MenuList.vue
  ui/console-src/modules/interface/themes/components/preview/ThemePreviewModal.vue
  ui/console-src/modules/system/auth-providers/components/AuthProvidersSection.vue
  ui/console-src/modules/system/backup/tabs/List.vue
  ui/console-src/modules/system/backup/tabs/Restore.vue
  ui/console-src/modules/system/plugins/PluginList.vue
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionListItem.vue
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionMultiInstanceView.vue
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionSingletonView.vue
  ui/console-src/modules/system/roles/RoleList.vue
  ui/console-src/modules/system/tools/Tools.vue
  ui/console-src/modules/system/users/UserList.vue
  ui/console-src/modules/system/users/components/UserListItem.vue
  ui/console-src/modules/system/users/widgets/NotificationWidget.vue
  ui/packages/components/src/components/entity/Entity.vue
  ui/packages/components/src/components/entity/EntityContainer.vue
  ui/packages/components/src/components/entity/EntityField.vue
  ui/packages/components/src/components/entity/index.ts
  ui/src/components/filter/CategoryFilterDropdown.vue
  ui/src/components/filter/TagFilterDropdown.vue
  ui/src/components/filter/UserFilterDropdown.vue
  ui/src/formkit/inputs/secret/components/SecretListModal.vue
  ui/src/locales/_missing_translations_es.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  ui/uc-src/modules/contents/posts/PostList.vue
  ui/uc-src/modules/profile/tabs/Devices.vue
  ui/uc-src/modules/profile/tabs/PersonalAccessTokens.vue
  ui/uc-src/modules/profile/tabs/TwoFactor.vue
Labels: release-note, kind/improvement, area/ui

#7456 Make uploads resources protected
  application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
Labels: lgtm, area/core, approved, kind/improvement

#7458 Fix the problem of undetermined locale
  application/src/main/java/run/halo/app/infra/webfilter/LocaleChangeWebFilter.java
  application/src/main/java/run/halo/app/theme/ThemeLocaleContextResolver.java
  application/src/test/java/run/halo/app/theme/ThemeLocaleContextResolverTest.java
  application/src/test/java/run/halo/app/webfilter/LocaleChangeWebFilterTest.java
Labels: kind/bug, lgtm, area/core, approved

#7459 Add support for configuring external URL online
  api/src/main/java/run/halo/app/infra/SystemSetting.java
  application/src/main/java/run/halo/app/infra/ExtensionResourceInitializer.java
  application/src/main/java/run/halo/app/infra/HaloPropertiesExternalUrlSupplier.java
  application/src/main/java/run/halo/app/infra/SystemConfigFirstExternalUrlSupplier.java
  application/src/main/java/run/halo/app/infra/SystemConfigurableEnvironmentFetcher.java
  application/src/main/java/run/halo/app/infra/actuator/GlobalInfoServiceImpl.java
  application/src/test/java/run/halo/app/infra/HaloPropertiesExternalUrlSupplierTest.java
  application/src/test/java/run/halo/app/infra/SystemConfigFirstExternalUrlSupplierTest.java
  ui/console-src/modules/system/overview/Overview.vue
  ui/console-src/modules/system/overview/components/ExternalUrlForm.vue
  ui/console-src/modules/system/overview/components/ExternalUrlItem.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: kind/feature, area/core, release-note

#7467 Bump Spring Boot to 3.5.0
  api/build.gradle
  application/build.gradle
  application/src/main/resources/application.yaml
  gradle/libs.versions.toml
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7463 Bump Spring Boot to 3.4.6
  build.gradle
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7468 Fix deprecation warnings from Gradle
  api/build.gradle
  application/build.gradle
  settings.gradle
Labels: release-note-none, area/core, kind/cleanup

#7440 Add shared events for listening user login and logout in plugins
  api/src/main/java/run/halo/app/event/user/UserLoginEvent.java
  api/src/main/java/run/halo/app/event/user/UserLogoutEvent.java
  application/src/main/java/run/halo/app/core/user/service/UserLoginOrLogoutProcessing.java
  application/src/main/java/run/halo/app/security/LoginHandlerEnhancerImpl.java
  application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
Labels: lgtm, approved, release-note, kind/improvement

#7470 Refactor logout handler
  application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
  application/src/main/java/run/halo/app/security/authentication/rememberme/TokenBasedRememberMeServices.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#7487 fix: correct attachment selection state after new upload
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentListItem.vue
  ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  ui/console-src/modules/contents/attachments/composables/use-attachment.ts
  ui/uc-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#7488 Add support for setting external URL at setup page
  application/src/main/java/run/halo/app/infra/ExternalUrlChangedEvent.java
  application/src/main/java/run/halo/app/infra/SystemConfigFirstExternalUrlSupplier.java
  application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
  application/src/main/resources/templates/setup.html
  application/src/main/resources/templates/setup.properties
  application/src/main/resources/templates/setup_en.properties
  application/src/main/resources/templates/setup_es.properties
  application/src/main/resources/templates/setup_zh_TW.properties
Labels: lgtm, area/core, approved, release-note, kind/improvement

#7486 fix: exclude reserved users from global search results
  ui/src/components/global-search/GlobalSearchModal.vue
Labels: kind/bug, release-note, area/ui
