Repository halo-dev/halo, pull requests merged in 2025-06, with the labels that each got.

#7494 refactor: remove time field from plugin list
  ui/console-src/modules/system/plugins/components/PluginListItem.vue
  ui/console-src/modules/system/plugins/components/tabs/Detail.vue
  ui/src/locales/_missing_translations_es.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#7495 Add support for configuring my preferences
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
  application/src/main/java/run/halo/app/core/endpoint/uc/UcUserPreferenceEndpoint.java
  application/src/main/resources/extensions/role-template-authenticated.yaml
  application/src/test/java/run/halo/app/core/endpoint/uc/UcUserPreferenceEndpointTest.java
  ui/packages/api-client/entry/api-client.ts
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api.ts
  ui/packages/api-client/src/api/user-preference-v1alpha1-uc-api.ts
Labels: kind/feature, lgtm, area/core, approved, release-note

#7523 chore: bump vue-related dependencies
  ui/console-src/main.ts
  ui/console-src/modules/interface/themes/ThemeDetail.vue
  ui/console-src/modules/interface/themes/ThemeSetting.vue
  ui/console-src/modules/system/plugins/components/tabs/Detail.vue
  ui/console-src/modules/system/plugins/components/tabs/Setting.vue
  ui/console-src/modules/system/settings/tabs/Setting.vue
  ui/package.json
  ui/packages/components/package.json
  ui/packages/editor/package.json
  ui/packages/editor/src/extensions/code-block/CodeBlockSelect.vue
  ui/packages/shared/package.json
  ui/packages/shared/src/types/plugin.ts
  ui/pnpm-lock.yaml
  ui/uc-src/main.ts
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#7524 refactor: migrate system settings to new configmap API
  ui/console-src/modules/system/settings/tabs/Setting.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7526 refactor: convert post publish dates to human-readable format
  ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
  ui/console-src/modules/contents/pages/components/SinglePageListItem.vue
  ui/console-src/modules/contents/posts/DeletedPostList.vue
  ui/console-src/modules/contents/posts/components/PostListItem.vue
  ui/console-src/modules/contents/posts/components/entity-fields/PublishTimeField.vue
  ui/console-src/modules/dashboard/widgets/presets/posts/RecentPublishedWidget.vue
  ui/console-src/modules/dashboard/widgets/presets/posts/components/PostListItem.vue
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
  ui/uc-src/modules/contents/posts/components/PostListItem.vue
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#7527 Provide storage policy config APIs to make it easy to use
  api-docs/openapi/v3_0/aggregated.json
  api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
  application/src/main/java/run/halo/app/core/attachment/endpoint/PolicyEndpoint.java
  application/src/main/java/run/halo/app/extension/exception/ExtensionNotFoundException.java
  application/src/test/java/run/halo/app/core/attachment/endpoint/PolicyEndpointTest.java
  ui/packages/api-client/entry/api-client.ts
  ui/packages/api-client/src/.openapi-generator/FILES
  ui/packages/api-client/src/api.ts
  ui/packages/api-client/src/api/policy-alpha1-console-api.ts
Labels: kind/feature, area/core, release-note

#7519 feat: add cover for post list
  ui/console-src/modules/contents/pages/components/SinglePageListItem.vue
  ui/console-src/modules/contents/posts/components/PostListItem.vue
  ui/console-src/modules/contents/posts/components/entity-fields/CoverField.vue
  ui/src/utils/thumbnail.ts
Labels: kind/feature, lgtm, approved, release-note, area/ui

#7517 refactor: improve button component styles
  ui/console-src/modules/contents/attachments/AttachmentList.vue
  ui/console-src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
  ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  ui/console-src/modules/contents/comments/components/CommentListItem.vue
  ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
  ui/console-src/modules/contents/pages/SinglePageEditor.vue
  ui/console-src/modules/contents/pages/SinglePageList.vue
  ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
  ui/console-src/modules/contents/posts/DeletedPostList.vue
  ui/console-src/modules/contents/posts/PostEditor.vue
  ui/console-src/modules/contents/posts/PostList.vue
  ui/console-src/modules/contents/posts/categories/CategoryList.vue
  ui/console-src/modules/contents/posts/components/PostSettingModal.vue
  ui/console-src/modules/contents/posts/tags/TagList.vue
  ui/console-src/modules/dashboard/Dashboard.vue
  ui/console-src/modules/dashboard/DashboardDesigner.vue
  ui/console-src/modules/interface/menus/Menus.vue
  ui/console-src/modules/interface/themes/components/list-tabs/InstalledThemes.vue
  ui/console-src/modules/interface/themes/layouts/ThemeLayout.vue
  ui/console-src/modules/system/backup/Backups.vue
  ui/console-src/modules/system/overview/Overview.vue
  ui/console-src/modules/system/plugins/PluginList.vue
  ui/console-src/modules/system/plugins/components/entity-fields/ReloadField.vue
  ui/console-src/modules/system/roles/RoleList.vue
  ui/console-src/modules/system/users/UserList.vue
  ui/packages/components/src/components/button/Button.vue
  ui/src/formkit/inputs/list/AddButton.vue
  ui/src/formkit/inputs/repeater/AddButton.vue
  ui/tailwind.config.cjs
  ui/uc-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
  ui/uc-src/modules/contents/posts/PostEditor.vue
  ui/uc-src/modules/contents/posts/PostList.vue
  ui/uc-src/modules/profile/tabs/PersonalAccessTokens.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7512 refactor: improve dialog styles in mobile devices
  ui/packages/components/src/components/dialog/Dialog.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7511 feat: refine i18n for dashboard widgets config form
  ui/console-src/modules/dashboard/components/WidgetConfigFormModal.vue
  ui/console-src/modules/dashboard/components/WidgetEditableItem.vue
  ui/console-src/modules/dashboard/widgets/index.ts
  ui/docs/extension-points/dashboard.md
  ui/packages/shared/src/types/widget.ts
  ui/src/locales/_missing_translations_es.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7522 feat: add empty state for some widgets
  ui/console-src/modules/dashboard/widgets/presets/comments/PendingCommentsWidget.vue
  ui/console-src/modules/dashboard/widgets/presets/posts/RecentPublishedWidget.vue
  ui/src/locales/_missing_translations_es.yaml
  ui/src/locales/en.yaml
  ui/src/locales/zh-CN.yaml
  ui/src/locales/zh-TW.yaml
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7529 refactor: update extension points settings using new configMap API
  ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionSingletonView.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7530 refactor: optimize global libs filenames for better cache hit rates
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/vite/library-external.ts
Labels: lgtm, approved, release-note, kind/improvement, area/ui

#7532 Upgrade SpringDoc to 2.8.9
  gradle/libs.versions.toml
Labels: area/core, release-note, kind/improvement

#7533 fix: encode post cover image URLs to prevent loading issue
  ui/src/utils/thumbnail.ts
Labels: kind/bug, lgtm, release-note-none, approved, area/ui

#7534 feat: add cover for post list in uc
  ui/uc-src/modules/contents/posts/components/PostListItem.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7535 Remove deprecated migrations
  application/src/main/java/run/halo/app/core/attachment/ThumbnailMigration.java
  application/src/main/java/run/halo/app/notification/SubscriptionMigration.java
Labels: lgtm, release-note-none, area/core, kind/cleanup, approved

#7543 fix: resolve text wrapping issue in entity field component
  ui/packages/components/src/components/entity/EntityField.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7545 refactor: remove unused width prop for post title field
  ui/console-src/modules/contents/posts/DeletedPostList.vue
  ui/console-src/modules/contents/posts/components/entity-fields/TitleField.vue
  ui/uc-src/modules/contents/posts/components/PostListItem.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7546 fix: prevent title text overflow in modal component
  ui/packages/components/src/components/modal/Modal.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#7548 chore: remove unnecessary ts checks and enable parallel build
  ui/package.json
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#7549 Reduce application size by removing unused JPA dependency
  api/build.gradle
  application/src/main/java/run/halo/app/extension/store/ExtensionStore.java
Labels: lgtm, area/core, kind/cleanup, approved, release-note

#7555 chore: bump preset plugins and themes version
  application/build.gradle
  application/src/main/resources/themes/theme-earth.zip
Labels: release-note-none, area/core

#7558 chore: fix incorrect imports
  ui/console-src/modules/contents/pages/components/SinglePageListItem.vue
  ui/src/layouts/MobileMenu.vue
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#7563 fix: display settings button in Stack widgets
  ui/console-src/modules/dashboard/widgets/presets/core/stack/components/WidgetEditableItem.vue
Labels: kind/bug, lgtm, approved, release-note, area/ui

#7559 Add support for rewriting URL with trailing slash
  application/src/main/java/run/halo/app/infra/config/WebFluxConfig.java
  application/src/test/java/run/halo/app/config/WebFluxConfigTest.java
Labels: area/core, release-note, kind/improvement

#7565 feat: add cover for deleted post list in console
  ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
  ui/console-src/modules/contents/posts/DeletedPostList.vue
Labels: lgtm, release-note-none, approved, kind/improvement, area/ui

#7573 chore: bump @halo-dev/ui-plugin-bundler-kit version
  ui/packages/ui-plugin-bundler-kit/package.json
Labels: lgtm, release-note-none, approved, area/ui

#7587 chore: bump vite version to 7
  ui/package.json
  ui/packages/ui-plugin-bundler-kit/package.json
  ui/packages/ui-plugin-bundler-kit/src/vite.ts
  ui/pnpm-lock.yaml
Labels: lgtm, release-note-none, approved, area/ui

#7594 feat: add details extension for editor
  ui/packages/editor/package.json
  ui/packages/editor/src/dev/App.vue
  ui/packages/editor/src/extensions/details/index.ts
  ui/packages/editor/src/extensions/index.ts
  ui/packages/editor/src/locales/en.yaml
  ui/packages/editor/src/locales/zh-CN.yaml
  ui/packages/editor/src/styles/details.scss
  ui/packages/editor/src/styles/index.scss
  ui/pnpm-lock.yaml
  ui/src/components/editor/DefaultEditor.vue
Labels: kind/feature, lgtm, approved, release-note, area/editor, area/ui

#7604 chore: bump tailwindcss version to 3.4
  ui/package.json
  ui/packages/components/package.json
  ui/packages/components/postcss.config.cjs
  ui/packages/components/tailwind.config.js
  ui/packages/components/tailwind.config.ts
  ui/packages/components/tsconfig.node.json
  ui/packages/editor/package.json
  ui/packages/editor/postcss.config.cjs
  ui/packages/editor/tailwind.config.js
  ui/packages/editor/tailwind.config.ts
  ui/packages/editor/tsconfig.node.json
  ui/pnpm-lock.yaml
  ui/tailwind.config.cjs
  ui/tailwind.config.ts
  ui/tsconfig.node.json
Labels: lgtm, release-note-none, kind/cleanup, approved, area/ui

#7606 fix: bump rolldown vite version to fix css chunk issue
  ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
  ui/package.json
  ui/pnpm-lock.yaml
Labels: kind/bug, lgtm, approved, release-note, area/ui

#7601 refactor: optimize the drag-and-drop performance
  ui/packages/editor/src/extensions/draggable/index.ts
Labels: lgtm, release-note-none, approved

#7600 refactor: optimize indentation behavior
  ui/packages/editor/src/extensions/indent/index.ts
  ui/packages/editor/src/extensions/paragraph/index.ts
Labels: lgtm, approved, release-note, kind/improvement, area/editor
